ministryofjustice/laa-apply-for-criminal-legal-aid

config/kubernetes/staging/deployment.tpl
config/kubernetes/staging/service.yml

As we are now using a rails app with Puma instead of the demo rack app.

Change port from rack default to puma default

---

app/controllers/bare_application_controller.rb
app/controllers/healthcheck_controller.rb
config/routes.rb
spec/requests/healthcheck_spec.rb

Add healthcheck endpoint to the application
At the moment it only checks there is a DB connection available, but it should be simple to adapt to add other checks as needed.
Are there other checks that we should add? Or other endpoints?

Add healthcheck endpoint

---

.github/pull_request_template.md

Please leave comments on this - I have tried to keep it really light touch. I also dislike those lists with checkboxes so I have just kept it textual.
This should automatically be available once this PR is merged according to [these docs ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[Jira ticket link](https://dsdmoj.atlassian.net/browse/CRIMAP-28)

Add simple PR template

---

app/forms/steps/client/contact_details_form.rb
config/locales/en/errors.yml

Updated previous regex that would allow all symbols and numeric input to allow numeric and +()- input only
Updated error messages to align with [design approved messaging ](https://docs.google.com/spreadsheets/d/1F30TsGgtB94e2AHoqo1piKqyF4_1kqbyIdKRtAFJzYQ/edit#gid=0)
https://dsdmoj.atlassian.net/browse/CRIMAP-64

Improve telephone number validation and update error messages

---

config/locales/en/helpers.yml

Updated the wording of the telephone number hint text to match [designs in figma ](https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=2769%3A25359)

Update tel hint text

---

config/importmap.rb
package.json

Forgot this in the previous PR #72, ouch.

Pin new version of govuk-frontend to importmap

---

app/services/decisions/address_decision_tree.rb
spec/services/decisions/address_decision_tree_spec.rb

There was a place where these 2 journeys were not joined together, when coming from a correspondence address sub-journey.

Join client details journey to case journey

---

app/controllers/steps/case/charges_controller.rb
app/forms/steps/case/charges_form.rb
app/forms/steps/case/offence_date_fieldset_form.rb
app/services/decisions/case_decision_tree.rb
app/views/steps/case/charges/edit.html.erb
config/locales/en/steps.yml
spec/controllers/steps/case/charges_controller_spec.rb
spec/forms/steps/case/charges_form_spec.rb
spec/forms/steps/case/offence_date_fieldset_form_spec.rb
spec/services/decisions/case_decision_tree_spec.rb

First PR for adding offence dates to charges page - others will follow.
The PR adds the new fields, ability to add and ability to delete dates + some basic test. 
Further PRs will add validations, clean up the erb file + i18n entries and headings.
[CRIMAP-72](https://dsdmoj.atlassian.net/browse/CRIMAP-72)
Add offence dates / delete offence dates on the Charges page

CRIMAP-72 offence dates

---

app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/case_details.rb
config/locales/en/summary.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/summary/sections/case_details_spec.rb

Add the case details section to the check your answers page. This only has 2 rows, one of them (URN) might be blank but we show them regardless so the provider can get back and add a reference if they need to.
There is some overlapping code between this PR and a previous one still open. Will fix conflicts before merging.
https://dsdmoj.atlassian.net/browse/CRIMAP-156

CRIMAP-156 Review case details

---

app/models/codefendant.rb
app/models/concerns/person_with_full_name.rb
app/models/person.rb
app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/codefendants.rb
app/views/steps/case/codefendants/edit.html.erb
config/locales/en/summary.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/summary/sections/codefendants_spec.rb

Add the co-defendants section to the check your answers page.
Some code might conflict with another open PR for the offences section. Depending on the order of the merges, it will require rebase and fixing conflicts.
https://dsdmoj.atlassian.net/browse/CRIMAP-159

CRIMAP-159 Review co-defendants

---

Gemfile
Gemfile.lock

Update dev api to a version that only lists submitted applications

Update dev api to only list submitted applications

---

app/forms/steps/case/ioj_form.rb
app/value_objects/ioj_reason_type.rb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/summary.yml
db/migrate/20221122170409_fix_ioj_column_name.rb
db/schema.rb
spec/forms/steps/case/ioj_form_spec.rb
spec/value_objects/ioj_reason_type_spec.rb

Fix spelling of livelihood

---

app/controllers/dashboard_controller.rb
app/services/datastore/application_counters.rb
app/views/shared/_subnavigation.html.erb
config/locales/en/dashboard.yml
spec/requests/dashboard_lists_spec.rb
spec/requests/dashboard_spec.rb
spec/services/datastore/application_counters_spec.rb
spec/system/sign_in_spec.rb

As per service designer request.

Remove submitted applications tab counter

---

app/controllers/completed_applications_controller.rb
app/controllers/crime_applications_controller.rb
app/controllers/dashboard_controller.rb
app/services/datastore/get_applications.rb
app/views/completed_applications/_datastore_unavailable.html.erb
app/views/completed_applications/index.html.erb
app/views/crime_applications/index.html.erb
config/locales/en/dashboard.yml
spec/requests/dashboard_lists_spec.rb

Adds message for users if no applications are available
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-243
destroy all application records in all three states

Crimap 246 no applications available

---

Gemfile.lock

update api client

---

app/forms/steps/client/contact_details_form.rb
app/views/steps/client/contact_details/edit.html.erb
config/locales/en/helpers.yml
spec/forms/steps/client/contact_details_form_spec.rb

Change client telephone number to be optional
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-226
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-231

make telephone number optional

---

app/views/home/index.en.html.erb

Update the start page help text to make it clear that the client needs a NINO
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-229

update start page help text

---

app/services/adapters/structs/interests_of_justice.rb
app/services/datastore/application_rehydration.rb
app/value_objects/ioj_reason_type.rb
spec/services/adapters/structs/applicant_spec.rb
spec/services/adapters/structs/case_details_spec.rb
spec/services/adapters/structs/interests_of_justice_spec.rb
spec/value_objects/ioj_reason_type_spec.rb

Another follow-up to previous PRs #252 and #253.
In this PR the rehydration of the Interests of Justice is implemented.
https://dsdmoj.atlassian.net/browse/CRIMAP-239
Refer to PR #252.

CRIMAP-239 Rehydrate Interests of Justice

---

config/locales/en/summary.yml

Some minor copy changes to the Interests of Justice in the check your answers page, as per service designer request.
https://dsdmoj.atlassian.net/browse/CRIMAP-258

CRIMAP-258 IoJ copy tweaks in CYA

---

app/lib/laa_portal_setup.rb
spec/lib/laa_portal_setup_spec.rb

Follow-up to previous PR #282.
After this test, I will revert back to SAMLmock.

(test) Portal DEV integration (SP-initiated post binding)

---

config/kubernetes/production/ingress.yml

Public production domain.
https://dsdmoj.atlassian.net/browse/CRIMAP-327

Add public prod domain to ingress

---

app/views/errors/not_enrolled.en.html.erb
config/locales/en/helpers.yml

As per content designer latest designs and suggestions.
https://dsdmoj.atlassian.net/browse/CRIMAP-345

CRIMAP-345 Copy tweaks to not enrolled page

---

app/views/steps/submission/declaration/edit.en.html.erb

As per content designer, and agreed with stakeholders.
https://dsdmoj.atlassian.net/browse/CRIMAP-348

CRIMAP-348 Copy tweaks to the declaration page

---

config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

Avoid false positives on our session cookie.
Improvement over previous PR #367.

Cover some additional modsec XSS rules

---

app/views/about/contact.en.html.erb
config/settings.yml
spec/system/contact_us_page_spec.rb

Update copy for contact us page
https://dsdmoj.atlassian.net/browse/CRIMAP-396

Update copy for contact us page

---

config/locales/en/dashboard.yml

Update submitted table heading to date submitted
https://dsdmoj.atlassian.net/browse/CRIMAP-394

Update submitted table heading to date submitted

---

app/views/about/accessibility.en.html.erb
config/settings.yml

Update copy for accessibility page
https://dsdmoj.atlassian.net/browse/CRIMAP-397

Update copy for accessibility page

---

app/controllers/about_controller.rb
app/views/about/feedback.en.html.erb
app/views/about/privacy.en.html.erb
app/views/layouts/_footer_links.html.erb
app/views/steps/submission/confirmation/show.en.html.erb
config/locales/en/layouts.yml
config/routes.rb
config/settings.yml
spec/controllers/about_controller_spec.rb

Updated link text for footers
Removed placeholder routes and pages for feedback
Added link to external feedback survey
https://dsdmoj.atlassian.net/browse/CRIMAP-390

Update footer links, add feedback url

---

app/views/shared/_eforms_redirect.en.html.erb

Universal Credits -> Universal Credit - error spotted in QA of https://dsdmoj.atlassian.net/browse/CRIMAP-425
Is correct on start page, just not on this eForms exit page

Fix copy typo

---

app/views/steps/case/charges/edit.html.erb
config/data/offence_synonyms.yml

Previous PR #417 weirdly didn't incorporate all the commits despite I'm fairly sure I pushed them to the branch.
I think it was a GitHub glitch.
I've had to create a separate PR with just these changes that were intended to go as a commit in that other PR.

Add ABH synonym and disable autocorrect

---

app/lib/laa_portal/saml_setup.rb
app/lib/logger_error_subscriber.rb
app/services/dwp/benefit_check_service.rb
app/services/ordnance_survey/address_lookup.rb
spec/lib/laa_portal/saml_setup_spec.rb
spec/services/dwp/benefit_check_service_spec.rb
spec/services/ordnance_survey/address_lookup_spec.rb

Follow-up to previous PR #426.
This finalises all work needed to change old code to new code. In the coming days there might be some additional error handling/reporting we might want to introduce in key areas of the application.
https://dsdmoj.atlassian.net/browse/CRIMAP-429

CRIMAP-429 Some additional error handling refactor

---

config/locales/en/helpers.yml
config/locales/en/steps.yml

As per content designer request.
https://dsdmoj.atlassian.net/browse/CRIMAP-427

CRIMAP-427 Copy tweaks to appeal details page

---

config/gatekeeper.yml

Add office codes for the initial onboarding, as agreed with the business. Spreadsheet and more details in Jira ticket.
We can merge this as long as we don't deploy yet to production.
https://dsdmoj.atlassian.net/browse/CRIMAP-419
Release due tomorrow most likely.

CRIMAP-419 First onboarding tranche

---

config/gatekeeper.yml

Add office codes for the second tranche of onboarding.
More details in Jira ticket.
[CRIMAP-521](https://dsdmoj.atlassian.net/browse/CRIMAP-521)
- please cross check with ticket to make doubly sure the codes are correct.
[CRIMAP-521]: https://dsdmoj.atlassian.net/browse/CRIMAP-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Second onboarding tranche

---

config/gatekeeper.yml

Typo on the month said was 08 (Aug) rather than 07(July)
[CRIMAP-521](https://dsdmoj.atlassian.net/browse/CRIMAP-521)
[CRIMAP-521]: https://dsdmoj.atlassian.net/browse/CRIMAP-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix date in comment

---

config/gatekeeper.yml

Description of change
Add office codes for the fourth tranche of onboarding.
More details in Jira ticket.
Link to relevant ticket
[CRIMAP-565](https://dsdmoj.atlassian.net/browse/CRIMAP-565)
Notes for reviewer
please cross check with ticket to make doubly sure the codes are correct.
[CRIMAP-565]: https://dsdmoj.atlassian.net/browse/CRIMAP-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add office codes for fourth tranche

---

.github/workflows/test-build-deploy.yml

Same as we did in datastore repo.
For reference, PRs in datastore:
https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/166
https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/169

Update deploy workflow with fix for ECR_URL

---

config/inactive_offices.yml

Adds inactive codes for currently onboarded offices.
[CRIMAP-593](https://dsdmoj.atlassian.net/browse/CRIMAP-593)
Check codes are correct based on those on the ticket.
[CRIMAP-593]: https://dsdmoj.atlassian.net/browse/CRIMAP-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds inactive codes for current onboarded offices

---

config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

Reverts ministryofjustice/laa-apply-for-criminal-legal-aid#477 due to staging build fail

Revert "[CRIMAP-594] Update modsecurity rules"

---

config/gatekeeper.yml
config/inactive_offices.yml

Adds active and inactive codes for seventh onboarding tranche
[CRIMAP-608](https://dsdmoj.atlassian.net/browse/CRIMAP-608)
[CRIMAP-608]: https://dsdmoj.atlassian.net/browse/CRIMAP-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAP-517] seventh onboarding tranche

---

Gemfile
Gemfile.lock
app/controllers/steps/client/benefit_exit_controller.rb
app/controllers/steps/client/benefit_type_controller.rb
app/forms/steps/client/benefit_type_form.rb
app/serializers/submission_serializer/definitions/applicant.rb
app/services/decisions/client_decision_tree.rb
app/value_objects/benefit_type.rb
app/views/steps/client/benefit_exit/show.html.erb
app/views/steps/client/benefit_type/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml
config/routes.rb
config/settings.yml
db/migrate/20230919153720_add_benefit_type_to_people.rb
db/schema.rb
spec/controllers/steps/client/benefit_exit_controller_spec.rb
spec/controllers/steps/client/benefit_type_controller_spec.rb
spec/forms/steps/client/benefit_type_form_spec.rb
spec/serializers/submission_serializer/sections/client_details_spec.rb
spec/services/adapters/structs/applicant_spec.rb
spec/services/datastore/application_submission_spec.rb
spec/services/decisions/client_decision_tree_spec.rb
spec/services/passporting/ioj_passporter_spec.rb

Add benefit type step
Add new feature flag
Show benefit step based on feature flag
Show eForms exit page if select benefit_type: none
https://dsdmoj.atlassian.net/browse/CRIMAP-575

Add Benefit Type Step

---

spec/helpers/application_helper_spec.rb
spec/lib/host_env_spec.rb
spec/presenters/crime_application_presenter_spec.rb
spec/presenters/summary/sections/legal_representative_details_spec.rb
spec/presenters/summary/sections/overview_spec.rb
spec/presenters/tasks/base_task_spec.rb
spec/services/decisions/case_decision_tree_spec.rb
spec/services/decisions/client_decision_tree_spec.rb
spec/services/decisions/dwp_decision_tree_spec.rb
spec/services/providers/gatekeeper_spec.rb

Fixes rubocop errors regarding usage of multiple 'receive' mocks
N/A
Probably due to upgraded ruleset

[CHORE] Fix rubocop errors

---

app/controllers/concerns/datastore_application_consumer.rb
config/environments/development.rb
spec/controllers/steps/submission/confirmation_controller_spec.rb
spec/requests/dashboard_lists_spec.rb
spec/requests/dashboard_spec.rb
spec/serializers/submission_serializer/application_spec.rb
spec/support/shared_contexts/with_office_code_selected.rb
spec/system/sign_in_spec.rb

Scope current crime application by selected office code.
Allow host to be set in development from env.

Scope applications by selected office code

---

config/gatekeeper.yml
config/inactive_offices.yml

Ninth onboarding tranche
https://dsdmoj.atlassian.net/browse/CRIMAP-656

Ninth onboarding office codes

---

config/gatekeeper.yml
config/inactive_offices.yml

PR to onboard next wave of providers
[CRIMAP-672](https://dsdmoj.atlassian.net/browse/CRIMAP-672)
[CRIMAP-672]: https://dsdmoj.atlassian.net/browse/CRIMAP-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAP-672] Tenth onboarding tranche

---

app/controllers/steps/income_step_controller.rb
app/services/decisions/income_decision_tree.rb
config/settings.yml
spec/services/decisions/income_decision_tree_spec.rb

Add means journey feature flag
Income step setup:
- step controller
- decision tree
https://dsdmoj.atlassian.net/browse/CRIMAP-677

CRIMAP-677 Means journey feature flag, income step setup

---

README.md

Adds basic information about ClamAv setup
https://dsdmoj.atlassian.net/browse/CRIMAP-649
N/A

[CRIMAP-649] Add readme clamav section

---

config/kubernetes/staging/prometheus.yml

Experiment to check reverting of most recent changes

---

app/controllers/crime_applications_controller.rb
app/controllers/documents_controller.rb
app/controllers/steps/evidence/upload_controller.rb
app/lib/logger_error_subscriber.rb
app/models/log_context.rb
app/services/application_purger.rb
app/services/datastore/documents/delete.rb
app/services/datastore/documents/scan.rb
app/services/datastore/documents/upload.rb
spec/models/log_context_spec.rb
spec/services/application_purger_spec.rb
spec/services/datastore/documents/delete_spec.rb
spec/services/datastore/documents/upload_spec.rb
spec/support/shared_contexts/with_an_existing_document.rb

Adds logging around evidence upload functionality. 
Logs have been added to capture errors in uploading and deleting a file. This currently makes use of the `LoggerErrorSubscriber` which has been modified to output additional args that are supplied to the `Rails.error.handle` call. These additional args are user id, ip address, severity (error), file type and s3 object key. This is provided alongside the information already outputted: timestamp, error message information and the error trace. An example of a log can be found below. 
This PR also introduces a `LogContext` module which is initialised with context (user id and ip address) that is shared across different error handling calls. Additional context can be appended to configure to your use case (e.g. to include file type …

[CRIMAP-687] Add logging to evidence upload

---

app/forms/steps/income/lost_job_in_custody_form.rb
app/validators/multiparam_date_validator.rb
app/views/steps/income/lost_job_in_custody/edit.html.erb
app/views/steps/income/manage_without_income/edit.html.erb
config/locales/en/errors.yml
config/locales/en/steps.yml
spec/forms/steps/income/lost_job_in_custody_form_spec.rb

https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?type=design&node-id=7384%3A40108&mode=design&t=3Cg5ka0gapovGaOS-1 -  I left the date format hint as this is on every date input field and it seems odd to remove

Update style and copy

---

README.md
docker-compose.yml

Basic instructions for uploading evidence with virus scanning on localhost
N/A

[CRIMAP-66] Update readme instructions and docker to instructions to upload files

---

config/inactive_offices.yml

Deactivate office codes as per request
- please check codes against those in ticket.
[CRIMAPP-175](https://dsdmoj.atlassian.net/browse/CRIMAPP-175)
[CRIMAPP-175]: https://dsdmoj.atlassian.net/browse/CRIMAPP-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Deactiveate office codes

---

app/serializers/submission_serializer/sections/means_details.rb

https://ministryofjustice.sentry.io/alerts/rules/details/143747/?alert=7266&environment=production&notification_uuid=cd926de7-e22d-4c5f-aff7-c95d737d5054&referrer=metric_alert_slack

Apply for criminal legal aid 1 p 2

---

config/settings.yml

Turn on evidence upload feature flag in production

Turn on evidence upload feature flag in production

---

Gemfile.lock

Upgrade to puma 6.4.3

---

app/controllers/application_controller.rb
app/controllers/completed_applications_controller.rb
spec/requests/dashboard_spec.rb

Scope in progress apps by office code.
[CRIMAPP-332](https://dsdmoj.atlassian.net/browse/CRIMAPP-332)
[CRIMAPP-332]: https://dsdmoj.atlassian.net/browse/CRIMAPP-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Crimapp 332 scope by office code

---

Dockerfile

Upgrade Alpine to 3.18 --> 3.19

Upgrade Alpine to 3.19

---

app/serializers/submission_serializer/sections/case_details.rb
spec/serializers/submission_serializer/sections/case_details_spec.rb
spec/services/datastore/application_submission_spec.rb

Add *case_concluded attributes for rehydration
https://dsdmoj.atlassian.net/browse/CRIMAPP-312

CRIMAPP-312 Apply rehydration

---

Gemfile
Gemfile.lock
app/presenters/task_list/collection.rb
app/serializers/submission_serializer/application.rb
app/serializers/submission_serializer/sections/pse_application_details.rb
app/services/adapters/json_application.rb
app/services/pse/find_or_create.rb
app/views/completed_applications/index.html.erb
config/locales/en/dashboard.yml
spec/serializers/submission_serializer/application_spec.rb
spec/serializers/submission_serializer/sections/application_details_spec.rb
spec/serializers/submission_serializer/sections/pse_application_details_spec.rb
spec/services/pse/find_or_create_spec.rb

Provider can submit PSE
CRIMAPP-419
Content for the post submission page is under review.
requires: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/206

Provider can submit PSE

---

app/serializers/submission_serializer/sections/application_details.rb
spec/serializers/submission_serializer/sections/application_details_spec.rb

Submit additional information to the datastore.
[CRIMAPP-425](https://dsdmoj.atlassian.net/browse/CRIMAPP-425)
Submit an application with "More information" confirm that the text added is present in the submitted application when viewed on Apply.
[CRIMAPP-425]: https://dsdmoj.atlassian.net/browse/CRIMAPP-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Crimapp 425 submit additional information

---

app/services/datastore/application_rehydration.rb
spec/services/datastore/application_rehydration_spec.rb

Additional information is added on rehydration.
[CRIMAPP-424](https://dsdmoj.atlassian.net/browse/CRIMAPP-424)
Return an application with "More information" on review.  From Apply, confirm that the "More information" text from the returned application is populated on the rehydrated application.
[CRIMAPP-424]: https://dsdmoj.atlassian.net/browse/CRIMAPP-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Crimapp 424 rhyrdate additional information

---

config/settings.yml

PR to turn on additional information feature flag to prepare for release

Turn on more information feature flag

---

config/locales/en/errors.yml

Update error messages for "Has the case concluded?" 
[CRIMAPP-481](https://dsdmoj.atlassian.net/browse/CRIMAPP-481)
Updated all error messages to match the spreadsheet(link in the ticket description)
[CRIMAPP-481]: https://dsdmoj.atlassian.net/browse/CRIMAPP-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-481 Update error messages

---

config/locales/en/errors.yml

Update error messages for "Has a court remanded your client in custody?"
[CRIMAPP-482](https://dsdmoj.atlassian.net/browse/CRIMAPP-482)
Updated all error messages to match the spreadsheet(link in the ticket description)
[CRIMAPP-482]: https://dsdmoj.atlassian.net/browse/CRIMAPP-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-482 Update error messages

---

app/controllers/developer_tools/crime_applications_controller.rb

Non-means tested value and navigation stack update in dev tools controller needs removing as the question is not always there depending on feature flag.

Remove non means tested answer and nav stack from dev tools

---

app/services/decisions/dwp_decision_tree.rb
config/routes.rb
config/settings.yml
spec/services/decisions/dwp_decision_tree_spec.rb

Removes evidence upload feature flag

Remove evidence upload feature flag

---

app/presenters/summary/sections/more_information.rb
app/presenters/tasks/more_information.rb
app/serializers/submission_serializer/sections/application_details.rb
app/serializers/submission_serializer/sections/pse_application_details.rb
app/services/decisions/case_decision_tree.rb
app/services/decisions/evidence_decision_tree.rb
config/settings.yml
spec/presenters/tasks/more_information_spec.rb
spec/services/decisions/case_decision_tree_spec.rb
spec/services/decisions/evidence_decision_tree_spec.rb

Remove more information feature flag

Remove more information feature flag

---

app/forms/steps/base_form_object.rb

Remove unrequired comment

---

app/models/case.rb
app/presenters/tasks/case_details.rb
spec/models/case_spec.rb

Update the completeness logic of case details
[CRIMAPP-489](https://dsdmoj.atlassian.net/browse/CRIMAPP-489)
This is the temporary fix to check the completeness of the case journey. Either we can use this solution to check completeness of journeys or need to  find another one. 
Partially filled case details shows "COMPLETED" label 
Partially filled case details shows "IN PROGRESS" label
/applications/:id/edit
[CRIMAPP-489]: https://dsdmoj.atlassian.net/browse/CRIMAPP-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-489 check pre order work form completeness

---

Gemfile
Gemfile.lock
app/models/capital.rb
app/serializers/submission_serializer/definitions/saving.rb
app/serializers/submission_serializer/sections/means_details.rb
app/services/adapters/structs/capital_details.rb
app/services/adapters/structs/crime_application.rb
app/services/datastore/application_rehydration.rb
config/locales/en.yml
spec/serializers/submission_serializer/application_spec.rb
spec/serializers/submission_serializer/definitions/saving_spec.rb
spec/serializers/submission_serializer/sections/means_details_spec.rb
spec/services/adapters/structs/crime_application_spec.rb
spec/services/datastore/application_rehydration_spec.rb
spec/services/datastore/application_submission_spec.rb

Adds rehydration of Capital
[CRIMAPP-556](https://dsdmoj.atlassian.net/browse/CRIMAPP-556)
[CRIMAPP-535](https://dsdmoj.atlassian.net/browse/CRIMAPP-535)
[CRIMAPP-556]: https://dsdmoj.atlassian.net/browse/CRIMAPP-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-535]: https://dsdmoj.atlassian.net/browse/CRIMAPP-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-535 savings rehydration

---

Gemfile
Gemfile.lock
app/serializers/submission_serializer/definitions/national_savings_certificate.rb
app/serializers/submission_serializer/sections/means_details.rb
app/services/adapters/structs/capital_details.rb
app/services/datastore/application_rehydration.rb
spec/presenters/summary/html_presenter_spec.rb
spec/serializers/submission_serializer/definitions/national_savings_certificate_spec.rb
spec/serializers/submission_serializer/sections/means_details_spec.rb
spec/services/datastore/application_rehydration_spec.rb

Submit and rehydrate National Savings Certificates
[CRIMAPP-582](https://dsdmoj.atlassian.net/browse/CRIMAPP-582)
[CRIMAPP-582]: https://dsdmoj.atlassian.net/browse/CRIMAPP-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-582 submit and rehydrate National Savings Certificates

---

config/inactive_offices.yml

Request to make office code inactive that has appeared in the list of a firm who are not associated with said office code
Made decision to make code inactive for the time being and raise with CWA
More details can be found in [this slack thread](https://mojdt.slack.com/archives/C03JS4V9TPU/p1710863676760209)

Make office code inactive

---

config/settings.yml

Enable PSE in production
[CRIMAPP-509](https://dsdmoj.atlassian.net/browse/CRIMAPP-509)
[CRIMAPP-509]: https://dsdmoj.atlassian.net/browse/CRIMAPP-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-509 Enable PSE on production

---

config/settings.yml

Enable summary cards on prod

---

app/controllers/steps/outgoings/answers_controller.rb
app/presenters/summary/html_presenter.rb
app/services/decisions/outgoings_decision_tree.rb
app/views/steps/outgoings/answers/edit.html.erb
config/locales/en/steps.yml
config/routes.rb
spec/controllers/steps/outgoings/answers_controller_spec.rb
spec/presenters/summary/html_presenter_spec.rb
spec/services/decisions/outgoings_decision_tree_spec.rb

Add "Check your answers" page to outgoings section
https://dsdmoj.atlassian.net/browse/CRIMAPP-259
> [!IMPORTANT]  
> -Special attention required for **outgoings_decision_tree.rb**
> -"Payments your client pays" section is not implemented yet, so separate ticket is required
- http://localhost:3000/applications/:id/steps/outgoings/housing_payments_where_client_lives
- http://localhost:3000/applications/:id/steps/outgoings/check_your_answers_capital

CRIMAPP-259 Outgoings check your answers page to outgoings section

---

app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/income_benefits_details.rb
app/presenters/summary/sections/income_payments_details.rb
app/presenters/summary/sections/payment_details.rb
app/services/adapters/structs/crime_application.rb
config/locales/en/summary.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/summary/sections/housing_payments_spec.rb
spec/presenters/summary/sections/income_benefits_details_spec.rb
spec/presenters/summary/sections/income_payments_details_spec.rb
spec/services/adapters/structs/income_details_spec.rb
spec/services/datastore/application_rehydration_spec.rb

Add Income Payments/Benefits to CYA

---

Gemfile
Gemfile.lock

Upgrade schema to v1.0.61

---

app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/outgoings_payments_details.rb
app/presenters/summary/sections/payment_details.rb
config/locales/en/summary.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/summary/sections/income_benefits_details_spec.rb
spec/presenters/summary/sections/outgoings_payments_details_spec.rb

Add outgoings payments to CYA
https://dsdmoj.atlassian.net/browse/CRIMAPP-707

[CRIMAPP-707] Add outgoings payments to CYA

---

app/views/shared/_eforms_redirect.en.html.erb

Add new content for the exit page behind the means journey feature flag
[CRIMAPP-712](https://dsdmoj.atlassian.net/browse/CRIMAPP-712)
Before change/with feature flag turned off: 
With the feature flag turned on: 
[CRIMAPP-712]: https://dsdmoj.atlassian.net/browse/CRIMAPP-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-712 exit page content

---

app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/overview.rb
app/services/adapters/structs/crime_application.rb
spec/presenters/summary/sections/overview_spec.rb

Show correct overview section for pse
https://dsdmoj.atlassian.net/browse/CRIMAPP-674

[CRIMAPP-674] Show correct overview section for pse

---

config/locales/en/summary.yml
spec/requests/dashboard_spec.rb

Update summary card copy for straightforward changes
https://dsdmoj.atlassian.net/browse/CRIMAPP-695 - more involved changes will possibly be deprioritised

Update summary card copy

---

app/models/concerns/type_of_means_assessment.rb
app/validators/capital_assessment/answers_validator.rb
spec/validators/capital_assessment/answers_validator_spec.rb

Summary only and Appeal to Crown Ct applications only require trust fund and frozen asset capital questions to be answered.
[CRIMAPP-760](https://dsdmoj.atlassian.net/browse/CRIMAPP-760)
[CRIMAPP-760]: https://dsdmoj.atlassian.net/browse/CRIMAPP-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Skip capital validations if does not require full capital

---

app/models/concerns/type_of_means_assessment.rb
app/services/decisions/case_decision_tree.rb
app/value_objects/benefit_type.rb
spec/services/decisions/case_decision_tree_spec.rb
spec/services/decisions/income_decision_tree_spec.rb
spec/validators/application_fulfilment_validator_spec.rb
spec/validators/income_assessment/answers_validator_spec.rb

Check if means test is required on after IoJ decision.
[CRIMAPP-783](https://dsdmoj.atlassian.net/browse/CRIMAPP-783)
See ticket
[CRIMAPP-783]: https://dsdmoj.atlassian.net/browse/CRIMAPP-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-783 check passporting for after ioj decision

---

.rubocop.yml
app/models/concerns/type_of_application.rb
app/models/concerns/type_of_means_assessment.rb
app/models/crime_application.rb
app/presenters/summary/html_presenter.rb
app/presenters/tasks/case_details.rb
app/presenters/tasks/client_details.rb
app/presenters/tasks/ioj.rb
app/services/decisions/case_decision_tree.rb
app/validators/application_fulfilment_validator.rb
app/validators/client_details/answers_validator.rb
config/locales/en/errors.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/tasks/client_details_spec.rb
spec/presenters/tasks/ioj_spec.rb
spec/validators/application_fulfilment_validator_spec.rb
spec/validators/client_details/answers_validator_spec.rb

Validate client details answers
Validate client detail completeness on submission
[CRIMAPP-781](https://dsdmoj.atlassian.net/browse/CRIMAPP-781)
Confirm task list status correct with all types of application (u18, PSE, initial, passported, not means tested, etc).
[CRIMAPP-781]: https://dsdmoj.atlassian.net/browse/CRIMAPP-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-781 understands when client details complete.

---

app/forms/steps/evidence/upload_form.rb
app/lib/errors.rb
app/models/concerns/person_with_dob.rb
app/services/evidence/prompt.rb
app/services/evidence/rule.rb
app/views/steps/evidence/upload/edit.en.html.erb
config/locales/en/evidence.yml
config/locales/en/steps.yml
spec/forms/steps/evidence/upload_form_spec.rb
spec/services/evidence/prompt_spec.rb

Extracts minimum for release from https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/818

Crimapp 649 add interim checks to evidence prompt

---

config/settings.yml

Enable means journey on production

---

.rubocop.yml
app/models/case.rb
app/services/decisions/case_decision_tree.rb
app/validators/case_details/answers_validator.rb
spec/models/case_spec.rb
spec/presenters/tasks/capital_assessment_spec.rb
spec/presenters/tasks/case_details_spec.rb
spec/services/decisions/case_decision_tree_spec.rb
spec/validators/case_details/answers_validator_spec.rb

Case details are only shown as complete on the task list when complete.
[CRIMAPP-775](https://dsdmoj.atlassian.net/browse/CRIMAPP-775)
Case details did not fully understand when it was complete. This PR uses the same pattern as applied to the means sections to ensure we understand when CaseDetails are complete.
See ticket for acceptance
[CRIMAPP-775]: https://dsdmoj.atlassian.net/browse/CRIMAPP-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-775 require next hearing date for complete

---

config/inactive_offices.yml

[CRIMAPP-880](https://dsdmoj.atlassian.net/browse/CRIMAPP-880)
[CRIMAPP-880]: https://dsdmoj.atlassian.net/browse/CRIMAPP-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-880] Inactive office code request

---

app/models/concerns/type_of_application.rb
app/services/decisions/base_decision_tree.rb
app/services/decisions/client_decision_tree.rb
app/services/decisions/submission_decision_tree.rb
app/validators/client_details/answers_validator.rb
spec/services/decisions/client_decision_tree_spec.rb
spec/services/decisions/submission_decision_tree_spec.rb
spec/validators/client_details/answers_validator_spec.rb

[CRIMAPP-893](https://dsdmoj.atlassian.net/browse/CRIMAPP-893)
[CRIMAPP-893]: https://dsdmoj.atlassian.net/browse/CRIMAPP-893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Crimapp 893 u18 appeal no changes

---

Gemfile
Gemfile.lock
app/forms/steps/capital/property_owner_fieldset_form.rb
app/forms/steps/capital/property_owners_form.rb
app/models/payment.rb
app/services/adapters/structs/income_details.rb
app/services/datastore/application_rehydration.rb
app/value_objects/property_relationship_type.rb
db/migrate/20240510150029_add_new_attributes.rb
db/schema.rb
spec/forms/steps/capital/property_owners_form_spec.rb
spec/models/property_owner_spec.rb
spec/presenters/summary/html_presenter_spec.rb
spec/services/adapters/structs/applicant_spec.rb
spec/services/adapters/structs/capital_details_spec.rb
spec/services/adapters/structs/income_details_spec.rb
spec/services/adapters/structs/outgoings_details_spec.rb
spec/services/datastore/application_rehydration_spec.rb

Adds attributes required for unemployed partner journey
[CRIMAPP-840](https://dsdmoj.atlassian.net/browse/CRIMAPP-840)
Could test an application all the way to resubmission to check it hasn't broken anything
[CRIMAPP-840]: https://dsdmoj.atlassian.net/browse/CRIMAPP-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-840] Add unemployed partner attributes

---

spec/forms/steps/income/client/self_assessment_tax_bill_form_spec.rb

Fix rspec mock error

---

app/controllers/steps/income/client/deductions_controller.rb
app/forms/steps/income/client/deduction_fieldset_form.rb
app/forms/steps/income/client/deductions_form.rb
app/models/deduction.rb
app/models/employment.rb
app/services/decisions/income_decision_tree.rb
app/validators/deductions_validator.rb
app/value_objects/deduction_type.rb
app/views/steps/income/client/deductions/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml
config/routes.rb
db/migrate/20240517104105_create_deductions.rb
db/migrate/20240517164736_add_has_no_income_payments_to_employments.rb
db/schema.rb
spec/controllers/steps/income/client/deductions_controller_spec.rb
spec/controllers/steps/income/client/employment_details_controller_spec.rb
spec/forms/steps/income/client/deductions_form_spec.rb
spec/services/decisions/income_decision_tree_spec.rb
spec/value_objects/deduction_type_spec.rb

Add "Deductions from your client’s pay" Page
https://dsdmoj.atlassian.net/browse/CRIMAPP-870
Start employment journey:

Crimapp 870 employed income deductions from your clients pay

---

app/services/datastore/application_rehydration.rb

Fixes sentry error when rehydrating an application: https://mojdt.slack.com/archives/C056U956ESH/p1717495014170419

Temp fix for sentry error when rehydrating partner fields

---

.rubocop.yml
app/forms/steps/income/frozen_income_savings_assets_form.rb
app/views/steps/capital/frozen_income_savings_assets_capital/edit.html.erb
app/views/steps/income/frozen_income_savings_assets/edit.html.erb
config/locales/en/errors.yml
config/locales/en/steps.yml
config/locales/en/summary.yml
spec/forms/steps/capital/frozen_income_savings_assets_form_spec.rb
spec/forms/steps/income/frozen_income_savings_assets_form_spec.rb

Add partner to BOTH capital AND income has frozen assets or income questions.
[CRIMAPP-954](https://dsdmoj.atlassian.net/browse/CRIMAPP-954)
THIS ALSO UPDATES THE SAME FORM IN THE INCOME SECTION
[CRIMAPP-954]: https://dsdmoj.atlassian.net/browse/CRIMAPP-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-954 add partner to capital freezing order

---

app/views/steps/capital/savings/edit.html.erb
config/locales/en/steps.yml

Update saving details form heading.
Done as part of: [CRIMAPP-945](https://dsdmoj.atlassian.net/browse/CRIMAPP-945)

Update savings details form header

---

app/forms/steps/income/answers_form.rb
app/forms/steps/outgoings/answers_form.rb
app/forms/steps/outgoings/board_and_lodging_form.rb
app/forms/steps/outgoings/council_tax_form.rb
app/forms/steps/outgoings/housing_payment_type_form.rb
app/forms/steps/outgoings/mortgage_form.rb
app/forms/steps/outgoings/outgoings_more_than_income_form.rb
app/forms/steps/outgoings/outgoings_payments_form.rb
app/forms/steps/outgoings/rent_form.rb
app/views/steps/outgoings/board_and_lodging/edit.html.erb
app/views/steps/outgoings/council_tax/edit.html.erb
app/views/steps/outgoings/housing_payment_type/edit.html.erb
app/views/steps/outgoings/mortgage/edit.html.erb
app/views/steps/outgoings/outgoings_more_than_income/edit.html.erb
app/views/steps/outgoings/outgoings_payments/edit.html.erb
app/views/steps/outgoings/rent/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml
config/locales/en/summary.yml

Adds dynamic partner text to the outgoings forms.
(Updates to CYA pages are forthcoming)
[CRIMAPP-921](https://dsdmoj.atlassian.net/browse/CRIMAPP-921)
[CRIMAPP-989](https://dsdmoj.atlassian.net/browse/CRIMAPP-989)
[CRIMAPP-934](https://dsdmoj.atlassian.net/browse/CRIMAPP-934)
[CRIMAPP-933](https://dsdmoj.atlassian.net/browse/CRIMAPP-933)
[CRIMAPP-932](https://dsdmoj.atlassian.net/browse/CRIMAPP-932)
[CRIMAPP-931](https://dsdmoj.atlassian.net/browse/CRIMAPP-931)
[CRIMAPP-921]: https://dsdmoj.atlassian.net/browse/CRIMAPP-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-989]: https://dsdmoj.atlassian.net/browse/CRIMAPP-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-934]: …

CRIMAPP-921 add partner to outgoings

---

app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/passporting_benefit_check.rb
app/presenters/summary/sections/passporting_benefit_check_partner.rb
app/services/dwp/benefit_check_status_service.rb
config/locales/en/summary.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/summary/sections/passporting_benefit_check_partner_spec.rb
spec/serializers/submission_serializer/sections/client_details_spec.rb
spec/services/dwp/benefit_check_status_service_spec.rb

Adds partner benefit check section to the review your application page 
Scenarios: 
- In the event that a client has a partner, this section will always display. 
- If the check was done on the client, then the partner section will display a no check required message 
- If the benefit check was performed on the partner, the partner section will display the outcome of the check and the client section will display a no check required message 
See screenshots below 
[CRIMAPP-894](https://dsdmoj.atlassian.net/browse/CRIMAPP-894)
Not sure if there is a simple way to dynamically add `:client` to the section heading. I couldn't think of way so left it to display `:client` for now 
**Example 1: When the benefit check was not performed on either the client or the partner** 
**Example 2: When the …

[CRIMAPP-894] Add partner benefit check section to cya

---

app/services/adapters/structs/crime_application.rb

Use safe navigation to avoid nil income_details error'

Fix employment summary section error

---

app/presenters/summary/sections/employment_income.rb
app/presenters/summary/sections/self_assessment_tax_bill.rb
app/presenters/summary/sections/work_benefits.rb
app/services/adapters/structs/crime_application.rb

Fixes issue reported submitting an application and viewing review/completed application pages
https://mojdt.slack.com/archives/C06DFR460F2/p1718176477586939
Sentry alert: https://ministryofjustice.sentry.io/issues/5478509258/?alert_rule_id=15141078&alert_type=issue&notification_uuid=957f7952-01c3-4166-aaa1-bfc5f1e62d05&project=4507142444023808&referrer=slack

Fix review/submission bugs

---

app/controllers/steps/income/partner_employment_status_controller.rb
app/forms/steps/client/has_partner_form.rb
app/forms/steps/income/partner_employment_status_form.rb
app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/partner_employment_details.rb
app/serializers/submission_serializer/sections/income_details.rb
app/services/decisions/income_decision_tree.rb
app/validators/employment_details/answers_validator.rb
app/validators/income_assessment/answers_validator.rb
app/views/steps/income/partner_employment_status/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml
config/locales/en/summary.yml
config/routes.rb
spec/controllers/steps/income/partner_employment_status_controller_spec.rb
spec/forms/steps/client/has_partner_form_spec.rb
spec/forms/steps/income/partner_employment_status_form_spec.rb
spec/presenters/summary/html_presenter_spec.rb
spec/serializers/submission_serializer/sections/income_details_spec.rb
spec/services/decisions/income_decision_tree_spec.rb
spec/validators/employment_details/answers_validator_spec.rb

Includes rehydration, task list validation, and cya/review page 
[CRIMAPP-998](https://dsdmoj.atlassian.net/browse/CRIMAPP-998)
[CRIMAPP-998]: https://dsdmoj.atlassian.net/browse/CRIMAPP-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-998] Add partner employment status page

---

Gemfile
Gemfile.lock

Upgrade schema version to v1.1.13

---

app/services/evidence/rules/20240425222456_benefits_recipient.rb
config/locales/en/evidence.yml
spec/services/evidence/rules/20240425222456_benefits_recipient_spec.rb

Updates benefit evidence rule for partner.

CRIMAPP-991 partner benefit evidence

---

app/services/evidence/rules/20240426002316_self_assessed.rb
spec/services/evidence/rules/20240426002316_self_assessed_spec.rb

Add partner self assessment evidence prompt.

CRIMAPP-991 partner self assesement

---

app/services/evidence/rules/20240426094427_premium_bonds.rb
spec/services/evidence/rules/20240426094427_premium_bonds_spec.rb

Add premium bonds partner prompt

CRIMAPP-991 add parter premium bonds prompt

---

config/locales/en/helpers.yml

Update outgoings payment question content
[CRIMAPP-1042](https://dsdmoj.atlassian.net/browse/CRIMAPP-1042)
[CRIMAPP-1043](https://dsdmoj.atlassian.net/browse/CRIMAPP-1043)
[CRIMAPP-1042]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1043]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1042] Update outgoings content

---

app/controllers/steps/income/client/other_work_benefits_controller.rb
app/controllers/steps/income/partner/other_work_benefits_controller.rb
app/forms/steps/income/partner/other_work_benefits_form.rb
app/services/decisions/income_decision_tree.rb
app/views/steps/income/partner/other_work_benefits/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml
config/routes.rb
db/migrate/20240618132557_add_partner_other_work_benefit_received_to_income.rb
db/schema.rb
spec/controllers/steps/income/partner/other_work_benefits_controller_spec.rb
spec/forms/steps/income/partner/other_work_benefits_form_spec.rb
spec/serializers/submission_serializer/sections/income_details_spec.rb
spec/services/decisions/income_decision_tree_spec.rb

Add page to add any other work benefits for the partner.
[CRIMAPP-1007](https://dsdmoj.atlassian.net/browse/CRIMAPP-1007)
[CRIMAPP-1007]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1007 Add partner other work benefits page

---

app/controllers/steps/income/client/employment_income_controller.rb
app/controllers/steps/income/partner/employment_income_controller.rb
app/forms/steps/income/partner/employment_income_form.rb
app/services/decisions/income_decision_tree.rb
app/views/steps/income/partner/employment_income/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml
config/routes.rb
spec/controllers/steps/income/partner/employment_income_controller_spec.rb
spec/forms/steps/income/partner/employment_income_form_spec.rb
spec/services/decisions/income_decision_tree_spec.rb

Add page for partner employment income
[CRIMAPP-1001](https://dsdmoj.atlassian.net/browse/CRIMAPP-1001)
[CRIMAPP-1001]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1001 Add partner employment income page

---

Gemfile
Gemfile.lock
app/models/income.rb
app/services/adapters/structs/income_details.rb
spec/services/adapters/structs/income_details_spec.rb

Upgrade schema to v1.1.19

---

Gemfile
Gemfile.lock
app/models/income.rb
app/presenters/summary/html_presenter.rb
app/presenters/summary/sections/employment_income.rb
app/presenters/summary/sections/partner_employment_income.rb
app/presenters/summary/sections/partner_self_assessment_tax_bill.rb
app/presenters/summary/sections/partner_work_benefits.rb
app/presenters/summary/sections/work_benefits.rb
app/serializers/submission_serializer/sections/income_details.rb
app/services/adapters/structs/crime_application.rb
app/services/adapters/structs/income_details.rb
app/views/steps/income/answers/edit.html.erb
config/locales/en/steps.yml
config/locales/en/summary.yml
spec/presenters/summary/html_presenter_spec.rb
spec/presenters/summary/sections/partner_employment_income_spec.rb
spec/presenters/summary/sections/partner_work_benefits_spec.rb
spec/presenters/summary/sections/work_benefits_spec.rb
spec/serializers/submission_serializer/sections/income_details_spec.rb

- Add partner employment details (CYA page, Review page)
- Rehydrate partner employments
https://dsdmoj.atlassian.net/browse/CRIMAPP-1008
https://dsdmoj.atlassian.net/browse/CRIMAPP-1025
https://dsdmoj.atlassian.net/browse/CRIMAPP-1028

CRIMAPP-1008,1025,1028 Income CYA  to include employed partner sections

---

config/settings.yml

Disable employment journey for staging

---

app/services/application_purger.rb
spec/services/application_purger_spec.rb

Purge orphaned partner assets.
[CRIMAPP-1127](https://dsdmoj.atlassian.net/browse/CRIMAPP-1127)
[CRIMAPP-1127]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1127 purge orphaned assets

---

app/services/adapters/structs/crime_application.rb
spec/services/adapters/structs/crime_application_spec.rb

Older submitted apps without partner were failing to load.
[CRIMAPP-1131](https://dsdmoj.atlassian.net/browse/CRIMAPP-1131)
[CRIMAPP-1131]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1131 pre partner returns

---

config/settings.yml

Enable partner in production

---

config/inactive_offices.yml

Deactivate office codes for offices out of contract
https://dsdmoj.atlassian.net/browse/CRIMAPP-1046

Deactivate office codes for offices out of contract

---

config/settings.yml

Enable employment journey for staging

---

app/services/evidence/rules/20240426002316_self_assessed.rb
app/services/evidence/rules/20240426014955_benefits_in_kind.rb
spec/services/evidence/rules/20240426002316_self_assessed_spec.rb
spec/services/evidence/rules/20240426014955_benefits_in_kind_spec.rb

Adds partner rules for
https://dsdmoj.atlassian.net/browse/CRIMAPP-1022
Adds checks for partner self self-assessment and work benefits received

[CRIMAPP-1022] Update partner rules 2, 4

---

app/services/evidence/rules/20240426012343_self_employed.rb
spec/services/evidence/rules/20240426012343_self_employed_spec.rb

Updates self employed rule to add partner 
[CRIMAPP-1070](https://dsdmoj.atlassian.net/browse/CRIMAPP-1070)
[CRIMAPP-1070]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1070] Add self employed evidence rule

---

spec/models/income_spec.rb

Add detailed specs for all permutations for Income#income_payments
[CRIMAPP-1153](https://dsdmoj.atlassian.net/browse/CRIMAPP-1153)
[CRIMAPP-1153]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1153 add detailed spec for Income#income_payment

---

config/settings.yml

Turn on employed ff on prod

---

app/presenters/summary/sections/businesses.rb
app/presenters/summary/sections/client_businesses.rb

Guard against there being no income object

Guard against there being no income object

---

app/models/business.rb
app/models/concerns/type_of_employment.rb
app/presenters/summary/components/amount_and_frequency_answer.rb
app/presenters/summary/components/business.rb
app/validators/employment_details/answers_validator.rb
app/validators/partner_employment_details/answers_validator.rb
config/locales/en/steps.yml
spec/models/business_spec.rb
spec/presenters/summary/components/business_spec.rb
spec/validators/employment_details/answers_validator_spec.rb
spec/validators/partner_employment_details/answers_validator_spec.rb

Adds task list validation for businesses to the task list and the review application page
[CRIMAPP-1066](https://dsdmoj.atlassian.net/browse/CRIMAPP-1066)
Note: there are a couple of screens yet to be implemented in the self employed flow so this implements only what is currently available. The validation will be amended as/when the new screens are added 
[CRIMAPP-1066]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1066] Add self employed businesses validation

---

app/forms/steps/income/client/employment_income_form.rb
app/forms/steps/income/partner/employment_income_form.rb
app/value_objects/before_or_after_tax.rb

Fix 'before_or_after_tax' struct issue

---

config/locales/en/helpers.yml
config/locales/en/steps.yml

Fix a couple of headers
[CRIMAPP-1097](https://dsdmoj.atlassian.net/browse/CRIMAPP-1097)
[CRIMAPP-1097]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1097 fix headers on partner journey

---

Gemfile
Gemfile.lock

Bump schema

---

app/services/decisions/income_decision_tree.rb
app/validators/income_assessment/answers_validator.rb
spec/services/decisions/income_decision_tree_spec.rb
spec/validators/income_assessment/answers_validator_spec.rb

Skip 'manage with no income' for self employed
https://dsdmoj.atlassian.net/browse/CRIMAPP-1209

CRIMAPP-1209 - Skip 'manage with no income' for self employed

---

app/views/layouts/govuk_template.html.erb
config/initializers/content_security_policy.rb

Update content security policy config

---

app/services/decisions/income_decision_tree.rb
config/locales/en/helpers.yml
spec/services/decisions/income_decision_tree_spec.rb

Fix routing for when applicant and/or partner employed and self employed

---

config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1227

[CRIMAPP-1227] Evidence upload bug fix

---

app/serializers/submission_serializer/sections/provider_details.rb
spec/serializers/submission_serializer/sections/provider_details_spec.rb

Ensure no partner declaration reason is persisted
https://dsdmoj.atlassian.net/browse/CRIMAPP-1234

CRIMAPP-1234 Ensure no partner declaration reason is persisted

---

app/views/home/index.en.html.erb

Start page content update ahead of self employed and non means release
[CRIMAPP-1236](https://dsdmoj.atlassian.net/browse/CRIMAPP-1236)
[CRIMAPP-1236]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1236] Start page content update

---

app/forms/steps/evidence/upload_form.rb
app/presenters/tasks/evidence_upload.rb
app/validators/application_fulfilment_validator.rb
app/validators/sections_completeness_validator.rb
config/settings.yml
spec/presenters/tasks/evidence_upload_spec.rb
spec/validators/sections_completeness_validator_spec.rb

Adds evidence validation feature flag to accommodate release of self employed and non means 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1238

[CRIMAPP-1238] Add evidence validation feature flag

---

config/settings.yml

Turn on non-means and self-employed ff

---

config/settings.yml

Disable CIFC for hotfix QA

---

config/settings.yml

Enable CIFC on staging

---

config/locales/en/helpers.yml

Update "is means tested?" form content.
[CRIMAPP-1250](https://dsdmoj.atlassian.net/browse/CRIMAPP-1250)
[CRIMAPP-1250]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1250 update is means tested form content

---

Gemfile
Gemfile.lock
app/controllers/steps/case/charges_controller.rb
app/controllers/steps/case/charges_summary_controller.rb
app/controllers/steps/case/codefendants_controller.rb
app/controllers/steps/case/first_court_hearing_controller.rb
app/controllers/steps/case/has_codefendants_controller.rb
app/controllers/steps/case/hearing_details_controller.rb
app/models/business.rb
app/presenters/tasks/ioj.rb
app/serializers/submission_serializer/sections/case_details.rb
app/services/decisions/case_decision_tree.rb
app/validators/case_details/answers_validator.rb
spec/controllers/steps/case/codefendants_controller_spec.rb
spec/controllers/steps/case/first_court_hearing_controller_spec.rb
spec/controllers/steps/case/has_codefendants_controller_spec.rb
spec/controllers/steps/case/hearing_details_controller_spec.rb
spec/presenters/tasks/ioj_spec.rb
spec/services/decisions/case_decision_tree_spec.rb
spec/validators/case_details/answers_validator_spec.rb

Alters user journey to skip codefendants, offences, court hearing questions in addition to IOJ reasons
https://dsdmoj.atlassian.net/browse/CRIMAPP-1244
- Forces change in the application schema
- Updates validation in tasklist

[CRIMAPP-1244] Update Change in Financial Circumstances user journey

---

app/views/home/index.en.html.erb

Update start page content in preparation for cifc release
[CRIMAPP-1253](https://dsdmoj.atlassian.net/browse/CRIMAPP-1253)
[CRIMAPP-1253]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1253] Update start page 

---

config/locales/en/steps.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1255

[CRIMAPP-1255] Update submission text for cifc apps

---

config/settings.yml

Disable evidence prompt validation on staging.

Disable evidence validation on staging

---

config/settings.yml

Turn off CIFC on staging

---

app/validators/application_fulfilment_validator.rb

Fixes bug where application was unable to be submitted due to removal of evidence present check in an [earlier pr](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1064)
https://dsdmoj.atlassian.net/browse/CRIMAPP-1260
Going to get this into staging for qa testing, will follow with a pr to add spec(s)

[CRIMAPP-1260] Application fulfilment means validator fix

---

app/controllers/completed_applications_controller.rb
app/services/datastore/application_counters.rb
spec/requests/dashboard_lists_spec.rb
spec/services/datastore/application_counters_spec.rb

HOT-FIX require current office code for completed applications

---

config/settings.yml

Turn on CIFC on staging

---

config/settings.yml

Enables CIFC change in financial circumstances in production
https://dsdmoj.atlassian.net/browse/CRIMAPP-533
N/A

[CHORE] Enable cifc_journey in PROD

---

app/services/decisions/client_decision_tree.rb
spec/services/decisions/client_decision_tree_spec.rb

Redirect to address details if an address was previously entered manually
[CRIMAPP-1155](https://dsdmoj.atlassian.net/browse/CRIMAPP-1155)
[CRIMAPP-1155]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1155 Show manual address

---

config/locales/en/steps.yml

Content updates to client has partner screen 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1252

[CRIMAPP-1255] Content updates to client has partner screen

---

app/views/steps/submission/confirmation/show.en.html.erb
config/locales/en/steps.yml

Updates the content on the application submitted page to match figma designs
https://dsdmoj.atlassian.net/browse/CRIMAPP-1256

[CRIMAPP-1256] Confirmation page content update

---

config/gatekeeper.yml

Adds office code that has been found to be missing from our service
https://dsdmoj.atlassian.net/browse/CRIMAPP-1270

[CRIMAPP-1270] Add missing office code

---

config/settings.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1170

Turn on evidence validation ff prod

---

app/views/steps/submission/more_information/edit.html.erb
config/locales/en/errors.yml
config/locales/en/helpers.yml
config/locales/en/summary.yml
spec/presenters/summary/components/saving_spec.rb

Various content fixes
https://dsdmoj.atlassian.net/browse/CRIMAPP-1266
Note: there are some property form changes in the ticket but rachel is going to go away and look at the form(s) again so the changes have not been done as part of this PR
**Additional information screen update**
**Outgoings payment form radio option update**
**Income payment form radio option hint update**
**Has benefit evidence form hint text update**
**Savings summary card update**
Go through an application, checking the screens above

[CRIMAPP-1266] Content fixes

---

config/locales/en/helpers.yml
config/locales/en/steps.yml

QA content amends 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1266
**Removes hint text**

[CRIMAPP-1266] QA amends

---

config/gatekeeper.yml

Add missing office code for test user.
[CRIMAPP-1297](https://dsdmoj.atlassian.net/browse/CRIMAPP-1297)
[CRIMAPP-1297]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make both acox office codes active

---

config/inactive_offices.yml

Deactivate office codes
[CRIMAPP-1308](https://dsdmoj.atlassian.net/browse/CRIMAPP-1308)
[CRIMAPP-1308]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAP-1308] deactivate production office codes

---

app/forms/steps/capital/property_address_form.rb
app/forms/steps/income/businesses_form.rb
app/views/steps/capital/property_address/edit.html.erb
config/locales/en/helpers.yml
spec/controllers/steps/capital/property_address_controller_spec.rb
spec/forms/steps/capital/property_address_form_spec.rb
spec/support/shared_examples/has_a_form_subject.rb

Fix linking of error summary to fields on property address form.
https://dsdmoj.atlassian.net/browse/CRIMAPP-679

[CRIMAPP-679] fix address validation

---

spec/support/capybara_helpers.rb
spec/system/applying/non_means_tested_spec.rb

Add system spec for Non-Means tested application
Building on: https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1138

Add system spec for Non-Means tested application

---

app/services/decisions/partner_decision_tree.rb
spec/services/decisions/partner_decision_tree_spec.rb

Move partner nino until after conflict
[CRIMAPP-1299](https://dsdmoj.atlassian.net/browse/CRIMAPP-1299)
[CRIMAPP-1299]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1299] Move partner nino until after conflict

---

app/forms/steps/income/income_benefit_fieldset_form.rb
app/forms/steps/income/partner/income_benefit_fieldset_form.rb
app/validators/income_benefits_validator.rb
app/validators/partner_income_benefits_validator.rb
app/validators/partner_income_payments_validator.rb
config/locales/en/errors.yml
config/locales/en/helpers.yml
spec/forms/steps/income/income_benefits_form_spec.rb

- Updated the missing changes to error messages and input labels identified in QA.
[CRIMAPP-1287](https://dsdmoj.atlassian.net/browse/CRIMAPP-1287)
[CRIMAPP-1287]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1287] Missing income assessment content updates

---

app/services/decisions/address_decision_tree.rb
app/services/decisions/submission_decision_tree.rb
spec/services/decisions/address_decision_tree_spec.rb
spec/services/decisions/submission_decision_tree_spec.rb
spec/system/applying/non_means_tested_spec.rb

- Fix client Nino routing regression.
[LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-3M](https://ministryofjustice.sentry.io/issues/5771654220/)

[LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-3M] fix has_nino regression

---

config/settings.yml

Enable Arc on staging to allow for QA
[CRIMAPP-1181](https://dsdmoj.atlassian.net/browse/CRIMAPP-1181)
[CRIMAPP-1181]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable Arc on staging for QA

---

app/views/about/contact.en.html.erb
config/settings.yml
spec/system/contact_us_page_spec.rb

Update the content of the Contact page with new ways for users to raise case enquiries and ask for technical support.
[CRIMAPP-1314](https://dsdmoj.atlassian.net/browse/CRIMAPP-1314)
[CRIMAPP-1314]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1314] Update contact page content

---

config/locales/en/errors.yml
config/locales/en/helpers.yml

Update `hint` and `error message` while selecting court name on create and update
https://dsdmoj.atlassian.net/browse/CRIMAPP-198

CRIMAPP-198 Updating a court after an initial input fails on a manual input

---

app/javascript/application.js
app/views/layouts/govuk_template.html.erb

Reverts ministryofjustice/laa-apply-for-criminal-legal-aid#1169

Revert "Disable JS "

---

app/controllers/crime_applications_controller.rb
app/controllers/steps/base_step_controller.rb
app/controllers/steps/circumstances_step_controller.rb
app/models/concerns/type_of_application.rb
app/validators/application_fulfilment_validator.rb
app/views/home/index.en.html.erb
app/views/shared/_dashboard_header.html.erb
config/routes.rb
spec/requests/dashboard_spec.rb
spec/services/decisions/client_decision_tree_spec.rb
spec/support/shared_examples/step_controller_shared_examples.rb
spec/validators/application_fulfilment_validator_spec.rb
spec/validators/case_details/answers_validator_spec.rb
spec/validators/circumstances/answers_validator_spec.rb

Remove `cifc_journey` feature flag
https://dsdmoj.atlassian.net/browse/CRIMAPP-1262

CRIMAPP-1262   CIFC | Delete cifc_journey feature flag

---

app/views/about/contact.en.html.erb

Update 'Find out about call charges' links
https://dsdmoj.atlassian.net/browse/CRIMAPP-1314

CRIMAPP-1314 Update links

---

config/settings.yml

Enable `other_charges` in production.
[CRIMAPP-825](https://dsdmoj.atlassian.net/browse/CRIMAPP-825)
[CRIMAPP-825]: https://dsdmoj.atlassian.net/browse/CRIMAPP-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable orher_charges in prod

---

config/gatekeeper.yml
config/inactive_offices.yml

Activate office codes that were previously deactivated or not present.

Update office codes

---

Gemfile
Gemfile.lock

Update to schema version that supports means decision.

Support means decision

---

config/kubernetes/production/ingress.yml

Updated the ModSec rules in production to prevent common false positives on select endpoints.

Update ModSec rules in production

---

config/gatekeeper.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1450

[CRIMAPP-1450] Add new office codes

---

app/controllers/application_searches_controller.rb
app/views/application_searches/_application_search_filter.html.erb
config/routes.rb
config/settings.yml

Prepare search url for UR testing
https://dsdmoj.atlassian.net/browse/CRIMAPP-1452

[CRIMAPP-1452] Search UR prep

---

app/views/application_searches/new.html.erb
app/views/application_searches/search.html.erb
spec/requests/search_spec.rb

Small content fix 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1452

[CRIMAPP-1452] Content fix

---

app/presenters/summary/components/funding_decision.rb
spec/presenters/summary/components/funding_decision_spec.rb

Update the funding decision to show the case ID.
[CRIMAPP-1398](https://dsdmoj.atlassian.net/browse/CRIMAPP-1398)
[CRIMAPP-1398]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1398] Update funding decision fields

---

app/controllers/developer_tools/crime_applications_controller.rb

Noticed on staging that I had missed a couple attributes that need to be set from the last PR

[CRIMAPP-1485] Set missing attributes

---

app/forms/concerns/steps/applicant_and_partner.rb
config/locales/en/helpers.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1418

[CRIMAPP-1418] Content amends to outgoings

---

config/locales/en/summary.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1417

[CRIMAPP-1417] Content amends to income section

---

config/locales/en/helpers.yml
config/locales/en/steps.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1416

[CRIMAPP-1416] URN screen content updates

---

config/gatekeeper.yml
config/inactive_offices.yml

Temporarily enable office codes tomorrow 21st November following request from business
To be disabled again on the 22nd  
https://dsdmoj.atlassian.net/browse/CRIMAPP-1500

[CRIMAPP-1500] Temporarily enable office codes

---

app/views/application_searches/_application_search_filter.html.erb
app/views/application_searches/new.html.erb
app/views/application_searches/search.html.erb
config/locales/en/helpers.yml
spec/requests/search_spec.rb
spec/system/primary_navigation_spec.rb

Update to design for user research next week
https://dsdmoj.atlassian.net/browse/CRIMAPP-1501

[CRIMAPP-1501] Update search UI

---

config/gatekeeper.yml
config/inactive_offices.yml

Reverts ministryofjustice/laa-apply-for-criminal-legal-aid#1266
To be merged/deployed tomorrow (22nd Nov)

Revert "[CRIMAPP-1500] Temporarily enable office codes"

---

config/kubernetes/staging/config_map.yml

[EXPERIMENTAL] Turn on omniauth test mode on staging

---

config/kubernetes/staging/config_map.yml

Reverts ministryofjustice/laa-apply-for-criminal-legal-aid#1269

Revert "[EXPERIMENTAL] Turn on omniauth test mode on staging"

---

config/kubernetes/staging/config_map.yml

For qa purposes
To be reverted after qa

Turn on omniauth test mode on staging

---

app/views/steps/client/date_stamp/edit.html.erb
config/locales/en.yml
config/locales/en/steps.yml

Updates date stamp screen as per design
https://dsdmoj.atlassian.net/browse/CRIMAPP-1491
[Designs](https://www.figma.com/design/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=21630-108389&node-type=frame&t=c2tv2WUfzuKqoB0Z-0)

[CRIMAPP-1491] Update date stamp screen

---

config/kubernetes/staging/config_map.yml

Disable protal on staging

---

app/controllers/application_searches_controller.rb
app/views/application/_header.html.erb
app/views/application_searches/_application_search_filter.html.erb
app/views/application_searches/new.html.erb
app/views/application_searches/search.html.erb
app/views/layouts/_primary_navigation.html.erb
app/views/layouts/application_dashboard.html.erb
app/views/layouts/govuk_template.html.erb
config/routes.rb
config/settings.yml
spec/system/primary_navigation_spec.rb
spec/system/sign_in_spec.rb

Enable submitted application Search in all Environments
https://dsdmoj.atlassian.net/browse/CRIMAPP-1499

Enable submitted application search in all envs

---

config/kubernetes/staging/config_map.yml

Re-enable portal on staging

---

app/views/steps/income/client_has_dependants/edit.html.erb
app/views/steps/income/dependants/edit.html.erb
config/locales/en/errors.yml
config/locales/en/steps.yml

Update dependant's content and validation text.
[CRIMAPP-1504](https://dsdmoj.atlassian.net/browse/CRIMAPP-1504)
[CRIMAPP-1504]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Crimapp 1504 depenants question

---

app/presenters/summary/sections/payment_details.rb
app/presenters/summary/sections/properties.rb
config/locales/en/summary.yml
spec/presenters/summary/sections/income_benefits_details_spec.rb
spec/presenters/summary/sections/income_payments_details_spec.rb
spec/presenters/summary/sections/investments_spec.rb
spec/presenters/summary/sections/outgoings_payments_details_spec.rb
spec/presenters/summary/sections/properties_spec.rb
spec/presenters/summary/sections/savings_spec.rb
spec/support/shared_examples/a_capital_records_section.rb

Updates content on the review application details screen 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1459

[CRIMAPP-1459] Review application content updates

---

config/locales/en.yml

Updates time display to 12hr from 24hr clock where necessary. This impacts the view of the datestamp.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1412

[CRIMAPP-1412] Update time display

---

config/locales/en/helpers.yml
config/locales/en/summary.yml

Content updates to capital section
https://dsdmoj.atlassian.net/browse/CRIMAPP-1462

[CRIMAPP-1462] capital section content amends

---

app/presenters/concerns/has_dynamic_subject.rb
app/presenters/summary/components/base_record.rb
app/presenters/summary/components/business.rb
app/presenters/summary/components/employment.rb
app/presenters/summary/components/grouped_list.html.erb
app/presenters/summary/components/grouped_list.rb
app/presenters/summary/sections/businesses.rb
app/presenters/summary/sections/client_employments.rb
app/presenters/summary/sections/employment_details.rb
app/presenters/summary/sections/income_benefits_details.rb
app/presenters/summary/sections/income_payments_details.rb
app/presenters/summary/sections/partner_employment_details.rb
app/presenters/summary/sections/partner_income_benefits_details.rb
app/presenters/summary/sections/partner_income_payments_details.rb
app/presenters/summary/sections/payment_details.rb
app/views/steps/income/answers/edit.html.erb
app/views/steps/outgoings/answers/edit.html.erb
config/locales/en/steps.yml
config/locales/en/summary.yml
spec/presenters/summary/components/business_spec.rb
spec/presenters/summary/components/grouped_list_spec.rb
spec/presenters/summary/sections/client_employments_spec.rb
spec/presenters/summary/sections/partner_employments_spec.rb

Made content changes to the summary cards as per the latest design.
[CRIMAPP-1508](https://dsdmoj.atlassian.net/browse/CRIMAPP-1508)
[Figma design](https://www.figma.com/design/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=19698-65906&t=Dl32HUvXFHf6vQOF-1)
[CRIMAPP-1508]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1508] Summary card content updates

---

app/forms/steps/evidence/upload_form.rb
app/forms/steps/shared/nino_form.rb
app/models/case/has_other_charges.rb
app/models/concerns/type_of_means_assessment.rb
app/presenters/summary/sections/case_details.rb
app/services/decisions/case_decision_tree.rb
app/services/decisions/dwp_decision_tree.rb
app/services/decisions/income_decision_tree.rb
app/services/passporting/ioj_passporter.rb
app/services/passporting/means_passporter.rb
app/validators/application_fulfilment_validator.rb
app/validators/sections_completeness_validator.rb
app/views/steps/shared/nino/edit.html.erb
config/routes.rb
config/settings.yml
spec/models/case/has_other_charges_spec.rb
spec/models/concerns/type_of_means_assessment_spec.rb
spec/services/decisions/dwp_decision_tree_spec.rb
spec/services/decisions/income_decision_tree_spec.rb
spec/services/passporting/ioj_passporter_spec.rb
spec/validators/application_fulfilment_validator_spec.rb

https://dsdmoj.atlassian.net/browse/CRIMAPP-1328

[CRIMAPP-1328] Remove redundant feature flags

---

app/assets/stylesheets/local/custom.scss
app/views/application_searches/search.html.erb
app/views/completed_applications/index.html.erb
app/views/crime_applications/index.html.erb

Make table overflows scroll when zoomed
[CRIMAPP-1548](https://dsdmoj.atlassian.net/browse/CRIMAPP-1548)
[CRIMAPP-1548]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1548 make app-tables scroll when zoomed

---

app/views/steps/provider_step/_header.html.erb

https://dsdmoj.atlassian.net/browse/CRIMAPP-1550

[CRIMAPP-1550] Remove unrequired aria role attribute

---

app/views/completed_applications/show.html.erb
app/views/steps/capital/answers/edit.html.erb
app/views/steps/income/answers/edit.html.erb
app/views/steps/outgoings/answers/edit.html.erb
app/views/steps/submission/review/edit.html.erb

https://dsdmoj.atlassian.net/browse/CRIMAPP-1559
**At 300% zoom**
**At 300% zoom**

[CRIMAPP-1559] Fix padding when zoomed past 200%

---

config/gatekeeper.yml

Add office 2R125Q
[CRIMAPP-1571](https://dsdmoj.atlassian.net/browse/CRIMAPP-1571)
[CRIMAPP-1571]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1571 add office 2R125Q

---

config/settings.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1575

[CRIMAPP-1575] Replace apply survey link

---

config/locales/en/helpers.yml
config/locales/en/summary.yml
spec/forms/steps/client/case_type_form_spec.rb
spec/presenters/summary/sections/case_details_spec.rb
spec/services/decisions/client_decision_tree_spec.rb
spec/system/applying/appeal_to_crown_court_spec.rb
spec/system/applying/appeal_to_crown_court_with_changes_spec.rb
spec/validators/client_details/answers_validator_spec.rb
spec/validators/supporting_evidence/answers_validator_spec.rb

https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1596
Navigate to /steps/client/case-type

Change "crown court" to title case

---

app/views/steps/submission/confirmation/show.en.html.erb
config/locales/en/steps.yml

https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1638

[CRIMAPP-1638] Amend application complete message on apply

---

app/views/errors/not_enrolled.en.html.erb
config/locales/en/errors.yml
spec/system/sign_in_spec.rb

Small content update
https://dsdmoj.atlassian.net/browse/CRIMAPP-1662

[CRIMAPP-1662] Update heading on not enrolled screen

---

config/locales/en/errors.yml

https://dsdmoj.atlassian.net/browse/CRIMAPP-1662

[CRIMAPP-1662] Update text as per design

---

Dockerfile

Reverting some changes to the Dockerfile to debug  CreateContainerConfigError

Debug container issues

---

config/inactive_offices.yml

Reactivate office
Assurance given to reinstate provider 
https://mojdt.slack.com/archives/C029FEETF26/p1742915890778209?thread_ts=1740584200.793479&cid=C029FEETF26

Reactivate office

---

config/kubernetes/staging/ingress.yml

Updated the ModSec ingress controller on staging for testing purposes ahead of the wider roll out on 15th April.
[Slack message](https://mojdt.slack.com/archives/CH6D099DF/p1743679136065029)

Upgrade ModSec controller on staging

---

Dockerfile

CRIMAPP-1712 Reinstate clamd

---

config/kubernetes/staging/deployment-clamav.yml

FRESHCLAM_CHECKS is string

---

.trivyignore

Ignore Trivy vulns outside our control

Ignore Trivy vulns outside our control

---

config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

Ignore problematic modSec rules on specific form pages for authenticated users.
[CRIMAPP-1749](https://dsdmoj.atlassian.net/browse/CRIMAPP-1749)
I'd hoped for a cleaner approach, and tried setting a variable to re-used but this failed. It would be good to find a better way of doing this.
[CRIMAPP-1749]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1749] adjust ModSec rules for logged in user input

---

config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

PR to remove problematic ModSec rules from saml auth
[CRIMAPP-1747](https://dsdmoj.atlassian.net/browse/CRIMAPP-1747)
[CRIMAPP-1747]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1747] remove problem modsec rules from auth

---

config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

Remove ModSec rule 932260 from saml endpoint
[CRIMAPP-1748](https://dsdmoj.atlassian.net/browse/CRIMAPP-1748)
On I missed in the first round
[CRIMAPP-1748]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1747 saml modsec part2

---

config/kubernetes/staging/config_map.yml

Temporarily disable staging for testing on staging

Temporarily disable portal on staging for testing

---

config/kubernetes/staging/config_map.yml

Reverts ministryofjustice/laa-apply-for-criminal-legal-aid#1414

Revert "Temporarily disable portal on staging for testing"

---

config/kubernetes/production/ingress.yml

Redirect production service to holding page

Redirect production to the holding page

---

app/views/steps/dwp/has_benefit_evidence/edit.html.erb
config/inactive_offices.yml
config/locales/en/helpers.yml
config/locales/en/steps.yml

https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1789
steps/dwp/has-benefit-evidence

[CRIMAPP-1789] Amend what evidence PPB needs to contain

---

config/kubernetes/staging/ingress.yml

Expand staging allowlist to include global protect

Expand staging allowlist to include global protect

---

config/kubernetes/staging/ingress.yml

Fix ModSec Rule ID collision and include VR ip's in allowlist.

Fix ModSec and rule ID collision.

---

.github/workflows/snyk-infrastructure.yml

This updates the Snyk IaC scanner workflow to allow us to run it on demand.

Allow Snyk IaC workflow to be run on demand

---

config/settings.yml

Disable developer tools on staging

---

app/views/layouts/_language_toggle.html.erb
app/views/layouts/application.html.erb
app/views/layouts/govuk_template.html.erb
config/settings.yml
spec/system/language_toggle_spec.rb

Feature flag language toggle

---

app/views/steps/dwp/cannot_check_dwp_status/edit.html.erb
config/locales/cy/helpers.yml
config/locales/cy/summary.yml
config/locales/en/helpers.yml
config/locales/en/summary.yml

Updates content when checker is unavailable as per design/ticket 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1890

[CRIMAPP-1890] Update checker unavailable content

---

config/application.rb
config/kubernetes/preprod/config_map.yml
config/kubernetes/production/config_map.yml
config/kubernetes/staging/config_map.yml

This period is a reduction from the previous 24 hours and aligns with the reauthentication period used by SILAS Entra service.

Reauthenticate every 12 hours

---

config/gatekeeper.yml
config/inactive_offices.yml

- Updates the active and inactive office codes based on the latest information.
[CRIMAPP-1902](https://dsdmoj.atlassian.net/browse/CRIMAPP-1902)
[CRIMAPP-1902]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1902] Update office codes

---

config/kubernetes/production/config_map.yml
config/kubernetes/production/ingress.yml
config/settings.yml

- Update production ingress for restoration
- Configure SILAS in production
- Use static list for office codes in preprod and production
[CRIMAPP-1897](https://dsdmoj.atlassian.net/browse/CRIMAPP-1897)
[CRIMAPP-1897]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1897] update production ingress and SILAS config

---

config/settings.yml

Enable PDA in staging
This reverts commit 7c74e6566c1bdb5c44d4d1493d0a8ad2aace2a52.

Revert "Disable PDA in staging (#1502)"

---

config/application.rb

[CRIMAPP-1921](https://dsdmoj.atlassian.net/browse/CRIMAPP-1921)
[CRIMAPP-1921]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1921] enable STS preloading

---

config/application.rb
config/kubernetes/preprod/ingress.yml
config/kubernetes/production/ingress.yml
config/kubernetes/staging/ingress.yml

Set STS preloading in the ingress
[CRIMAPP-1921](https://dsdmoj.atlassian.net/browse/CRIMAPP-1921)
[CRIMAPP-1921]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1921] set STS preloading in ingress

---

config/locales/cy/layouts.yml

Give service name welsh translation

---

config/settings.yml

Activate welsh language toggle on Staging

---

config/settings.yml

[CRIMAPP-1942] Set deletion event ff to true on staging

---

config/kubernetes/staging/config_map.yml

Use latest provider data on staging

[CRIMAPP-1952] use Sept 25 provider data on staging

---

app/lib/provider_data_api/active_office_codes_filter.rb
app/lib/provider_data_api/get_office_schedules.rb
spec/lib/provider_data_api/active_office_codes_filter_spec.rb

Refactor ActiveOfficeFilter to use GetOfficeSchedules
[CRIMAPP-1952](https://dsdmoj.atlassian.net/browse/CRIMAPP-1952)
[CRIMAPP-1952]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1952] ActiveOfficeFilter uses GetOfficeSchedules
