- config/kubernetes/staging/config_map.yml
- config/kubernetes/staging/deployment.tpl
- config/kubernetes/staging/disruption.yml
- config/kubernetes/staging/ingress.yml
- config/kubernetes/staging/service.yml
This is the basic configuration to be able to deploy the Hello World app.
I'm not adding a secrets file just yet as that can be a bit more involved with git-crypt, but that will be next, and will also allow us to set the http basic-auth credentials.
Note: once we have a Rails app we need to replace the port `9292` with the standard `3000`, but other than that, and maybe adding the RDS endpoint, this should all continue to be valid.
> CAD-323 Add initial kubernetes manifest files

- .dockerignore
- .github/workflows/test-build-deploy.yml
- config/kubernetes/staging/ingress.yml
Follow-up to PR #3 to finalise the deploy pipeline.
This is a basic pipeline with a test, build and deploy jobs. However the test step will do little right now until we actually have... tests.
Also on second thought I've manually created an http basic-auth secret so it can be used in the ingress and the deployed app is not left wide open.
This secret is not yet committed to the repo until we setup git-crypt etc. Credentials will be shared in confluence/slack.
> CAD-323 Add Github workflow for CI/CD

- config/kubernetes/staging/disruption.yml
This fixes a deprecation warning:
```Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget```
> Change PodDisruptionBudget apiVersion

- Brewfile
- README.md
- app/javascript/application.js
- config/importmap.rb
- package.json
- yarn.lock
We are pinning the `govuk-frontend` JS to the `importmap.rb` and
also ensuring same version is pinned as a postinstall yarn script.
Added instructions on how to build and run the app to the README.
> Add govuk-frontend javascript as import-map

- lib/tasks/rspec.rake
- lib/tasks/rubocop.rake
Follow-up to PR #14.
Some tasks rely on gems only included in specific Gemfile groups (like `development` and/or `test`).
On building the docker image, we exclude those groups from the Gemfile (as we run on `production`).
We need to guard these tasks against trying to require unavailable gems, or the build will fail.
> Ensure env is correct for rspec and rubocop tasks

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/helpers/form_builder_helper.rb
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/govuk_template.html.erb
- config/initializers/form_builder.rb
- config/locales/en.yml
- config/locales/en/helpers.yml
- spec/helpers/application_helper_spec.rb
- spec/helpers/form_builder_helper_spec.rb
In preparation for the step-by-step journey and the different form elements, first we add the Form Builder which is 100% compatible with GOV.UK Frontend.
https://govuk-form-builder.netlify.app
https://github.com/DFE-Digital/govuk-formbuilder
Some basic configuration to customise the default tags and size (these can be override on individual elements).
Also added some basic helpers to the `ApplicationHelper` to deal with the service name and the title of the pages.
> CRIMAP-13 Add DfE Form Builder and configuration

- app/attributes/yes_no_type.rb
- app/value_objects/value_object.rb
- app/value_objects/yes_no_answer.rb
- config/initializers/attribute_types.rb
- spec/attributes/yes_no_type_spec.rb
- spec/value_objects/value_object_spec.rb
- spec/value_objects/yes_no_answer_spec.rb
This value object along with its custom Type can be used for basic yes-no step questions.
It will be used for the first time in a follow-up PR to implement the `client has a partner` question.
> CRIMAP-11 Add yes-no value object

- .github/workflows/test-build-deploy.yml
- app/controllers/application_controller.rb
- app/forms/steps/base_form_object.rb
- app/helpers/steps_helper.rb
- app/models/crime_application.rb
- app/views/layouts/_step_header.html.erb
- config/application.rb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- db/migrate/20220712141730_add_crime_applications_table.rb
- db/schema.rb
- spec/forms/steps/base_form_object_spec.rb
- spec/helpers/steps_helper_spec.rb
- spec/rails_helper.rb
- spec/support/view_spec_helpers.rb
Just a pretty much empty table, only attributes are timestamps and a `navigation_stack` that will be used for the back link.
Also some step helpers used to build the forms, the back link and show errors.
Trying to split as much as possible all the steps framework but unsure the test coverage will pass as some methods etc. are tested via other tests and shared examples not yet included here.
> CRIMAP-11 Add main DB table and step helpers

- app/controllers/healthcheck_controller.rb
- config/kubernetes/staging/deployment.tpl
- config/routes.rb
- spec/requests/healthcheck_spec.rb
Ticket: https://dsdmoj.atlassian.net/browse/CRIMAP-31
This endpoint `/ping` exposes currently deployed build details and also can be used as a lightweight probe.
The ENV variables are exposed in the Dockerfile, and passed as `build-arg` when building the image in the deploy pipeline.
I've also pointed the k8s probes to the new /health endpoint created in PR #19.
> CRIMAP-31 Add ping endpoint to expose build info

- config/kubernetes/staging/ingress.yml
Ticket https://dsdmoj.atlassian.net/browse/CRIMAP-16
To improve security of the Cloud Platform they have introduced new v1 Ingress Controllers.
Tweaked the existing ingress manifest as per documentation here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/Switch-ingress-to-v1-ingress-controller.html#switch-ingress-to-the-new-nginx-ingress-controller-v1-2
And slack convo here:
https://mojdt.slack.com/archives/CH6D099DF/p1657794137979789
This would have incur a minor downtime but because this service is not live/production we can do this all in one go.
To not incur downtime there are specific instructions to do it in 2-steps creating a separate ingress controller.
> CRIMAP-16 Update to new ingress controller

- app/controllers/application_controller.rb
- app/controllers/concerns/error_handling.rb
- app/controllers/errors_controller.rb
- app/controllers/steps/base_step_controller.rb
- app/helpers/steps_helper.rb
- app/lib/errors.rb
- app/views/errors/application_not_found.html.erb
- app/views/errors/invalid_session.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unhandled.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/routes.rb
- spec/controllers/application_controller_spec.rb
- spec/helpers/steps_helper_spec.rb
- spec/requests/errors_spec.rb
- spec/support/shared_examples/step_controller_shared_examples.rb
Handling of a few common errors, like invalid session or `ApplicationNotFound` (this one still not really in use until we have the applications dashboard functionality). No doubt there will be more.
The error pages copy is kind of placeholder, generic copy. This will have to revised at some point in the future.
https://dsdmoj.atlassian.net/browse/CRIMAP-6
Example of an error, all are very similar just changing the copy:
You can access each of the error pages by using their URL, for example:
http://localhost:3000/errors/not_found
http://localhost:3000/errors/application_not_found
http://localhost:3000/errors/invalid_session
In production, any URL that doesn't exist will trigger the not found error page. In non-production the exception is shown in the browser on purpose for debug purposes.
> CRIMAP-6 Add basic error handling and error pages

- .rubocop.yml
- app/controllers/steps/base_step_controller.rb
- app/controllers/steps/client/details_controller.rb
- app/forms/concerns/steps/has_one_association.rb
- app/forms/steps/client/details_form.rb
- app/models/applicant_detail.rb
- app/models/applicant_details.rb
- app/models/crime_application.rb
- app/services/decisions/client_decision_tree.rb
- app/views/steps/client/details/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20220721131958_create_applicant_details_table.rb
- db/schema.rb
- spec/controllers/steps/client/details_controller_spec.rb
- spec/forms/steps/client/details_form_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
- spec/support/shared_examples/form_validation_shared_examples.rb
This step is a bit more elaborated and we are going to need form objects to work with `has_one` records (a crime application has one applicant details).
This can be used as well as an example for similar steps.
For now, I'm leaving the date field (DOB) to simplify the form object.
Individual commits with more details.
https://dsdmoj.atlassian.net/browse/CRIMAP-32
> CRIMAP-32 Add client details step to journey

- app/controllers/steps/client/has_nino_controller.rb
- app/forms/steps/client/has_nino_form.rb
- app/services/decisions/client_decision_tree.rb
- app/views/home/nino_no.html.erb
- app/views/home/nino_yes.html.erb
- app/views/steps/client/has_nino/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/client/has_nino_controller_spec.rb
- spec/forms/steps/client/has_nino_form_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Add form to collect client Nino details + specs / validations
atm validations for NINO format are in the form, but these could be moved to a custom validator at some future point if needed.
Also added some holding pages for the progression of the form steps (`nino_yes.html.erb` and `nino_no.html.erb`) that can be removed as we build out more steps.
[CRIMAP](https://dsdmoj.atlassian.net/browse/CRIMAP-44)
- please check that our 'conventions' are followed 👍  
Format Error:
Blank error:
Run through the stepped journey form  `/has_partner`:
- `/details` on completion now routes to `has_nino`
- check validations on `/has_nino`:
- if radios are blank it errors saying choose one 
- if yes selected and NINO is blank or incorrect then it will error saying that you need to enter a NINO in the right …
> CRIMAP-44 Enter client's NINO step

- app/controllers/sessions_controller.rb
- app/views/home/index.html.erb
- app/views/layouts/_developer_tools.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- config/settings.yml
- spec/controllers/sessions_controller_spec.rb
Just some basic operations for now. It is behind a feature flag, enabled in development/staging envs, disabled on production (although we don't have yet prod).
https://dsdmoj.atlassian.net/browse/CRIMAP-10
As we develop more of the app, we might have to change some of the links/actions but that is OK, this is supposed to help us get quicker to some steps / pre-fill something etc. For now we don't have a lot anyways.
I tried to use a request spec, instead of controller spec, and couldn't make it work to check the `reset_session` was being called as apparently request specs don't have access to the session. So instead of having one test (the redirect) in the request spec, and another test (the reset session) in the controller spec, I opted for having all in the controller spec...
> CRIMAP-10 Add developer tools to footer

- app/controllers/sessions_controller.rb
- app/forms/steps/client/details_form.rb
- app/forms/steps/client/has_nino_form.rb
- app/models/applicant.rb
- app/models/applicant_details.rb
- app/models/concerns/has_contact_details_through_people.rb
- app/models/contact_details.rb
- app/models/crime_application.rb
- app/models/partner.rb
- app/models/person.rb
- db/migrate/20220801144304_create_people_table.rb
- db/migrate/20220801144512_drop_applicant_details_table.rb
- db/migrate/20220801144607_create_contact_details_table.rb
- db/schema.rb
- spec/forms/steps/client/details_form_spec.rb
- spec/forms/steps/client/has_nino_form_spec.rb
- spec/models/crime_application_spec.rb
To anticipate for when we have `partner`, it makes more sense to have a `Person` superclass with 2 (for now and probably not to change ever) subclasses `Applicant` and `Partner`.
Also to prepare for the contact details, it makes more sense for these to be a `has_one` relationship on each person. However trying to simplify second level relationships, we expose 2 `has_one through` relationships on the `crime_application` so it keeps behaving kind of like a 1st level relation and our form object are kept simple.
This work is partially motivated by the following story:
https://dsdmoj.atlassian.net/browse/CRIMAP-60
Everything should continue working but any locally created applicant details will be purged from DB.
> Refactor people relationships and prepare contact details

- app/controllers/steps/contact/home_address_controller.rb
- app/controllers/steps/contact_step_controller.rb
- app/forms/steps/contact/home_address_form.rb
- app/services/decisions/client_decision_tree.rb
- app/services/decisions/contact_decision_tree.rb
- app/views/steps/contact/home_address/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/contact/home_address_controller_spec.rb
- spec/forms/steps/contact/home_address_form_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
- spec/services/decisions/contact_decision_tree_spec.rb
- spec/support/shared_examples/form_validation_shared_examples.rb
- spec/support/shared_examples/step_controller_shared_examples.rb
First part of the journey to enter the home address of the applicant (client's home address).
For now just the manual entry. Postcode lookup will be added later on as a separate one or more PRs.
The code is somehow coupled for now to the applicant as we don't have `partner` yet for the MVP, but in the future I anticipate we could make these controllers / form objects somehow work for partner too with not too much effort.
The database models already supports as of PR #36 to have different contact details for applicant and for partner.
https://dsdmoj.atlassian.net/browse/CRIMAP-60
Manual entry only. After entering details it goes back to home (as we don't have yet following step).
> CRIMAP-60 Add home address manual entry

- app/controllers/steps/client/partner_exit_controller.rb
- app/services/decisions/client_decision_tree.rb
- app/views/home/nino_no.html.erb
- app/views/home/nino_yes.html.erb
- app/views/home/selected_no.html.erb
- app/views/home/selected_yes.html.erb
- app/views/shared/_eforms_redirect.en.html.erb
- app/views/steps/client/nino_exit/show.html.erb
- app/views/steps/client/partner_exit/show.html.erb
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/client/partner_exit_controller_spec.rb
- spec/requests/home_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Adds eFroms redirect to `/has_partner` page if applicant has a partner (selects 'yes')
- I haven't added to the request spec for the eforms redirect as I think it is covered by the nino_exit path.
- Also removed some the temp `selected_yes/no` routes views for has_partner and has_nino as these now have places to go as extra steps have been added.
- start application > at has partner? select 'Yes' > submit
- should go to eForms redirect page.
> Add eForms redirect when there is a partner

- app/assets/stylesheets/local/info_card.scss
- app/views/shared/_eforms_redirect.en.html.erb
Improving button contrast and slightly bigger font-size in the link.
Removing unused class `app-inverted-narrow-width`.
> Minor styling tweak in the info card

- app/forms/steps/client/has_nino_form.rb
- app/services/decisions/client_decision_tree.rb
- app/views/steps/client/has_nino/edit.html.erb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/forms/steps/client/has_nino_form_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Slight rework of nino page as per updated design
[CRIMAP-80](https://dsdmoj.atlassian.net/browse/CRIMAP-80)
Check that NINO validation works the same as before.
Check that link to eForms redirect works.
> CRIMAP-80 Implement Nino form redesign

- app/forms/steps/client/contact_details_form.rb
- app/views/steps/client/contact_details/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- db/migrate/20220808161007_add_telephone_number_to_people.rb
- db/schema.rb
- spec/forms/steps/client/contact_details_form_spec.rb
Add phone number input to client/contact_details form view, add very basic validation and enforce presence. Strip spaces prior to validation and storage. 
Adds telephone_number column to people table. 
https://dsdmoj.atlassian.net/browse/CRIMAP-63
rails db:migrate to update people table
Checkout, rails db:migrate, bin/dev - view at http://localhost:3000/steps/client/contact_details
> Add phone number attribute and input

- Gemfile
- Gemfile.lock
- app/forms/steps/address/lookup_form.rb
- app/forms/steps/address/results_form.rb
- app/services/ordnance_survey/address_lookup_results.rb
- app/validators/uk_postcode_validator.rb
- app/views/steps/address/results/edit.html.erb
- config/locales/en/errors.yml
- spec/forms/steps/address/lookup_form_spec.rb
- spec/forms/steps/address/results_form_spec.rb
- spec/services/ordnance/address_lookup_results_spec.rb
Improve the postcode lookup step by ensuring valid UK postcodes are used, as otherwise Ordnance Survey will fail or return no addresses anyways.
It validates against million of postcodes in England, Wales, Scotland, Northern Ireland, the Channel Islands, and the Isle of Man.
I've also checked and it pass for Guernsey and Jersey postcodes too.
Not really related to this validator but I've renamed the Struct method from `address_lines` to `compact_address` to better capture the meaning, and added the city to it because at first glance in the dropdown a provider might want to have the assurance they are looking at results from a city they might expect, particularly important if we are going to skip the address manual entry page after they select an address in the dropdown.
> Add UK postcode validator

- config/importmap.rb
- package.json
- yarn.lock
No breaking changes or new features really, but good to be always in the latest version as they fix things behind the scenes.
Changelog:
https://github.com/alphagov/govuk-frontend/releases/tag/v4.3.0
After checkout, just in case run stop the server, run `rails assets:clobber` and then run `bin/dev` again. Don't think is purely necessary but might avoid any issues.
> deps: Bump to latest GOV.UK Frontend version

- config/importmap.rb
When running `yarn` it will remove the `preload: true` anyways causing a change to the working branch.
Apparently there is no way at the moment of specifying preload when using the `bin/importmap` command.
Once you checkout the branch, run `yarn` to pull the latest npm modules. The `importmap.rb` file should not change.
> Remove preload from importmap

- app/views/steps/address/lookup/edit.html.erb
- app/views/steps/address/results/edit.html.erb
- app/views/steps/client/contact_details/edit.html.erb
- app/views/steps/client/details/edit.html.erb
- app/views/steps/client/has_nino/edit.html.erb
- app/views/steps/client/has_partner/edit.html.erb
- config/initializers/form_builder.rb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- db/schema.rb
We had non-standard defaults set for the form builder. These are good defaults when an app is mainly done by many 1 question per page, as it saves having to set again and again the same tag, size, etc.
But in reality this app will not have that many individual questions and where we have them, we can customise accordingly.
Removed the custom defaults and tweaked the existing pages where needed to output proper markup, tags and sizes.
Also added `autocomplete: 'off'` if it was missing.
Somehow some of the previous PR didn't commit the last version of the schema.rb, I've added it here otherwise migrations can fail.
Visually there is not that much difference, and everything should look pretty much the same.
> Sort out form builder defaults and fix markup

- .rubocop.yml
- app/value_objects/correspondence_type_answer.rb
- app/value_objects/value_object.rb
- app/value_objects/yes_no_answer.rb
- spec/value_objects/correspondence_type_answer_spec.rb
- spec/value_objects/value_object_spec.rb
- spec/value_objects/yes_no_answer_spec.rb
I've probably spent more time that I should on this little QoL thing, but in the end it is kind of nice :-)
Instead of implementing again and again inquiry methods for each of the values on a value-object (although in many cases it is not necessary if they are not inspected later on), now the  superclass `ValueObject` takes care of defining this "question mark" methods to ask a value object about its values.
It iterates through all defined values in the `VALUES` constant declaring methods like `yes?` or `no?` or `home_address?` etc.
Also moved to the superclass the class method `.values`. This makes for leaner value objects, to the point many will only have the `VALUES` constant and nothing else.
Any more complicated inquiry logic can be defined as separated methods in each value object …
> Implement inquiry mechanism for value objects

- Gemfile
- Gemfile.lock
- app/forms/steps/client/contact_details_form.rb
- app/models/person.rb
- app/value_objects/correspondence_type.rb
- spec/forms/steps/client/contact_details_form_spec.rb
- spec/models/person_spec.rb
- spec/value_objects/correspondence_type_spec.rb
Dynamically changes the Correspondence Address selection on the contact details page
[CRIMAP-101](https://dsdmoj.atlassian.net/browse/CRIMAP-101)
- when no home address:
Go through the form to the client details page, you should see all three options available to select a Correspondence address:
- Same as home address
- Provider's address
- Somewhere else
Open rails console, run the following:
```
ha = HomeAddress.last
ha.address_line_one = nil
ha.save
```
Reload the page. You should see only the following options now:
- Provider's address
- Somewhere else
Submit the form - validations should work as before.
> CRIMAP-101 Make corrs selector dynamic

- app/decorators/address_form_decorator.rb
- app/decorators/base_decorator.rb
- app/forms/steps/address/results_form.rb
- app/helpers/application_helper.rb
- app/services/decisions/address_decision_tree.rb
- app/services/decisions/client_decision_tree.rb
- app/views/steps/address/details/edit.html.erb
- app/views/steps/address/lookup/edit.html.erb
- app/views/steps/address/results/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/decorators/address_form_decorator_spec.rb
- spec/decorators/base_decorator_spec.rb
- spec/forms/steps/address/results_form_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/services/decisions/address_decision_tree_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
We had already the home address sub-journey. The correspondence address one is the same but it customise some of the copy and links in the views accordingly.
In order to do this more clean and to copy with future changes if any, a decorator is used, that enhance the form object and expose some helper methods for the i18n, etc.
Also some logic previously existing in the form object has been moved to this decorator (the addresses counter).
Updated the decision trees to be able to enter this sub-journey from the contact details step, if the selected radio is "other address".
https://dsdmoj.atlassian.net/browse/CRIMAP-67
https://dsdmoj.atlassian.net/browse/CRIMAP-68
Select "other address" in the contact details step. After finishing the correspondence address sub-journey you will get back to …
> CRIMAP-67 Add correspondence address sub-journey

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/task_list.scss
- app/controllers/crime_applications_controller.rb
- app/presenters/task_list/base_task_renderer.rb
- app/presenters/task_list/progress_tag.rb
- app/presenters/task_list/task.rb
- app/views/crime_applications/edit.html.erb
- config/locales/en/tasklist.yml
- config/routes.rb
- spec/presenters/task_list/progress_tag_spec.rb
- spec/presenters/task_list/task_spec.rb
This is just a first stab at the task list. For now the markup and styling is as accurate as it gets, also the localisations and the main categories and tasks are there.
However **it has no logic**. It is for now just a first iteration and logic will be added on follow-up PRs, along with any necessary changes and refactors.
The main idea is the task list will be an object (not yet in this version) which has tasks (`Task`), that contain the logic, or knowledge about if they are completed, or in progress, etc. so they can render their corresponding badge (`ProgressTag`).
https://dsdmoj.atlassian.net/browse/CRIMAP-91
This is a first iteration, it is intended to be evolved but didn't want to wait too much as there might be other dependencies with this work in other tickets so at least we have …
> CRIMAP-91 Task list page and basic presenters

- app/controllers/crime_applications_controller.rb
- app/models/person.rb
- spec/controllers/crime_applications_controller_spec.rb
- spec/requests/dashboard_spec.rb
This improves a bit the dashboard `#index` (list) action so that it only returns applications that have advanced enough to at the very least have an applicant with a name, as otherwise the dashboard either blows app (if there is no applicant record yet) or shows a blank name, no link (if the applicant has no name).
Move the index controller test to a `request` test `spec/requests/dashboard_spec.rb` as it makes a lot of sense for this to be a request test, and much easier to test (although slower I reckon as we are not mocking and we are using real records).
https://dsdmoj.atlassian.net/browse/CRIMAP-90
Dashboard will not blow up if there are crime_application records without an applicant relationship. Also, applicants without a `first_name` will not show. Removed N+1 query.
> Return applications having applicants with name

- app/controllers/steps/base_step_controller.rb
- app/helpers/form_builder_helper.rb
- app/views/steps/client/details/edit.html.erb
- app/views/steps/client/has_partner/edit.html.erb
- spec/controllers/steps/client/has_partner_controller_spec.rb
- spec/helpers/form_builder_helper_spec.rb
- spec/support/shared_examples/step_controller_shared_examples.rb
We decided it doesn't make too much sense to show the "Save and come back later" button right from the beginning when the provider didn't enter anything yet.
As we are taking the provider back to the task list, at least we want to wait until past the client details step so they enter first name / last name and there is something to show if they get back to their list of applications.
Made it so we can disable the secondary action in specific steps by passing `secondary: false`. Default it to show secondary action.
I still think it makes more sense to take the provider to their application list (i.e. to the "dashboard") as it will be more likely they want to either continue with another application or start a new one. The task list feels like a weird choice, but at least is easy to change …
> Hide secondary button on some steps

- config/routes.rb
- spec/presenters/tasks/client_details_spec.rb
Small follow-up to PR #70.
Also the steps are now part of this same path, making it more logical when thinking in terms of resources and members:
```
/applications
/applications/:id/edit
/applications/:id/steps/client/has_partner
/applications/:id/steps/client/details
/applications/:id/steps/address/details/:address_id
(...)
```
In terms of functionality everything remains the same, and also named routes are kept the same. This is only an external facing URL rename.
https://dsdmoj.atlassian.net/browse/CRIMAP-115
Check all generated routes with: `rails routes | grep applications`
Delete existing applications in the DB as they may have wrong navigation stack. everything else should work as before.
> Rename routes `crime_applications` to `applications`

- app/forms/steps/address/results_form.rb
- app/services/decisions/address_decision_tree.rb
- spec/forms/steps/address/results_form_spec.rb
- spec/services/decisions/address_decision_tree_spec.rb
If the provider finds a suitable address when using the postcode lookup, after selecting this address and submitting the form, we “skip“ the manual entry page.
This applies to home address and correspondence address.
We've been showing these pages as a way to test/debug the address lookup but the original designs and user journey was to not show them.
Still providers can access these pages when entering addresses manually, and will also be accessible from the CYA when we have it.
https://dsdmoj.atlassian.net/browse/CRIMAP-117
After selecting an address from the dropdown, and submitting the form, the next page is no longer the manual entry (with the address pre-filled) but instead the following step.
For home address that is contact details, and for correspondence address that is the home …
> CRIMAP-117 Skip address manual entry pages

- app/forms/steps/client/has_partner_form.rb
- app/models/crime_application.rb
- app/value_objects/application_status.rb
- db/migrate/20220822103823_add_status_to_crime_applications.rb
- db/schema.rb
- spec/forms/steps/client/has_partner_form_spec.rb
- spec/models/crime_application_spec.rb
- spec/value_objects/application_status_spec.rb
Adds application status to a crime application
I was getting clash errors with the key "initialised" so I settled on "newly_initialised"
Another problem was that the `deafult:` in the migration wasn't working so I decided to set it in the enum declaration instead.
[CRIMAP-116](https://dsdmoj.atlassian.net/browse/CRIMAP-116)
- Create a new application, post has_partner if you get the record from the DB it should have a status of `in_progress`
- from the console create a new record with `CrimeApplication.create` - it should have a default status of `newly_initialised`
> Crimap 116 tidy application statuses

- app/views/crime_applications/edit.html.erb
- app/views/crime_applications/index.html.erb
- app/views/shared/_flash_banner.html.erb
- config/locales/en.yml
- spec/requests/dashboard_spec.rb
Mainly changes in the flash banner markup according to the design system guidelines (position above the page h1, avoid using h3 in banner content).
Added the banner to the `govuk-grid-column-full` container also as per guidelines.
https://design-system.service.gov.uk/components/notification-banner/
Fixed the back link in the task list and removed the back link in the dashboard index as it is not accurate where it will take the user. Civil Apply doesn't have back link in their dashboard either.
https://dsdmoj.atlassian.net/browse/CRIMAP-92
https://dsdmoj.atlassian.net/browse/CRIMAP-95
> Some minor fixes to markup and back links

- app/assets/stylesheets/local/custom.scss
- app/views/crime_applications/index.html.erb
- config/locales/en/dashboard.yml
- spec/requests/dashboard_spec.rb
The vertical alignment (top) in the table rows was driving me crazy LOL.
Now it is aligned in the middle and universe balance has been restored.
Also added a bit of extra markup to the table according to the design system (mainly the `scope` attribute), and i18n.
> Tweak dashboard table css and markup

- app/controllers/crime_applications_controller.rb
- app/forms/steps/client/has_partner_form.rb
- app/models/crime_application.rb
- app/value_objects/application_status.rb
- app/views/crime_applications/index.html.erb
- app/views/shared/_application_status_tag.html.erb
- config/locales/en/shared.yml
- spec/forms/steps/client/has_partner_form_spec.rb
- spec/models/crime_application_spec.rb
- spec/requests/dashboard_spec.rb
- spec/value_objects/application_status_spec.rb
Removes hard coded "IN PROGRESS" from the dashboard and instead gets the value from the application object.
[CRIMAP-116](https://dsdmoj.atlassian.net/browse/CRIMAP-116)
Added a pretty_status method to the CrimeApplication, happy to move to a presenter / decorator at a later date - think its fine here for now.
- create a case > in progress should be viewable on the list page
- in the rails console generate a case with an "initialised" status it should not be viewable on the crime_applications page
> Remove hardcoded status from list and add status from application

- app/lib/refinements/decorate_collection.rb
- app/lib/refinements/present_collection.rb
- config/initializers/refinements.rb
It turned out we don't really need these to be pure refinements as we want these methods to be in all arrays and all AR relations, and we are accomplishing that just by including the modules.
Previous code was working because of that, not really because of the `refine`.
I would keep the structure as in the future we might have pure refinements that are to be used in specific classes or modules in a more surgical way.
> Simplify collection refinements

- app/assets/stylesheets/local/custom.scss
- app/controllers/crime_applications_controller.rb
- app/presenters/crime_application_presenter.rb
- app/presenters/task_list/collection.rb
- app/views/crime_applications/confirm_destroy.html.erb
- app/views/crime_applications/edit.html.erb
- app/views/crime_applications/index.html.erb
- config/locales/en/dashboard.yml
- spec/presenters/crime_application_presenter_spec.rb
- spec/requests/dashboard_spec.rb
Last batch (maybe) of refinements, tidy up and TLC.
Added the right hand column to the task list page, showing the LAA reference. We pick this from the presenter.
Made the reference in the presenter be a bit more dynamic so is more evident clicking through different applications in the dashboard takes you to different task lists (I think the task list should include also the client's name, I've added a comment in figma design).
As we now use the presenter in the task list, and in the destroy page, made the code in the controller a bit more generic.
Tidy up some html markup and extracted to locales some hardcoded strings.
https://dsdmoj.atlassian.net/browse/CRIMAP-91
Nothing special, but If the blue bar in the right hand doesn't show, purge local assets and recompile.
> Add right hand column to task list, markup tidy up

- app/assets/stylesheets/local/custom.scss
- app/presenters/crime_application_presenter.rb
- app/views/crime_applications/edit.html.erb
- config/locales/en.yml
- config/locales/en/dashboard.yml
- spec/presenters/crime_application_presenter_spec.rb
- spec/requests/dashboard_spec.rb
I totally missed there was another figma slide where these details are shown.
Glad we now have the presenter all setup so it was kind of just reusing almost everything, I just added a couple more methods to the presenter.
DRY the time/date format. The `datetime` format is not used yet, but will be used for the stamp date.
https://dsdmoj.atlassian.net/browse/CRIMAP-120
A brand new application will only show the LAA reference. Once the client details step is completed, the task list page for that application will show the additional details.
> Add client details to task list aside

- spec/spec_helper.rb
Updates SimpleCov to use rails specific config option.
There was an issue where it was reporting false positives locally, and after some manual testing it seems like this will fix the issue.
Added some filters for rails classes that are useful to have as starting points for non MVP functionality but don't need to be covered at the moment i.e. jobs / mailers etc.
- run `rake` locally you should have no errors in the coverage report.
- If you take away the `# :nocov` from the `CaseDecisionTree` class, and then rerun rake you will see it will be reported as a failure in the coverage report (this was not happening before this change)
> Use rails specific simplecov config

- app/models/case.rb
- app/models/codefendant.rb
- app/models/crime_application.rb
- config/routes.rb
- db/migrate/20220826083744_create_codefendants_table.rb
- db/schema.rb
- spec/models/codefendant_spec.rb
Just the basic schema that we will require for the co-defendants (a case has many co-defendants, a co-defendant belongs to a case).
Added the routes as well. Rename the existing `cases` namespace to be singular `case` to follow the pattern we have (like `client` or `address`).
https://dsdmoj.atlassian.net/browse/CRIMAP-109
I'm not subclassing `Codefedant` from `Person` because apart from first_name and last_name, all other attributes are not relevant to co-defendants, don't have addresses either, and the relationship is with the Case, not with the CrimeApplication (although we expose a shortcut using `through`).
> CRIMAP-109 Initial co-defendants DB schema and model

- app/controllers/steps/case/urn_controller.rb
- app/forms/steps/case/urn_form.rb
- app/services/decisions/case_decision_tree.rb
- app/services/decisions/client_decision_tree.rb
- app/views/steps/case/urn/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/controllers/steps/case/urn_controller_spec.rb
- spec/forms/steps/case/urn_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Adds URN input to user journey after client contact details input
[CRIMAP-74](https://dsdmoj.atlassian.net/browse/CRIMAP-74)
Follow user journey to create an application. This step is added to follow after client contact details page. 
Designs as per [Figma screen](https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=2773%3A29320)
Follow user journey to create an application. This step is added to follow after client contact details page. 
Check against designs as per [Figma screen](https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=2773%3A29320)
> Add URN step

- app/controllers/steps/base_step_controller.rb
- app/controllers/steps/case/codefendants_controller.rb
- app/controllers/steps/case_step_controller.rb
- app/forms/concerns/steps/has_one_association.rb
- app/forms/steps/case/codefendant_fieldset_form.rb
- app/forms/steps/case/codefendants_form.rb
- app/forms/steps/case/urn_form.rb
- app/models/case.rb
- app/services/decisions/case_decision_tree.rb
- app/validators/codefendants_validator.rb
- app/views/steps/case/codefendants/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/case/codefendants_controller_spec.rb
- spec/forms/steps/case/codefendant_fieldset_form_spec.rb
- spec/forms/steps/case/codefendants_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Follow-up to previous preparation PR #87.
This implements the controller and form object(s) needed for the CRUD step to add/edit/delete co-defendants.
Note: in this PR only add and edit actions are implemented. In a future PR the delete will also be implemented.
Also only first_name and last_name attributes in this PR. Conflict of interest is a separate ticket and will be added later, otherwise the PR grows too much.
There are some ancillary changes in this PR that were needed as this was our first CRUD step really (addresses was kind of different).
The way this works is slightly different to other steps. Basically, we have a main form object, named `CodefendantsForm` which is in charge of rendering the view which is composed of a collection of `CodefendantFieldsetForm` which are like …
> CRIMAP-109 Enter codefendant names

- app/controllers/steps/case/codefendants_controller.rb
- app/forms/steps/case/codefendant_fieldset_form.rb
- app/forms/steps/case/codefendants_form.rb
- app/models/case.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/codefendants/edit.html.erb
- config/locales/en/steps.yml
- spec/controllers/steps/case/codefendants_controller_spec.rb
- spec/forms/steps/case/codefendants_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Follow-up to PR #89.
Implement the delete functionality.
It works automatically thanks to `accepts_nested_attributes_for`.
The only complication is we don't want to run validations when removing a co-defendant, as for once, removing a blank one will give us errors, but also, if any previous co-defendant are edited (like blanking any of their text fields) it will also give us errors on those unrelated fields.
This was solved by bypassing validations if any of the records are marked for destruction (`_destroy` param).
Also, on removal, we circle back to the same page, similar to adding another, but in this case we don't add another blank record obviously.
Note: we only show delete buttons after there is more than 1 co-defendant, as deleting the only one in the page would leave the page …
> CRIMAP-109 Implement co-defendants deletion

- app/forms/steps/case/codefendant_fieldset_form.rb
- app/views/steps/case/codefendants/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- spec/forms/steps/case/codefendant_fieldset_form_spec.rb
- spec/forms/steps/case/codefendants_form_spec.rb
Another follow-up to all previous PRs related to co-defendants.
This I think is the last one. We add the conflict of interest yes-no radios.
Pretty simple PR as almost everything has been done already in previous PRs.
Only pain was configuring the `govuk_collection_radio_buttons`, because we are using nested attributes, the locales are not automagically fetched for us and we must pass them explicitly to the legend and to both options (the yes and the no).
I've [raised an issue](https://github.com/DFE-Digital/govuk-formbuilder/issues/385) in the `govuk-formbuilder` gem repository for a possible enhancement that would make these nested attribute locales work automagically too so we could simplify a lot the code in this view if that happens.
https://dsdmoj.atlassian.net/browse/CRIMAP-110
> CRIMAP-110 Add conflict of interest radio options

- app/controllers/steps/case/case_type_controller.rb
- app/forms/steps/case/case_type_form.rb
- app/forms/steps/case/urn_form.rb
- app/services/decisions/case_decision_tree.rb
- app/value_objects/case_type.rb
- app/views/steps/case/case_type/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20220830134258_add_case_type_to_case.rb
- db/migrate/20220831110636_add_maat_id_to_case.rb
- db/schema.rb
- spec/controllers/steps/case/case_type_controller_spec.rb
- spec/forms/steps/case/case_type_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/value_objects/case_type_spec.rb
Adds the ability to select a case type for a case
[CRIMAP-96](https://dsdmoj.atlassian.net/browse/CRIMAP-96)
- MAAT ids are only optional for Appeal to crown court types (the last two)
- Details on changes are mandatory for Appeals to CC with a change of financial curcumstances
- Please look at the wording of the errors are they clear?
---
- go through the regular journey until you reach the case type page
- submit blank --> error
- select either appeal type > add MAAT ID > select non appeal type -> error as MAAT ID present
- do the same for last appeal type with the extra details field
- leave MAAT ID blank on an appeals case --> should not error on submission
- leave extra details page blank on Appeal CC + change of financial circs --> should error as field is blank
- if valid should …
> CRIMAP-96 enter case type

- .better-html.yml
- .erb-lint.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- Rakefile
- lib/rubocop/custom_cops/govuk_formbuilder/text_field_autocomplete.rb
- lib/tasks/erblint.rake
- spec/spec_helper.rb
This is more of a learning exercise but I went through the rabbit hole of learning (barely) how to code custom Rubocop cops and when I got the matcher working I realised Rubocop doesn't run on ERB files.
So I researched a bit and found out a suitable ERB linter made by the nice folks at Shopify which lets you, in addition to its own linting (including some HTML linting), runs Rubocop on the ERB "ruby" code.
As expected there are some offences already in the views we already have, that's why I've disabled for now some linters.
In a separate PR I will enable some of them and fix the offences, mostly related to simple things like indentation, spacing, double quotes instead of single quotes, etc. Some of these may be annoying so we can discuss how strict we want to be LOL.
NOTE: the erb …
> Add an ERB linter and initial support for custom cops

- app/presenters/tasks/case_details.rb
- spec/presenters/tasks/case_details_spec.rb
Now that we have some of the case details steps, we can update this task so it links to the first step (URN) and also to know when it is in progress or not.
We will not be able to set the "completed" status tag until we have finalised all the case details step so that will need to change sometime in the future.
Start an application and run through the client details up until you pass the NINO step. Then go to the task list and the "Case details" task should be enabled and be able to click the link to go to the URN step.
When you run through some of the case details steps, and go back to the task list, the case details task will be marked as "in progress".
> Enable case details in task list

- app/forms/steps/case/codefendants_form.rb
- app/forms/steps/case/has_codefendants_form.rb
- app/services/decisions/case_decision_tree.rb
- spec/forms/steps/case/codefendants_form_spec.rb
- spec/forms/steps/case/has_codefendants_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
As we now have the previous yes-no step, I'm removing some of the temporary code I added in the co-defendants form object (and cleaned up the specs).
The temporary code was introduced to simplify development and testing, by creating a blank co-defendant record to start with, just by visiting the co-defendants page.
The decision tree is now in charge of handling this logic as it is bad practise to create records on GET requests.
I've also taken care of resetting any previously entered co-defendants, if the provider go back to the `yes-no` question and selects `no`.
https://dsdmoj.atlassian.net/browse/CRIMAP-109
https://dsdmoj.atlassian.net/browse/CRIMAP-111
Run through the journey up until the "Does your client have any co-defendants in this case?" question. Answer `yes` and a new record …
> Cleanup temporary code from co-defendants form object

- .erb-lint.yml
- app/views/layouts/govuk_template.html.erb
- app/views/steps/case/case_type/edit.html.erb
- app/views/steps/case/codefendants/edit.html.erb
- app/views/steps/client/contact_details/edit.html.erb
- lib/tasks/erblint.rake
Enabling Rubocop and default linters in `erblinter`.
This will run Rubocop on any ruby code found in ERB templates, with the same configuration we have for the rest of the code base. This includes our custom cops (for now just the autocomplete, as per PR #94).
However some cops are highly annoying or return false positives (i.e. Style/BlockDelimiters), thus we can tweak the configuration to disable some of these cops on ERB code, while still using them for normal non-ERB code, to get us to a good balance.
It also enables all the default linters except one I've disabled explicitly:
https://github.com/Shopify/erb-lint#linters
I had to fix a few very minor offences. I did individual commits with each of the fixes for better context.
This linter is run automatically as part of `rake` or …
> Enable Rubocop and default linters in ERB

- .github/workflows/test-build-deploy.yml
By explicitly identifying the environment where the workflow performs the deploy, we can set rules and assign reviewers.
This is mostly used for production environments (to assign reviewers), which we don't have yet, but for staging environment it can also be useful and we can then enable the setting "Require deployments to succeed before merging", so a merge to `main` can't happen if there is a deploy to `staging` in progress.
> Identify deployment environment in github workflow

- app/models/case.rb
- app/models/charge.rb
- app/models/offence.rb
- app/models/offence_date.rb
- db/migrate/20220908101956_create_offences_table.rb
- db/migrate/20220908104055_create_charges_table.rb
- db/migrate/20220908112104_create_offence_dates_table.rb
- db/schema.rb
- spec/models/charge_spec.rb
- spec/models/offence_date_spec.rb
- spec/models/offence_spec.rb
As we start to tackle the offences step, we need a series of DB tables and models to represent the data and relationships.
This might change slightly later on if we find out some missing attribute, or weird thing, but overall is the high level representation of what we want.
In a later PR a DB seed migration will be created to populate the `Offences` table based on the spreadsheet. Note the rank attribute will be populated based on the offence number of occurrences on the spreadsheet, creating a column we can use to sort by (`asc` 1 to 237). Frequency can be used for our internal analytics and also with enough time for ranking purposes if we want but this will have a bias given the very small number of providers for MVP, etc.
https://dsdmoj.atlassian.net/browse/CRIMAP-134
In a console: …
> CRIMAP-134 Initial offences DB schema and models

- app/models/charge.rb
- app/models/concerns/csv_queryable.rb
- app/models/offence.rb
- config/data/offences.csv
- spec/models/offence_spec.rb
Store the CSV file containing the pre-filtered list of offences and their attributes, and a thin layer to read it and perform basic operations like find by code (or by name if that make sense), and retrieve all offences.
This is inspired by HMCTS common platform with a very similar approach: https://github.com/ministryofjustice/hmcts_common_platform
I've made some small tweaks and modifications to better fit our purposes (also implemented the equality methods), but overall is exactly the same.
We might not need the Offences DB table anymore but for now I'm not doing anything on that front until we've validated this other alternative (CSV file).
I've just reused the same `Offence` model but removed its ActiveRecord capabilities so it is just a simple PORO/entity for now. …
> CRIMAP-125 Initial commit of offences CSV

- app/controllers/steps/case/charges_controller.rb
- app/forms/steps/case/charges_form.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/charges/edit.html.erb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/case/charges_controller_spec.rb
- spec/forms/steps/case/charges_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Routes, controller, form object and view with locales for a very basic initial boilerplate of the `Charges` step.
This already takes care of creating a `charge` record to work with (CRUD) but it only has an attribute, `offence_name` and no validation etc.
This is so we have something to start with and there are not too much code conflicts/clashing.
https://dsdmoj.atlassian.net/browse/CRIMAP-73
The step comes right after codefendants, either if you answer `NO` to has codefendants, or after entering some codefendants.
> CRIMAP-125 Initial setup of `Charges` step

- app/controllers/crime_applications_controller.rb
- app/controllers/steps/case/charges_summary_controller.rb
- app/forms/steps/case/charges_summary_form.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/charges_summary/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/case/charges_summary_controller_spec.rb
- spec/forms/steps/case/charges_summary_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
This is as well kind of the boilerplate (although it is totally functional) for the offences summary page, where offences will show and they can be changed, removed, or add another.
For now it only shows the yes-no radios to add another offence, with validation, and the decision tree has been updated to introduce this new flow.
In a follow-up PR, I will add to the summary page the list of offences, as well as the additional edit/delete actions.
https://dsdmoj.atlassian.net/browse/CRIMAP-127
Offences will not show yet on the list/page.
You reach this page either:
a) after adding one offence for the first time.
b) having added already some offences, if you go back in the journey to the codefendants, after codefendants you will go directly to the offences summary page, instead of to a blank …
> CRIMAP-127 Implement offences summary page

- app/forms/steps/case/charges_summary_form.rb
- app/presenters/charge_presenter.rb
- app/views/steps/case/charges_summary/edit.html.erb
- config/locales/en/steps.yml
- spec/presenters/charge_presenter_spec.rb
Little follow-up PR to #106, so we have something to "see" if the offences page is adding offences and dates as expected.
It is still kind of a mock (there is a presenter with some mock data), and no remove functionality implemented yet, that will be next in another PR, but the "change" link will work.
https://dsdmoj.atlassian.net/browse/CRIMAP-127
> CRIMAP-127 List of added offences

- .erb-lint.yml
- app/controllers/steps/case/charges_controller.rb
- app/models/case.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/charges/confirm_destroy.html.erb
- app/views/steps/case/charges/edit.html.erb
- app/views/steps/case/charges_summary/_offence_details.html.erb
- app/views/steps/case/charges_summary/edit.html.erb
- config/locales/en/steps.yml
- config/routes.rb
- spec/models/case_spec.rb
- spec/requests/charges_summary_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Another follow-up to previous offence summary page PRs.
This one implements the "Remove" link.
It follows the same pattern we already did for the applications dashboard, with a confirmation page, and shows a flash banner as well.
I tweaked a bit the routes `crud_step` helper to simplify this and to expose the `confirm_destroy` action when we have a `destroy`.
As agreed, if the offence being removed is the last one in the list, we redirects to a brand new offence, but if there are more offences left, we redirect back to the summary page.
https://dsdmoj.atlassian.net/browse/CRIMAP-130
There are some conversations around the wording "delete" or "remove" and also around the dates format. I'm leaving that out of this PR for now, once decided, we can change whatever is needed.
When deleting the …
> CRIMAP-130 Implement offence destroy action

- app/forms/steps/case/charges_form.rb
- app/forms/steps/case/offence_date_fieldset_form.rb
- app/validators/charges_validator.rb
- app/views/steps/case/charges/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/forms/steps/case/charges_form_spec.rb
Adds validations and fixes the labels and hint text of the offence dates on the charges page 
[CRIMAP-72](https://dsdmoj.atlassian.net/browse/CRIMAP-72)
- you views on accessibility would be appreciated
- note: I haven't removed the blank date initialisation in the cases decision tree in the PR. Can raise another one when we decide the best way to do this.
- try to submit dates in the future 
- try to submit blank dates
> CRIMAP-72 Offence Date Validations

- app/forms/steps/case/charges_form.rb
- app/models/charge.rb
- app/models/concerns/csv_queryable.rb
- app/models/offence.rb
- app/presenters/charge_presenter.rb
- app/views/steps/case/charges/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/steps.yml
- db/migrate/20220916151948_drop_offences_table.rb
- db/schema.rb
- spec/forms/steps/case/charges_form_spec.rb
- spec/models/charge_spec.rb
- spec/models/offence_spec.rb
- spec/presenters/charge_presenter_spec.rb
- spec/requests/charges_summary_spec.rb
Individual commits for more context.
This datalist is populated from the CSV, and offences are assigned to the Charge as value-objects making use of `composed_of` where we find the most suitable offence by name and return it if found, otherwise we assume the offence is being "created" by the provider, in which case we will not have an `#offence` (returns nil) and thus we lack additional attributes like offence class and type.
Add basic presence validation on the `offence_name` attribute.
Update the `ChargePresenter` as almost everything is now retrieved from the offence instance (or returns `nil` for manual offences).
In follow-up PRs we will add some javascript to be able to style the dropdown and to perform better in terms of accessibility. This is the non-JS version. …
> CRIMAP-124 Add datalist for the non-JS offences dropdown

- app/forms/steps/case/charges_form.rb
- spec/forms/steps/case/charges_form_spec.rb
Allows blank offence dates to be deleted from the Charges page as it makes validations dependant on there not being "_destroy" params in the form attributes sent to the server.
[CRIMAP-72](https://dsdmoj.atlassian.net/browse/CRIMAP-72)
- on Charges page add another date, so there are is a blank date input on the form. Then try to delete this without adding any date into it. The page should reload without the blank date, and not error.
> CRIMAP-72 Add .any_marked_for_destruction? to ChargesForm + test

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/suggestions.scss
- app/javascript/application.js
- app/javascript/local/suggestions.js
- app/views/steps/case/charges/edit.html.erb
- config/importmap.rb
Preliminary discovery work and first rough version of the javascript enhancement in the offences `datalist`.
This produces a "suggestions" dropdown, with consistent look and feel across all browsers, when javascript is enabled.
When javascript is disabled the normal "datalist" is shown instead so functionality is not lost.
Fair disclaimers:
- We are piggybacking on a draft PR for an unfinished work, not part of the GOV.UK Frontend yet. And it might not be part of it for a long time, if ever.
- It just doesn't work out of the box. I had to made a few modifications to the javascript.
- Additionally, to show the offence class, I also had to extend the functionality with a `data-caption` feature. This has an impact on the render of the datalist markup too.
- I've marked all this modifications …
> CRIMAP-129 Enhancement of offence datalist with JS

- app/controllers/steps/case/date_stamp_controller.rb
- app/views/steps/case/date_stamp/show.html.erb
- config/locales/en/steps.yml
- config/routes.rb
PR adds a basic, essentially static, "date stamp" page. Logic etc. to follow in a future PR.
[CRIMAP-49](https://dsdmoj.atlassian.net/browse/CRIMAP-49)
n/a - this is a new page
- currently this is "outside" the step flow. you need to hit the URL directly. Also note the buttons don't really do anything at the moment - this will come in a future PR.
- open an application and go to `/case/date_stamp`
> Adds basic "date stamp" page without any business logic

- app/controllers/steps/case/hearing_details_controller.rb
- app/forms/steps/case/hearing_details_form.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/hearing_details/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20220928100647_add_court_hearing_fields_to_cases.rb
- db/schema.rb
- spec/controllers/steps/case/hearing_details_controller_spec.rb
- spec/forms/steps/case/hearing_details_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
This includes the route, controller, view and form object as well as new required DB attributes on the `cases` table.
Court name input text, does not implement the dropdown or typeahead / suggestions yet. That will be part of a separate task/PR as it requires further research around where this data is coming from or how to "store" it in our application (if we do).
Co-Authored-By: timpeat <tim@timpeat.com>
Co-Authored-By: Chris Gannon <cjgannon@gmail.com>
https://dsdmoj.atlassian.net/browse/CRIMAP-75
No courts suggestions/typeahead yet. It will be part of a follow-up PR.
This step comes after the offences "basket".
> CRIMAP-75 Implement basic court hearing step

- app/forms/steps/case/case_type_form.rb
- app/presenters/crime_application_presenter.rb
- app/services/date_stamper.rb
- app/services/decisions/case_decision_tree.rb
- app/value_objects/case_type.rb
- app/views/crime_applications/edit.html.erb
- app/views/steps/case/date_stamp/show.html.erb
- config/locales/en/dashboard.yml
- db/migrate/20220929082638_add_date_stamp_to_crime_application.rb
- db/schema.rb
- spec/controllers/steps/case/date_stamp_controller_spec.rb
- spec/forms/steps/case/case_type_form_spec.rb
- spec/presenters/crime_application_presenter_spec.rb
- spec/services/date_stamper_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/value_objects/case_type_spec.rb
Adds date stamp to the CrimeApplication after the CaseType step, and redirects user to see the "date stamp" page if one is added (its dependant on the case type), or moves them on to the "has codefendants" page if not.
[CRIMAP-138](https://dsdmoj.atlassian.net/browse/CRIMAP-138)
- what are your thoughts on the `DateStamper`? I wanted to encapsulate any logic here in a re-usable component. So we thought it was better as a service than as a method in the `CaseDecisionTree`
- create a new application, take it through to case type, if you select: "Summary", "Either way", "committal", "Crown Court Appeal" you should see the date stamp page - if you select any other type it should go on to "has co-defendants" page.
> Crimap 138 date stamp logic

- app/forms/steps/case/case_type_form.rb
- spec/forms/steps/case/case_type_form_spec.rb
- spec/forms/steps/case/offence_date_fieldset_form_spec.rb
This change skips date stamping if the case type update fails.
https://dsdmoj.atlassian.net/browse/CRIMAP-138
Ideally we'd wrap this #persist! in an active record transaction. I did this initially but the implications seemed too widespread without further discussion.
> Don't date stamp if case_type update fails.

- Gemfile
- Gemfile.lock
- app/models/court.rb
- app/views/steps/case/hearing_details/edit.html.erb
- spec/models/court_spec.rb
Uses https://github.com/ministryofjustice/hmcts_common_platform/ gem to create a list of court names.
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897/backlog?selectedIssue=CRIMAP-119&text=crimap-11
We are waiting to confirm the final list of court name. This may impact on which source we use for the court names.  (See ticket for more discussion.)
If the source and way of filtering used in this PR is compatible with the finalised list, submit a PR to the hmcts_common_platform to exposed the L1_code instead of accessing the gem's csv file.
The width of the court name input has been increased to accommodate the wider names in this list. This may change once the final list is confirmed. 
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/124 adds …
> CRIMAP-119-select-court-from-list

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/accessible-autocomplete.scss
- app/assets/stylesheets/local/custom.scss
- app/javascript/application.js
- config/importmap.rb
- config/locales/en/helpers.yml
- spec/models/court_spec.rb
Adds accessible-autocomplete to court name select.
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-149
> CRIMAP-149 Implement Court Search Javascript on the Details of Next Court Hearing Page

- app/controllers/steps/client/benefit_check_result_controller.rb
- app/forms/steps/client/benefit_check_result_form.rb
- app/services/benefit_check_service.rb
- app/services/decisions/client_decision_tree.rb
- app/services/mock_benefit_check_service.rb
- app/views/steps/client/benefit_check_result/edit.html.erb
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/client/benefit_check_result_controller_spec.rb
- spec/forms/steps/client/benefit_check_result_form_spec.rb
- spec/services/benefit_check_service_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
- spec/services/mock_benefit_check_service_spec.rb
Adds a mock benefit service to check on the benefits status of an applicant. Also adds the BenefitCheckService, but this currently only calls the mock.
https://dsdmoj.atlassian.net/browse/CRIMAP-107
https://dsdmoj.atlassian.net/browse/CRIMAP-133
After the has_nino step, you should see a simple page with the result of the benefit check
> Add benefit check service and mock benefit check service

- app/forms/steps/case/case_type_form.rb
- app/services/date_stamper.rb
- app/services/decisions/case_decision_tree.rb
- spec/forms/steps/case/case_type_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Only shows the user the date_stamp page on the first time a date_stampable case_type is chose and the form is submitted.
Modified the logic in the case_decision_tree to allow for this - called the DateStamper from the decision tree so it returns false if the date_stamp is not updated by the DateStamper on subsequent re submissions of case_type step.
https://dsdmoj.atlassian.net/browse/CRIMAP-148
Go through user flow up to Case Type step
Select a date stampable Case Type (e.g. Summary Only)
Submit form and be redirected to Case Stamp page
Hit the back button to return to Case Type step 
Resubmit form/ change case type and resubmit and get redirected to charges journey
> Move DateStamper call to decision tree, only show date_stamp page once

- app/forms/steps/client/contact_details_form.rb
- app/models/person.rb
- spec/forms/steps/client/contact_details_form_spec.rb
As we do in other places, if provider changes the correspondence type selection from `other` to anything else (like home or provider's office) we reset the previously entered correspondence address (if any).
As this is a `has_one` relationship, nilling the attribute will remove the record from the `Addresses` table.
https://dsdmoj.atlassian.net/browse/CRIMAP-154
Go to contact details and select "other address", enter a correspondence address, then go back and change selection, the correspondence address record will be deleted.
> CRIMAP-154 Reset correspondence address when not applicable

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/moj.scss
- app/forms/steps/case/charges_summary_form.rb
- app/models/charge.rb
- app/views/steps/case/charges_summary/_offence_details.html.erb
- config/locales/en/errors.yml
- config/locales/en/steps.yml
- package.json
- spec/forms/steps/case/charges_summary_form_spec.rb
- spec/models/charge_spec.rb
- yarn.lock
Due to the way the offences page work (a page with nested attributes for details of the offence like offence name and one or more dates), each time the provider adds a new offence through the summary page, a blank record is created in the database, for the provider to fill in the details (offence name and dates).
This usually happens in one go, but if at that point, without finalising all the details, the provider clicks the “save and come back later“ button, for example, or click the “back“ link in the page, they will leave the offence in an incomplete state, maybe missing the name, or the dates, or both.
Removing these empty records is not a nice solution really, as some might contain partially entered details, like the offence name (but no dates) or vice versa, if the provider clicks …
> CRIMAP-163 Better handling of incomplete offences

- .erb-lint.yml
- .rubocop.yml
- app/controllers/steps/submission/review_controller.rb
- app/presenters/summary/components/base_answer.rb
- app/presenters/summary/components/date_answer.rb
- app/presenters/summary/components/free_text_answer.rb
- app/presenters/summary/components/value_answer.rb
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/base_section.rb
- app/presenters/summary/sections/client_details.rb
- app/views/steps/submission/review/edit.html.erb
- app/views/steps/submission/shared/_date_answer.html.erb
- app/views/steps/submission/shared/_free_text_answer.html.erb
- app/views/steps/submission/shared/_section.html.erb
- app/views/steps/submission/shared/_summary_row.html.erb
- app/views/steps/submission/shared/_value_answer.html.erb
- config/locales/en/summary.yml
- spec/presenters/summary/components/base_answer_spec.rb
- spec/presenters/summary/components/date_answer_spec.rb
- spec/presenters/summary/components/free_text_answer_spec.rb
- spec/presenters/summary/components/value_answer_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/base_section_spec.rb
- spec/presenters/summary/sections/client_details_spec.rb
- spec/rails_helper.rb
- spec/support/matchers/instances_array_matcher.rb
- spec/views/steps/submission/shared/_date_answer.html.erb_spec.rb
- spec/views/steps/submission/shared/_free_text_answer.html.erb_spec.rb
- spec/views/steps/submission/shared/_value_answer.html.erb_spec.rb
Note: this PR is quite large as it sets out the "framework" to present the "check your answers" page and to edit the answers (change links).
As part of this framework, the `Client details` section has been partially implemented. There are a few remaining questions-answers I'm leaving for a follow-up PR so this one does not grow even larger.
Despite the many files, only 5 classes are the main implementation. The other files are view partials and many tests, including some view tests.
The general idea is: each time we want to add a new section to the check your answers page, we implement a new class inheriting from `Sections::BaseSection` and define all the answers making use of the different "answer" types and their change link, if any.
These classes will render themselves making use of …
> CRIMAP-155 Review client details

- app/value_objects/case_type.rb
- spec/services/date_stamper_spec.rb
- spec/value_objects/case_type_spec.rb
Confirmed with Carolina, `Appeal to crown court with changes in financial circumstances` is a date stampable case type.
Only non-stampable ones are: `Indictable` and `Trial already in crown court`.
> Add `cc_appeal_fin_change` to date stampable types

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/contact_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/contact_details_spec.rb
Follow-up to PR #137, to add the client contact details to the review page.
It was agreed with Caroline this to be a separate section to group anything related to contact (addresses, phone), instead of being all together in the Client details section.
https://dsdmoj.atlassian.net/browse/CRIMAP-155
https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=2712%3A15417
The correspondence address row only shows if the "where to send correspondence" is "other address". For home, and provider's office, it will not show.
> CRIMAP-155 Review contact details

- app/presenters/summary/components/offence_answer.rb
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/offences.rb
- app/views/steps/submission/shared/_offence_answer.html.erb
- config/locales/en/summary.yml
- spec/presenters/summary/components/offence_answer_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/offences_spec.rb
- spec/views/steps/submission/shared/_offence_answer.html.erb_spec.rb
Add the offences section to the check your answers page.
This renders a slightly different markup as the offences are indexed, and shows more details like the class or the dates.
In order to do this in a clean way, a specific "OffenceAnswer" component has been created, with its corresponding view partial. Other than that it behaves the same as other answers really.
https://dsdmoj.atlassian.net/browse/CRIMAP-157
> CRIMAP-157 Review offences

- app/forms/concerns/steps/has_one_association.rb
Sometimes we may have 2nd level associations in a form object.
For example this may be the case for IoJ:
`application -> (has_one) case -> (has_one) ioj`
The current `Steps::HasOneAssociation` does not support this, and only supports first level relationships.
With these changes, the module is prepared to be used in second level relationships as well if it was needed.
To use it in this way, just do:
```ruby
include Steps::HasOneAssociation
has_one_association :ioj, through: :case
```
Then the form object and controller behaves exactly the same as we've been doing with 1st level associations.
This may be used in PR #136, if we decide to keep the `IoJ` as a `has_one` in the `case` instead of moving the relationship to the `crime_application`.
> Support second level associations in form concern

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/case_details.rb
- app/presenters/summary/sections/client_details.rb
- app/presenters/summary/sections/contact_details.rb
- app/presenters/summary/sections/next_court_hearing.rb
- app/presenters/summary/sections/offences.rb
- config/locales/en/summary.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/case_details_spec.rb
- spec/presenters/summary/sections/client_details_spec.rb
- spec/presenters/summary/sections/codefendants_spec.rb
- spec/presenters/summary/sections/contact_details_spec.rb
- spec/presenters/summary/sections/next_court_hearing_spec.rb
- spec/presenters/summary/sections/offences_spec.rb
Add the "next court hearing" section to the check your answers page.
Additionally, in a separate commit, made a few refinements to previous sections, so they do not show if the record is not yet created.
https://dsdmoj.atlassian.net/browse/CRIMAP-160
> CRIMAP-160 Review court hearing

- app/controllers/steps/submission/declaration_controller.rb
- app/forms/steps/submission/declaration_form.rb
- app/services/decisions/submission_decision_tree.rb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20221021110132_add_declaration_signed_field.rb
- db/schema.rb
- spec/controllers/steps/submission/declaration_controller_spec.rb
- spec/forms/steps/submission/declaration_form_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
Simple page, with content (may change, awaiting approval) and a check box to confirm, in order to proceed to what will be the final step, the submission confirmation (in a future PR).
Note: because this page is mostly all content, it makes sense to have it as a localised view (`edit.en.html.erb`) and not extract to locales the content as that would make it more difficult to update/translate in the future.
Linked this step to the overall journey, right after the review page.
https://dsdmoj.atlassian.net/browse/CRIMAP-114
Privacy policy page is part of another ticket.
This pages comes next after the review application page. On submission of the declaration it circles back to the home until we have next step (confirmation page).
> CRIMAP-114 Add declaration page

- Gemfile
- Gemfile.lock
Uses the lasted version of https://github.com/ministryofjustice/laa-crime-apply-dev-api and makes it available in all environments. (Previously it was only available in development.)
[CRIMRE-62](https://dsdmoj.atlassian.net/browse/CRIMRE-62)
This has been tested in development, and can be confirmed by viewing the schema at (/api/schemas/application.json)
> Use latest dev-api on staging.

- app/forms/steps/case/ioj_form.rb
- app/models/concerns/routing.rb
- app/presenters/tasks/base_task.rb
- app/presenters/tasks/case_details.rb
- app/presenters/tasks/client_details.rb
- app/presenters/tasks/ioj.rb
- spec/presenters/tasks/base_task_spec.rb
- spec/presenters/tasks/case_details_spec.rb
- spec/presenters/tasks/client_details_spec.rb
- spec/presenters/tasks/ioj_spec.rb
Some refactor and improvement of the previous existing tasks, and adding the new IoJ task to the task list.
We still need to revisit the `Client` task after we introduce the DWP check.
In a follow-up PR the review and declaration tasks will also be added.
https://dsdmoj.atlassian.net/browse/CRIMAP-171
The case task will be completed once the contact details page is completed (telephone number and correspondence address type). Then the IoJ will appear as "ready to start", if you save and come back later at that point it will show as "in progress". If you complete the IoJ it will show as "completed".
> CRIMAP-171 Add IoJ to task list and improve existing tasks logic

- app/controllers/steps/submission/confirmation_controller.rb
- app/services/decisions/submission_decision_tree.rb
- app/views/steps/submission/confirmation/show.en.html.erb
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/submission/confirmation_controller_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
This is just a show action, rendering a localised view (as there is no complex logic or anything like that, just some content).
Updated the decision tree, so this page is shown right after the declaration page.
In another PR, the green button "View completed application" will be implemented to show a read-only view of the "check your answers". At the moment, it just goes to the list of applications.
Note: for now there is no logic to mark applications as submitted (and of course, no actual "submission" to any place). This is all smoke and mirrors until we flesh out next pieces of the puzzle.
https://dsdmoj.atlassian.net/browse/CRIMAP-113
https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=2711%3A6381
We don't have yet a link for the survey/feedback.
Signed the …
> CRIMAP-113 Add submission confirmation page

- app/controllers/about_controller.rb
- app/views/about/privacy.en.html.erb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/locales/en/about.yml
- config/routes.rb
- spec/controllers/about_controller_spec.rb
Add privacy policy page with content from civil apply (to be reviewed in https://dsdmoj.atlassian.net/browse/CRIMAP-150) 
Minor changes to copy where looked to be incorrect in civil. Adding full stop, removing colon from a h2 heading to make consistent. Adding missing into line to an address that is in the civil yml but unused. 
https://dsdmoj.atlassian.net/browse/CRIMAP-168
To match https://staging.apply-for-legal-aid.service.justice.gov.uk/privacy_policy?locale=en
> CRIMAP-168 Add about controller and privacy page

- config/routes.rb
Co-authored-by: willmcb <william.mcbrien@digital.justice.gov.uk>
Modify the catch all routing constraint so that it ignores requests to the dev api when in a production environment.
Reluctantly proposing this change to Apply in order to allow us to use the dev api on staging.
The dev api's routes are loaded after those in Apply. This was fine in development and test because the catch all's constraint   ignored test and dev requests (so as to show the rails errors etc).  However, on staging the catch all constraint was satisfied, preventing any requests to the dev api. 
We also considered explicitly adding the dev api routes to apply, and removing the catch all altogether.
> Allow api requests on staging.

- .rubocop.yml
- app/assets/stylesheets/local/custom.scss
- app/presenters/crime_application_presenter.rb
- app/services/application_submission.rb
- app/views/crime_applications/edit.html.erb
- app/views/crime_applications/show.html.erb
- config/locales/en.yml
- config/locales/en/dashboard.yml
- spec/presenters/crime_application_presenter_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/application_submission_spec.rb
The date stamp logic is a bit more tricky than anticipated, but in summary, it follows these broad rules:
- If case type is “date stampable”, we set and use the date stamp value across the application
- If case type is non “date stampable”, we don't set it until submission, at which time this becomes the date stamp
Across the application there are places (mainly task list) where the date stamp needs to show even if the application is not yet submitted, so the logic has been improved to cope with this.
On the certificate page (post submission) we've added in addition to the date stamp, the submission date. For non-stampable case types these 2 dates will be identical. For stampable case types, the dates will differ.
https://dsdmoj.atlassian.net/browse/CRIMAP-176
NOTE: at the moment is …
> CRIMAP-176 Implement date stamp logic on submission

- app/controllers/completed_applications_controller.rb
- app/controllers/developer_tools/crime_applications_controller.rb
- app/controllers/sessions_controller.rb
- app/presenters/crime_application_presenter.rb
- app/services/mock_benefit_check_service.rb
- app/value_objects/application_status.rb
- app/views/layouts/_developer_tools.html.erb
- config/locales/en/dashboard.yml
- config/routes.rb
- spec/models/crime_application_spec.rb
- spec/presenters/crime_application_presenter_spec.rb
- spec/value_objects/application_status_spec.rb
This is a first PR to add some additional actions to the developer tools (in the footer) that will be necessary to progress with the user story in CRIMAP-97 (amend application).
Mainly, I've added a "mark as returned" button that will only show when "viewing" a `submitted` application. This button will put it into a `returned` status which later on can be used to filter in the dashboard and to amend it through the certificate page. This will be done in a separate follow-up PR.
I've also added a quick action to fill up an application up to the DWP check (success) result page, as I kept forgetting myself which combinations of surname, dob and NINO pass the check (mock values).
Overall, reorganised a bit the developer tools into its own controller, leaving the `SessionsController` as might …
> CRIMAP-97 Add additional actions to developer tools

- app/controllers/steps/dwp/confirm_details_controller.rb
- app/forms/steps/dwp/confirm_details_form.rb
- app/presenters/summary/sections/base_section.rb
- app/presenters/summary/sections/client_details.rb
- app/views/steps/client/benefit_check_result/edit.html.erb
- app/views/steps/dwp/confirm_details/edit.html.erb
- app/views/steps/dwp/confirm_result/edit.html.erb
- app/views/steps/submission/shared/_date_answer.html.erb
- app/views/steps/submission/shared/_free_text_answer.html.erb
- app/views/steps/submission/shared/_offence_answer.html.erb
- app/views/steps/submission/shared/_section.html.erb
- app/views/steps/submission/shared/_summary_row.html.erb
- app/views/steps/submission/shared/_value_answer.html.erb
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- spec/presenters/summary/sections/base_section_spec.rb
- spec/presenters/summary/sections/client_details_spec.rb
- spec/requests/dwp_benefit_checker_spec.rb
- spec/views/steps/submission/shared/_date_answer.html.erb_spec.rb
- spec/views/steps/submission/shared/_free_text_answer.html.erb_spec.rb
- spec/views/steps/submission/shared/_offence_answer.html.erb_spec.rb
- spec/views/steps/submission/shared/_value_answer.html.erb_spec.rb
This PR is a bit of tidy up, DRY and preparing for continuing with CRIMAP-97 (amend applications).
It looks like lots of changes but it is very minor overall. I've split this into 2 separate commits.
First thing, decouple the views from having to use the `current_crime_application` to know if the change links should show or not. Instead, make it part of the configuration of each of the sections (`editable`), and propagate this to the views as `locals`.
Same if we want to hide the header of the section. Default is false, but we can pass `headless: true` to hide the header.
This makes for more flexible "section" components so we can reuse them in other places (like in the DWP confirm applicant details page).
Also tests are simpler and do not need to have the knowledge or concept of a "crime …
> Configurable summary presenters, reuse in DWP journey

- app/assets/stylesheets/print.scss
- app/views/completed_applications/show.html.erb
- config/initializers/dartsass.rb
Apply a basic print stylesheet in the application certificate page, to remove superfluous visual elements like the header or footer, when printing the page.
The printing can be invoked through the "Print application" button (but this will only work with javascript enabled) or just by going to the browser menubar and selecting "File - Print".
We can tweak the print stylesheet if required, but for now it looks good enough. Also, in the future, this might be superseded by a PDF download (probably post-MVP as it is not a very high priority right now).
https://dsdmoj.atlassian.net/browse/CRIMAP-98
Important: after checking out this branch, stop the server, run `rails assets:clobber` and then `bin/dev` to ensure the styles are properly compiled.
Go to a certificate page, and click the "Print …
> CRIMAP-98 Print application certificate

- app/assets/stylesheets/local/custom.scss
- app/controllers/completed_applications_controller.rb
- app/services/application_amendment.rb
- app/views/completed_applications/show.html.erb
- config/locales/en/dashboard.yml
- config/routes.rb
- spec/controllers/completed_applications_controller_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/application_amendment_spec.rb
Follow-up to previous preparation PRs, this one implements a barebones "amend" action, with a button in the certificate page so the provider can put back an application into "editable" mode (`in_progress`) and make changes in order to submit again the application.
Note: there are so many implementation details we are still missing that is not worth it taking this further until we have perhaps the document store.
For now is a bit smoke and mirrors but it serve the purpose of getting an idea how the user experience will look like and we can test this with providers.
I'm awaiting confirmation regarding some of the time stamps on the application, if we have to keep the originals or reset on re-submission. I think we might have to introduce a `parent_id` at some point, it will keep track of …
> CRIMAP-97 Amend returned application

- README.md
- app/lib/settings.rb
- config/settings.yml
- spec/lib/settings_spec.rb
We had `FeatureFlags` in the application already, and back at the time we talked about having a similar approach for general settings, those not requiring to change between environments.
These settings are added sometimes to the `application.rb` file and then retrieved with `Rails.configuration.x.whatever` but I think it is cleaner to have them in a separate file not relying on Rails.
The file is the same used for the feature flags too, so all is kept in the same place for easy tweaking.
> Add settings mechanism, similar to `FeatureFlags`

- app/presenters/crime_application_presenter.rb
- app/views/completed_applications/index.html.erb
- app/views/crime_applications/index.html.erb
- spec/presenters/crime_application_presenter_spec.rb
- spec/requests/dashboard_spec.rb
Removes status tags from the applications page as they are no longer required.
> remove status tags from applications

- app/views/completed_applications/show.html.erb
- config/locales/en/dashboard.yml
As per latest designs.
The helpline details will not show on returned applications as per designer decision.
> Tweak certificate page helpline copy

- config/locales/en/dashboard.yml
Change "LAA reference" label to "Reference number" on applications dashboard
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-205
Go to the applications dashboard
> change laa reference to reference number

- Dockerfile
It seems there have been some regression or breaking change starting with 3.16 (published 2 days ago).
Will investigate further, but for now this unblocks the deploys.
> Locking alpine image to version 3.15

- app/lib/usn_seq_helper.rb
- config/brakeman.ignore
- db/migrate/20221108112731_add_usn_attribute.rb
- db/schema.rb
This will be later on used to replace our current (mocked) LAA reference.
This PR only adds the sequence and attribute, along with a looong comment explaining some gotchas.
Upon migrate, any existing applications in the DB will see their `usn` attribute populated based on the sequence, starting at `6_000_000`
But this attribute is not yet used anywhere. A separate PR will be raise to replace the LAA reference with this USN.
https://dsdmoj.atlassian.net/browse/CRIMAP-204
https://dsdmoj.atlassian.net/wiki/spaces/CRIMAP/pages/4210524301/USN
Checkout, run the migration, open a console and do:
```ruby
> a = CrimeApplication.create
> a.reload
> a.usn
=> 6000001
> b = CrimeApplication.create
> b.reload
> b.usn
=> 6000002
> b.usn = a.usn
=> 6000001
> b.save # raises ActiveRecord::RecordNotUnique …
```
> CRIMAP-204 Add USN sequence (serial) DB attribute

- app/controllers/steps/submission/confirmation_controller.rb
- app/presenters/crime_application_presenter.rb
- config/locales/en/dashboard.yml
- spec/controllers/steps/submission/confirmation_controller_spec.rb
- spec/presenters/crime_application_presenter_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
Follow-up to PR #173, to start showing to the provider on the views the USN.
I've not changed the name of the method (`#laa_reference`) in the presenter as to make it easier to move from using USN to any other ID/ref in the future if we need to.
https://dsdmoj.atlassian.net/browse/CRIMAP-204
> CRIMAP-204 Change the ref number format

- app/helpers/steps_helper.rb
- app/views/home/index.en.html.erb
- app/views/home/index.html.erb
- app/views/shared/_eforms_redirect.en.html.erb
- config/settings.yml
- spec/helpers/steps_helper_spec.rb
In preparation for user test sessions, make the homepage more similar to what eventually will be (once we have post-login journey).
Note the view is localised, as is heavy on content, with no dynamic/complex components.
The `start button` will go to the dashboard, this is the same as going to the `developer tools` and clicking "your applications", but is better for user testing, as providers might get confused what this developer tools is about.
Once we have the Portal Login, the start button in reality will go to the selection of office account number. But we can't implement that yet.
https://dsdmoj.atlassian.net/browse/CRIMAP-39
https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=2711%3A7235&t=QN4uBvORzji6zsjO-4
> CRIMAP-39 Add proper content to home page

- README.md
- app/lib/feature_flags.rb
- app/lib/host_env.rb
- config/settings.yml
- spec/controllers/completed_applications_controller_spec.rb
- spec/lib/feature_flags_spec.rb
- spec/lib/host_env_spec.rb
- spec/services/application_submission_spec.rb
As we develop some code behind feature flags, like right now the datastore integration, we might not want yet to go ahead and write detailed tests for it.
One way to handle this was to use, for instance:
```ruby
allow(
FeatureFlags
).to receive(:datastore_submission).and_return(double(enabled?: false))
```
But when you have many places where the feature flag might trigger, adding this to every single test (and then remember to remove it, etc.) can be tiresome.
Adding some granularity to the `HostEnv` and `FeatureFlags` mechanism to treat the `test` environment as any other environment so we can turn on/off features will make this hopefully a bit easier.
By default, local and test envs, if not explicitly declared on the feature flags configuration, will be turned on. To disable just …
> Add granularity to `FeatureFlags` for test env

- Gemfile.lock
- app/controllers/completed_applications_controller.rb
- app/presenters/infinite_pagination.rb
- app/views/completed_applications/index.html.erb
- app/views/shared/_infinite_pagination.html.erb
- config/locales/en/dashboard.yml
A limitation of DynamoDB is the pagination is not like a traditional pagination where you have pointers to each page through an offset and a limit.
Pagination with DynamoDB is really an "infinite scroll" pagination where you just get a "token" based on the last record returned in the previous page, so you can pass this token in the next request and continue loading records where you left.
This means you can only advance forwards, and not go to a specific page, just the immediate next page to the one you are.
There are ways to get back to the previous page if you track the previous token as query params, but that is all, only current page, previous and next are supported, the moment you go backwards more than 1 page, you don't have a previous token anymore.
This PoC is a limited version of …
> Pagination proof of concept (dynamodb)

- app/controllers/completed_applications_controller.rb
- app/presenters/infinite_pagination.rb
- app/presenters/infinite_pagination_v2.rb
- app/views/shared/_infinite_pagination_v2.html.erb
- config/locales/en/dashboard.yml
This is another kind of pagination, as a follow up to PR #184.
This one is a bit more complex on the markup side (probably a fair amount of DRY and tidy up can be done, but this is a quick PoC), but may be more useful to users.
This one allows to always move, from the page you are in, one page forward and one page backwards, however when going backwards only the immediate previous page can be accessed.
The benefit of this pagination is that it is "almost" like a traditional pagination, and has visual feedback of which page you are in, which is the next one, and which is the previous one. When there are no more previous pages (because of dynamo limitation) we show page 1.
Same as previous PR, but now you can choose which pagination to use with the query param `v`, so `v=1` is version 1 …
> Another pagination proof of concept (dynamodb)

- Gemfile.lock
- app/controllers/developer_tools/crime_applications_controller.rb
- app/models/crime_application.rb
- app/presenters/crime_application_presenter.rb
- app/presenters/infinite_pagination.rb
- app/presenters/infinite_pagination_v2.rb
- app/services/adapters/base_application.rb
- app/services/adapters/database_application.rb
- app/services/adapters/json_application.rb
- app/services/application_submission.rb
- app/services/decisions/submission_decision_tree.rb
- spec/presenters/crime_application_presenter_spec.rb
Now that we've started to validate the JSON payload against the schema on the datastore, some of the code was outdated. Also the JSON responses have changed so we need to adapt some of the proof of concept code we had (like the paginators).
In addition, the presenters need to work with both, DB applications and JSON applications. I've started some work on this front but is far from perfect and definitely kind of ugly.
https://dsdmoj.atlassian.net/browse/CRIMAP-210
After checking out this branch, remove all existing applications in your local datastore as most likely these will be in an old format (or none at all) and may cause issues.
One way to do this, is with the rake task `rake dynamo:destroy_all` (in the datastore directory).
New submitted applications will conform to the basic …
> Update code to work with latest schema

- Gemfile.lock
- app/forms/steps/case/case_type_form.rb
- app/models/structs/crime_application.rb
- app/services/adapters/json_application.rb
- app/value_objects/case_type.rb
- app/views/steps/case/case_type/edit.html.erb
- config/locales/en/helpers.yml
- config/locales/en/summary.yml
- spec/forms/steps/case/case_type_form_spec.rb
- spec/value_objects/case_type_spec.rb
Also bump the version of the schemas gem, and use it through inheritance instead of directly instantiating the gem class, to allow for more flexibility.
NOTE: important, as some case types values has been changed, if in your local DB you have applications created with the old names, they might start to blow up.
Quickest solution is to delete from your local DB the offending applications.
> Unify case types across app and schemas

- app/forms/steps/case/case_type_form.rb
- app/views/steps/case/case_type/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- db/migrate/20221123104634_rename_case_appeal_fields.rb
- db/schema.rb
- spec/forms/steps/case/case_type_form_spec.rb
For consistency with the schemas and the previous renaming of case types in PR #188.
Functionally everything should be the same.
> Rename case type maat details DB fields

- Gemfile.lock
- app/controllers/completed_applications_controller.rb
- app/controllers/dashboard_controller.rb
- app/models/address.rb
- app/models/crime_application.rb
- app/models/structs/crime_application.rb
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/contact_details.rb
- app/presenters/summary/sections/justification_for_legal_aid.rb
- app/presenters/summary/sections/passport_justification_for_legal_aid.rb
- app/services/adapters/base_application.rb
- app/services/adapters/database_application.rb
- app/services/adapters/structs/applicant.rb
- app/services/adapters/structs/base_struct_adapter.rb
- app/services/adapters/structs/case_details.rb
- app/services/adapters/structs/crime_application.rb
- app/services/adapters/structs/interests_of_justice.rb
- app/views/layouts/_developer_tools.html.erb
- spec/presenters/crime_application_presenter_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/justification_for_legal_aid_spec.rb
- spec/presenters/summary/sections/passport_justification_for_legal_aid_spec.rb
- spec/rails_helper.rb
- spec/services/adapters/structs/applicant_spec.rb
- spec/services/adapters/structs/case_details_spec.rb
- spec/services/adapters/structs/crime_application_spec.rb
- spec/services/adapters/structs/interests_of_justice_spec.rb
Ensure the already existing presenters we had (all under `app/presenters/summary/...`)  works also with a submitted application, as in an application coming from the Datastore and thus not persisted to Apply local DB.
It mostly works out of the box but a few tweaks were needed, because some attributes are named differently in our DB and in the datastore JSON.
To accomplish this in the most transparent way possible a few Adapters have been created in `app/services/adapters/structs/...`. The purpose of these adapters is to take the JSON from the datastore, create Struct objects (from the `laa_crime_schemas` gem) and then apply a thin layer on top of them to customise behaviour and allow for some method renames.
This is not yet completed, but in order to not make this PR too big, will leave …
> CRIMAP-213 Render submitted application certificate

- app/services/adapters/structs/base_struct_adapter.rb
- app/services/adapters/structs/case_details.rb
- app/services/adapters/structs/charge.rb
- spec/services/adapters/structs/case_details_spec.rb
- spec/services/adapters/structs/charge_spec.rb
Follow-up to previous PR #196 to finalise the `offences` section.
Because the way the presenters work internally to present the offences class, etc. in the different parts of the service (offences basket, check your answers, certificate page) there is a bit more of complexity in the "thin adapter layer", as we want to reuse our "Charge" model and not to re-implement most of it.
Also, charges in our database might not be "completed" (lacking some details like the name or the dates) but those coming from the datastore can be assumed to be completed as they fulfilled the JSON schema already.
https://dsdmoj.atlassian.net/browse/CRIMAP-213
Offences should just show on the certificate page as long as they are present in the JSON coming from the datastore.
> CRIMAP-213 Show offences in submitted certificate

- Gemfile.lock
- app/presenters/summary/sections/passport_justification_for_legal_aid.rb
- app/presenters/tasks/ioj.rb
- app/services/adapters/structs/applicant.rb
- app/services/adapters/structs/case_details.rb
- app/services/decisions/case_decision_tree.rb
- app/services/ioj_passporter.rb
- db/migrate/20221128154645_move_ioj_passport_field_to_application.rb
- db/schema.rb
- spec/presenters/summary/sections/passport_justification_for_legal_aid_spec.rb
- spec/presenters/tasks/ioj_spec.rb
- spec/services/adapters/structs/applicant_spec.rb
- spec/services/adapters/structs/case_details_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/ioj_passporter_spec.rb
This is I believe the final bit of information we have to read from the datastore application and be able to render in the certificate page.
I've moved the DB attribute from the `case` to the `crime_application` table as it is something that applies globally to the "application" as a whole.
It also makes the code much simpler and I've been able to cleanup quite a lot and refactor some additional code in the task list page, and check your answers page.
https://dsdmoj.atlassian.net/browse/CRIMAP-213
In order to test this, make sure to be running latest code in the datastore and submit an application containing the attributes:
```json
"ioj_passport": ["on_age_under18"],
"interests_of_justice": null
```
> CRIMAP-213 Refactor and show IoJ passported in certificate page

- .env.development
- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/routes.rb
Now that we have the client API and can set up the datastore locally, there is no need for the direct dev-api gem so this PR removes it from apply.
n/a
> Remove dev api gem + config for it

- config/locales/en/helpers.yml
Expert examination IOJ was using same copy as Witness tracing.
https://dsdmoj.atlassian.net/browse/CRIMAP-223
> CRIMAP-223 Fix duplicated IoJ copy

- app/controllers/completed_applications_controller.rb
- app/serializers/submission_serializer/definitions/address.rb
- app/serializers/submission_serializer/definitions/base_definition.rb
- app/serializers/submission_serializer/sections/ioj_details.rb
- app/services/application_submission.rb
- app/services/decisions/submission_decision_tree.rb
- config/settings.yml
- spec/controllers/completed_applications_controller_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/client_details_spec.rb
- spec/services/application_submission_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
This involves:
- No code is feature flagged anymore.
- On application submission, we call the datastore (for real) submitting the serialized application.
- We purge the application from the local DB (if submission is successful).
- Rescue and gracefully handle errors on submission giving the user an error message (copy / design TBD).
- All operations on the dashboard (submitted and returned lists) call the datastore. There is no graceful handling of errors here yet.
Additionally I found a few minor issues with nil values in the serializers and fixed these.
Pending:
- graceful errors if datastore service is not accessible or similar on the dashboard
- dashboard counters
- amend journey (returned applications) is not working now as it relied on local DB, this will need to be refactored. …
> CRIMAP-212 Cleanup datastore feature flag

- Gemfile.lock
- app/serializers/submission_serializer/definitions/address.rb
- app/serializers/submission_serializer/definitions/base_definition.rb
- spec/serializers/submission_serializer/application_spec.rb
Empty collections like `codefendants` (if there are no codefendants in the case) or `offences`, should be serialized as empty arrays, instead of `nil`.
Bump schemas version that makes `codefendants` a required attribute (but can be an empty array).
> Serialize empty collections to arrays

- .env.development
- README.md
We have a new namespace for the datastore service, which can be used in localhost without having to setup the local datastore service, dynamo etc.
Added some info about it.
> Add note about the datastore harness namespace

- Gemfile.lock
- app/controllers/developer_tools/crime_applications_controller.rb
- app/views/layouts/_developer_tools.html.erb
We are now using the datastore for everything post-submission of an application.
Some operations of the “developer tools“ (in the footer, intended for speed up some actions in development/demo environments) relied on local DB so these need to be tweaked to work again with the datastore.
Now, depending on the current application (in progress, or submitted) the operations will perform the expected action on the correct "database".
Please note marking a submitted application as returned will work, but there is no counter in the returned tab (it was removed couple days ago until counters are reworked, part of another ticket).
However trying to update a returned application (re-hydration) is not yet implemented so will blow up if tried.
https://dsdmoj.atlassian.net/browse/CRIMAP-240
Play with …
> CRIMAP-240 Adapt developer tools to datastore

- app/views/completed_applications/index.html.erb
- app/views/crime_applications/index.html.erb
- app/views/shared/_dashboard_header.html.erb
- app/views/steps/case/hearing_details/edit.html.erb
- config/locales/en/dashboard.yml
As per original Figma designs.
And DRY a bit the dashboard across in progress and submitted applications tabs.
No functional changes, just visual.
> Fix a couple of styling annoyances

- config/kubernetes/staging/config_map.yml
It seems `true` value needs to be quoted. Oh well.
> Fix config map value

- app/controllers/concerns/steps/no_op_advance_step.rb
- app/controllers/steps/submission/failure_controller.rb
- app/forms/steps/shared/no_op_form.rb
- app/services/decisions/submission_decision_tree.rb
- app/views/steps/submission/declaration/edit.en.html.erb
- app/views/steps/submission/failure/edit.html.erb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/submission/failure_controller_spec.rb
- spec/forms/steps/shared/no_op_form_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
- spec/support/shared_examples/step_controller_shared_examples.rb
This builds on the back of some previous work we had to handle submission errors, but we were redirecting the user to a generic "unhandled error" page.
Now we have a proper design and content for this error page, and also as per service designer, the `Try again` button will re-try the submission, without taking the user back to the `declaration` page.
The user can keep re-trying as many times as they want, or click `back` link to go to the declaration page, or `Back to all applications` to go to the dashboard.
Also as part of this, a minor copy change to the declaration primary button was done, as per ticket CRIMAP-242.
NOTE: I've introduced a `Steps::NoOpAdvanceStep` concern as well as a `NoOpForm` to be used in controllers that don't persist anything, and are only used to control flow …
> CRIMAP-244 Retry application submission failures

- app/controllers/completed_applications_controller.rb
- app/controllers/crime_applications_controller.rb
- app/controllers/dashboard_controller.rb
- app/services/datastore/application_counters.rb
- app/views/completed_applications/index.html.erb
- app/views/crime_applications/index.html.erb
- app/views/shared/_subnavigation.html.erb
- config/locales/en/dashboard.yml
- spec/requests/dashboard_lists_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/datastore/application_counters_spec.rb
- spec/system/sign_in_spec.rb
This adds again the counters for `returned` applications, and also additionally `submitted` applications.
Cleanup a lot of code and made it resilient so the whole dashboard will not blow up if the datastore is not available.
NOTE: I've split the `dashboard_spec` into 2, moving the tests related to the application lists to a separate file, as to avoid as much as possible conflicts with a separate open PR.
https://dsdmoj.atlassian.net/browse/CRIMAP-236
When datastore is available:
When datastore is not available:
> CRIMAP-236 Reimplement dashboard counters

- Gemfile
- Gemfile.lock
There seems to be some issues with latest version of this gem, which was bumped in previous PR #223.
Locking its version temporarily until 2.8.1 is released.
> Fix for `mail` gem latest version

- Dockerfile
After the introduction of Devise in previous PR, the assets pipeline require an additional ENV variable as Devise use it in its initialiser.
The value doesn't matter at this time, as the real values come from the kubernetes cluster.
> Ensure assets precompile have all required env vars

- app/controllers/steps/provider/confirm_office_controller.rb
- app/controllers/steps/provider_step_controller.rb
- app/forms/steps/provider/confirm_office_form.rb
- app/models/provider.rb
- app/services/decisions/provider_decision_tree.rb
- app/views/steps/provider/confirm_office/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/provider/confirm_office_controller_spec.rb
- spec/forms/steps/provider/confirm_office_form_spec.rb
- spec/services/decisions/provider_decision_tree_spec.rb
- spec/system/sign_in_spec.rb
First part of the provider's office account selection.
Currently this is not yet hooked to the general flow. That will come in a separate PR.
Usual controller, form object, decision tree, etc. New `provider` namespace and decision tree to separate concerns. Only difference here is that at any point in these steps we will have a `current_crime_application` as these steps come before the creation of the application.
https://dsdmoj.atlassian.net/browse/CRIMAP-40
For now, the only way to test this is to be signed in and access the URL directly: `/steps/provider/confirm_office`
> CRIMAP-40 Confirm office account number

- app/controllers/steps/provider/select_office_controller.rb
- app/forms/steps/provider/select_office_form.rb
- app/services/decisions/provider_decision_tree.rb
- app/views/steps/provider/confirm_office/edit.html.erb
- app/views/steps/provider/select_office/edit.html.erb
- config/initializers/i18n.rb
- config/locales/en/devise.yml
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- docker-compose.yml
- spec/controllers/steps/provider/select_office_controller_spec.rb
- spec/forms/steps/provider/select_office_form_spec.rb
- spec/services/decisions/provider_decision_tree_spec.rb
Follow-up to PR #231.
Allows the provider to select the office account number from a list. This will persist the selected code to the provider's setting so we don't have to ask again until next login.
Still not integrated in the wider journey, this will come as a separate PR.
https://dsdmoj.atlassian.net/browse/CRIMAP-41
Like the other step, in order to test this one, go to `/steps/provider/select_office` manually.
> CRIMAP-41 Select office code from a list

- app/controllers/application_controller.rb
- app/controllers/providers/omniauth_callbacks_controller.rb
- app/models/provider.rb
- spec/models/provider_spec.rb
- spec/system/sign_in_spec.rb
Wiring up the previous work.
If the provider has more than 1 office account, show the confirmation page (implemented in previous PR #231 and #232) upon signing in.
If provider has only 1 account, do not show this page, and take them directly to the dashboard.
The selected account will persist across logins, but the provider will be asked again to confirm, in case they want to change it.
https://dsdmoj.atlassian.net/browse/CRIMAP-40
The mock has more than one account so it will show these pages. If using a provider account with only 1 account, it will not show.
> CRIMAP-40 Confirm office account on sign in

- Gemfile.lock
- app/controllers/completed_applications_controller.rb
- app/controllers/crime_applications_controller.rb
- app/controllers/dashboard_controller.rb
- app/services/datastore/application_counters.rb
- app/services/datastore/get_applications.rb
- spec/services/datastore/application_counters_spec.rb
- spec/services/datastore/get_applications_spec.rb
Similar to previous PR #234, this one will propagate the `office_code` query param to perform the scoping in the datastore API. Also the counters has been adapted.
Bumped schemas gem that includes the new `office_code` attribute.
NOTE: the filter will not have any effect until the datastore endpoint is updated to perform the scoping using this new query param.
https://dsdmoj.atlassian.net/browse/CRIMAP-249
> CRIMAP-249 Scope datastore applications by office

- app/controllers/providers/omniauth_callbacks_controller.rb
- app/models/provider.rb
- app/services/provider_office_router.rb
- app/views/steps/provider/confirm_office/edit.html.erb
- app/views/steps/provider/select_office/edit.html.erb
- spec/requests/dashboard_lists_spec.rb
- spec/services/provider_office_router_spec.rb
- spec/system/sign_in_spec.rb
This is a refinement on top of previous PR #233.
When a provider signs in for the first time, if they have multiple offices, we don't set a default one, instead we show them a list of offices for them to select. Subsequents signs in will present them the office confirmation page in case they want to change their selection.
If they only have one office, then we default to that one as before, and do not show them the office selection or confirmation pages.
https://dsdmoj.atlassian.net/browse/CRIMAP-41
> Show office list on sign in if no office is selected

- app/controllers/steps/submission/declaration_controller.rb
- app/forms/steps/submission/declaration_form.rb
- app/models/provider.rb
- app/presenters/tasks/declaration.rb
- app/presenters/tasks/review.rb
- app/services/datastore/application_amendment.rb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- db/migrate/20221222105156_remove_declaration_signed_field.rb
- db/migrate/20221222105608_add_legal_representative_fields.rb
- db/schema.rb
- spec/controllers/steps/submission/declaration_controller_spec.rb
- spec/forms/steps/submission/declaration_form_spec.rb
- spec/presenters/tasks/declaration_spec.rb
- spec/presenters/tasks/review_spec.rb
- spec/services/datastore/application_amendment_spec.rb
- spec/services/datastore/application_submission_spec.rb
Adapt the existing declaration page to collect the legal representative details, who is the one signing the declaration.
Removed the previous "check box" as it is no longer used.
These legal rep details are also stored as "settings" of the currently signed in provider, so next time they get to a declaration page on a new application, these details get pre-populated.
If any of the details are changed in a declaration page, the settings are also updated, and will have effect on new applications (not existing ones).
NOTE: integration with the datastore will be done in a separate PR.
https://dsdmoj.atlassian.net/browse/CRIMAP-224
Go all the way to the declaration. It will be blank the first time, and then for new applications it will pre-populate with previous values. Validation is in place …
> CRIMAP-224 Collect legal rep details in declaration page

- Gemfile.lock
- app/controllers/steps/submission/declaration_controller.rb
- app/forms/steps/submission/declaration_form.rb
- app/serializers/submission_serializer/sections/provider_details.rb
- spec/controllers/steps/submission/declaration_controller_spec.rb
- spec/forms/steps/submission/declaration_form_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/provider_details_spec.rb
- spec/services/datastore/application_submission_spec.rb
Little follow-up to previous PR #237, to add to the JSON payload of the submitted application, the legal representative details captured in the declaration page.
https://dsdmoj.atlassian.net/browse/CRIMAP-224
> Propagate legal representative details to datastore

- app/forms/steps/submission/declaration_form.rb
- spec/forms/steps/submission/declaration_form_spec.rb
Fixes a bug that was stopping users submitting applications
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-250
Users were only able to submit an application if they changed the legal representative details on the declaration page
Users should be able to submit applications without changing the legal representative details
Submit multiple applications without changing the legal representative details
> change location of guard clause for updating provider details

- app/forms/steps/case/offence_date_fieldset_form.rb
- app/models/charge.rb
- app/presenters/charge_presenter.rb
- app/presenters/summary/components/offence_answer.rb
- app/serializers/submission_serializer/definitions/offence.rb
- app/services/adapters/structs/charge.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/charges/edit.html.erb
- app/views/steps/case/charges_summary/_offence_details.html.erb
- app/views/steps/shared/_charge.html.erb
- app/views/steps/submission/shared/_offence_answer.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- db/migrate/20230110130424_add_range_to_offence_dates.rb
- db/schema.rb
- spec/forms/steps/case/charges_form_spec.rb
- spec/forms/steps/case/offence_date_fieldset_form_spec.rb
- spec/models/charge_spec.rb
- spec/presenters/summary/components/offence_answer_spec.rb
- spec/presenters/summary/sections/offences_spec.rb
- spec/requests/charges_summary_spec.rb
- spec/serializers/submission_serializer/definitions/offence_spec.rb
- spec/services/adapters/structs/charge_spec.rb
- spec/services/datastore/application_submission_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/views/steps/submission/shared/_offence_answer.html.erb_spec.rb
A new requirement is needed to allow adding date ranges, with a start and end date, being the end date optional, to the current offences page.
Figma designs (still some open questions to be addressed in follow-up PRs): https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=3328%3A27560&t=NqyXwuhArytsMxws-4
Note this PR looks like a lot of changes but it is mostly the removal of the old `date` attribute and replacement with a `date_from` (and `date_to` still not used in many places).
To maintain compatibility as much as possible, existing submitted applications will continue rendering the certificate page. Also, applications will keep submitting a "dates" array with just the `date_from` until the schema is changed in a follow-up PR.
NOTE: locally stored applications (not …
> CRIMAP-232 Add date ranges in offences page

- app/models/charge.rb
- app/presenters/charge_presenter.rb
- app/services/adapters/structs/charge.rb
- app/views/steps/shared/_charge.html.erb
- spec/models/charge_spec.rb
- spec/presenters/charge_presenter_spec.rb
- spec/requests/charges_summary_spec.rb
- spec/services/adapters/structs/charge_spec.rb
This PR builds up upon previous one #242 to show in the different views the date ranges when there are any, or just the `date_from` if there is no range.
It prepares the path to update the schema and start submitting ranges to the datastore, which will be done separated in another PR.
https://dsdmoj.atlassian.net/browse/CRIMAP-232
Add offences with different combinations of single date or range dates, and see how they show in the charges summary page, and the check your answer page.
> CRIMAP-232 Show date ranges if entered

- Gemfile.lock
- app/serializers/submission_serializer/definitions/offence.rb
- app/services/adapters/structs/charge.rb
- spec/serializers/submission_serializer/definitions/offence_spec.rb
- spec/services/adapters/structs/charge_spec.rb
Final follow up to previous PRs.
This uses the updated schema, to push the new ranges format for offence dates.
However sadly old submitted applications can't be read once this is merged. An SQL migration can be run to update those applications or maybe is time to wipe out the datastore and start fresh.
NOTE: the schemas gem is not yet updated in the datastore. Merge this PR after that is done.
https://dsdmoj.atlassian.net/browse/CRIMAP-251
New applications are able to be submitted with date ranges in the offences, once the datastore start using the new schema.
> Submit to datastore new offence ranges

- Gemfile.lock
- app/presenters/summary/sections/case_details.rb
- app/presenters/summary/sections/contact_details.rb
- config/locales/en/errors.yml
- config/locales/en/summary.yml
- spec/presenters/summary/sections/case_details_spec.rb
- spec/presenters/summary/sections/contact_details_spec.rb
Add previous MAAT ID and financial change details (depending on case type selection) to the Check your answers page.
Additionally and on the back of recent PR #244 that made the applicant telephone number optional, update the CYA to show `None` if the telephone is left blank so the provider is aware of this. Same as we do with other optional fields.
https://dsdmoj.atlassian.net/browse/CRIMAP-222
> CRIMAP-222 Add missing MAAT ID info to CYA

- app/controllers/steps/base_step_controller.rb
- app/controllers/steps/case/charges_controller.rb
- app/controllers/steps/case/codefendants_controller.rb
- app/views/steps/case/codefendants/edit.html.erb
- config/locales/en/steps.yml
- spec/controllers/steps/case/charges_controller_spec.rb
- spec/controllers/steps/case/codefendants_controller_spec.rb
On the back of some recent accessibility conversations, it was raised the suggestion to show a notification when an item, from a list of multiple items, is deleted, so screen readers can read it aloud.
Made possible by extending the `#update_and_advance` method to support a new `flash` kwarg, so this can be used in other steps to show a flash when advancing to next step.
This applies to the co-defendants page (removing an existing co-defendant) and to the offences page (removing an existing offence date).
Additionally and to be consistent with Offences, the co-defendant "Remove" buttons are also numbered, as required for accessibility reasons.
https://dsdmoj.atlassian.net/browse/CRIMAP-253
Add more than 1 co-defendant or more than 1 offence date, and then delete any of those. It should …
> CRIMAP-253 Confirm item deletion with flash alert

- app/views/steps/client/has_partner/edit.html.erb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
Remove hint text on the partnership page and replace with a list of definitions of a partner
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-230
> update hint text on partner page

- app/presenters/summary/sections/case_details.rb
- spec/presenters/summary/sections/case_details_spec.rb
This is a small refinement to a previous PR #246 to ensure optional fields like the previous MAAT ID show as `None` in the check your answers page, if they are left blank.
This comes as confirmation from service designer that this is how it should be.
https://dsdmoj.atlassian.net/browse/CRIMAP-222
Select different case types, with or without MAAT ID, and see how it shows in the CYA as `None` depending if it was entered or not.
> CRIMAP-222 Reference optional MAAT ID in CYA

- .dockerignore
- .github/workflows/test-build-deploy.yml
- Dockerfile
Although currently our docker image is quite contained in size, and it is fast enough to build, some gains can be obtained (and make it easier to expand in the future) by using multi-stage builds.
Removed a few build deps that it seems were not necessary, at least in my local tests, but until a full deployment is done I can't be certain for sure. Worst case scenario we need to add them back.
Additionally, the Alpine image has been bumped to the latest one, 3.16
Results for `time docker build --no-cache .`
```
Original Dockerfile
non-cached build
time - 1:01
size - 877MB
Improved Dockerfile (multi-stage)
non-cached build
time - 0:48
size - 597MB
```
> Use Dockerfile multi-stage builds and update deps

- .rubocop.yml
- Gemfile.lock
- app/forms/steps/submission/declaration_form.rb
- app/lib/laa_portal_setup.rb
- app/models/crime_application.rb
- app/models/provider.rb
- app/presenters/summary/html_presenter.rb
- app/serializers/submission_serializer/sections/application_details.rb
- app/serializers/submission_serializer/sections/provider_details.rb
- app/services/datastore/application_submission.rb
- db/migrate/20230119163611_add_provider_details_to_application.rb
- db/schema.rb
- spec/forms/steps/submission/declaration_form_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/application_details_spec.rb
- spec/serializers/submission_serializer/sections/provider_details_spec.rb
- spec/services/datastore/application_submission_spec.rb
On submission, the currently signed in provider email address gets injected into the application to be propagated to the datastore along with the already existing legal representative attributes.
NOTE: on staging we are currently using a somehow lacking SAML mock, which does not return to us any email address. In the interim until we properly integrate with LAA Portal staging environment, a fallback email will be used, just so the schema validates the payload.
Additionally, and as recently discussed, Apply will stop sending a `status` attribute when submitting applications to the datastore. This attribute is redundant on submissions and the datastore was already setting the status to `submitted` anyways.
https://dsdmoj.atlassian.net/browse/CRIMAP-121
Submitted applications (if testing …
> CRIMAP-121 Propagate provider email address

- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/completed_applications_controller.rb
- app/controllers/concerns/datastore_application_consumer.rb
- app/controllers/dashboard_controller.rb
- app/controllers/steps/submission/confirmation_controller.rb
- app/presenters/crime_application_presenter.rb
- app/serializers/submission_serializer/sections/application_details.rb
- app/services/adapters/base_application.rb
- app/services/datastore/application_rehydration.rb
- app/services/decisions/submission_decision_tree.rb
- app/views/completed_applications/index.html.erb
- app/views/completed_applications/show.html.erb
- app/views/crime_applications/edit.html.erb
- app/views/crime_applications/index.html.erb
- app/views/steps/submission/confirmation/show.en.html.erb
- db/migrate/20230123111219_add_parent_id_to_applications.rb
- db/schema.rb
- spec/controllers/steps/submission/confirmation_controller_spec.rb
- spec/presenters/crime_application_presenter_spec.rb
- spec/serializers/submission_serializer/sections/application_details_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
The PR is a bit large with a changes in some other files as I took the opportunity to refactor some of the old code we had (from the time when the applications were still not purged in the local DB).
On rehydration of returned applications, persist the UUID of the returned application as `parent_id` in the new, in_progress, application, so by the time it is submitted we can propagate this to the datastore.
This `parent_id` can then be used to know things like:
- it is a resubmission (as first-time submissions will have this attribute to nil)
- what application (submitted, persisted in the datastore) this new resubmission was originated from
- link all resubmissions together for a given USN and perform diffs.
https://dsdmoj.atlassian.net/browse/CRIMAP-239 …
> CRIMAP-239 Implement returned applications parent_id

- Gemfile.lock
- app/controllers/developer_tools/crime_applications_controller.rb
- app/views/layouts/_developer_tools.html.erb
Use the new v2 return endpoint to mark an application as returned from the developer tools.
When viewing a submitted application, go to the footer, developer tools, and there will be a button `Return application`.
Returned applications will show in the returned list in the dashboard.
The reason will be added in another PR.
NOTE: it requires a PR currently open in the datastore to be merged in order for the new endpoint to work.
> Update developer tools with new return action

- app/views/completed_applications/_return_notification.html.erb
- app/views/completed_applications/show.html.erb
- config/locales/en/dashboard.yml
- spec/requests/dashboard_spec.rb
NOTE: design and copy is still under discussion with service designers but will be some similar incarnation to what is being implemented here.
When an application is returned, rendering its certificate page will show a notification banner in the top of the page with the return details. These details come from the datastore.
There is a separate ticket to redesign the application overview details (reference number, date stamp, date submitted...)
https://dsdmoj.atlassian.net/browse/CRIMAP-264
Mark an application as returned, and go to its certificate page in the dashboard. It requires latest version of the datastore running locally (or use harness).
> CRIMAP-264 Show return details in certificate page

- config/kubernetes/staging/deployment.tpl
Follow-up to previous PR #267.
The new secrets (portal certificates) are created but if we don't specify them in the deployment template, they are not being picked up 🤦‍♂️
> Add additional secretRef to deployment template

- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/completed_applications_controller.rb
- app/controllers/concerns/datastore_application_consumer.rb
- app/controllers/developer_tools/crime_applications_controller.rb
- app/models/crime_application.rb
- app/presenters/crime_application_presenter.rb
- app/presenters/tasks/declaration.rb
- app/services/adapters/base_application.rb
- app/services/datastore/get_application.rb
- app/services/datastore/list_applications.rb
- app/value_objects/application_status.rb
- app/value_objects/value_object.rb
- db/migrate/20230130161415_set_default_application_status.rb
- db/schema.rb
- spec/models/crime_application_spec.rb
- spec/presenters/crime_application_presenter_spec.rb
- spec/presenters/summary/sections/base_section_spec.rb
- spec/presenters/tasks/declaration_spec.rb
- spec/services/adapters/structs/applicant_spec.rb
- spec/services/adapters/structs/case_details_spec.rb
- spec/services/adapters/structs/crime_application_spec.rb
- spec/services/adapters/structs/interests_of_justice_spec.rb
- spec/services/datastore/get_application_spec.rb
- spec/services/datastore/list_applications_spec.rb
- spec/support/factory_helpers.rb
- spec/value_objects/application_status_spec.rb
- spec/value_objects/value_object_spec.rb
This is mostly a refactor and tidy up of some code that no longer makes sense because we only have in progress applications locally, and anything else is remote (datastore).
Previously, we had still a few coupling of the `status` values to locally persisted records, this is no longer the case.
To be extremely explicit, the `enum` in the `CrimeApplication` model now only support `in_progress` values so it forbids trying to persist to local DB a record in any other status (to limit mistakes).
Implement (similar to the others we already had) a `Datastore::GetApplication` service object that encapsulates the call to the API and handling of errors (including not found).
Awaiting confirmation from service designer on what to do with `superseded` applications, but for now, and for the sake of …
> CRIMAP-267 Better handling of application statuses

- app/views/completed_applications/_return_notification.html.erb
- app/views/completed_applications/show.html.erb
- config/locales/en/dashboard.yml
- spec/requests/dashboard_spec.rb
This is a follow-up PR to #265, as the final design and copy has now been decided by service designers.
There are no functional changes.
https://dsdmoj.atlassian.net/browse/CRIMAP-264
Figma resubmission journey:
https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=4595%3A50120
This will show in any returned application certificate.
> CRIMAP-264 Update design and copy in returned page

- config/kubernetes/staging/deployment.tpl
We are not using these portal secrets anymore as a consequence of previous PR #273. Forgot to clean up this.
> Remove unused secret ref from deployment

- .env.development
- Gemfile
- Gemfile.lock
- config/initializers/datastore_client.rb
- config/initializers/simple_jwt_auth.rb
- config/kubernetes/staging/deployment.tpl
Merging this will not enable JWT or change any functionality on Apply, as it is not enabled yet (to enable, change `config.auth_type = :jwt`).
Once enabled, the datastore API client will make use of a little middleware introduced in the `simple-jwt-auth` gem to generate and send a JWT bearer token.
https://dsdmoj.atlassian.net/browse/CRIMAP-273
If wanted to test locally, a corresponding PR has been raised in the datastore repo, in order to have an end to end, locally-testable demo.
> Prepare Apply to use datastore JWT auth

- .env.development
- .env.test
- Gemfile
- Gemfile.lock
- config/initializers/datastore_client.rb
The `moj-simple-jwt-auth` gem is now included in the `datastore-api-client` gem, so we don't have to add it explicitly to the Gemfile.
Tidy up some env variables.
**NOTE: this PR once merged will enable JWT authentication against the Datastore. Corresponding PRs will be raised in Review and in the Datastore.
Keeping all in place for a quick revert to http basic auth if needed.**
https://dsdmoj.atlassian.net/browse/CRIMAP-277
> Bump datastore api client gem and enable JWT auth

- .env.development
With openssl >= 3.0.0 you need to have something in those secrets. Nil or empty string will produce an error.
With openssl < 3.0.0 a nil value will blow up but funnily enough not an empty string.
To avoid confusion and edge cases with the openssl version installed in each system, we set a default dummy value, so developers don't need to set their own in their `.local` files.
> Set a more sensible default for ENV variable

- Gemfile
- Gemfile.lock
- config/initializers/filter_parameter_logging.rb
- config/initializers/lograge.rb
Logs to stdout so other systems can route these logs to final destinations for viewing and long-term archival. For example this is needed to see the logs in Kibana.
Also, added PII parameters to the filter. These are also used by Sentry when reporting exceptions.
https://dsdmoj.atlassian.net/browse/CRIMAP-286
On local environments this new log stream to stdout can seen and tested by running the app in production mode, or by using docker-compose.
In our k8s namespaces, logs will output to stdout and can be accessed in Kibana.
> CRIMAP-286 Configure logging and filtering of PII

- config/initializers/lograge.rb
This should read `filtered_parameters` instead of `params`. Which is why I added the params to the `config/initializers/filter_parameter_logging.rb` file in previous PR #280 :facepalm
> Use the post-processed and filtered params hash

- app/lib/laa_portal_setup.rb
- app/models/provider.rb
- config/kubernetes/staging/config_map.yml
- config/laa_portal/metadata/dev.xml
- spec/lib/laa_portal_setup_spec.rb
This is just a test. We will not be using Portal DEV on staging, however in conversations with PCUAM team we want to try if SP-initiated auth works in a cloud environment as opposite to localhost.
I may try this twice, first with `idp_sso_service_binding: :redirect` followed with a second test with `idp_sso_service_binding: :post`.
> (test) Portal DEV integration (SP-initiated)

- app/lib/laa_portal_setup.rb
- config/kubernetes/staging/config_map.yml
- spec/lib/laa_portal_setup_spec.rb
Follow-up to PRs #282 and #283.
Revert to use SAMLmock so staging is functional for the time being until we have a corresponding Portal staging env integration.
> (test) Portal DEV integration (use SAMLmock again)

- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/forms/steps/case/charges_form_spec.rb
As a preparation for an accessibility audit, we must try to avoid repetition of error messages (in summary) when in a page there are more than "1 thing of the same".
For instance, in the interests of justice page, when more than one justification text area was left blank, the error summary was repeating "Enter more detail" multiple times. This is no good.
Tweaked these and other minor changes in Offences page (hint texts, labels, etc.) after suggestions from content designer.
Some more copy changes might be implemented on follow-up PRs.
https://dsdmoj.atlassian.net/browse/CRIMAP-254
Go to the corresponding pages and produce the errors by leaving blank fields or incorrect dates, etc.
> CRIMAP-254 Avoid error message repetition

- app/javascript/local/suggestions.js
This minor improvement will show in the "Suggestions" dropdown header, the number of offences returned. This is handy for non visually impaired users, as it may not be immediately evident to some that the suggestions box is scrollable when more than 5 or 6 offences are returned.
Additionally, it is even more important for visually impaired users, using screen readers, as the number of suggestions will be announced whenever there are any changes (polite so it waits for any other text to be read first).
Tested with VoiceOver on Mac, further testing or tweaks might be needed, these may come up as part of the accessibility audit.
NOTE: I've marked the code changes, as with other tweaks we've made to this component, with `[change]`, so it is easy to cherry pick these in case the component …
> Offence suggestions a11y tweaks

- config/locales/en/helpers.yml
Related to accessibility issue "Secondary input field not linked to primary input".
We are using visually-hidden labels for each of those text areas, so I believe a screen reader should have additional context when using each of the text areas.
For example these visually hidden labels read like this:
- Unable to represent themselves justification
- Expert cross-examination justification
Etc.
I've updated to copy in some of them to be in line with the same copy we use in the Check your answers page.
Tested with VoiceOver on Mac, the visually hidden label is read aloud when entering the text area, giving full context to the user.
https://dsdmoj.atlassian.net/browse/CRIMAP-296
> CRIMAP-296 IoJ secondary input field copy tweaks

- .env.development
- README.md
The harness has been decommissioned in favour of running a local instance of the datastore.
https://dsdmoj.atlassian.net/browse/CRIMAP-287
> Remove references to the datastore harness

- config/kubernetes/staging/config_map.yml
- config/kubernetes/staging/ingress.yml
As per documentation:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrating-from-live-1-domain-name.html
This is part of a broader ticket to use a custom domain for staging, however, for now this makes the service more resilient in case of cluster changes, until we have a production namespace and we set the proper final (and public) domains.
Old `*.apps.live` domain redirects to new domain to avoid breaking bookmarks etc.
https://dsdmoj.atlassian.net/browse/CRIMAP-172
Both domains should work. If using old one (the `live` one) it will redirect to the non-cluster one (as in, no `live` in the URL).
> CRIMAP-172 Use non-cluster specific domain

- app/services/dwp/mock_benefit_check_service.rb
There are some scenarios where the DWP mock values wouldn't work, if the day or the month was entered with a different format to the expected by the mock.
Tweaked the code so it works no matter the format, so it works for 1-digit or 2-digits days and months (i.e. 1/1/1980 or 01/01/1980).
https://dsdmoj.atlassian.net/browse/CRIMAP-298
Raised as some team members found issues entering mock DWP details. I've also updated the confluence page.
You can enter date of births with 1-digit or 2-digits for day or month, and it will still validate if it is a mock DWP or not.
> CRIMAP-298 Ensure DWP mock works in all cases

- config/kubernetes/staging/config_map.yml
- config/kubernetes/staging/deployment.tpl
- config/laa_portal/metadata/dev.xml
- config/laa_portal/metadata/samlmock.xml
- config/laa_portal/metadata/staging.xml
Swap SAMLmock with Portal Staging.
So our staging talks to Portal staging, as it should be.
Keeping the DEV and samlmock metadata files around, because on localhost envs is useful to be able to use SAMLmock, although ideally this will some day be replaced with DEV (but it is not working so far).
There will be some follow-up PRs for some tickets that are unblocked by this PR.
NOTE 1: there is still a chance this will not work on staging. I've tested locally SP-initiated auth and it works, but can't test IdP-initiated auth until this is deployed and our service is using the staging certificates.
NOTE 2: if this works, new credentials are required to sign in to Apply. These credentials will be shared with the team. Also, the office codes of the new user(s) will change so old applications …
> CRIMAP-38 Replace samlmock with portal staging

- app/lib/laa_portal_setup.rb
- spec/lib/laa_portal_setup_spec.rb
This is a pre-requisite in order to test if Portal can trigger a SLO request to our service. The URL must be exposed in the metadata.
https://dsdmoj.atlassian.net/browse/CRIMAP-300
After deploy, the metadata will expose the SLO url.
> CRIMAP-300 Expose SP SLO url in metadata

- app/controllers/providers/omniauth_callbacks_controller.rb
- app/lib/laa_portal_setup.rb
- app/models/provider.rb
- app/services/provider_gatekeeper.rb
- config/locales/en/devise.yml
- spec/models/provider_spec.rb
- spec/services/provider_gatekeeper_spec.rb
- spec/system/sign_in_spec.rb
Also there is some work in preparation for CRIMAP-261, to allow or disallow providers using our service unless they've been onboarded to our private MVP.
In this PR the rules based on office code are not implemented yet, but I've implemented some boilerplate code to prepare for this, and to stop providers without LAA accounts (office codes) from using our service.
https://dsdmoj.atlassian.net/browse/CRIMAP-259
https://dsdmoj.atlassian.net/browse/CRIMAP-261
This can be tested locally by checking out the branch, using the SAMLmock, and signing in with user "ABRA-S" who doesn't have any office codes. On staging I don't know how likely this scenario would be, probably very unlikely, but as some degree of gatekeeping is necessary, this is a fair check.
Email of the signed in provider is shown …
> CRIMAP-259 Show provider email in header

- .github/workflows/test-build-deploy.yml
Github is deprecating the `set-output` and `save-state` commands. More info: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Updated the cache action where this is used.
Also bumped `gh-ecr-push` action to latest version (sha).
> Fix github set-output command deprecation

- app/controllers/errors_controller.rb
- app/controllers/providers/omniauth_callbacks_controller.rb
- app/services/providers/gatekeeper.rb
- app/views/errors/not_enrolled.en.html.erb
- config/application.rb
- config/gatekeeper.yml
- config/locales/en/devise.yml
- config/locales/en/errors.yml
- config/routes.rb
- spec/requests/errors_spec.rb
- spec/services/providers/gatekeeper_spec.rb
- spec/system/sign_in_spec.rb
Implement an initial enrolment/allowlist based on office account codes.
The error page where the user is redirected is still TBD and copy and design will be provided once that has been agreed (there is a separate ticket).
Upon some comments in previous PR #294 I cleanup some of the previous gatekeeper code, and did some renaming too.
Note it may be we also want to allow by email address, but that has not been decided yet. If required, it is almost ready to implement, only caveat we would not want emails committed to the repo, so they might require hashing.
https://dsdmoj.atlassian.net/browse/CRIMAP-246
https://dsdmoj.atlassian.net/browse/CRIMAP-303
Copy in the error page TBD. There is a separate ticket for design/content (CRIMAP-260)
This can be tested locally by using the SAMLmock and …
> CRIMAP-246 Provider's office account enrolment check

- app/lib/laa_portal/saml_setup.rb
- app/lib/laa_portal/saml_strategy.rb
- spec/lib/laa_portal/saml_setup_spec.rb
This is a follow-up to PR #293 for the SLO investigations/spike.
Trying out `post` binding instead of `redirect` binding, as with redirect we get blocked with a 403 by cloudfront.
Also, do not blow up at the rack level if the endpoint can't process the SLO request (for example if it is called without a SAML payload), and show a nice page with a flash error instead (by bubbling up a re-raised `StandardError`).
https://dsdmoj.atlassian.net/browse/CRIMAP-300
> CRIMAP-300 Tweaks for Portal SLO

- app/assets/config/manifest.js
- app/controllers/concerns/error_handling.rb
- app/controllers/providers/omniauth_callbacks_controller.rb
- app/views/layouts/govuk_template.html.erb
- config/environments/production.rb
- config/initializers/assets.rb
- config/kubernetes/staging/config_map.yml
- docker-compose.yml
Some assets coming from `govuk-frontend` were not being correctly referenced and part of the assets pipeline.
These mainly includes favicons of different sizes. Removed static favicon files in `public` directory as we don't want these to be used, but instead the govuk frontend ones.
Modernised the `govuk_template` and the references to these paths.
Additionally, set logging to stdout on production (this is separate to lograge that logs the requests and was already configured to use stdout), and add some additional logging in key areas.
https://dsdmoj.atlassian.net/browse/CRIMAP-305
> CRIMAP-305 Fix govuk branded assets

- app/models/person.rb
- app/presenters/tasks/client_details.rb
- spec/models/person_spec.rb
- spec/presenters/tasks/client_details_spec.rb
Originally we had the `telephone_number` as a mandatory field, but some time ago we decided to make it optional, thus we don't have to check for presence in order to consider the task "completed", as `telephone_number` can be left blank.
Only `correspondence_address_type` is mandatory now.
Made the rules for the correspondence address more stringent by checking we have indeed the address record filled when `home address` or `other address` are selected.
> Update client details task completed rules

- app/assets/stylesheets/local/custom.scss
- app/javascript/application.js
- app/views/layouts/_header_navigation.html.erb
This was driving me crazy when testing the site on small screens / mobile. It is very noticeable on Safari, less so on Chrome. The recordings are from Safari.
There is an annoying thing happening with the header menu when a user is signed in to Apply.
On small screens, like mobile devices, each time a page is loaded, the header menu briefly shows (a few milliseconds) before being hidden. This is a bit annoying.
The header menu should be hidden on small screens unless the user clicks the “Menu“ button, at that point the menu is revealed, until they click the “Menu” button again, and it is hidden.
After playing with the order of the javascript loading, `preload` and other things, I've not been able to pinpoint exactly why this happen and how to solve it, thus this mitigation which shouldn't …
> CRIMAP-307 Mitigate header menu flickering

- config/kubernetes/staging/config_map.yml
The accessibility audit team needs testing on mobile devices, however the VPN is quite tricky to setup on mobile, thus temporarily we are going to disable LAA Portal auth and fake it with the omniauth test mode.
> Enable omniauth test mode temporarily

- config/kubernetes/staging/config_map.yml
This reverts commit 7bbfe33cdc35c5bacb8462cac60f2887e49cffa5.
Accessibility audit on mobile devices has concluded and we are re-enabling LAA Portal staging again.
> Revert "Enable omniauth test mode temporarily (#307)"

- app/forms/steps/case/charges_form.rb
- app/forms/steps/case/offence_date_fieldset_form.rb
- spec/forms/steps/case/charges_form_spec.rb
On the offences page, the dates are nested attributes. On submit these nested attributes were assigned to the `record` (`Charge` model) with `record.offence_dates_attributes=(params)`.
We use `accepts_nested_attributes_for :offence_dates` in `Charge` for this.
This works perfectly fine when the dates are valid. However if any of the dates is invalid, for instance month 13, or day 38, it blows up with `ActiveRecord::MultiparameterAssignmentErrors` because Rails internally was instantiating Date objects from the params, and `Date.new(2022, 13, 5)` is invalid.
What we want is to give a meaningful error to the user, and style as "red" the field giving the error, and show the error summary.
In order to do this we have to change the approach, instead of:
1. Assign the dates params (which …
> CRIMAP-308 Fix offence dates validation

- config/locales/en/dashboard.yml
Without split_case in dashboard.yml the app will fail to work as expected when a split_case return type is returned (possible as laa schema now allows it)
Partially completes https://dsdmoj.atlassian.net/browse/CRIMAP-311
N/A
Manually change the return_details.reason field to 'split_case' in datastore DB
Load Apply, navigate to the returned application and the banner title will have the 'split case' title
> [CRIMAP-311] Temporarily add split_case locale entry

- app/services/age_calculator.rb
- app/services/decisions/client_decision_tree.rb
- app/services/ioj_passporter.rb
- config/settings.yml
- spec/services/decisions/client_decision_tree_spec.rb
Currently all applicants route from client details to NINO u18 applicants are passported and do not need a passporting benefit therefore do not need a NINO to run a DWP check
This PR changes the routing for u18 applicants from client details to address lookup
u18 passporting feature flag turned on for test env
https://dsdmoj.atlassian.net/browse/CRIMAP-317
Feature flag for u18 passporting is on in the test env
Enter a dob on client details page that means a user is u18
> Fix routing for u18 post client details

- app/presenters/summary/sections/passport_justification_for_legal_aid.rb
- app/presenters/tasks/ioj.rb
- app/services/datastore/application_rehydration.rb
- app/services/ioj_passporter.rb
- config/locales/en/summary.yml
- config/settings.yml
- db/migrate/20230411155225_add_ioj_override_field.rb
- db/schema.rb
- spec/presenters/summary/sections/passport_justification_for_legal_aid_spec.rb
- spec/presenters/tasks/ioj_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
- spec/services/ioj_passporter_spec.rb
Split case passported applications are returned to the provider asking them to provide IoJ details.
This PR implements a new boolean flag in the `Ioj` table `passport_override` (false by default). This flag gets set on rehydration of returned application that have been returned due to split case.
In a few places along the application, changes has been made to use this flag so:
1. On a returned application, the "Review" page shows an "Justification for legal aid" section with a different copy and a change link (NOTE: copy to be confirmed with content designer, can be done in a separate PR).
2. If the provider clicks any other change link before the IOJ and goes through the application, the `passport_override` flag is used to show the IOJ page, even if they are passported.
3. The task list …
> CRIMAP-312 Implement split case IoJ passporting logic

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/developer_tools/crime_applications_controller.rb
- app/presenters/summary/sections/client_details.rb
- app/serializers/submission_serializer/sections/application_details.rb
- app/services/adapters/structs/applicant.rb
- app/services/datastore/application_rehydration.rb
- app/services/passporting/ioj_passporter.rb
- app/services/passporting/means_passporter.rb
- spec/presenters/summary/sections/client_details_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/application_details_spec.rb
- spec/services/adapters/structs/applicant_spec.rb
- spec/services/adapters/structs/case_details_spec.rb
- spec/services/adapters/structs/interests_of_justice_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
- spec/services/datastore/application_submission_spec.rb
Second part of previous PR #321.
It bumps the schemas gem and uses the new attribute when reading back applications and on rehydration.
Removed some previous, hardcoded, unused attributes.
NOTE: DoB edge case is not yet deal with here (where a submitted application is under18 but on re-hydration applicant has become over18).
https://dsdmoj.atlassian.net/browse/CRIMAP-331
Submission of under 18 passported applications (NINO will be nil as we don't ask for it) should be successful. On the submitted application JSON, the `ioj_passport` should contain `['on_age_under18']` and the `means_passport` should contain ['on_age_under18'].
IoJ page is not shown on first run, but it is shown on returned applications due to split case.
> CRIMAP-331 Propagate `means_passport` to datastore

- app/models/concerns/passportable.rb
- app/models/crime_application.rb
- app/presenters/tasks/case_details.rb
- app/presenters/tasks/ioj.rb
- app/services/decisions/client_decision_tree.rb
- app/services/passporting/base_passporter.rb
- app/services/passporting/means_passporter.rb
- config/settings.yml
- spec/models/concerns/passportable_spec.rb
- spec/presenters/tasks/case_details_spec.rb
- spec/presenters/tasks/ioj_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
- spec/services/passporting/means_passporter_spec.rb
One edge case not covered in previous PR was the fact, a passported application (mostly on the basis of under 18, but could also be on the basis of the DWP check) that is returned back to the provider, should keep the original passporting and not try to re-run the checks or take the provider through a different journey to the original one.
In practice this means:
- if original application was for an under 18 client, then the returned application will not ask for NINO nor run the DWP check, and remain passported upon submission.
- same for over 18 with a successful DWP check (in this case, the NINO page is shown to the provider, but the DWP check is not triggered).
This PR introduce some refactor to make this easier, with some syntax-sugar methods in a concern `Passportable`.
Also, …
> CRIMAP-337 Deal with returned passported applications

- app/services/datastore/application_rehydration.rb
- spec/services/datastore/application_rehydration_spec.rb
Non date-stampable case types should obtain a new date stamp on resubmission, instead of inheriting their parent's.
This fixes a bug observed on staging with resubmission of `Indictable` and `Already in Crown Court` application case types.
https://dsdmoj.atlassian.net/browse/CRIMAP-338
Submit 2 applications. One application with a date-stampable case type, (for instance, Summary only) and another with a non date-stampable case type (for instance, Indictable).
Return both applications back to the provider.
Resubmit both applications. Date stampable one will retain original date stamp. Non date-stampable one will generate a new date stamp on submission (equal to submitted_at date).
> CRIMAP-338 Handle resubmission date stamp

- config/kubernetes/staging/config_map.yml
We are evaluating internal cross-namespace networking between Apply/Review and Datastore.
For the time being and until we decide so, external ingress will still be available.
https://dsdmoj.atlassian.net/browse/CRIMAP-328
In theory everything should continue working as before, just slightly less latency when loading lists or paginating (thus difficult to evaluate as we don't have that many records yet).
> CRIMAP-328 Switch datastore URL to internal svc

- .github/workflows/test-build-deploy.yml
- .gitignore
- docker-compose.yml
The version of postgres in cloud platform Apply namespace has been upgraded to 15.2.
For consistency, use the same version in the CI/CD pipeline and in the docker-compose file.
Also as I have set up RubyMine locally, so i've added code to ignore the local `.idea/` repository which contains project-specific settings 
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-343
> Upgrade ci/cd postgres version

- Gemfile.lock
We've updated recently a couple of internal gems, although is not needed for Apply, is recommended to use these new versions in case we've introduced any regression inadvertently.
> Minor bundle bump to use latest datastore gems

- README.md
- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
This is a subdomain of our production domain.
Follow-up to PR #331.
Internal cloud platform URLs are still available and functional, but this is now an easier to remember domain.
The cloud URLs will redirect to their corresponding "nice" domains.
Some functionality in Portal will still redirect to old cloud URL until metadata is updated on their side.
https://dsdmoj.atlassian.net/browse/CRIMAP-172
> CRIMAP-172 Add staging subdomain to ingress

- .env.development
- config/application.rb
- config/initializers/devise.rb
- config/kubernetes/production/config_map.yml
- config/kubernetes/staging/config_map.yml
- config/settings.yml
We had a hardcoded, long session timeout. This was fine for staging as we don't want to have to continuously authenticate with Portal (specially because it also needs the VPN).
However in production we want this to be a much shorter period of time, to increase security.
It is configurable, so in localhost we can still have a longer or shorter period that can help with development by setting the `SESSION_TIMEOUT_MINUTES` variable in the `.env.development.local` file.
Reduced staging from 48 hours to 24 hours timeout. Configured production to 1 hour timeout.
These are sensible defaults, can be tuned later on.
> Tweak devise session timeout depending on env

- config/initializers/datastore_client.rb
- spec/controllers/steps/submission/confirmation_controller_spec.rb
- spec/requests/dashboard_lists_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/datastore/application_counters_spec.rb
- spec/services/datastore/application_submission_spec.rb
- spec/services/datastore/get_application_spec.rb
- spec/services/datastore/list_applications_spec.rb
This needs to go together or soon after this other PR: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/88
https://dsdmoj.atlassian.net/browse/CRIMAP-350
> Use v1 of the datastore

- app/services/passporting/base_passporter.rb
- app/services/passporting/ioj_passporter.rb
- app/services/passporting/means_passporter.rb
- spec/services/passporting/ioj_passporter_spec.rb
This covers an edge case where the applicant is aged under 18 and thus is passported on IoJ on the first submission and then the application is returned by the caseworker when applicant is already over 18, or the applicant turns 18 before the application is resubmitted again.
In summary, if the application is a resubmission, we don't run again the age check, instead we use whatever result the initial submission had.
https://dsdmoj.atlassian.net/browse/CRIMAP-346
Application remains IoJ passported on age, even when the applicant have turned 18 between the original application being submitted and the resubmitted application being submitted.
> CRIMAP-346 Under 18 IoJ on returned applications

- app/controllers/providers/omniauth_callbacks_controller.rb
- app/views/errors/not_enrolled.en.html.erb
- app/views/shared/_eforms_redirect.en.html.erb
- config/gatekeeper.yml
- config/settings.yml
- spec/system/sign_in_spec.rb
Implement the content agreed for the not enrolled "error" page, and add the prod test user to the list of allowed office codes in the gatekeeper, so we can access with this user in production.
https://dsdmoj.atlassian.net/browse/CRIMAP-345
This can be tested by using any provider that doesn't have their office codes allowed. Refer to confluence page.
> CRIMAP-345 Implement content for not enrolled page

- .env.development
- app/lib/devise/hooks/reauthable.rb
- app/lib/devise/models/reauthable.rb
- app/models/provider.rb
- config/application.rb
- config/initializers/devise.rb
- config/kubernetes/production/config_map.yml
- config/kubernetes/staging/config_map.yml
- config/locales/en/devise.yml
- spec/models/provider_spec.rb
- spec/support/shared_examples/reauthable_shared_examples.rb
- spec/system/sign_in_spec.rb
This is in addition to the existing idle session timeout mechanism. Implemented via a new custom Devise module `:reauthable`.
The session lifespan will sign out a user (provider), and force them to re-authenticate with Portal, after X minutes have passed from their last sign in, regardless of their activity.
It is configurable, so in localhost we can still have a longer or shorter period that can help with development by setting the `REAUTHENTICATE_AFTER_MINUTES` variable in the `.env.development.local` file.
Staging set to 48 hours. Production set to 24 hours. These are sensible defaults, can be tuned later on.
https://dsdmoj.atlassian.net/browse/CRIMAP-355
On localhost, as per above instructions to set the ENV variable. On staging or prod, waiting for time to pass.
> CRIMAP-355 Implement session lifespan

- app/models/offence.rb
- app/services/passporting/ioj_passporter.rb
- config/settings.yml
- spec/services/passporting/ioj_passporter_spec.rb
Still awaiting final CSV file that will mark the offences that are "passportable". This PR just assumes a new column, named `ioj_passport` and for now it is `nil` for all offences, thus none is passportable.
The logic however is implemented in this PR and also a feature flag to globally (instead of at the offence level) can enable/disable this IoJ passporting.
I've not wanted to make changes to our current CSV file because it will have to change soon again, probably the columns too, as we are splitting multi-class offences.
https://dsdmoj.atlassian.net/browse/CRIMAP-146
User-facing there are no changes with this PR as everything is backend and no offences are passportable yet (CSV file needs to be updated). Can be tested by doctoring the CSV locally. Specs also cover the expected logic.
> CRIMAP-146 Prepare for offence IoJ passporting

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Adds modsecurity to production/staging ingress, copied from Review app
https://dsdmoj.atlassian.net/browse/CRIMAP-358
- Limits HTTP request payloads to 1 Mib
- Limits file upload to 1 Mib
- Enables owasp rules as well
- May be too restrictive
Full smoke test required
Any file upload/download functionality requires manual testing on Staging.
> [CRIMAP-358] Add modsecurity rules to ingress

- app/controllers/application_controller.rb
- app/helpers/analytics_helper.rb
- app/views/layouts/_analytics.html.erb
- app/views/layouts/application.html.erb
- config/application.rb
- config/kubernetes/production/config_map.yml
- config/kubernetes/staging/config_map.yml
- spec/helpers/analytics_helper_spec.rb
This is the basic setup to track visits, drop outs, etc.
More complex analytics (to be able to measure interactions within the step forms) will come as a separate PR. Some custom javascript is required for these.
Also, no cookies consent yet, as that's part of a separate ticket.
https://dsdmoj.atlassian.net/browse/CRIMAP-9
Traffic can be seen in the google analytics website.
> CRIMAP-9 Add basic google analytics setup

- .codeclimate.yml
- app/javascript/application.js
- app/javascript/local/ga-events.js
- app/views/steps/case/charges_summary/_offence_details.html.erb
- app/views/steps/submission/shared/_summary_row.html.erb
This will enhance the basic analytics, with some custom events triggered for certain actions throughout the application steps.
Radio options, checkboxes and dates (just the year part) will be submitted as events on form submits.
Also, individual links can be annotated with the class `ga-pageLink` and a couple data attributes to also send an event. This is useful mostly for "action" links, for instance "change", "remove"... links. I've added a few examples but we can annotate more links if they seem useful.
https://dsdmoj.atlassian.net/browse/CRIMAP-9
> CRIMAP-9 Add some custom GA events

- app/controllers/about_controller.rb
- app/controllers/cookies_controller.rb
- app/controllers/home_controller.rb
- app/controllers/unauthenticated_controller.rb
- app/forms/cookies/settings_form.rb
- app/helpers/analytics_helper.rb
- app/views/cookies/show.en.html.erb
- app/views/layouts/_footer_links.html.erb
- app/views/layouts/application.html.erb
- config/application.rb
- config/routes.rb
- spec/controllers/cookies_controller_spec.rb
- spec/forms/cookies/settings_form_spec.rb
- spec/helpers/analytics_helper_spec.rb
This first PR implements the new cookies controller, helpers and the handling of the cookie settings.
The banner is not shown yet on the page, this is only the backend work.
In a follow-up PR we will enable the banner and its functionality on the frontend following the guidelines and design stated in the design system: https://design-system.service.gov.uk/components/cookie-banner/
https://dsdmoj.atlassian.net/browse/CRIMAP-14
Nothing visible yet (other than a placeholder cookies page, accessible from the footer).
> CRIMAP-14 Prepare for cookies consent

- app/assets/stylesheets/local/custom.scss
- app/views/layouts/_phase_banner.html.erb
- app/views/layouts/govuk_template.html.erb
- config/locales/en/layouts.yml
- spec/requests/home_spec.rb
A few tweaks that makes it more robust. Follow-up to PR #346.
The CSS will in effect use the orange colour for any environment unless it is production (this is better than having to specify one by one the non-prod envs).
The phase tag text will also default to whatever is the name of the env, unless overridden by locales (as it is the case of `production` -> `alpha`). This is also better than having to specify one by one all the env names, as usually the phase tag just shows the same (`staging` -> `staging`, `local` -> `local`).
Added a simple smoke test to ensure the CSS classes are applied correctly and the phase tag text is also correct.
> Tweaks to header colour handling and smoke test

- app/views/steps/dwp/confirm_result/edit.html.erb
Fixes accessibility issue flagged in the audit for screen reader users, where there is no programmatic association between the radio button grouping and the `h1` element on the confirm dwp result page which makes it difficult for non-sighted and low-vision screen reader users to answer if the DWP records are correct.
This PR adds the recommended `aria-describedby` attribute to establish a relationship between the question ‘Are the DWP records correct?’ and the content of the `h1` providing the DWP check result
[CRIMAP-364](https://dsdmoj.atlassian.net/browse/CRIMAP-364)
[CRIMAP-364]: https://dsdmoj.atlassian.net/browse/CRIMAP-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [a11y] No programmatic association between DWP records and radio buttons

- app/views/crime_applications/index.html.erb
- config/locales/en/dashboard.yml
Fixes flagged issue from accessibility audit where there is no association between delete button and applicant name which makes it difficult for screen readers to know which application they are deleting as they are all announced by the screen reader as “Action Column 4 Delete button”
This PR adds an `aria-label` that overrides the existing text and adds the applicant's name as context to which application is being deleted  
[CRIMAP-365](https://dsdmoj.atlassian.net/browse/CRIMAP-365)
[CRIMAP-365]: https://dsdmoj.atlassian.net/browse/CRIMAP-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [a11y] No association between 'delete' button and applicant name

- app/views/steps/case/charges/edit.html.erb
- config/locales/en/helpers.yml
This PR adds a hint to the start date field on the offence page to specify to screenreader users what format the date should be.  This was flagged in the [accessibility audit](https://uv2866-apply-for-criminal-legal-aid.uservisionaccessibility.co.uk/date-format-not-clear-medium.html)
[CRIMAP-368](https://dsdmoj.atlassian.net/browse/CRIMAP-368)
[CRIMAP-368]: https://dsdmoj.atlassian.net/browse/CRIMAP-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [a11y] Date format not clear (offence page)

- app/assets/stylesheets/local/custom.scss
- app/javascript/application.js
- app/javascript/local/subnavigation.js
- app/views/shared/_subnavigation.html.erb
As part of the accessibility audit, a medium severity issue was found with the way the applications sub-navigation tabs reload the whole page (as these are not AJAX).
When the user selects one of these tabs the page reloads and focus moves to the first focusable element on the page.
This can be frustrating for keyboard users who need to tab through the page again to get back to their previous position. For blind and low-vision users relying on screen readers, this behaviour can also be confusing.
The recommendations were to make it AJAX (which has other issues if JS is not enabled, etc.), so this option was disregarded, or to ensure the focus remains on the element it was on prior to the page refreshing.
This is the chosen fix, and although not perfect, it will ensure the navigation with …
> CRIMAP-370 Keep focus on selected sub-nav tab

- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/locales/en/dashboard.yml
The accessibility audit flagged an issue on the ‘Your Applications’ page where the 'next' link does not provide context for screen reader users as to where they will be navigated and what they will be shown. A visually hidden span element has been added to provide additional context to screen reader users that they will be navigated to the next page of applications (as opposed to the next page of the journey for example). This allows them to get a better sense of the content and functionality of the page without having to go through the content in its entirety
[CRIMAP-369](https://dsdmoj.atlassian.net/browse/CRIMAP-369)
Can use voiceover on mac to verify 
[CRIMAP-369]: https://dsdmoj.atlassian.net/browse/CRIMAP-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
> [a11y] Link purpose unclear (pagination)

- app/views/steps/case/charges/confirm_destroy.html.erb
- config/locales/en/steps.yml
The accessibility audit flagged instances of there being no programmatic association between input fields and their question. 
On the 'Clients details' page, context regarding who's details need to be entered is missing for screen reader users where screen readers only announce the label and the type of input, (e.g. 'Full name grouping' "First name edit blank").  In this instance, it is not necessarily clear that those details are about the client.
On the 'Offences summary' page, when inputting the offence of the client, users are given an opportunity to delete the offence. There is no programmatic association between the question 'Are you sure you want to delete this offence?' and the buttons, 'Yes, delete it' and 'No, do not delete it'. For blind and low vision screen reader users the …
> [a11y] No programmatic association between interactive controls and question

- app/controllers/developer_tools/crime_applications_controller.rb
- app/services/dwp/mock_benefit_check_service.rb
- app/views/layouts/_developer_tools.html.erb
- config/routes.rb
Previously there was only one "bypass DWP", which picks a random "mock" user (dob, nino, surname) and creates the record.
However there was a mock under18 so randomly it could happen this under18 user was picked for bypass, leaving the underlying record with inconsistent data (like having NINO, or the `passporting_benefit` flag set to true), which is incorrect for under 18s as we don't ask for NINO nor perform DWP check for those.
Removed this mock user as is no longer needed (no DWP is performed for under 18 anyways) and added a new button to explicitly trigger a bypass of an under 18, which will set everything correctly and even advance a bit more, up to the case type step.
> Allow bypass with an under 18 (developer tools)

- app/controllers/developer_tools/crime_applications_controller.rb
- app/views/layouts/_developer_tools.html.erb
In previous PR #356, the attribute for override should be `passporting_benefit` instead of `dwp`.
Also, hide the bypass buttons once we reach the case details section as by that point these are no longer needed. Keep them during client details section.
> Fix developer tools override attribute name

- Gemfile
- Gemfile.lock
- app/services/adapters/structs/case_details.rb
- spec/services/datastore/application_submission_spec.rb
This version has some breaking changes, mainly for the time being we will only be able to submit single-class (or manually entered) offences, until the split of offences is finalised and the new list is incorporated to the service.
Fixed a few test, one of them for this reason (Robbery was C/B class, changed to a single-class offence).
> Bump the schemas gem to 0.1.9

- Gemfile
- Gemfile.lock
- app/views/steps/case/case_type/edit.html.erb
- app/views/steps/case/charges/edit.html.erb
- app/views/steps/case/codefendants/edit.html.erb
- app/views/steps/case/urn/edit.html.erb
- app/views/steps/client/contact_details/edit.html.erb
- app/views/steps/client/has_nino/edit.html.erb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/importmap.rb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- package.json
- spec/views/steps/submission/shared/_date_answer.html.erb_spec.rb
- yarn.lock
Update GDS and MOJ design systems to their latest releases.
Update form builder to latest version 4.0.0
https://github.com/DFE-Digital/govuk-formbuilder/releases/tag/v4.0.0
This version finally incorporates the improvements to localisation in nested fields, so we can get rid of some superfluous code in the co-defendant and offence pages. https://github.com/DFE-Digital/govuk-formbuilder/pull/386
Also, a new `extra_letter_spacing` can be used in input texts like reference numbers, telephones, codes, etc. that makes it easier to read. I've added this flag where it makes sense in our service. https://github.com/alphagov/govuk-frontend/pull/2230
https://dsdmoj.atlassian.net/browse/CRIMAP-380
After checking out make sure to run `yarn` to pull the new versions of the node modules, and then …
> CRIMAP-380 Update design system and form builder

- app/views/crime_applications/confirm_destroy.html.erb
- app/views/steps/case/case_type/edit.html.erb
- app/views/steps/case/charges/confirm_destroy.html.erb
- app/views/steps/case/ioj/edit.html.erb
- config/locales/en/dashboard.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
The accessibility audit flagged instances throughout the user journey where changes that dynamically appear on screen are not communicated to screen reader users. These are fixed on the `'What is the case type'` and '`Reason for legal aid'` pages by adding aria-labels `aria-live` and `aria-label` that notify users of changes and overrides the visually presented text adding additional context to the user as to what is being requested
This pr also fixes an issue in a [previous PR](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/351) where newly added `aria-labelledby` attributes to delete buttons was subsequently only reading out the question and not the button text. This was replaced by an `aria-label` that will add further context as to what is being deleted …
> [a11y] Dynamic changes not announced to screen reader users

- app/forms/concerns/steps/has_one_association.rb
- app/forms/steps/client/details_form.rb
- app/forms/steps/client/has_nino_form.rb
- spec/forms/steps/client/details_form_spec.rb
- spec/forms/steps/client/has_nino_form_spec.rb
- spec/support/shared_examples/form_validation_shared_examples.rb
This is an evolving piece of work so we might have to tweak some things later on.
But for now (bear in mind most of this PR are refactored tests), this will ensure proper handling of dependent attributes on the `client details` page, and the `NINO` page.
This covers a few scenarios that most likely will never happen in real life but it is easy to trigger these when doing test applications. In particular, the one where DWP was successful, and changing the NINO keeps saying it is successful (as it will take previous value and not re-trigger the check).
https://dsdmoj.atlassian.net/browse/CRIMAP-375
```
New applications (not yet submitted):
- Client is under 18 based on DoB, thus, NINO was not asked
- Provider goes back to client details and submit without any changes
- Still under 18, still …
```
> CRIMAP-375 Cover additional passporting edge cases

- Gemfile
- Gemfile.lock
- app/serializers/submission_serializer/sections/application_details.rb
- app/value_objects/application_type.rb
- spec/serializers/submission_serializer/sections/application_details_spec.rb
- spec/value_objects/application_type_spec.rb
This attribute is always "initial" for MVP, but we prepare the path for post-MVP where other types will be needed.
Propagates the type in the JSON to the datastore.
New schemas gem validates/uses this new attribute too.
https://dsdmoj.atlassian.net/browse/CRIMAP-383
https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/26
Submissions should work as expected, and propagate the new attribute to the datastore. Existing applications can be read back with no issues.
> CRIMAP-383 Propagate `application_type` to datastore

- Gemfile
- Gemfile.lock
- spec/requests/dashboard_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
This is part of an overall work to rationalise and remove any unneeded, unused, or superfluous fixtures, as these grow a bit out of hand for a while for no good reason.
On Apply I've only detected one superfluous fixture, `application_returned_split_case.json`
It has been replaced by the overarching `application_returned`, with reason variant `split_case`. There is nothing different or complicated that requires having this as a full separate fixture at all.
https://dsdmoj.atlassian.net/browse/CRIMAP-385
> CRIMAP-385 Remove dependency on unneeded fixture

- Gemfile
- Gemfile.lock
- app/services/adapters/json_application.rb
- app/services/adapters/structs/pruned_application.rb
- spec/services/adapters/structs/pruned_application_spec.rb
- spec/support/factory_helpers.rb
This is part of the overall work to simplify the JSON response when listing applications, by removing all unneeded attributes.
As this new representation lacks many of the required attributes, and could even change structure in the future, a new struct has been created to handle it. Otherwise trying to use the existing struct with the pruned JSON raises multiple errors about required attributes (case_details, provider_details, etc.)
Other than that there is little more to it, as Apply will still find in this pruned struct everything it needs to render the dashboard lists and pagination.
https://dsdmoj.atlassian.net/browse/CRIMAP-387
To be deployed at the same time that the datastore changes in PR https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/104
It requires …
> CRIMAP-387 Support for pruned application struct

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Rule ID 941100 was triggering randomly on session cookies:
```"Matched Data: XSS data found within REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session: TJwwf4nGhgKbr9DgkOrRS5..."```
Skip this rule on the session cookie. We will need to do this in all services, each one has a different cookie name.
Also, remove unnecessary annotation `enable-owasp-core-rules`, because cloud-platform modsec ingress has these enabled by default and it should not be used together with `modsecurity-snippet` as per documentation:
```Note: If you use both enable-owasp-core-rules and modsecurity-snippet annotations together, only the modsecurity-snippet will take effect.```
More info on slack:
https://mojdt.slack.com/archives/C03JS4V9TPU/p1685710140212729
> Fix random modsec false positives in session cookie

- config/initializers/filter_parameter_logging.rb
This is the specific selected address (as per Ordnance Survey API) and can be used to retrieve back a full address.
Removed a few unneeded params.
> Add `lookup_id` to filter_parameters config

- Gemfile
- Gemfile.lock
- spec/services/adapters/structs/case_details_spec.rb
Note by merging this PR, many existing submitted applications in the datastore will stop loading on Apply as their JSON representation will not "fit" into these more strict structs.
Do not merge until we are good to go (there is another PR on the datastore for this too).
https://dsdmoj.atlassian.net/browse/CRIMAP-388
> CRIMAP-388 Bump schemas gem (stricter structs)

- app/views/steps/address/lookup/edit.html.erb
- config/locales/en/helpers.yml
The postcode lookup step didn't have a specific label for the input, instead it used the h1 of the page as label, but it wasn't entirely clear. Also the hint text didn't make a lot of sense because of this.
As per content/service designers, we are adding a specific label, with text `Postcode`.
https://dsdmoj.atlassian.net/browse/CRIMAP-407
Go to the postcode lookup page and see the label.
> CRIMAP-407 Add postcode label

- app/lib/feature_flags.rb
- spec/requests/home_spec.rb
Although very rare to occur, as we run the tests randomised, there was a scenario where the `FeatureFlags` which is a Singleton was being initialised with an incorrect stubbed `env_name`, and a few subsequent tests making use of some feature flags, were unpredictable.
If this keep happening will investigate further or another solution.
Without this fix, a seed that has failures was:
`rspec spec --seed 26039`
With the changes in this PR, using the same seed, should have green tests.
> Tentatively fix flaky tests

- app/lib/refinements/localize_with_tz.rb
- app/presenters/base_presenter.rb
- app/services/date_stamper.rb
- config/application.rb
- config/initializers/refinements.rb
- spec/presenters/summary/sections/next_court_hearing_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/date_stamper_spec.rb
The application by default is set to UTC time zone, same as Datastore and Review. In the database(s) we store dates in UTC across the board.
However in some places, the presented date/time should be in the corresponding user's timezone which by default for our service (and unlikely to change or be configurable) will be `London`.
In order to avoid repetition, a new view helper has been exposed, analogous to `#l()` named `#tz_l()` to localize dates in the time zone of the user. This is used in the views.
Also, although originally unrelated to this, ensure the date stamp and the submission date have both the same precision (`Time.current`)
https://dsdmoj.atlassian.net/browse/CRIMAP-409
> Handle user time zone (London) when presenting dates

- config/kubernetes/production/prometheus.yml
Removed one that is not useful at all, if there is any problem with replicas or pods, other alerts will trigger instead.
Removed Medium vulns from Trivy alert, although all the noise so far has been from High vulns, not Medium. But given most vulns are not on our hands (docker/OS/etc.) no point in having Medium alerts right now.
Tweaked the 4xx and 5xx alerts so they are a bit less noisy. Instead of triggering just with 1 error, now it needs to have more than 5 errors in a 5 mins timespan. We can observe how this goes or tweak it until we are happy.
> Relax some prometheus alerts

- app/assets/stylesheets/local/custom.scss
- app/views/about/privacy.en.html.erb
- app/views/layouts/_footer_links.html.erb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/settings.yml
Updated privacy policy as per https://docs.google.com/document/d/1fVLqKKDMeZ2gIWfR99ULjPWh6TFT-xNdm5f22rlFPUA/edit
Decision was made not to duplicate the LAA-wide privacy policy, but to link out to the help and info page where the pdf is hosted. 
Updated link text in the declaration to "privacy notice" which is the title on the help and info page to ensure that it is clear which pdf we are directing the user to. 
https://dsdmoj.atlassian.net/browse/CRIMAP-398
> Crimap 398 update privacy content

- app/views/about/privacy.en.html.erb
- app/views/layouts/_footer_links.html.erb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/settings.yml
Agreed with Fleur that adding fragment ids will assist with users finding the document we are getting them to navigate to. 
If the document id is updated, fragment will not cause a 404 but just result in the current behaviour.
> Update portal doc links with fragment ids

- app/services/passporting/ioj_passporter.rb
- app/value_objects/case_type.rb
- spec/services/passporting/ioj_passporter_spec.rb
- spec/value_objects/case_type_spec.rb
The appeal is a separate issue to the original proceedings trying the offence(s), and the defendant must demonstrate they have grounds for appeal by completing the IoJ reasons.
As a result, the offences on the appeal application cannot be IoJ passported either by offence or age.
https://dsdmoj.atlassian.net/browse/CRIMAP-405
Where previously an application would have been IoJ passported, now selecting an appeal case type, will ignore the passporting (either under 18 or on offence). No other changes made.
> CRIMAP-405 Appeal case types do not trigger IoJ passport

- app/presenters/summary/sections/contact_details.rb
- spec/presenters/summary/sections/contact_details_spec.rb
Small QoL refinement.
We can direct the provider to a more precise page when they click the `change` link on an address in the Review application page.
- If the address has not been entered, on the Review page it shows as "None", and the change link will take the provider to the postcode lookup so they can start the address journey.
- If an address haas been selected via postcode lookup, the change link will take them back to the dropdown with the results, so they can either pick a different one, or go back to change the postcode and run again the lookup.
- If an address has been manually entered we take them directly to the details page where they can tweak any part of the address (line one, line two, city, country...)
> More precise `change` address link in Review page

- app/lib/prometheus_metrics/configuration.rb
- config/kubernetes/staging/deployment.tpl
All working fine! Tiny tweaks:
There is no need for a custom `hostname` label as we get "for free" a "pod" label which is exactly what we need to identify each of the pod's metrics.
Also, exposed the port in the deployment. I think technically is not needed if we have a service mapping but just in case.
> Additional prometheus exporter tweaks

- app/lib/prometheus_metrics/configuration.rb
- config/kubernetes/production/config_map.yml
- config/kubernetes/production/deployment.tpl
- config/kubernetes/production/service.yml
Also, set the default prefix for prometheus metrics to `ruby_`. This was previously set in the background process which we don't run anymore.
https://dsdmoj.atlassian.net/browse/CRIMAP-414
> Enable prometheus exporter in production

- app/lib/prometheus_metrics/applications_count_collector.rb
- spec/lib/prometheus_metrics/applications_count_collector_spec.rb
This is more in line with how prometheus likes this kind of metrics and also makes it easier to visualise in graphs.
This is now the result:
```
ruby_crime_apply_applications_count{status="started"} 8
ruby_crime_apply_applications_count{status="in_progress"} 6
ruby_crime_apply_applications_count{status="date_stamped"} 5
ruby_crime_apply_applications_count{status="stale"} 3
```
> Refactor application counters to use tags

- config/kubernetes/staging/grafana-applications.yml
- config/kubernetes/staging/prometheus.yml
A basic grafana dashboard making use of the recently added custom prometheus metrics.
There is plenty of scope for improvement, this is just an example.
Moved the prometheus rules to the staging namespace so it is easier to iterate them without having to deploy all the way to production (although they can be applied manually anyways).
Added a new prometheus rule to monitor the exporters.
https://dsdmoj.atlassian.net/browse/CRIMAP-379
~Cloud Platforms are having issues with new grafana boards or updates to existing ones. It takes a long time to show the changes. Once that is resolved I will share the link to the dashboard.~
URL here (needs to sign in with github)
https://grafana.live.cloud-platform.service.justice.gov.uk/d/crime-applications-dashboard/laa-crime-apply-applications-dashboard? …
> CRIMAP-379 Add applications grafana dashboard

- .env.development
- app/services/dwp/benefit_check_service.rb
- config/application.rb
- spec/fixtures/files/benefit_checker_responses/successful.xml
- spec/services/dwp/benefit_check_service_spec.rb
Michael has confirmed the `dateOfAward` parameter is no longer needed, in any environment, so it is safe to be removed.
Make sure the `clientReference` can be traced back to one of our applications, so changed to the application UUID (because the applicant record UUID is not persisted anywhere post-submission).
Few other non-functional tweaks.
https://dsdmoj.atlassian.net/browse/CRIMAP-275
Everything should keep working as before, no functional changes.
> CRIMAP-275 Remove unused DWP check param

- Gemfile
- Gemfile.lock
- app/models/offence.rb
- app/serializers/submission_serializer/definitions/offence.rb
- app/services/passporting/ioj_passporter.rb
- config/data/offences.csv
- config/settings.yml
- spec/models/offence_spec.rb
- spec/serializers/submission_serializer/definitions/offence_spec.rb
- spec/services/passporting/ioj_passporter_spec.rb
No functional changes other than this renaming.
Enabled the passport-related feature flags on production as we'll soon start doing some final round of testing before going live.
https://dsdmoj.atlassian.net/browse/CRIMAP-415
No functional changes, everything should continue working as before. Just the attribute sent to the datastore has changed.
A separate PR to the datastore will follow.
> CRIMAP-415 Rename `passportable` to `slipstreamable`

- .erb-lint.yml
- app/javascript/application.js
- app/javascript/local/print-action.js
- app/views/completed_applications/show.html.erb
- app/views/layouts/_analytics.html.erb
- app/views/layouts/govuk_template.html.erb
- config/initializers/content_security_policy.rb
Configure and enforce Configure Content Security Policy.
It will block all fetch directives by default. Other directives added as needed (for example GA and Portal).
Had to change the way the print worked as no inline JS is now allowed.
I didn't find any issues or violations on my testing but we should keep an eye.
https://dsdmoj.atlassian.net/browse/CRIMAP-421
Just use the service as usual, everything should keep working as before and no violations are reported in the browser console.
> CRIMAP-421 Configure Content Security Policy - CSP

- .trivyignore
These keep coming back in prometheus alerts and we are unable to fix them as it seems to be on cloud platforms side.
As a test I installed and run Trivy locally (before adding this ignore file that is!) and it didn't detect any vulns so it must have something to do with k8s.
NOTE: this may not work, unsure until we deploy.
> Ignore trivy vulns outside our control

- app/views/about/privacy.en.html.erb
- app/views/cookies/show.en.html.erb
- app/views/errors/not_enrolled.en.html.erb
- app/views/home/index.en.html.erb
- app/views/shared/_eforms_redirect.en.html.erb
- config/kubernetes/staging/grafana-applications.yml
- config/locales/en/dashboard.yml
- config/locales/en/helpers.yml
- public/404.html
- public/422.html
- public/500.html
- spec/requests/dashboard_spec.rb
CRIMAP-425 update start page and eforms redirect page to include that u18 clients don't need a NINO
CRIMAP-424 update not enrolled message to remove suggestion that provider can join beta upon request
https://dsdmoj.atlassian.net/browse/CRIMAP-425
https://dsdmoj.atlassian.net/browse/CRIMAP-424
> CRIMAP-425 update u18 no nino and CRIMAP-424 update not enrolled message 

- config/data/offence_synonyms.yml
- config/data/offences.csv
I've let Chris know to also update the offences spreadsheet.
Added a couple additional common abbreviations/synonyms to speed up entering offences.
https://dsdmoj.atlassian.net/browse/CRIMAP-426
ASB, will come up with `Breach of an anti-social behaviour order`
CBO, will come up with `Breach a criminal behaviour order`
> Fix extraneous spacing in some offence names

- app/javascript/application.js
- app/javascript/local/cbc.js
Some browsers come with built in extra privacy measures, and also some plugins can be used to block some "annoyances" like cookie banners.
Main issue was, the blocking was stopping other genuine modules from being properly loaded by the browser, making some functionality that relies on JS fail, like the offences list, or the print button.
Seems to be "fixed" by obfuscating the name of the JS module so it doesn't contain keywords that are likely to be blocked, like `cookie`, `banner` or `consent`.
> Fix cookie banner JS module blocked by browsers

- app/controllers/steps/case/appeal_details_controller.rb
- app/forms/steps/case/appeal_details_form.rb
- app/forms/steps/case/case_type_form.rb
- app/models/case.rb
- app/presenters/summary/sections/case_details.rb
- app/serializers/submission_serializer/sections/case_details.rb
- app/services/adapters/structs/case_details.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/appeal_details/edit.en.html.erb
- app/views/steps/case/case_type/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- config/routes.rb
- db/migrate/20230704081647_refactor_appeal_case_fields.rb
- db/schema.rb
- spec/controllers/steps/case/appeal_details_controller_spec.rb
- spec/forms/steps/case/appeal_details_form_spec.rb
- spec/forms/steps/case/case_type_form_spec.rb
- spec/presenters/summary/sections/case_details_spec.rb
- spec/serializers/submission_serializer/sections/case_details_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
I'm worried the PRs might become too big so I'll try to split them up into (almost) functional smaller PRs.
In order to keep backward compatibility as much as possible with existing applications in datastore, I've done a few temporary workarounds that will be removed once all the work is finalised and the schemas/fixtures/datastore are also updated.
This first part cleanup the existing case type step, adds the new appeal details step, adapt the decision tree with the new logic, and also updates the serialisers and the summary presenters.
https://dsdmoj.atlassian.net/browse/CRIMAP-427
Few things still to do, and separately there will be changes to schema/fixtures. Will be done next.
Go the case type page, select any appeal radio option, you will be directed to the appeal details page, …
> CRIMAP-427 First part of appeal details refactor

- app/javascript/local/suggestions.js
The accessibility audit flagged an issue on the ‘What has your client been charged with’ page where the offence input field was not accessible on iOS using swipe gestures when voice over is active (see before changes video below).
This was fixed by setting the aria attributes on the offence input element that controls the listbox rather than the overall form container
[CRIMAP-371](https://dsdmoj.atlassian.net/browse/CRIMAP-371)
Bare with my terrible swipe navigation skills! 
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/assets/51047911/d33ceaa2-c477-4693-a961-d2d3552e3ab9
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/assets/51047911/8dcbf39a-2381-441b-8c09-ccb0d51b0057
[CRIMAP-371]: …
> [a11y] Make offence input field accessible on ios

- app/forms/steps/case/appeal_details_form.rb
- app/forms/steps/case/urn_form.rb
- app/forms/steps/client/contact_details_form.rb
- app/forms/steps/client/has_nino_form.rb
- app/forms/steps/submission/declaration_form.rb
- config/locales/en/errors.yml
- spec/forms/steps/case/appeal_details_form_spec.rb
Simple validation to avoid fat fingers or other issues.
The attribute is optional so we still allow blanks. But if the attribute is filled, then we validate is a numeric 6-9 digits.
Ensure all existing regex in other places use `\z` (lowercase) instead of `\Z` (uppercase) as:
> \Z Matches the end of the string unless the string ends with a "\n", in which case it matches just before the "\n".
Which means by using \Z someone could sneak in a newline character and still pass validation.
https://dsdmoj.atlassian.net/browse/CRIMAP-427
Absense is allowed. If something is entered, only numeric values 6-9 digits length will pass validation.
> CRIMAP-427 Validate format of previous MAAT ID

- app/controllers/concerns/error_handling.rb
- app/lib/logger_error_subscriber.rb
- app/services/datastore/application_counters.rb
- app/services/datastore/application_submission.rb
- app/services/datastore/get_application.rb
- app/services/datastore/list_applications.rb
- config/initializers/sentry.rb
- spec/controllers/application_controller_spec.rb
- spec/services/datastore/application_counters_spec.rb
- spec/services/datastore/application_submission_spec.rb
- spec/services/datastore/get_application_spec.rb
- spec/services/datastore/list_applications_spec.rb
This is a first part of at least a couple PRs intended to remove some technical debt by refactoring exception capture and error reporting using the modern Rails error reporting API introduced in Rails 7+
https://edgeguides.rubyonrails.org/error_reporting.html
Functionally it should be the same as before, but some boilerplate code is simplified.
Only thing I noticed is the Rails.error.handle, Rails.error.report etc methods do not log the exception, which makes sense, but without it, the exception is quietly hidden and particularly in localhost it can be misleading.
I've made a basic error subscriber just to perform the `Rails.logger.error(e)` so it behaves like before, adding one line of backtrace for additional context.
https://dsdmoj.atlassian.net/browse/CRIMAP-429
In localhost is easy …
> CRIMAP-429 Refactor error reporting using Rails new API

- app/controllers/developer_tools/crime_applications_controller.rb
- app/presenters/summary/sections/case_details.rb
- app/presenters/tasks/case_details.rb
- app/services/decisions/case_decision_tree.rb
- app/services/decisions/client_decision_tree.rb
- config/routes.rb
- spec/presenters/summary/sections/case_details_spec.rb
- spec/presenters/tasks/case_details_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Move URN step after the date stamp (i.e. after case type and/or appeal details).
Update task list so the case details task starts with the case type and not with the URN as it was until now.
For consistency, moved also the place where the URN shows in the review application page (and caused a bit of a mess in the tests, sorry).
Everything (except the order, that is) should continue working as before, nothing really has changed except the order of the steps.
https://dsdmoj.atlassian.net/browse/CRIMAP-430
Start a new application and after the contact details, instead of taking you to the URN step, it will take you to the case type step. The date stamp logic remains, and after the date stamp (or for non date-stampable cases, after the case type) you will be taken to the URN page.
Task list …
> CRIMAP-430 Swap order of the URN step

- config/kubernetes/staging/grafana-applications.yml
- config/kubernetes/staging/grafana-golden-signals.yml
- config/kubernetes/staging/grafana-rails-metrics.yml
This can be iterated over time.
Cloud platforms are having issues with new dashboards, or updates to existing ones, showing up. This is because each dashboard from every team needs to have a unique UID, and some teams pushes dashboards with duplicate UIDs making grafana to stop updating/creating any dashboard completely.
~Once that is sorted out, these dashboards should show and I'll add links.~
~Marking this as a draft until we can actually "see them" LOL.~
Links to dashboards, we can iterate and tweak them over time, this is the baseline:
- In progress applications
https://grafana.live.cloud-platform.service.justice.gov.uk/d/crime-applications-dashboard/laa-crime-apply-applications-dashboard?orgId=1&refresh=1m
- Golden signals (no ingress metrics for datastore as it lacks ingress) …
> Add golden signals and rails metrics grafana dashboards

- app/controllers/providers/omniauth_callbacks_controller.rb
- config/locales/en/devise.yml
- spec/system/sign_in_spec.rb
Although it should be very rare and edge case, there could be sometimes Portal authentication errors.
We were showing a rather obscure error message in a flash alert. This has now been replaced with the generic "unhandled" error page, and also we send the exception to Sentry so we are alerted.
More context on this slack thread:
https://mojdt.slack.com/archives/C03JS4V9TPU/p1688989509642419
It's rather difficult, you need to disable omniauth test mode, and configure Portal locally, then disable something that Portal except, for example `authn_requests_signed` in the file `LaaPortal::SamlSetup`
> Replace cryptic Omniauth error flash alert

- Gemfile
- Gemfile.lock
It is required to use the latest schemas gem version as the `ReturnDetails` struct in versions `< 0.7.0` states `returned_at` attribute as mandatory presence, which the datastore will no longer be returning.
Note: Review will need to bump the version too due to the same reason.
https://dsdmoj.atlassian.net/browse/CRIMAP-433
No functional changes, everything keep working as before.
> CRIMAP-433 Bump schemas gem (return_details refactor)

- Gemfile
- Gemfile.lock
- app/models/case.rb
- app/models/court.rb
- config/data/courts.csv
- spec/models/case_spec.rb
- spec/models/court_spec.rb
Based on some recent conversations, and the fact the repo for `hmcts_common_platform` is archived and apparently unmaintained and outdated, one immediate easy thing we can do is bring over the (simplified) CSV file and use the same approach we used for offences.
Functionally everything should continue working as before, and we have more flexibility to update or tweak the CSV file to add/remove or rename courts.
In the future we can plan to move to an API based approach using FaCT.
https://dsdmoj.atlassian.net/browse/CRIMAP-435
Slack thread:
https://mojdt.slack.com/archives/C02AFLHGK9S/p1689069962130059
Go to the hearing court page, and play around.
> CRIMAP-435 Remove `hmcts_common_platform` gem dependency

- app/helpers/form_builder_helper.rb
- app/javascript/application.js
- app/javascript/local/multi-action-form.js
- app/views/steps/address/lookup/edit.html.erb
- app/views/steps/case/charges/edit.html.erb
- app/views/steps/case/codefendants/edit.html.erb
- spec/helpers/form_builder_helper_spec.rb
Default browser behaviour when user focus in a form input, like a text field, and they press enter, is to submit the form.
This usually works just fine, as there is only one submit per form or the main submit comes before the others.
However, in some steps, like the postcode lookup, there is more than 1 submit action and the browser picks the first one in order of appearance in the DOM, which might not be the one that actually performs the “save and continue” (or the postcode search in this case).
This works around this behaviour in a progressive enhancement way with a bit of JS, by cloning the main submit action and positioning it (hidden, even for screen-readers) right at the top of the form so `enter key` picks this one always.
Only forms tagged with "data-multi-action-form=true" will …
> CRIMAP-439 Ensure enter key triggers main submit action

- Gemfile
- Gemfile.lock
- spec/services/adapters/structs/applicant_spec.rb
Just tweaked a test as `other_names` have been added to the fixture, it was missing.
No other changes were required.
https://dsdmoj.atlassian.net/browse/CRIMAP-442
> Bump schemas gem to v1.0.0

- app/controllers/dashboard_controller.rb
- app/controllers/steps/base_step_controller.rb
It avoids possibly exposing personal information when using the browser back button after the current session has been terminated.
This is similar to the [approach taken on Review](https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/361) however instead of adding it to all controller actions, this is only set on those exposing possible personal information.
There are many other pages on Apply (all footer pages, and some others) that are not sensitive.
Note pragma header not set as is deprecated and no longer recommended. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma
I'm not 100% sure this works well with Safari. Tested well in all other browsers including Firefox, Chrome, Opera and Edge.
Sign in, go to the dashboard, then go to submitted applications …
> Set `Cache-Control` response header to no-store

- app/controllers/concerns/error_handling.rb
- app/controllers/errors_controller.rb
- app/controllers/providers/omniauth_callbacks_controller.rb
- app/views/errors/invalid_token.en.html.erb
- config/routes.rb
- spec/controllers/application_controller_spec.rb
- spec/requests/errors_spec.rb
- spec/system/sign_in_spec.rb
Omniauth authentication could fail due to an invalid authenticity token. For instance, by re-submitting the same form twice. In this scenario we were redirecting to the unhandled error page, which is not correct and confusing to the user.
Now we just let `InvalidAuthenticityToken` exceptions bubble up, so it can be rescued and handled accordingly within the generic error handling block.
Also previously we were bunching together the invalid session and the authenticity token errors, but they are not really the same and to a user's point of view, showing the invalid session error when the error was produced by an invalid authenticity token (forgery protection) might be confusing as we tell them:
"For your security, we signed you out
This is because you were inactive for 48 hours."
Now each …
> Discern between invalid session and invalid token errors

- app/views/layouts/_developer_tools.html.erb
Change to go along with [datastore PR](https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/137) so on staging (where developer tools is active) the `return` functionality will not show as it can leave inconsistent or corrupted data in the datastore.
Leave it enabled for quick tests on local environments.
On staging the button will not show anymore 😿
> Only show dev tools `return` button in development

- config/initializers/filter_parameter_logging.rb
- config/initializers/lograge.rb
In the `filter_parameter_logging` we had `details` which is a too broad term that was hindering some logs unnecessarily.
For instance, whole steps like `contact_details`, `address_details`, `appeal_details` or `hearing_details` where being filtered, however there are attributes we don't need to filter in those.
Also city and country are not PII and can be left unfiltered.
Added the signed in provider selected `office_code` to each log trace for better debug purposes.
https://dsdmoj.atlassian.net/browse/CRIMAP-460
```
Processing by Steps::Address::DetailsController#update as HTML
Parameters: {"authenticity_token"=>"[FILTERED]", "steps_address_details_form"=>"[FILTERED]", "id"=>"a22f89c2-49eb-40e7-9dd3-395a35177e7c", "address_id"=>"5b21cfa2-1103-4e3d-adde-9f7a74fc27ff"}
```
```
Processing …
```
> CRIMAP-460 Minor tweaks to logging

- config/initializers/lograge.rb
On the back of previous PR #445.
This is the second time we've been bitten by this. Maybe some smoke test will be required, will think of something.
For now, fixing this by calling the warden exposed method instead of the helper controller method.
And added a cautionary comment.
> Fix method missing in healthcheck

- config/kubernetes/staging/grafana-rails-metrics.yml
Updated the Request duration and Request count widgets, to `avg` or `sum` requests grouped by controller and action.
Previously it would show n-times the same controller/action, as many times as pods (4 in production, 2 in staging).
I've applied it already so it so we can see how it looks.
> Tweak rails Grafana dashboard

- Gemfile
- Gemfile.lock
- config/initializers/datastore_client.rb
- config/initializers/lograge.rb
- config/kubernetes/staging/grafana-rails-metrics.yml
- config/routes.rb
- spec/requests/datastore_healthcheck_spec.rb
Use the datastore health rails engine on Apply to act as a proxy for the health and ping endpoints given the datastore is an internal service only accessible from the cluster.
Moved the `require 'datastore_api'` to the Gemfile declaration as otherwise it wasn't properly loading the engine, I think it may be because the name of the gem is different to the name of the lib require.
Note: the gem ref to be changed with the tag 1.1.0 when new tag is released.
https://dsdmoj.atlassian.net/browse/CRIMAP-462
Spin up both, datastore and Apply, and from Apply, observe how `/datastore/ping` or `/datastore/health` reach the datastore. If datastore is down, those endpoints will return error.
Also:
```
$ rails routes | grep datastore
datastore_api_health_engine   /datastore …
```
> CRIMAP-462 Datastore health engine routes

- config/data/offence_synonyms.yml
This will return 10 offences all related to "possess with intent to supply ..."
https://dsdmoj.atlassian.net/browse/CRIMAP-505
Note there is no need to finalise the acronym, just by typing a few letters of it will find results, but I added the full acronym as it is clearer this way.
> CRIMAP-505 Add `pwits` to offence synonyms list

- app/lib/prometheus_metrics/applications_count_collector.rb
- app/lib/prometheus_metrics/collectors.rb
- app/lib/prometheus_metrics/configuration.rb
- app/lib/prometheus_metrics/providers_count_collector.rb
- config/kubernetes/staging/grafana-applications.yml
- spec/lib/prometheus_metrics/applications_count_collector_spec.rb
- spec/lib/prometheus_metrics/providers_count_collector_spec.rb
Similar to the existing applications collector, this new collector will expose a few basic metrics about providers as they are being enrolled and use our service.
Added a new panel and widgets to the existing Grafana dashboard so all is in one place.
Note until the collector is deployed, the dashboard will show no data.
https://dsdmoj.atlassian.net/browse/CRIMAP-503
Metrics can be observed in the local /metrics endpoint when enabling prometheus exporter via ENV variables.
> CRIMAP-506 Providers prometheus custom collector

- Gemfile
- Gemfile.lock
- spec/support/webmock.rb
And cleanup Webmock initialiser as now there is nothing needed in it, the default is to `allow_localhost` anyways.
Note: we need to observe if this runs properly on CI. It `works on my machine ™`
> Remove unneeded webdrivers gem

- app/lib/prometheus_metrics/configuration.rb
- docker-compose.yml
With the objective of being able to run all 3 services (apply, review and datastore) at the same time as docker containers, some tweaks are needed.
Prometheus exporter port was hardcoded, it needs to be different in each container otherwise it will clash. Also by default now is disabled as most of the time we will never need it locally, but can be enabled for quick tests.
Added the datastore dummy credentials and endpoint (it works wether datastore is running also in a container, or on the host machine, assuming it's running in port 3003).
`docker-compose up` will no longer run prometheus exporter. If datastore is up and running in port 3003, Apply container will be able to talk to datastore too.
> Tweak docker-compose

- app/assets/config/manifest.js
- app/assets/stylesheets/local/moj.scss
- app/controllers/documents_controller.rb
- app/javascript/application.js
- app/views/steps/evidence/upload/edit.en.html.erb
- config/importmap.rb
- config/routes.rb
- package.json
- yarn.lock
Add all the stuff needed to render an MOJ multi-upload component (dropzone behind the scenes).
Note in order to do this we now have to add to the application the MOJ javascript plus dropzone dependencies.
I'm raising this PR just to have it all set, but is obviously not functional, and I doubt it can be functional out of the box without modifying MOJ javascript because for once, the JS is not propagating the authenticity token and I don't see a way to configure this, meaning only way to propagate the token is to modify the javascript.
My opinion is we shouldn't be using MOJ component, which couples us to their javascript (and requires jQuery nonetheless) and instead code our own JS handling and apply our own styling (which can be the same as the MOJ styling if we wish). …
> CRIMAP-529 Add MOJ javascript and dropzone

- Dockerfile
The `postgresql-dev` package used in the Dockerfile was outdated, now that we are running postgres 15.x (locally, CI and also cloud platform through RDS).
This ensure alpine build the image using latest versions of the postgres libraries.
More info in slack thread
https://mojdt.slack.com/archives/C056U956ESH/p1692175607705879
> Resolve postgres related Trivy vulns

- app/forms/steps/case/urn_form.rb
- spec/forms/steps/case/urn_form_spec.rb
URN field was raising validation errors on valid URNs. The rules we have been told are not correct, so we need to reduce restrictions given we now don't know what the specific format is.
Following suit of VCD, which has validations that URN is alphanumeric and fewer than 20 chars. This PR also sets a minimum of 6 chars, but otherwise the same as VCD
> Reduce restrictions on URN validation

- .github/workflows/test-build-deploy.yml
Transition to shortlived secrets for ECR workflow.
See[ here for technical details](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-github-actions)
Relevant cloud platform [PR here](https://github.com/ministryofjustice/cloud-platform-environments/pull/15975)
[CRIMAP-577](https://dsdmoj.atlassian.net/browse/CRIMAP-577)
[CRIMAP-577]: https://dsdmoj.atlassian.net/browse/CRIMAP-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use shortlived creds for ECR uploads

- app/lib/laa_portal/saml_strategy.rb
- app/models/provider.rb
- app/services/providers/active_office_checker.rb
- config/application.rb
- config/inactive_offices.yml
- spec/services/providers/active_office_checker_spec.rb
An implementation using a flat file as an interim solution to filter out inactive office codes from the portal.
Idea her is to test on staging and then I will raise another PR with the inactive prod codes and deploy this again.
**The flow of this is:**
1. sign in is user attempts sign-in from portal 
2. callback in `OmniauthCallbacksController` checks they are allowlisted/enrolled with the `Providers::GateKeeper`
3. the `saml` method is called in the controller which in turn calls `Provider.from_omniauth` method with the `auth_hash`
4. `from_omniauth` finds or initialises a new provider, or updates them if they are already present
5. In the update statement, the `active_office_codes` method calls the new `ActiveOfficeChecker` service which filters our inactive offices based on the …
> Add flat file for inactive offices

- app/presenters/tasks/case_details.rb
- spec/presenters/tasks/case_details_spec.rb
Update can_start? criteria for case_details  to require all client_detail steps to be completed first
Fixes a bug whereby a user could exit the journey after completing the DWP check then start Case details with no later prompt to complete client details.
https://dsdmoj.atlassian.net/browse/CRIMAP-584
Plan to write a ticket to decide any plan to allow user to have multiple sections in progress at the same time
Current = 
1. Start new application, complete up to DWP check
2. Click save and continue without filling in any address details
3. Dashboard shows Case Details available to start
Now = 
1. Start new application, complete up to DWP check
2. Click save and continue without filling in any address details
3. Dashboard shows Case Details NOT available to start
> Update can_start? criteria for case_details 

- app/assets/stylesheets/local/custom.scss
- app/forms/steps/submission/declaration_form.rb
- app/lib/logger_error_subscriber.rb
- app/models/crime_application.rb
- app/presenters/fulfilment_errors_presenter.rb
- app/services/decisions/case_decision_tree.rb
- app/validators/application_fulfilment_validator.rb
- app/views/steps/submission/declaration/_fulfilment_errors.html.erb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/locales/en/errors.yml
- config/locales/en/steps.yml
- spec/forms/steps/submission/declaration_form_spec.rb
- spec/presenters/fulfilment_errors_presenter_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/validators/application_fulfilment_validator_spec.rb
Due to the loosely coupled nature of the step-by-step architecture where, as much as possible, each step is isolated from others and perform their own validations, and branching out can produce many different paths for a user, there may be rare situations (or by malice) where some important details of the application are not properly calculated.
Majority of these problems are caught by the JSON schema validation at point of submission, however there is not a proper user interface to present these errors.
This PR introduces the concept of "fulfilment validation" that happens at point of submission (technically right after declaration is signed) and raise any issues that hopefully can be recovered from by re-running some of the steps.
The validator allows to introduce further validations in …
> CRIMAP-636 Implement end-of-journey fulfilment validations

- app/controllers/documents_controller.rb
- app/controllers/steps/evidence/upload_controller.rb
- app/controllers/steps/evidence_step_controller.rb
- app/forms/steps/evidence/upload_form.rb
- app/models/crime_application.rb
- app/models/document.rb
- app/models/document_bundle.rb
- app/serializers/submission_serializer/sections/supporting_evidence.rb
- app/services/datastore/application_rehydration.rb
- app/services/datastore/documents/upload.rb
- app/views/steps/evidence/upload/edit.en.html.erb
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20230927100615_refactor_documents.rb
- db/schema.rb
- spec/controllers/steps/evidence/upload_controller_spec.rb
- spec/models/document_spec.rb
- spec/requests/evidence_upload_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/supporting_evidence_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
- spec/support/shared_contexts/with_an_existing_document.rb
Bit of a refactor before this becomes too entangled to remove the DocumentBundle intermediate table and abstraction as it seems is of no use and makes code a bit more convoluted and creates additional indirection.
To the best of my efforts everything should continue working as before, no changes to external URLs etc. have been made, and is all internal.
As part of this I've taken the opportunity to introduce in the Documents DB table 2 new attributes:
- `submitted_at` - can be populated on rehydration from a submitted application, and this can signalise which documents are already submitted and thus we shouldn't do a hard delete on S3 (just soft delete setting the `deleted_at` attribute)
- `annotations` - jsonb attribute that initially will be used for the virus scanner to annotate files …
> Refactor evidence data model removing bundle abstraction

- Brewfile
- Dockerfile
- Gemfile
- Gemfile.lock
- app/services/datastore/documents/upload.rb
- config/clamd/clamd.docker.conf
- config/clamd/clamd.local.conf
- config/clamd/clamd.production.conf
- config/clamd/clamd.staging.conf
- config/clamd/clamd.staging2.conf
- config/initializers/clamby.rb
- config/kubernetes/production/config_map.yml
- config/kubernetes/staging/config_map.yml
- config/kubernetes/staging/deployment-clamav.yml
- config/kubernetes/staging/prometheus.yml
- config/kubernetes/staging/service.yml
- docker-compose.yml
Just a PoC to validate assumption we can have ClamAV and signatures in a container while communicating with it through the TCP socket and the `clamdscan` CLI tool.
Using HMPPS docker image because it is already pre-configured and works out of the box but we can use any other. https://github.com/ministryofjustice/hmpps-utility-container-images/tree/main/hmpps-clamav
Using the most bare bones gem I could find for it, Clamby.
Only "tricky" thing is we have to provide individual config files dependent on environment. The port does not change but the address will, and couldn't find a nice way to do this via ENV variables, as `clamdscan` expects as input a config file.
Not done kubernetes production yet, until we validate this can work on staging (TCP connectivity mainly). …
> CRIMAP-596 ClamAV in a separate container PoC

- app/validators/file_upload_validator.rb
- config/kubernetes/staging/ingress.yml
- spec/models/document_spec.rb
- spec/requests/evidence_upload_spec.rb
This PR fixes a bug on staging where files larger than 1MB were not uploading and errors were not being presented to the user. It was discovered that this was due to a modsec file upload limit which was set to 1MB. 
Two changes have been made. Apply's file upload limit has been decreased from 20MB to 10MB to match eForms. And the modsec upload limit has been increased to 15MB. This is slightly above our file size limit to act as a buffer to account for the increased number of http envelopes and storage needed to transport a 10MB file.
This has been tested on staging and fixes the issue. Screen recording below. 
[CRIMAP-616](https://dsdmoj.atlassian.net/browse/CRIMAP-616)
An example of the original issue can be found in [this slack …
> CRIMAP-616 evidence upload bug patch

- app/controllers/steps/case/first_court_hearing_controller.rb
- app/forms/steps/case/first_court_hearing_form.rb
- app/value_objects/first_hearing_answer.rb
- app/views/steps/case/first_court_hearing/edit.en.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20230929140740_add_first_court_hearing_attributes.rb
- db/schema.rb
- spec/controllers/steps/case/first_court_hearing_controller_spec.rb
- spec/forms/steps/case/first_court_hearing_form_spec.rb
- spec/value_objects/first_hearing_answer_spec.rb
Not yet linked to the wider journey, this is the first part of a few PRs to implement the gathering of the first hearing court name, determined by the provider answer to a series of radio options (not implemented in this PR).
Trying to raise smaller PRs.
https://dsdmoj.atlassian.net/browse/CRIMAP-598
In order to view this page, as it is not part of the journey yet, start an application, go all the way to the court hearing step, and then enter URL manually: `applications/[uuid]/steps/case/first_court_hearing`
The submit will raise an error as there is no next page yet, but the page is functional.
> CRIMAP-599 Add first hearing court name page

- app/forms/steps/case/hearing_details_form.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/hearing_details/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- spec/forms/steps/case/hearing_details_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Follow-up to PR #493 to expose the radio options in the existing hearing details page, for the provider to select whether the first hearing court is the same as the next hearing court and logic to move to next page.
Includes validation as well as logic to delete previous answer if the provider changes the radio selection.
This is now part of the wider journey, but there is not Check Your Answer yet, that will be part of the next PR. Also missing submission to datastore/rehydration.
This is not behind a feature flag as I'm hoping to finish it soonish enough to be able to test and release as is a minor iteration on current form.
https://dsdmoj.atlassian.net/browse/CRIMAP-598
In any application go to the hearing details step, you should see the new radio options. It has validation. Selecting …
> CRIMAP-598 First court hearing selection

- config/clamd/clamd.staging2.conf
- config/kubernetes/staging/deployment-clamav.yml
This ensures stickiness of persistent volumes on rollouts and scaling.
Delete unused file. We can access the service with the short name as it is inside the same namespace, no need to use the fully qualified name.
This is a follow-up to previous PR #490.
> Refactor clamav deployment to use StatefulSet

- app/controllers/developer_tools/crime_applications_controller.rb
- app/forms/steps/client/details_form.rb
- app/forms/steps/client/has_nino_form.rb
- app/presenters/summary/sections/client_details.rb
- config/locales/en/summary.yml
- spec/forms/steps/client/details_form_spec.rb
- spec/forms/steps/client/has_nino_form_spec.rb
- spec/presenters/summary/sections/client_details_spec.rb
Added the benefit type to the check your answer page, in place of the previous "Passporting benefit" essentially merging both rows into one as confirmed by content designer.
If the question is not asked (under 18s) then the row will not show up.
Ensured `benefit_type` attribute is reset in a couple places if some key details are changed, as this value is linked to the DWP benefit checker.
Feature is still being feature flag, need to be removed if we want this in production at some point in the future once QA'ed.
https://dsdmoj.atlassian.net/browse/CRIMAP-644
Slack thread: https://mojdt.slack.com/archives/C03JS4V9TPU/p1696328705798759
For under 18s this row will not show.
For over 18s, run through the DWP check successfully and reach the CYA page, you should see whatever benefit was …
> CRIMAP-644 Show benefit type in CYA page

- app/services/decisions/client_decision_tree.rb
- config/routes.rb
- config/settings.yml
- spec/services/decisions/client_decision_tree_spec.rb
In the event we want to release this.
As part of this PR I've also re-wired the logic for retrying the DWP check when it fails due to connectivity or unhandled exceptions, so it does not go again to the benefit type page, and instead just re-try the DWP check as intended.
No changes other than removing the feat flag and fixing the retry DWP check. To test it locally, point the DWP checker to an invalid endpoint for instance, and run the DWP check. It would present the "retry" page, and when clicking the retry button it will retry the DWP instead of taking provider back to benefit type page.
> Remove `benefit_type` step feature flag

- app/controllers/steps/client/evidence_exit_controller.rb
- app/controllers/steps/client/has_benefit_evidence_controller.rb
- app/forms/steps/client/has_benefit_evidence_form.rb
- app/services/decisions/client_decision_tree.rb
- app/services/decisions/dwp_decision_tree.rb
- app/views/steps/client/evidence_exit/show.html.erb
- app/views/steps/client/has_benefit_evidence/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20230929171846_add_expected_evidence_field.rb
- db/migrate/20231005102741_add_has_benefit_evidence_attribute.rb
- db/schema.rb
- spec/controllers/steps/client/evidence_exit_controller_spec.rb
- spec/controllers/steps/client/has_benefit_evidence_controller_spec.rb
- spec/forms/steps/client/has_benefit_evidence_form_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
If benefit check fails, details are correct, user can register that they have evidence they intend to upload later
Adds virtual attribute, only needed locally in apply to resurface later at evidence upload step.
FYI I have also removed the feature flag for the benefit type page - So this would make it a live service change on deploy to prod.
https://dsdmoj.atlassian.net/browse/CRIMAP-576
As I am away this week, please feel free to commit any changes and merge as needed! I'm not precious!
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/assets/45827968/287006df-15c8-4241-8eed-2d2143a84460
Uploading Hasevidence.mov…
> CRIMAP-576 Add `has_benefit_evidence` page

- app/presenters/tasks/evidence_upload.rb
- app/services/decisions/case_decision_tree.rb
- app/services/evidence/requirements.rb
- app/validators/application_fulfilment_validator.rb
- app/views/steps/evidence/upload/edit.en.html.erb
- config/locales/en/steps.yml
- spec/presenters/tasks/evidence_upload_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/evidence/requirements_spec.rb
- spec/validators/application_fulfilment_validator_spec.rb
Create the task implementation, in the task list.
A basic wrapper to hold the logic on whether evidence is needed or not, and which types. This for now is up in the air so I've done it as basic as possible.
Link the evidence upload page to the journey, post IoJ, depending on the value of the previously asked question "has_benefit_evidence"
Modify the fulfilment validator because now it will be possible to have non means passported applications, but with evidence supplied.
No datastore/schema/rehydration yet.
Some unknowns yet to be confirmed/decided.
Note all this still remains behind feat flag, so nothing will show on production even if we release.
https://dsdmoj.atlassian.net/browse/CRIMAP-576
Run a DWP check that comes up without benefit, answer YES to the question about having …
> CRIMAP-576 Link evidence upload to wider journey

- config/kubernetes/production/ingress.yml
Update production ingress to be the same as staging.
Prevent sql injection false positives on the rails session cookie
[CRIMAP-651](https://dsdmoj.atlassian.net/browse/CRIMAP-651)
This has been on staging for a couple of days without any reported issues.
False positives on the session cookie have been causing 403 errors. Here we use tags rather than id to prevent the offending rules being applied to the rails session cookie.  After testing on staging, this change will need to be applied to the production ingress.
[CRIMAP-651]: https://dsdmoj.atlassian.net/browse/CRIMAP-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-651 Skip attack-sqli check on production

- app/controllers/steps/income/lost_job_in_custody_controller.rb
- app/controllers/steps/income_step_controller.rb
- app/forms/steps/income/lost_job_in_custody_form.rb
- app/services/decisions/income_decision_tree.rb
- app/views/steps/income/lost_job_in_custody/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20231023200153_add_lost_job_in_custody_to_people.rb
- db/schema.rb
- spec/controllers/steps/income/lost_job_in_custody_controller_spec.rb
- spec/forms/steps/income/lost_job_in_custody_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Add new step behind feature flag
Add to income decision tree, but not in flow yet
Add route with alias, controller, form and errors
https://dsdmoj.atlassian.net/browse/CRIMAP-683
run `rails db:migrate`
Start a new application 
Go to /steps/income/did_client_lose_job_being_in_custody
> Add did_client_lose_job_being_in_custody step

- config/data/offences.csv
- spec/models/offence_spec.rb
Added new offence Intentional Strangulation to list of existing offences
https://dsdmoj.atlassian.net/browse/CRIMAP-647
- User creates a new application in Apply
- User gets to 'What has your client been charged with?' page
- User clicks on offence box to add an offence and enters 'Intentional Strangulation'
- 'Intentional Strangulation' will appear in the list of offences
> CRIMAP-647 Added new offence Intentional Strangulation

- config/kubernetes/staging/prometheus.yml
Rename severity label in prometheus rule to prevent CP labelset collision.
> Replace prometheus 'severity' label to prevent collision

- app/controllers/steps/evidence/upload_controller.rb
Adds back in a line of code to delete documents from the datastore that was accidentally deleted in yesterday's[ logging PR](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/522/files#diff-c8e8604fbd874ead2602a128f806c0a5c5fe9e3d12cb5924dddd216169f3e4d3L23) (my bad!). Evidence upload functionality has been tested locally and the rest is functioning as expected.
> Patch: fix evidence delete functionality

- app/controllers/crime_applications_controller.rb
- app/controllers/steps/evidence/upload_controller.rb
- app/services/datastore/documents/delete.rb
- config/locales/en/helpers.yml
- spec/services/datastore/documents/delete_spec.rb
Fixes bug introduced in previous PR which meant it was not possible to delete a draft application which had supporting evidence. See sentry error [here](https://ministryofjustice.sentry.io/issues/4593077416/?alert_rule_id=14332616&alert_timestamp=1698849012915&alert_type=email&environment=staging&notification_uuid=310d9517-b09e-459b-a8de-284764ee884a&project=6587263&referrer=alert_email)
Also updates the delete service spec based on a previous PR where the `document.destroy` call was accidentally deleted, adds testing to ensure this is caught in the future: https://mojdt.slack.com/archives/C04TGATBWNL/p1698771504841059
Also adds a missing full stop to hint text (see screenshot below)
> Fix bug around deleting applications with documents

- app/views/home/index.en.html.erb
Updates start page copy to match means journey designs.
Is behind feature flag awaiting wider means journey release. Once this has happend, PR can be raised to remove the defunct copy when the feature flag is removed.
[CRIMAP-722](https://dsdmoj.atlassian.net/browse/CRIMAP-722)
Please see ticket for figma designs and double check that the copy is the same.
- make sure your meanse journey feature flag is on so as to see the new copy on the start page.
- check copy etc.
- set the feature flag to false --> then make sure current non-means copy shows instead.
[CRIMAP-722]: https://dsdmoj.atlassian.net/browse/CRIMAP-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add new start page copy for means assessment journey

- app/controllers/steps/income/manage_without_income_controller.rb
- app/forms/steps/income/manage_without_income_form.rb
- app/services/decisions/income_decision_tree.rb
- app/value_objects/manage_without_income_type.rb
- app/views/steps/income/manage_without_income/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20231025070727_manage_without_income_to_people.rb
- db/schema.rb
- spec/controllers/steps/income/manage_without_income_controller_spec.rb
- spec/forms/steps/income/manage_without_income_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/value_objects/manage_without_income_type_spec.rb
Add new step behind feature flag
Add to income decision tree, but not in flow yet
Add route with alias, controller, form and errors
https://dsdmoj.atlassian.net/browse/CRIMAP-696
run rails db:migrate
Start a new application
Go to /steps/income/how_does_client_manage_with_no_income
> CRIMAP-696 Add manage_no_income page

- app/controllers/steps/income/income_before_tax_controller.rb
- app/forms/steps/income/income_before_tax_form.rb
- app/models/crime_application.rb
- app/models/income_detail.rb
- app/models/income_details.rb
- app/models/person.rb
- app/services/decisions/income_decision_tree.rb
- app/views/steps/income/income_before_tax/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20231107202222_create_income_details.rb
- db/schema.rb
- spec/controllers/steps/income/income_before_tax_controller_spec.rb
- spec/forms/steps/income/income_before_tax_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Adds the "clients_income_before_tax"  to the income journey.
Also adds a new `IncomeDetails` object that we can use going forward to collect income related information in subsequent steps.
the relationship to crime_application is:
`crime_application.applicant.income_details`
i.e. it is a relationship through the applicant, but this is defined on the `Person` model so should be ameanable to `Partner` when the time comes to add those steps in as well. 
[CRIMAP-676](https://dsdmoj.atlassian.net/browse/CRIMAP-676)
n/a
- Start an application and go through the first step so you enter client details.
- then head to `applications/<application id>/steps/income/clients_income_before_tax`
- try to submitt the form without aswering the question, you should get a validation error in this case.
You …
> Crimap 676 add income model and bf tax form

- app/value_objects/manage_without_income_type.rb
- config/locales/en/helpers.yml
- db/schema.rb
- spec/value_objects/manage_without_income_type_spec.rb
QA modification request to update copy. 
Also updated ValueObject to more accurately match the meaning of the option.
https://dsdmoj.atlassian.net/browse/CRIMAPP-110
Start a new application
Go to /steps/income/how_does_client_manage_with_no_income
> Relabel homeless option on manage_no_income form, update ValueObject

- app/views/steps/address/lookup/edit.html.erb
We had removed the decorator class but were still calling it when we should have been calling the "present" method in this partial.
Create a new applicaion locally
Go enter basic details and ten do the DWP bypass
When you click save and continue no exeption should be raised.
> Presenter bug fix

- app/javascript/local/dropzone-cfg.js
- app/validators/file_upload_validator.rb
- spec/models/document_spec.rb
- spec/requests/evidence_upload_spec.rb
Rollback file upload restrictions enough to test a test malicious file upload
https://dsdmoj.atlassian.net/browse/CRIMAPP-207
1. Find an existing application in progress or create a new application, amend URL to look like https://staging-apply.com/applications/773bd241-6324-4fde-81b2-d48a94308d2a/steps/evidence/upload
2. Upload the malicious file and expect an error message
> [CRIMAP-207] Rollback file upload restrictions for testing

- app/javascript/local/dropzone-cfg.js
- app/validators/file_upload_validator.rb
- spec/models/document_spec.rb
- spec/requests/evidence_upload_spec.rb
Reverts temporary changes to allow file upload testing on Staging. Getting ready for production.
Rolling back temp changes so no changes in behaviour
> [CRIMAP-66] Rollback file upload restrictions for testing anti-virus

- app/forms/steps/income/income_before_tax_form.rb
- app/models/crime_application.rb
- app/models/income_details.rb
- app/models/person.rb
- db/migrate/20231114075123_modify_income_details_to_ref_crime_application.rb
- db/schema.rb
- spec/forms/steps/income/income_before_tax_form_spec.rb
Instead it makes it related to CrimeApplication. A CrimeApplication has_one income_details
This is an object that will eventually have the common income related data in relation to applicant/client and partner
As part of discussions on [CRIMAPP-131](https://dsdmoj.atlassian.net/browse/CRIMAPP-131) we created this refactor.
This will create data issues if you apply the migration and have `IncomeDetails` <---> `Person` data in your DB due to its removal of foreign keys.
You will need to remove these records for the rollback to happen.
In the UI should work the same as [CRIMAP-676](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/531)
[CRIMAPP-131]: https://dsdmoj.atlassian.net/browse/CRIMAPP-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> Removes relationship between IncomeDetails and Person

- config/routes.rb
Removes restriction to access the /steps/evidence/upload URL in all environments
Do all the routes restrictions need removing?
Create an application and append /steps/evidence/upload to the URL
> [CRIMAP-66] Remove routing restrictions for evidence upload

- app/controllers/steps/income/client_owns_property_controller.rb
- app/forms/steps/income/client_owns_property_form.rb
- app/services/decisions/income_decision_tree.rb
- app/views/steps/income/client_owns_property/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20231114162825_add_client_owns_property_to_income_details.rb
- db/schema.rb
- spec/controllers/steps/income/client_owns_property_controller_spec.rb
- spec/forms/steps/income/client_owns_property_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Adds "Apply: Add Does your client own their home, or any other land or property?" page into the application.
[CRIMAPP-208](https://dsdmoj.atlassian.net/browse/CRIMAPP-208)
Page:
Errors:
- create a case, get through the inital info page
- go to `/steps/income/clients_income_before_tax` click no
- this takes you to the next step (the one added in this PR): `/steps/income/does_client_own_home_land_property`
- try to submit without adding an answer - you should revcieve and error message.
- answer either yes or no --> it should then allow you to submit and will return you to the homepage pending further additions.
[CRIMAPP-208]: https://dsdmoj.atlassian.net/browse/CRIMAPP-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add client owns property step + specs

- app/controllers/steps/evidence/upload_controller.rb
- app/services/datastore/documents/delete.rb
- config/locales/en/errors.yml
- spec/controllers/steps/evidence/upload_controller_spec.rb
- spec/services/datastore/documents/delete_spec.rb
Fixes a bug spotted where files that did not upload to s3 were unable to be deleted in the non JS evidence upload form.
Also agreed to amend error messages to be clearer about upload status in the non JS form, so it is clear that files that have an error message did not upload and won't be submitted with the application (see screenshot below)
[CRIMAPP-236](https://dsdmoj.atlassian.net/browse/CRIMAPP-236)
**Bug - deleted file has been deleted but remains in uploaded files table**
**Deleted file has been deleted and is no longer in uploaded files table**
**Error messages have been appended with file 'File could not be uploaded' to be clearer that they have not been uploaded (non js form only)**
[CRIMAPP-236]: https://dsdmoj.atlassian.net/browse/CRIMAPP-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> Fix error deleting document in non js upload form

- config/routes.rb
- config/settings.yml
Re-instate Evidence Upload Feature Flag
Reinstates the feature flag, production still not enabled
> [CRIMAP-66] Re-instate Evidence Upload Feature Flag, remain disabled in production

- app/serializers/submission_serializer/sections/means_details.rb
https://ministryofjustice.sentry.io/alerts/rules/details/143747/?alert=7266&environment=production&notification_uuid=cd926de7-e22d-4c5f-aff7-c95d737d5054&referrer=metric_alert_slack
> HOTFIX: Application without income details can be serialised.

- Gemfile
- Gemfile.lock
Upgrade Schema to v1.0.11
https://dsdmoj.atlassian.net/browse/CRIMAPP-246
Makes `income_details` optional
> [CRIMAP-246] Upgrade Schema to v1.0.11

- config/kubernetes/production/deployment-clamav.yml
Adds Kubernetes StatefulSet deployment-clamav.yml to generate the production ClamAV service on port 3310
Will need trial and error in production unfortunately. Currently replicates (working) staging settings. Environment variables needed for virus scanning are already in place in config_map.yml
> [CRIMAP-66] Add clamav production service

- app/forms/steps/income/client_owns_property_form.rb
- app/forms/steps/income/employment_status_form.rb
- app/forms/steps/income/frozen_income_savings_assets_form.rb
- app/forms/steps/income/income_before_tax_form.rb
- app/forms/steps/income/lost_job_in_custody_form.rb
- app/forms/steps/income/manage_without_income_form.rb
- app/models/crime_application.rb
- app/models/income.rb
- app/models/income_details.rb
- app/serializers/submission_serializer/sections/means_details.rb
- app/services/adapters/structs/crime_application.rb
- app/services/adapters/structs/income_details.rb
- app/services/datastore/application_rehydration.rb
- db/migrate/20231127115239_move_income_detail_columns_from_people_to_income_details.rb
- db/migrate/20231127163617_change_income_details_to_incomes.rb
- db/schema.rb
- spec/forms/steps/income/client_owns_property_form_spec.rb
- spec/forms/steps/income/employment_status_form_spec.rb
- spec/forms/steps/income/frozen_income_savings_assets_form_spec.rb
- spec/forms/steps/income/income_before_tax_form_spec.rb
- spec/forms/steps/income/lost_job_in_custody_form_spec.rb
- spec/forms/steps/income/manage_without_income_form_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/means_details_spec.rb
- spec/services/adapters/structs/income_details_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
- spec/services/datastore/application_submission_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Move income detail columns from People to IncomeDetails table
Serialization and rehydration of income_above_threshold and lost_job
https://dsdmoj.atlassian.net/browse/CRIMAPP-97
1. Run `bin/rails db:migrate RAILS_ENV=development`
2. Create a new application, fill all details but DO NOT SUBMIT
3. Go to /steps/income/clients_income_before_tax
4. Select 'Yes'
5. Hit Save and continue
6. Reopen that application
7. Go to Confirm declaration and submit application
8. Submit application 
9. Go to Review
10. Assign that application to your list
11. Return to provider for any reason
12. Go to Apply
13. Open application and select Update
14. Go to /steps/income/clients_income_before_tax - radio should be selected
> [CRIMAPP-97] Move income detail columns from People to IncomeDetails table

- config/kubernetes/production/deployment-clamav.yml
- config/kubernetes/staging/deployment-clamav.yml
Increases the delay for the `readinessProbe` to give clamav more time to download in production, testing in staging first
This was tested in staging and worked as expected.
Reduces replicas from 2 down to 1 for troubleshooting purposes.
> [CRIMAP-66] Increase ClamAV readiness, reduce replicas

- config/kubernetes/production/deployment-clamav.yml
- config/kubernetes/staging/deployment-clamav.yml
Manually forces `freshclam` to run on container build because the [Dockerfile.freshclammed](https://github.com/ministryofjustice/hmpps-utility-container-images/tree/main/hmpps-clamav) doesn't seem to run 
Already Deployed to staging via command line, requires creation in Staging as part of build pipeline and then into production
On staging create a new evidence upload
On production watch the k8s pods and then log into the pod and try a manual file scan.
> [CRIMAP-66] Update deployment-clamav.yml with manual entrypoint

- Gemfile
- Gemfile.lock
- app/serializers/submission_serializer/sections/means_details.rb
- spec/serializers/submission_serializer/sections/means_details_spec.rb
N.B. Merge https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/559 and https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/564 first
Serialize has_frozen_income_or_assets 
Bump schema to v1.0.15
https://dsdmoj.atlassian.net/browse/CRIMAPP-205
bundle install 
update schema on datastore to v1.0.15 and bundle 
Create a new application, fill all details but DO NOT SUBMIT
Go to /steps/income/what_is_clients_employment_status
Select 'My client is not working', Select 'No'
Click Save and continue
Reopen that application
Go to /steps/income/clients_income_before_tax
Select 'Yes'
Click Save and continue
Reopen that application
Go to /steps/income/income_savings_assets_under_restraint_freezing_order
Click Save and continue
Reopen that application
Click …
> [CRIMAPP-205] Serialize freezing order

- app/services/decisions/income_decision_tree.rb
- app/views/layouts/_developer_tools.html.erb
- config/routes.rb
- spec/services/decisions/income_decision_tree_spec.rb
To help with manual testing, chain all income journey steps together, add a button in dev tools for Selenium to click to jump to the first page of the journey
> Reorder and chain steps, add income path to dev tools

- Gemfile
- Gemfile.lock
- app/presenters/summary/sections/employment_details.rb
- app/services/adapters/structs/income_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/employment_details_spec.rb
- spec/services/adapters/structs/income_details_spec.rb
Show employment details in CYA
https://dsdmoj.atlassian.net/browse/CRIMAPP-116
Designs are presumed based on the design on interim CYAs [here](https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?type=design&node-id=8959%3A130668&mode=design&t=zL5fWCdmRelppqV4-1)
1. bundle install
2. Create a new application, fill all details but DO NOT SUBMIT
3. Go to /steps/income/what_is_clients_employment_status (now also in dev tools)
4. Select 'My client is not working', Select 'Yes'
5. Hit Save and continue
6. Select 'Yes', Enter 1/11/2023
8. Hit Save and continue
9. Select 'No' for £12,475
10. Hit Save and continue
11. Select 'No' for Freezing order
12. Hit Save and continue
13. Select 'No' for Freezing order
14. Hit Save and continue
15. Select 'No' for Own home
16. Hit Save and continue …
> [CRIMAPP-116] Rehydrate/Show employment details in CYA

- Gemfile
- Gemfile.lock
- app/presenters/summary/sections/income_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/income_details_spec.rb
- spec/services/adapters/structs/income_details_spec.rb
Rehydrate/add freezing order to CYA
https://dsdmoj.atlassian.net/browse/CRIMAPP-206
1. bundle install
2. Set schema gem in datastore to v1.0.17 and bundle install
3. Create a new application, fill all details but DO NOT SUBMIT
4. Go to /steps/income/what_is_clients_employment_status (now also in dev tools)
5. Select 'My client is not working', Select 'Yes'
6. Hit Save and continue
7. Select 'Yes', Enter 1/11/2023
8. Hit Save and continue
9. Select 'No' for £12,475
10. Hit Save and continue
11. Select 'No' for Freezing order
12. Hit Save and continue
13. Select 'No' for Freezing order
14. Hit Save and continue
15. Select 'No' for Own home
16. Hit Save and continue
17. Select 'No' for Dependants
18. Hit Save and continue
19. Select 'Other' Enter some text for manage no income
20. Hit Save …
> [CRIMAPP-206] Rehydrate/add freezing order to CYA

- app/presenters/summary/sections/income_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/income_details_spec.rb
Adds "Does your client own their home, or any other land or property?" answer to the CYA page
- create new application
- go through inital application stages
- click on the dev tools to go to the income pages answer in the following way:
1. What is your client's employment status? -> My Client is not working -> No
2. £12,475 a year before tax? -> No
3. assets under a restraint or freezing order? -> No
4. Does your client own their home, or any other land or property? -> No
5. Does your client have any savings or investments? -> No
6. Does your client have any dependants? -> No
7. How does your client manage with no income? -> select any
8. Continue should take you back to application list
9. Click on the application and go to "Review the application" in the task list
10. Scroll to income …
> CRIMAPP-210 rehydrate property

- app/presenters/summary/sections/income_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/income_details_spec.rb
Adds "Does your client have any savings or investments?" answer to the CYA page
[CRIMAPP-213](https://dsdmoj.atlassian.net/browse/CRIMAPP-213)
- create new application
- go through inital application stages
- click on the dev tools to go to the income pages answer in the following way:
1. What is your client's employment status? -> My Client is not working -> No
2. £12,475 a year before tax? -> No
3. assets under a restraint or freezing order? -> No
4. Does your client own their home, or any other land or property? -> No
5. Does your client have any savings or investments? -> Yes
6. Does your client have any dependants? -> No
7. How does your client manage with no income? -> select any
8. Continue should take you back to application list
9. Click on the application and go to "Review the …
> Add savings yes/no answer to CYA page

- app/controllers/steps/outgoings/outgoings_more_than_income_controller.rb
- app/controllers/steps/outgoings_step_controller.rb
- app/forms/steps/outgoings/outgoings_more_than_income_form.rb
- app/models/crime_application.rb
- app/models/outgoings.rb
- app/services/decisions/outgoings_decision_tree.rb
- app/views/steps/income/lost_job_in_custody/edit.html.erb
- app/views/steps/outgoings/outgoings_more_than_income/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20231218162300_create_outgoings.rb
- db/schema.rb
- spec/controllers/steps/outgoings/outgoings_more_than_income_controller_spec.rb
- spec/forms/steps/outgoings/outgoings_more_than_income_form_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
Create outgoings table, add outgoings more than income page
https://dsdmoj.atlassian.net/browse/CRIMAPP-226
1. rails db:migrate
2. start a new application
3. go to steps/outgoings/are_clients_outgoings_more_than_income
4. submit with no selection to check errors https://docs.google.com/spreadsheets/d/1gdDpuyqWO6MJgUT1SOy0nbHd8AAdp1YebBzh1WDG040/edit#gid=0&range=B58:B59
5. select yes and input no text, submit to check errors
6. enter text and submit to check submits and doesn't raise an error
> Create outgoings table, add outgoings more than income page

- app/views/steps/income/client_has_dependants/edit.html.erb
- app/views/steps/income/client_owns_property/edit.html.erb
- app/views/steps/income/employment_status/edit.html.erb
- app/views/steps/income/frozen_income_savings_assets/edit.html.erb
- app/views/steps/income/has_savings/edit.html.erb
- app/views/steps/income/income_before_tax/edit.html.erb
- app/views/steps/income/lost_job_in_custody/edit.html.erb
- app/views/steps/income/manage_without_income/edit.html.erb
- app/views/steps/outgoings/outgoings_more_than_income/edit.html.erb
Fixes the back link for the income and new outgoings journeys. Was just a copy paste error. The `step_header` helper accepts a path as an overide which can be used on pages where the back link just needs to go back to the landing page or some other page when the user isn't in an application journey.
Issue was that we were passing `<% step_header(path: crime_applications_path) %>` on the steps and overriding the default behaviour of utilising the navigation stack to get the back link.
n/a
- check back links on the current live journey they should be uneffected.
- start a new application, go past the initial client details page, then use dev tools sto start the income journey.
- go through the income journey, and after you submit each step click the back link, and make sure it takes you …
> BUGFIX: Fix back links for income/outgoings journey

- Gemfile
- Gemfile.lock
- app/serializers/submission_serializer/sections/means_details.rb
- app/services/adapters/structs/crime_application.rb
- app/services/adapters/structs/outgoings_details.rb
- spec/serializers/submission_serializer/sections/means_details_spec.rb
- spec/services/adapters/structs/crime_application_spec.rb
- spec/services/adapters/structs/outgoings_details_spec.rb
- spec/services/datastore/application_submission_spec.rb
Serialize outgoings, with first attrs
https://dsdmoj.atlassian.net/browse/CRIMAPP-227
outgoings array is hardcoded as this ticket is not for that attribute, but the schema requires something. It will be an empty array if no options are selected (or maybe ['none']
1. `bundle install`
2. Create a new application, fill all details but DO NOT SUBMIT
3. Go to /steps/outgoings/are_clients_outgoings_more_than_income
4. Select 'Yes'
5. Enter some text in the text area
6. Click Save and continue
7. Reopen that application
8. Click Confirm declaration and submit application
9. Make sure submits ok
10. Click View completed application
11. Copy the UUID from the url
12. Run `rails c` in your datastore locally
13. Enter `a = CrimeApplication.find('UUID')`
14. Enter a.submitted_application
15. Make …
> Serialize outgoings, with first attrs

- Gemfile
- Gemfile.lock
- app/controllers/steps/outgoings/income_tax_rate_controller.rb
- app/forms/steps/outgoings/income_tax_rate_form.rb
- app/serializers/submission_serializer/sections/means_details.rb
- app/services/adapters/structs/outgoings_details.rb
- app/services/datastore/application_rehydration.rb
- app/services/decisions/outgoings_decision_tree.rb
- app/views/steps/outgoings/income_tax_rate/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20231220184900_add_income_tax_above_threshold_to_outgoings.rb
- db/schema.rb
- spec/controllers/steps/outgoings/income_tax_rate_controller_spec.rb
- spec/forms/steps/outgoings/income_tax_rate_form_spec.rb
- spec/serializers/submission_serializer/sections/means_details_spec.rb
- spec/services/adapters/structs/outgoings_details_spec.rb
- spec/services/datastore/application_rehydration_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
Introduces new Outgoings form 'In the last 2 years, has your client paid the 40% income tax rate?'.
Introduces Outgoings rehydration.
https://dsdmoj.atlassian.net/browse/CRIMAPP-223
https://dsdmoj.atlassian.net/browse/CRIMAPP-225
https://dsdmoj.atlassian.net/browse/CRIMAPP-114 (Part)
- The `Outgoings` model breaks convention - it should be `Outgoing` singular. Does this matter?
- The rehydration of Outgoings omits the `outgoings` field which is not present in the Apply database, pending CRIMAP-98
N/A
> [CRIMAP-223/225/114] Outgoings 'Paid 40% Tax Rate'

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/base_section.rb
- app/presenters/summary/sections/case_details.rb
- app/presenters/summary/sections/client_details.rb
- app/presenters/summary/sections/codefendants.rb
- app/presenters/summary/sections/contact_details.rb
- app/presenters/summary/sections/employment_details.rb
- app/presenters/summary/sections/first_court_hearing.rb
- app/presenters/summary/sections/income_details.rb
- app/presenters/summary/sections/justification_for_legal_aid.rb
- app/presenters/summary/sections/legal_representative_details.rb
- app/presenters/summary/sections/next_court_hearing.rb
- app/presenters/summary/sections/offences.rb
- app/presenters/summary/sections/other_income_details.rb
- app/presenters/summary/sections/other_outgoings_details.rb
- app/presenters/summary/sections/overview.rb
- app/presenters/summary/sections/passport_justification_for_legal_aid.rb
- app/presenters/summary/sections/supporting_evidence.rb
- app/services/datastore/application_rehydration.rb
- config/locales/en/summary.yml
- db/schema.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/other_outgoings_details_spec.rb
Rehydrate/add other outgoings details to CYA
https://dsdmoj.atlassian.net/browse/CRIMAPP-228
Designs assumed based on https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?type=design&node-id=8963%3A132484&mode=design&t=nO6xIcvVLqvY7Fvi-1
1. Make sure schema is at v1.0.22 here and on the datastore
2. Create a new application, fill all details but DO NOT SUBMIT
3. Go to /steps/income/what_is_clients_employment_status (now also in dev tools)
4. Select 'My client is not working', Select 'Yes'
5. Hit Save and continue
6. Select 'Yes', Enter 1/11/2023
7. Hit Save and continue
8. Select 'No' for £12,475
9. Hit Save and continue
10. Select 'No' for Freezing order
11. Hit Save and continue
12. Select 'No' for Freezing order
13. Hit Save and continue
14. Select 'No' for Own home
15. Hit …
> [CRIMAPP-228] Add other outgoings details to CYA

- app/views/layouts/_developer_tools.html.erb
Adds DWP bypass back in post the case type move.
Does a check on charge as this is the next mandatory data point we can use to remove it when it is not relevant.
No strong feelings either way - guess it could get more crowded if we add more buttons etc.
- DWP bypass button should be back now when you start the case.
- it will disappear on the offences page as its not relevant after the DWP page of the journey
> Show DWP bypass in Dev post case type move

- app/controllers/steps/outgoings/council_tax_controller.rb
- app/forms/steps/outgoings/council_tax_form.rb
- app/services/decisions/income_decision_tree.rb
- app/services/decisions/outgoings_decision_tree.rb
- app/views/steps/income/lost_job_in_custody/edit.html.erb
- app/views/steps/outgoings/council_tax/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20240103143020_add_council_tax_to_outgoings.rb
- db/schema.rb
- spec/controllers/steps/outgoings/council_tax_controller_spec.rb
- spec/forms/steps/outgoings/council_tax_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
Add council tax page
https://dsdmoj.atlassian.net/browse/CRIMAPP-265
1. rails db:migrate
2. Start an application
3. Go to steps/outgoings/does_client_pay_council_tax
4. Check that submitting the form without selecting an option displays error 'Select yes if your client pays Council Tax where they usually live'
5. Check that submitting the form with Yes selected but no amount number input displays error 'Enter how much your client pays yearly'
6. Check that submitting with Yes selected and an amount input submits ok
> [CRIMAPP-265] Add council tax page

- Gemfile
- Gemfile.lock
- app/serializers/submission_serializer/sections/means_details.rb
- spec/serializers/submission_serializer/sections/means_details_spec.rb
- spec/services/adapters/structs/outgoings_details_spec.rb
Serialize housing payments, bump schema
https://dsdmoj.atlassian.net/browse/CRIMAPP-275
1. `bundle install`
2. Set local datastore schema in Gemfile to tag: 'v1.0.24' `bundle install`
3. Create a new application, fill all details but DO NOT SUBMIT
4. Go to /steps/income/what_is_clients_employment_status
5. Select 'My client is not working', Select 'No'
6. Click Save and continue
7. Select 'No' to £12,475
8. Click Save and continue
9. Select 'No' to frozen assets
10. Click Save and continue
11. Select 'No' to property
12. Click Save and continue
13. Select 'No' to savings
14. Select 'No' to dependants
15. Click Save and continue
16. Select any for how manage
17. Click Save and continue
18. Select any for housing payment
19. Click Save and continue
20. Select no for 40%
21. Click Save and …
> Serialize housing payments, bump schema

- app/controllers/steps/dwp/confirm_details_controller.rb
- app/presenters/summary/sections/dwp_client_details.rb
- app/views/steps/dwp/confirm_details/edit.html.erb
- spec/presenters/summary/sections/dwp_client_details_spec.rb
Remove benefit type from DWP confirm details page
> Remove benefit type from DWP confirm details page

- app/views/steps/client/appeal_details/edit.en.html.erb
- config/locales/en/helpers.yml
Remove MAAT ID field from appeal with changes page
Ticket has been deleted as it was created after I completed this PR, and I said it was done. 
Designs have now been updated to appear like it has already been done. 
https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?type=design&node-id=9182%3A66774&mode=design&t=ul8sC0nTj8KLZdwZ-1
Start an application
Fill in client details
Click Save and continue
Select Appeal to crown court with changes in financial circumstances
Click Save and continue
Check screen reflects designs
> Remove MAAT ID field from appeal with changes page

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/housing_payments.rb
- config/locales/en/summary.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/housing_payments_spec.rb
Add housing payment to CYA
https://dsdmoj.atlassian.net/browse/CRIMAPP-219
1. Create a new application, fill all details but DO NOT SUBMIT
2. Go to /steps/income/what_is_clients_employment_status (now also in dev tools)
3. Select 'My client is not working', Select 'No'
4. Hit Save and continue
5. Select 'No' for £12,475
6. Hit Save and continue
7. Select 'No' for Freezing order
8. Hit Save and continue
9. Select 'No' for Land/property
10. Hit Save and continue
11. Select 'No' for Savings
12. Hit Save and continue
13. Select 'No' for Dependants
14. Hit Save and continue
15. Select any for How manage
16. Hit Save and continue
17. Select any for Housing Payment
18. Hit Save and continue
19. Select 'No' for Council tax
20. Hit Save and continue
21. Select 'No' for Income more than outgoings …
> [CRIMAPP-219] Add housing payment to CYA

- config/locales/en/steps.yml
- config/locales/en/summary.yml
Change "Has the case concluded?" date description
Before: When did the case conclude?
After: Enter when the case concluded
https://dsdmoj.atlassian.net/browse/CRIMAPP-385
> CRIMAPP-385 Content change

- Gemfile
- Gemfile.lock
- app/controllers/steps/case/is_client_remanded_controller.rb
- app/forms/steps/case/is_client_remanded_form.rb
- app/presenters/summary/sections/case_details.rb
- app/serializers/submission_serializer/sections/case_details.rb
- app/services/decisions/case_decision_tree.rb
- app/views/steps/case/is_client_remanded/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- config/routes.rb
- db/migrate/20240125141124_add_is_client_remanded_to_cases.rb
- db/schema.rb
- spec/controllers/steps/case/is_client_remanded_controller_spec.rb
- spec/forms/steps/case/is_client_remanded_form_spec.rb
- spec/presenters/summary/sections/case_details_spec.rb
- spec/serializers/submission_serializer/sections/case_details_spec.rb
- spec/services/adapters/structs/case_details_spec.rb
- spec/services/datastore/application_submission_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Add "Has court remanded client in custody" page behind feature flag `means_journey`
**Add db columns**
cases.is_client_remanded(string)
cases.date_client_remanded(date)
https://dsdmoj.atlassian.net/browse/CRIMAPP-314
Currently "Has court remanded client in custody" page is behind a feature flag for local and staging
> CRIMAPP-314  Add "Has the court remanded your client in custody" page

- app/controllers/steps/submission/more_information_controller.rb
- app/forms/steps/submission/more_information_form.rb
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/more_information.rb
- app/presenters/task_list/collection.rb
- app/presenters/tasks/more_information.rb
- app/services/decisions/base_decision_tree.rb
- app/services/decisions/case_decision_tree.rb
- app/services/decisions/evidence_decision_tree.rb
- app/services/decisions/submission_decision_tree.rb
- app/views/steps/submission/more_information/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- config/locales/en/tasklist.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20240129124609_add_additional_information_to_crime_applications.rb
- db/schema.rb
- spec/controllers/steps/submission/more_information_controller_spec.rb
- spec/forms/steps/submission/more_information_form_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/task_list/collection_spec.rb
- spec/presenters/tasks/more_information_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/decisions/evidence_decision_tree_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
Add and optional more information step before submission/review for all application types.
[CRIMAPP-427](https://dsdmoj.atlassian.net/browse/CRIMAPP-427)
This PR does not include submission to the datastore.
[CRIMAPP-427]: https://dsdmoj.atlassian.net/browse/CRIMAPP-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-427 Add more information to submission

- app/models/charge.rb
- app/services/decisions/case_decision_tree.rb
- spec/services/decisions/case_decision_tree_spec.rb
Empty charges getting created while navigating from `remand` to `offence` page 
https://dsdmoj.atlassian.net/browse/CRIMAPP-357
1. Save form "Has a court remanded your client in custody?"
2. Next page should be "What has your client been charged with?"
3. Click "back" button
4. Save form "Has a court remanded your client in custody?"
5. Next page should be "What has your client been charged with?"  (earlier it was "You have added 1 offence" page with 1 incomplete offence)
> CRIMAPP-357 - Fix charges page flow

- app/models/crime_application.rb
- app/validators/application_fulfilment_validator.rb
- app/validators/base_fulfilment_validator.rb
- app/validators/pse_fulfilment_validator.rb
- config/locales/en/errors.yml
- spec/validators/pse_fulfilment_validator_spec.rb
Adds validation to the review/submit page to prevent users from submitting a pse application without uploading evidence 
[CRIMAPP-457](https://dsdmoj.atlassian.net/browse/CRIMAPP-457)
I attempted to add a validation message to the upload screen itself but the error was shown when evidence was deleted meaning when an application only has one piece of evidence and that is deleted, the validation checking there is at least one piece of supporting evidence fails and then the error is shown. This is not simple to change so this approach was implemented instead as it is technically simpler
1. Start a pse application
2. Click save and continue on the add supporting evidence screen 
3. Click whatever option on the adding more information and save and continue 
4. Review the application and save …
> [CRIMAPP-457] Prevent pse apps from being submitted without evidence

- app/forms/steps/income/dependants_form.rb
- app/models/dependant.rb
- config/locales/en/errors.yml
- config/locales/en/integer.yml
- spec/forms/steps/income/dependants_form_spec.rb
Limits number of dependants a user can add to 50. Arbitrary number, seems sensible.
https://dsdmoj.atlassian.net/browse/CRIMAPP-281
- Added the 'fifty first' translation string because of a quirk in the way this 50 limit works:
- When the user presses 'Add new dependant' that creates a new row in the `dependants` database table, but wit a `NULL` age value.
- If the user then presses 'Add new dependant' to save the age for entry number 50 (which updates the database correctly), yet another row is generated in the database for entry number 51, with a `NULL` age, however a validation error is also shown
- Therefore the simplest solution is to allow Dependant entry number 51 to show on screen, show the error message and hope the user does not ever have 50 dependants.
Create an application and …
> [CRIMAPP-281] Limit dependants to 50

- app/forms/steps/case/has_case_concluded_form.rb
- app/services/decisions/case_decision_tree.rb
- spec/forms/steps/case/has_case_concluded_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
Add conditional logic for "Has the Case concluded" question
Has the case concluded?
- yes
> -  Redirects to **"Do you intend to claim pre-order work?"** page
- no
>-  Redirects to **"Has a court remanded your client in custody?"** page
>- Reset 'Pre-order work' attributes to nil
https://dsdmoj.atlassian.net/browse/CRIMAPP-516
> CRIMAPP-516 Make pre-order work page conditional

- app/controllers/concerns/error_handling.rb
- app/controllers/steps/capital/saving_type_controller.rb
- app/controllers/steps/capital/savings_controller.rb
- app/forms/steps/capital/saving_type_form.rb
- app/forms/steps/capital/savings_form.rb
- app/lib/errors.rb
- app/models/crime_application.rb
- app/models/saving.rb
- app/services/decisions/capital_decision_tree.rb
- app/value_objects/ownership_type.rb
- app/views/steps/capital/savings/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20240216142643_create_savings.rb
- db/schema.rb
- spec/controllers/steps/capital/savings_controller_spec.rb
- spec/forms/steps/capital/saving_type_form_spec.rb
- spec/forms/steps/capital/savings_form_spec.rb
- spec/models/saving_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/support/matchers/validation_matchers.rb
- spec/value_objects/ownership_type_spec.rb
Adds the ‘Your Client’s savings?’ page. 
Creates a new saving from the saving_type page.
[CRIMAPP-511](https://dsdmoj.atlassian.net/browse/CRIMAPP-511)
This is the 2nd screen in the savings loop/journey.
The savings summary page and premium bond destinations are part of a separate ticket.
This PR also introduces a new validation helper to check that an attribute is validated as a ValueObject. For example: 
```ruby
it { is_expected.to validate_is_a(:account_holder, OwnershipType) }
```
[CRIMAPP-511]: https://dsdmoj.atlassian.net/browse/CRIMAPP-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-511 add savings

- app/models/crime_application.rb
- app/models/outgoings_payment.rb
- app/value_objects/outgoings_payment_type.rb
- db/migrate/20240208114218_create_outgoings_payments.rb
- db/schema.rb
- Add migration to create outgoing payments table,
- Add uniqueness index on crime_application_id with payment_type columns so each application can have only one of each payment type
- Add model which belongs_to CrimeApplication
[CRIMAPP-458](https://dsdmoj.atlassian.net/browse/CRIMAPP-458)
N/A
[CRIMAPP-458]: https://dsdmoj.atlassian.net/browse/CRIMAPP-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-458 add outgoing payments table and model

- app/controllers/steps/capital/premium_bonds_controller.rb
- app/forms/steps/base_form_object.rb
- app/forms/steps/capital/premium_bonds_form.rb
- app/models/capital.rb
- app/models/crime_application.rb
- app/services/decisions/capital_decision_tree.rb
- app/views/steps/capital/premium_bonds/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20240221120639_create_capital.rb
- db/schema.rb
- spec/controllers/steps/capital/premium_bonds_controller_spec.rb
- spec/forms/steps/capital/premium_bonds_form_spec.rb
[CRIMAPP-560](https://dsdmoj.atlassian.net/browse/CRIMAPP-560)
This PR also adds "before_save" to the save methods on the base steps controller to clean up how we currently reset attributes. 
[CRIMAPP-560]: https://dsdmoj.atlassian.net/browse/CRIMAPP-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP 502 premium bonds

- app/forms/steps/capital/savings_form.rb
- spec/forms/steps/capital/savings_form_spec.rb
The provider is now required to confirm account ownership when saving an existing and valid application. Prior to this, the confirm box was checked if the provider has previously confirmed ownership was with the applicant. 
https://dsdmoj.atlassian.net/browse/CRIMAPP-511
This change also updates the form to use the recently introduced `Form#before_save`.
> CRIMAPP-511 Confirm account holder on edit

- config/inactive_offices.yml
An office that was added as inactive needs to be allowed on to the service
As per this thread https://mojdt.slack.com/archives/C06DFR460F2/p1709048987313009
> Remove office from inactive list

- app/controllers/concerns/error_handling.rb
- app/controllers/steps/capital/properties_controller.rb
- app/forms/steps/capital/properties_form.rb
- app/forms/steps/capital/property_type_form.rb
- app/lib/errors.rb
- app/models/crime_application.rb
- app/models/person.rb
- app/models/property.rb
- app/services/decisions/capital_decision_tree.rb
- app/value_objects/house_type.rb
- app/views/steps/capital/properties/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20240221121558_create_properties.rb
- db/schema.rb
- spec/controllers/steps/capital/properties_controller_spec.rb
- spec/forms/steps/capital/properties_form_spec.rb
- spec/forms/steps/capital/property_type_form_spec.rb
- spec/models/property_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/value_objects/house_type_spec.rb
- spec/value_objects/property_type_spec.rb
Add 'Your client’s residential property' page
Creates a new property from the property_type page.
https://dsdmoj.atlassian.net/browse/CRIMAPP-486
- This is the 2nd screen in the assets loop/journey.
- Currently, after saving properties, page gets redirected to "Which savings does your client have inside or outside the UK?" page. 
- Next page should be "What is the address of your client’s land?" (yet to implement)
http://localhost:3000/applications/:id/capital/which_assets_does_client_own
> CRIMAPP-486 Add residential property page

- app/services/decisions/capital_decision_tree.rb
- app/services/decisions/income_decision_tree.rb
- app/services/decisions/outgoings_decision_tree.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
- spec/value_objects/outgoings_payment_type_spec.rb
Update routing of means journey
Stitch together capital pages as placeholder route
Connect outgoings to capital
Add routing logic to Income as per https://miro.com/app/board/uXjVO75Jwao=/?moveToWidget=3458764570607376929&cot=14
Check means journey skips to evidence upload if case type is appeal to CC (no changes) aka appeal_to_crown_court after the employment page (or job lost in custody page if triggered)
Check dependants skipped based on: https://www.figma.com/file/thkvnDBbQbHlSqzt1TE3lk?node-id=7035:54438&mode=design#651514930
Check manage_no_income page is not shown if any payments/benefits are declared 
(I did consider adding a check if income < £12,475 == 'yes' too but it would take us to a cul-de-sac where income > £12,475 && no payments declared  and we wouldn't show the …
> Update routing of means journey

- config/locales/en/helpers.yml
Typo, missing vowel
N/A
N/A
`<staging url>/applications/<crime application id>/steps/income/which_benefits_does_client_get`
> [CHORE] Typo Child Benfit in Outgoings

- app/views/steps/submission/shared/_section.html.erb
- config/settings.yml
- spec/requests/dashboard_spec.rb
Uses summary cards for the Review screen.
Feature flagged to staging and local only.
> Add summary cards to staging and local

- app/controllers/steps/capital/properties_controller.rb
- app/controllers/steps/capital/property_address_controller.rb
- app/forms/steps/capital/properties_form.rb
- app/forms/steps/capital/property_address_form.rb
- app/models/property.rb
- app/services/decisions/capital_decision_tree.rb
- app/validators/address_validator.rb
- app/views/steps/capital/property_address/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20240229125141_change_column_address_in_properties.rb
- db/schema.rb
- spec/controllers/steps/capital/property_address_controller_spec.rb
- spec/forms/steps/capital/property_address_form_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
Add "What is the address of your client’s residential property?" page if client selects 'no' for the question "Is the address of the property the same as your client’s home address?" in the "Your client’s residential property" page
[CRIMAPP-487](https://dsdmoj.atlassian.net/browse/CRIMAPP-487)
Currently we are routing to "which_savings_does_client_have" for all paths of capital assets. It will change as we introduce more pages to the journey
[CRIMAPP-487]: https://dsdmoj.atlassian.net/browse/CRIMAPP-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-487 - Add residential property address page

- .overcommit.yml
- README.md
Overcommit allows you to install a pre-commit hook to run linters and/or tests on files you have changed before making the commit/pushing. Personally I find this useful because it means you never push changes and then see the pipeline fail e.g. because you used the wrong kind of quotation marks or accidentally added a new line. But it's optional to install anyway so not everyone has to use it. 
https://github.com/sds/overcommit
This PR:
- Adds the config file overcommit.yml
- Updates the README
N/A
N/A
N/A
N/A
> Add overcommit to the repo

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/premium_bonds.rb
- config/locales/en/summary.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/premium_bonds_spec.rb
Add premium bonds to submission/review
[CRIMAPP-559](https://dsdmoj.atlassian.net/browse/CRIMAPP-559)
[CRIMAPP-559]: https://dsdmoj.atlassian.net/browse/CRIMAPP-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-559 add premium bonds to submission/review

- Gemfile
- Gemfile.lock
- app/forms/steps/income/income_benefits_form.rb
- app/forms/steps/income/income_payments_form.rb
- app/models/address.rb
- spec/presenters/summary/components/property_spec.rb
- spec/presenters/summary/sections/contact_details_spec.rb
Small refactor to income benefits and payments forms to use shared type in schema
Also amends the presentation of address to Address line 1 -> Address line 2 -> City -> Postcode -> Country
[CRIMAPP-284](https://dsdmoj.atlassian.net/browse/CRIMAPP-284)
[CRIMAPP-284]: https://dsdmoj.atlassian.net/browse/CRIMAPP-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-284] Income benefits and payment minor refactor 

- app/attributes/type/pence.rb
- spec/attributes/type/pence_spec.rb
Truncate rather than rounding 10ths of a penny. 
[CRIMAPP-606](https://dsdmoj.atlassian.net/browse/CRIMAPP-606)
Previously the Pence type would round tenths of a penny which meant that a form input of 0.999 would be saved and displayed as £1.00. This PR changes that behaviour so that £0.999 is saved and displayed as £0.99.
[CRIMAPP-606]: https://dsdmoj.atlassian.net/browse/CRIMAPP-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-606 Truncate 10ths of a penny

- app/views/steps/client/has_nino/edit.html.erb
Remove no nino link for non-means tested applications
https://dsdmoj.atlassian.net/browse/CRIMAPP-615
> [CRIMAPP-615] Remove no nino link for non-means tested applications

- app/services/decisions/case_decision_tree.rb
- app/services/decisions/client_decision_tree.rb
- config/locales/en/helpers.yml
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Discovered during qa testing, when no passporting benefit is selected then applicant is not being routed to means assessment and they are not being correctly routed to the ioj screens 
Makes the following fixes: 
- Reverts to routing to the ioj screens following the court hearing details 
- Routes to means assessment following ioj screens if the applicant does not have a passporting benefit or does not have benefit evidence 
- Following an undetermined dwp check, routes to case details if instead of the benefit exit screen if user does not have benefit evidence
[CRIMAPP-693](https://dsdmoj.atlassian.net/browse/CRIMAPP-693)
Test the scenarios above and in the ticket 
[CRIMAPP-693]: https://dsdmoj.atlassian.net/browse/CRIMAPP-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
> Fix app flow when passporting benefit is not selected

- app/services/decisions/income_decision_tree.rb
- spec/services/decisions/income_decision_tree_spec.rb
Discovered issue testing in staging where user is routed to case details section following partial means assessment. This should be the evidence upload screen
[CRIMAPP-693](https://dsdmoj.atlassian.net/browse/CRIMAPP-693)
[CRIMAPP-693]: https://dsdmoj.atlassian.net/browse/CRIMAPP-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-693] Route to evidence upload following partial means assessment

- app/forms/steps/capital/property_type_form.rb
- spec/forms/steps/capital/property_type_form_spec.rb
Delete existing assets if user select "My client does not own any of these assets" option
https://dsdmoj.atlassian.net/browse/CRIMAPP-677
Please follow ticket [comments](https://dsdmoj.atlassian.net/browse/CRIMAPP-677?focusedCommentId=441715)
http://localhost:3000/applications/:id/steps/capital/which_assets_does_client_own
> CRIMAPP-677 Delete existing assets on selecting 'My client does not own any of these assets' option

- app/services/decisions/case_decision_tree.rb
- app/services/decisions/client_decision_tree.rb
- config/locales/en/helpers.yml
- config/settings.yml
- spec/services/decisions/case_decision_tree_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Discovered a bug with routing when the means  journey feature flag is set to false
When a user enters a nino and selects a passporting benefit and then selects that they do not have evidence, they were not being shown the evidence exit screen 
This is due to previous changes to routing for means applications 
Scenarios 
<table>
<tr>
<td>
Means journey ff 
<td>
Nino
<td>
benefit type
<td>
Has benefit evidence
<td>
Result
<tr>
<td>
False
<td>
Yes
<td>
Yes
<td>
No
<td>
Evidence exit
</table>
<table>
<tr>
<td>
Means journey ff 
<td>
Nino
<td>
benefit type
<td>
Has benefit evidence
<td>
Result
<tr>
<td>
False
<td>
Yes
<td>
No
<td>
-
<td>
Evidence exit
</table>
<table>
<tr>
<td>
Means journey ff 
<td>
Nino
<td>
benefit type
<td>
Has benefit evidence
<td>
Result
<tr>
<td>
False
<td>
Yes
<td>
Yes …
> Fix routing for non means tested applications

- app/controllers/steps/income/answers_controller.rb
- app/presenters/summary/html_presenter.rb
- app/services/decisions/income_decision_tree.rb
- app/views/steps/income/answers/edit.html.erb
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/income/answers_controller_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
Add "Check your answers" page to income section
https://dsdmoj.atlassian.net/browse/CRIMAPP-258
> [!IMPORTANT]  
> -Special attention required for **income_decision_tree.rb**
> CRIMAPP-258 income add check your answers page to income section

- app/views/steps/capital/property_owners/edit.html.erb
- config/locales/en/helpers.yml
- spec/presenters/summary/components/property_spec.rb
Percentage ownership text for the residential property property owners form page was not matching design. This has been updated
[CRIMAPP-678](https://dsdmoj.atlassian.net/browse/CRIMAPP-678)
1. Navigate to the 'Which assets does your client own or part-own inside or outside the UK?' page
2. Select Residential Property' Radio button'
3. Save and continue
4. Enter the required data selecting YES to the ‘Does anyone else own part of the property?’ question.
5. Save and continue
6. On the 'Other people who own your client’s residential property' page, verify the question text reads 'What percentage of the property do they own?'
Repeat the steps for the commercial property property owner screen. The question text should be 'What percentage of the property do they own?. 
Repeat the steps for …
> [CRIMAPP-678] Display correct percentage ownership question text

- app/validators/application_fulfilment_validator.rb
- spec/validators/application_fulfilment_validator_spec.rb
The application should be able to be submitted without the NINO as the applicant is in Court Custody and receiving passporting benefits.
https://dsdmoj.atlassian.net/browse/CRIMAPP-703
Please refer to JIRA comments: https://dsdmoj.atlassian.net/browse/CRIMAPP-703?focusedCommentId=445551
Application submitted successfully
Start a new application:
- Is this application subject to the usual means or passported test? Yes
- Does your client have a partner? No
- Enter your client’s details
- What is the case type? Either way
- My client does not have a home address (Use Provider’s office as Correspondence address)
- Does your client have a National Insurance number? No
- Does your client get one of these passporting benefits? Universal Credit
- I will enter the National Insurance number later
- …
> CRIMAPP-703 Staging - Unable to submit pp application no nino in ct custody

- app/views/home/index.en.html.erb
Update start page content for means journey
[CRIMAPP-711](https://dsdmoj.atlassian.net/browse/CRIMAPP-711)
The means journey feature flag must be switched on 
[CRIMAPP-711]: https://dsdmoj.atlassian.net/browse/CRIMAPP-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-711 Update start page content for means journey

- app/forms/steps/client/benefit_type_form.rb
- app/presenters/summary/sections/client_details.rb
- app/views/steps/client/benefit_type/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- db/migrate/20240415145143_add_last_jsa_appointment_date_to_people.rb
- db/schema.rb
- spec/forms/steps/client/benefit_type_form_spec.rb
- spec/presenters/summary/sections/client_details_spec.rb
Add last_jsa_appointment_date field
Modifies Benefit Type page to add a date field when JSA is selected. 
https://dsdmoj.atlassian.net/browse/CRIMAPP-441
This is the modification to Apply only. No submission.
For some reason Benefit type is not persisting, but this is also not persisting on staging at the moment, so a bug ticket is being raised to look into that separately 
Run migration
Create an application with JSA benefit type
Do not enter date, attempt form submit, check error message shows
Check any other date validations you want (no day, no month, year in future, year in 1800, day = 34 etc)
Put in valid date and click save and continue
Navigate to /submission/review, check Date is in the Client details section after benefit type - check copy against designs. 
Hit change link on …
> [CRIAMPP-411] Add last_jsa_appointment_date field

- app/forms/steps/outgoings/board_and_lodging_form.rb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- spec/forms/steps/outgoings/board_and_lodging_form_spec.rb
Fix validation to allow food amount to be 0, but not less. 
Add missing validation to check that food amount is less than board amount
Update hint text on food amount field
[CRIMAPP-699](https://dsdmoj.atlassian.net/browse/CRIMAPP-699)
[CRIMAPP-699]: https://dsdmoj.atlassian.net/browse/CRIMAPP-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-699 Fix food amount validation error

- app/services/decisions/client_decision_tree.rb
- spec/services/decisions/client_decision_tree_spec.rb
Add guard clause to `entered_appeal_reference_number?` to prevent  throwing an error when case type is nil
[Sentry alert](https://ministryofjustice.sentry.io/issues/5216134617/?alert_rule_id=14332616&alert_type=issue&notification_uuid=dc0ac186-f05b-4a47-9dc9-dfcd66094590&project=6587263&referrer=slack)
> Fix bug in client decision tree 

- app/services/passporting/means_passporter.rb
- spec/services/passporting/means_passporter_spec.rb
Fix inablity to submit appeal no changes
https://dsdmoj.atlassian.net/browse/CRIMAPP-748
Scenario 1: Appeal no changes
1. Create a means tested application with appeal case type
2. Select yes to original application
3. Select no to financial change and add a ref number
4. Finish application and make sure it submits
Scenario 2: Appeal with changes
1. Create a means tested application with appeal case type
2. Select yes to original application
3. Select yes to financial change and add a desc
4. Finish application and make sure it shows you the nino/ppt pages and submits
Scenario 2: Appeal with changes
1. Create a means tested application with appeal case type
2. Select yes to original application
3. Select yes to financial change and add a desc
5. Fail the DWP check, select to upload …
> [CRIMAPP-748] Fix inablity to submit appeal no changes

- app/forms/steps/outgoings/outgoings_more_than_income_form.rb
- spec/forms/steps/outgoings/outgoings_more_than_income_form_spec.rb
Reset the `how_manage` attribute when no is selected before saving
[CRIMAPP-720](https://dsdmoj.atlassian.net/browse/CRIMAPP-720)
1. In Apply, process an application to navigate to the OUTGOINGS Are your client’s outgoings more than their income? question
2. Answer YES. Text box with extra question How does your client manage if their outgoings are more than their income? appears
3. Enter text into the text field and Save and Continue
4. On the CYA page under Other Outgoings' section, the answer and supporting text displays as expected
5. Go back to Are your client’s outgoings more than their income? question
6. Change answer to NO. Text field is no longer present. Save and Continue
7. **On the CYA page under Other Outgoings' section, the answer has changed to NO and the supporting text …
> CRIMAPP-720 Fix bug in displaying other outgoings

- app/models/concerns/type_of_means_assessment.rb
- app/services/decisions/income_decision_tree.rb
- spec/validators/application_fulfilment_validator_spec.rb
Fulfilment validator can handle income below threshold.
https://ministryofjustice.sentry.io/issues/5221747359/
Fixes bug introduced to staging last night.
Attempt to submit an application with means but income below threshold. You will not be able to do that without this fix.
> FIX APPLY-FOR-CRIMINAL-LEGAL-AID-2T

- app/value_objects/investment_type.rb
Adds missing share option to investment type form
[CRIMAPP-742](https://dsdmoj.atlassian.net/browse/CRIMAPP-742)
I've tested it end to end and works fine 
1. Start an means tested application with an either way case type
2. Enter a nino 
3. Select no to passporting benefit
4. Go through the income, outgoings and capital screens until you get to the investment type page
5. Confirm the share option is visible 
6. Select the share option and add a share investment
7. Finish the rest of the application 
8. Confirm the share investment is visible on the review your application screen 
9. Submit the application 
10. Confirm the share investment is visible on the completed application screen 
11. Open review, navigate to the application and confirm the share investment is visible on review
12. …
> [CRIMAPP-742] Add investment share option

- app/validators/application_fulfilment_validator.rb
- spec/validators/application_fulfilment_validator_spec.rb
Ignore fulflilment validation when income section not present.
[APPLY-FOR-CRIMINAL-LEGAL-AID-2V](https://ministryofjustice.sentry.io/issues/5221972373/)
Make sure you can submit both a means passported and non means application.
> APPLY-FOR-CRIMINAL-LEGAL-AID-2V

- app/forms/steps/income/lost_job_in_custody_form.rb
- app/views/steps/capital/premium_bonds/edit.html.erb
- config/locales/en.yml
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/summary.yml
- spec/forms/steps/income/lost_job_in_custody_form_spec.rb
- spec/presenters/crime_application_presenter_spec.rb
- spec/presenters/summary/components/investment_spec.rb
- spec/presenters/summary/components/offence_spec.rb
- spec/requests/dashboard_lists_spec.rb
- spec/requests/dashboard_spec.rb
- spec/requests/dwp_benefit_checker_spec.rb
Fix small spelling and design mismatches
Bit of a hodgebodge, sorry!
1. Correct spelling of State Pensions -> State Pension
2. Correct spelling of Stock -> Stocks on investment CYA playback
3. Update premium bond question order, wording and hints
4. Set date defaults to full length month name
5. Remove full stop from error message
6. Correct checkbox copy on investment 'I confirm account is in client's name' -> I confirm investment is in client's name
Remove 3month restriction on date job lost input (to allow for resubmission etc. no validated on eForms)
1.https://dsdmoj.atlassian.net/browse/CRIMAPP-737
2. https://dsdmoj.atlassian.net/browse/CRIMAPP-744
3. https://dsdmoj.atlassian.net/browse/CRIMAPP-750
4. https://dsdmoj.atlassian.net/browse/CRIMAPP-718
5. …
> Fix small spelling and design mismatches

- app/services/decisions/case_decision_tree.rb
- spec/services/decisions/case_decision_tree_spec.rb
Non-means applications are not shown the is client remanded in custody question
Flow also broke in a regression at some point which sent user to means questions so this fixes that too
> Fix non means tested application from triggering 'means_test_required?'

- app/presenters/summary/sections/trust_fund.rb
- spec/presenters/summary/sections/trust_fund_spec.rb
Fix exception when trust fund not answered
Visit the submisison/review page with capital section started but not completed (stopped before trust fund question).
> Fix exception when trust fund not answered

- app/presenters/tasks/evidence_upload.rb
- spec/presenters/tasks/evidence_upload_spec.rb
Supporting evidence always applicable
Supporting evidence can be started at any time
[CRIMAPP-772](https://dsdmoj.atlassian.net/browse/CRIMAPP-772)
[CRIMAPP-772]: https://dsdmoj.atlassian.net/browse/CRIMAPP-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Supporting evidence always applicable and startable

- app/presenters/summary/sections/payment_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/outgoings_payments_details_spec.rb
Display `Does not pay` instead of `Does not get` for outgoings payment categories
[CRIMAPP-792](https://dsdmoj.atlassian.net/browse/CRIMAPP-792)
[CRIMAPP-792]: https://dsdmoj.atlassian.net/browse/CRIMAPP-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-792 Outgoings content bug

- app/forms/steps/capital/property_owners_form.rb
- spec/forms/steps/capital/property_owners_form_spec.rb
Fixes issue with adding a property owner when percentage ownership is invalid 
See slack thread: https://mojdt.slack.com/archives/C06DFR460F2/p1713965263582019
[CRIMAPP-785](https://dsdmoj.atlassian.net/browse/CRIMAPP-785)
Sadly the indexed errors are not working 😢 don't think this blocks this though 
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/assets/51047911/565560b9-9a71-4760-8c8a-c538aa0ed5f5
1. Navigate to capital assets section and add a property of any type 
2. Enter applicant ownership value under 100% e.g. 80%
3. Select yes to having other owners
4. For additional owner enter ownership e.g. 5%
5. Select option to add another additional owner
6. You should be able to add another owner with no percentage ownership validation errors appearing
7. You should …
> [CRIMAPP-785] Asset ownership bug fix

- app/forms/steps/capital/other_investment_type_form.rb
- app/forms/steps/capital/other_property_type_form.rb
- app/forms/steps/capital/other_saving_type_form.rb
- spec/forms/steps/capital/other_investment_type_form_spec.rb
- spec/forms/steps/capital/other_property_type_form_spec.rb
- spec/forms/steps/capital/other_saving_type_form_spec.rb
Bug reported in qa where an instance of an incomplete property is created and then a user clicks to create another asset and selects save and come back later to the other property type form. Then when they click capital assessment from the task list the app breaks 
This is because an instance of a property with a property type of '' is being created when save and come back later is selected on the other property type form 
This also impacts the other saving type and other investment type forms and fix has been implemented for all forms 
[Slack thread here](https://mojdt.slack.com/archives/C06DFR460F2/p1714055720215749?thread_ts=1714050467.447539&cid=C06DFR460F2)
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/assets/51047911/e5265596-fc2e-4c55-96ce-321e91229009 …
> Do not create record when save and come back later selected

- app/controllers/developer_tools/crime_applications_controller.rb
- app/forms/steps/client/appeal_reference_number_form.rb
- app/forms/steps/client/benefit_type_form.rb
- app/forms/steps/client/details_form.rb
- app/forms/steps/client/has_nino_form.rb
- app/presenters/summary/sections/contact_details.rb
- spec/forms/steps/client/appeal_reference_number_form_spec.rb
- spec/forms/steps/client/benefit_type_form_spec.rb
- spec/forms/steps/client/details_form_spec.rb
- spec/forms/steps/client/has_nino_form_spec.rb
Resets `has_benefit_evidence`  if a user 
1. User selects None for Passporting benefit
2. User updates DoB to be u18
3. User changes case type to Appeal no changes (i.e. there is an appeal_reference_number present)
Reset `will_enter_nino` if:
1. NINO is subsequently entered
2. User updates DoB to be u18 and/or client's last name
3. User changes case type to Appeal no changes (i.e. there is an appeal_reference_number present)
User changes case type to Appeal no changes, all client details are reset if the question is no longer applicable. This affects
Residence type, Home address, Correspondence address, telephone number, nino, benefit type and other applicable attributes
[CRIMAPP-799](https://dsdmoj.atlassian.net/browse/CRIMAPP-799)
Test the scenarios listed in the above description …
> [CRIMAPP-799] Reset attributes when form answers updated

- app/forms/steps/dwp/confirm_result_form.rb
- spec/forms/steps/dwp/confirm_result_form_spec.rb
Set 'benefit_type' to 'none' if provider confirms DWP result "DWP records show that your client does not receive a passporting benefit" is correct.
Previously the provider was able to proceed, with the applicant benefit_type set to a passporting benefit.
[CRIMAPP-809](https://dsdmoj.atlassian.net/browse/CRIMAPP-809)
[CRIMAPP-809]: https://dsdmoj.atlassian.net/browse/CRIMAPP-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Redirect to client/benefit_type after dwp fail is confirmed by provider

- app/controllers/steps/submission/declaration_controller.rb
- app/forms/steps/submission/review_form.rb
- app/models/concerns/type_of_means_assessment.rb
- app/models/crime_application.rb
- app/validators/application_fulfilment_validator.rb
- app/validators/client_details/answers_validator.rb
- app/validators/sections_completeness_validator.rb
- app/views/steps/submission/review/edit.html.erb
- spec/controllers/steps/submission/declaration_controller_spec.rb
- spec/forms/steps/submission/review_form_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/validators/application_fulfilment_validator_spec.rb
- spec/validators/client_details/answers_validator_spec.rb
- spec/validators/sections_completeness_validator_spec.rb
Skip means assessment when nino forthcoming
Submission/declaration redirects to submission/review unless all sections complete
Extract section completeness validations from the fulfilment validator
[CRIMAPP-818](https://dsdmoj.atlassian.net/browse/CRIMAPP-818)
This PR introduces a behaviour change with submission validation. Previously section completeness was combined with fulfilment validation. When showing incomplete sections on submission/review was introduced it caused a regression in existing fulfilment validation handling for the nino. This pr separates section completeness validation from fulfilment_validation and only undertakes section completness validation on submission/review and fulfilment_validation on submission/declaration.
Section completness validation for fulfilment is …
> CRIMAPP-818 Skip means assessment when NINO forthcoming

- app/models/concerns/type_of_means_assessment.rb
- app/services/passporting/means_passporter.rb
- app/validators/passporting_benefit_check/answers_validator.rb
- spec/services/passporting/means_passporter_spec.rb
- spec/validators/passporting_benefit_check/answers_validator_spec.rb
Returned applications can become passported.
We consider will_enter_nino complete if we already know applicant in custody.
[CRIMAPP-841](https://dsdmoj.atlassian.net/browse/CRIMAPP-841)
[CRIMAPP-820](https://dsdmoj.atlassian.net/browse/CRIMAPP-820)
See ticket
[CRIMAPP-841]: https://dsdmoj.atlassian.net/browse/CRIMAPP-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-820]: https://dsdmoj.atlassian.net/browse/CRIMAPP-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix task list for returned applications

- app/services/adapters/structs/applicant.rb
- app/services/adapters/structs/crime_application.rb
- spec/services/adapters/structs/applicant_spec.rb
- spec/services/adapters/structs/crime_application_spec.rb
Set passporting_benefit based on means_passport on rehydration.
> Infer passporting_benefit on rehydration

- app/validators/passporting_benefit_check/answers_validator.rb
- spec/models/crime_application_spec.rb
- spec/validators/passporting_benefit_check/answers_validator_spec.rb
Fixes issue with task list for appeal no changes and u18 apps where the validator was marking the benefit type as incomplete when it was not asked for these application types
> Fix tasklist issues for u18 and appeal no changes apps

- app/forms/steps/income/employment_status_form.rb
- app/services/evidence/rules/20240426012343_self_employed.rb
- app/value_objects/employment_status.rb
- config/locales/en/helpers.yml
- config/locales/en/summary.yml
- spec/forms/steps/income/employment_status_form_spec.rb
- spec/services/evidence/rules/20240425220057_salaried_employee_spec.rb
- spec/services/evidence/rules/20240426012343_self_employed_spec.rb
- spec/value_objects/employment_status_spec.rb
Remove three checkbox options and update content.
I haven't changed the routing yet (in the Figma if you select `Employed` then you continue down the `Income assessment` route) this will be updated later on when the rest of the Employed journey is actually available. For the time being I think it makes sense to keep the routing the same as it is currently i.e. if you select 'Employed or self-employed' then you are redirected to the 'Please use eForms' page.
[CRIMAPP-859](https://dsdmoj.atlassian.net/browse/CRIMAPP-859)
Navigate to the `Employed Status` page.  Check that the content, checkboxes and error messages are correct.
[CRIMAPP-859]: https://dsdmoj.atlassian.net/browse/CRIMAPP-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-859 Update employment status page

- app/models/concerns/type_of_means_assessment.rb
- app/presenters/summary/sections/base_section.rb
- app/presenters/tasks/base_task.rb
- app/presenters/tasks/income_assessment.rb
- app/presenters/tasks/passporting_benefit_check.rb
- app/services/decisions/case_decision_tree.rb
- app/validators/passporting_benefit_check/answers_validator.rb
- spec/models/concerns/type_of_means_assessment_spec.rb
- spec/models/crime_application_spec.rb
- spec/presenters/tasks/base_task_spec.rb
- spec/presenters/tasks/income_assessment_spec.rb
- spec/presenters/tasks/passporting_benefit_check_spec.rb
- spec/services/decisions/case_decision_tree_spec.rb
- spec/validators/passporting_benefit_check/answers_validator_spec.rb
Validate passporting benefit check based on outcome not answers.
Also shifts testing details of TypeOfMeansAssessment to the concern.
Uses the answer validator for completed and not_applicable  status in the task list, in preparation for using the same logic to decide which answers are displayed/submitted to the datastore.
[CRIMAPP-891](https://dsdmoj.atlassian.net/browse/CRIMAPP-891)
See steps in ticket
[CRIMAPP-891]: https://dsdmoj.atlassian.net/browse/CRIMAPP-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-891 Unable to submit because passporting benefit section appears incorrectly incomplete

- app/controllers/steps/income/client/employment_income_controller.rb
- app/forms/steps/income/client/employment_income_form.rb
- app/models/income_payment.rb
- app/services/decisions/income_decision_tree.rb
- app/value_objects/before_or_after_tax.rb
- app/value_objects/income_payment_type.rb
- app/views/steps/income/client/employment_income/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/income/client/employment_income_controller_spec.rb
- spec/forms/steps/income/client/employment_income_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Add the new page 'Your client's employment income' which follows the `has_savings` page. 
This page is currently behind the employed journey feature flag. 
[CRIMAPP-867](https://dsdmoj.atlassian.net/browse/CRIMAPP-867)
This page is behind a feature flag but is also not accessible via the flow yet (see [CRIMAPP-863](https://dsdmoj.atlassian.net/browse/CRIMAPP-863)). Start a new application. When you get to the `employment_status` page, remove the end of the URL `what_is_clients_employment_status` and replace it with `client/employment_income`. You should now be on the new client Employment Income page. If you continue from this page, you should be on the 'Which of these payments does your client get?' page. 
[CRIMAPP-867]: https://dsdmoj.atlassian.net/browse/CRIMAPP-867?atlOrigin=eyJpIjoiNW …
> CRIMAPP-867 Add employment income page

- app/controllers/steps/dwp/partner_benefit_type_controller.rb
- app/forms/steps/dwp/partner_benefit_type_form.rb
- app/models/applicant.rb
- app/models/partner.rb
- app/models/person.rb
- app/services/decisions/dwp_decision_tree.rb
- app/views/steps/dwp/partner_benefit_type/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- config/settings.yml
- spec/controllers/steps/dwp/partner_benefit_type_controller_spec.rb
- spec/forms/steps/dwp/partner_benefit_type_form_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
Adds screen to select partners benefit type 
Also updates routing of related screens
[CRIMAPP-889](https://dsdmoj.atlassian.net/browse/CRIMAPP-889)
To test the screen itself 
1. Start an application and fill in client details and navigate to `/steps/dwp/partner_benefit_type `
2. Verify the validation is in place when no option is selected and when no jsa date is inputted 
3. Select an option and select save and continue and verify you are able to continue to another screen 
To test the routing 
1. Start an application and select yes to having a partner. 
2. You will be shown the partner exit screen but you can use the url to navigate to the task list to begin the application (`/edit`)
3. Create a over 18 client, summary only application where the client does not have a nino or a …
> [CRIMAPP-889] Add partner benefit type screen

- app/presenters/task_list/collection.rb
- app/presenters/task_list/task.rb
- app/views/crime_applications/edit.html.erb
- spec/presenters/task_list/collection_spec.rb
Task list only counts applicable tasks when reporting progress.
[CRIMAPP-915](https://dsdmoj.atlassian.net/browse/CRIMAPP-915)
[CRIMAPP-915]: https://dsdmoj.atlassian.net/browse/CRIMAPP-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-915 Task list only includes applicable sections in total count

- app/services/decisions/income_decision_tree.rb
- config/locales/en/helpers.yml
- spec/services/decisions/income_decision_tree_spec.rb
This PR updates the routing to redirect to the employed loop.
Preconditions: 
1. They have selected only 'Employed' on the employment status page
2. The employment journey feature flag is on
If they above conditions are true, then you should be redirected to the 'Employer details' page immediately after answering 'Yes' on any of the following pages:
-  Is your client’s annual income more than £12475 a year before tax?
- Does your client have any income, savings or assets under a restraint or freezing order?
- Does your client own their home, or any other land or property?
- Does your client have any savings or investments?
If you answer 'No' the flow continues as before. 
If the client is not employed AND/OR the feature flag is not enabled, the flow stays the same as before. …
> CRIMAPP-863 Update routing for employed journey

- app/services/decisions/submission_decision_tree.rb
- app/validators/application_fulfilment_validator.rb
- spec/services/decisions/submission_decision_tree_spec.rb
Fix bug where Nino was incorrectly being required when benefit_type nil.
Also fixes a regression where applicants without NINO and not in custody could access the declaration page from the task list.
[CRIMAPP-917](https://dsdmoj.atlassian.net/browse/CRIMAPP-917)
See ticket
> CRIMAPP-917 Nino not required when passported on age

- Gemfile
- Gemfile.lock
`ownership_type` was previously a required field in the schema which was breaking in progress applications 
Fixes sentry error: https://mojdt.slack.com/archives/C056U956ESH/p1716307797032809
> Update schema to v1.1.3

- app/controllers/steps/income/client/self_assessment_tax_bill_controller.rb
- app/forms/steps/income/client/self_assessment_tax_bill_form.rb
- app/models/outgoings_payment.rb
- app/services/decisions/income_decision_tree.rb
- app/value_objects/outgoings_payment_type.rb
- app/views/steps/income/client/self_assessment_tax_bill/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- db/migrate/20240516140643_add_applicant_self_assessment_tax_bill_to_income.rb
- db/schema.rb
- spec/controllers/steps/income/client/self_assessment_tax_bill_controller_spec.rb
- spec/forms/steps/income/client/self_assessment_tax_bill_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/value_objects/outgoings_payment_type_spec.rb
Add the page 'Does your client pay a Self Assessment tax bill received in the last 2 years?'. This page follows on from the shopping basket page which is in progress, so does not currently exist in the flow, but can be accessed directly via the URL. 
[CRIMAPP-873](https://dsdmoj.atlassian.net/browse/CRIMAPP-873)
Proceed to the employment status page. Change the URL ending to `/client/self_asssessment_tax_bill`
[CRIMAPP-873]: https://dsdmoj.atlassian.net/browse/CRIMAPP-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-873 Add client self assessment tax bill page

- app/models/crime_application.rb
- app/presenters/tasks/base_task.rb
- app/presenters/tasks/capital_assessment.rb
- app/presenters/tasks/client_details.rb
- app/presenters/tasks/declaration.rb
- app/presenters/tasks/more_information.rb
- app/presenters/tasks/review.rb
- app/validators/client_details/answers_validator.rb
- spec/presenters/tasks/capital_assessment_spec.rb
- spec/presenters/tasks/client_details_spec.rb
- spec/presenters/tasks/declaration_spec.rb
- spec/presenters/tasks/more_information_spec.rb
- spec/presenters/tasks/review_spec.rb
- spec/validators/client_details/answers_validator_spec.rb
The 'Review the application’ task cannot be started until all required sections have been completed.
Also, only mark 'more information' task as completed if more information has been provided when answered 'yes'.
[CRIMAPP-937](https://dsdmoj.atlassian.net/browse/CRIMAPP-937)
Previously, if an application was Means Passported or if the means assessment had started, a provider could navigate to the ‘Review the application’ page from the Task List.
However, UCD has confirmed that this is not the desired behavior. The ‘Review the application’ task should be marked as ‘cannot yet start’ until all required sections have been completed. This means that all prior sections, except for ‘Supporting evidence,’ must be marked as either ‘complete’ or ‘not applicable’.
Check the ‘Review the application’ …
> CRIMAPP-937 review task locked until other tasks fulfilled

- app/controllers/concerns/steps/income/client/employment_update_step.rb
- app/controllers/steps/income/client/employer_details_controller.rb
- app/controllers/steps/income/client/employment_details_controller.rb
- app/controllers/steps/income/client/employments_controller.rb
- app/controllers/steps/income/client/employments_summary_controller.rb
- app/forms/steps/income/client/employments_summary_form.rb
- app/models/deduction.rb
- app/models/employment.rb
- app/presenters/summary/components/employment.rb
- app/presenters/summary/sections/employments.rb
- app/services/decisions/income_decision_tree.rb
- app/validators/deductions_validator.rb
- app/value_objects/income_payment_type.rb
- app/views/steps/income/client/employments/confirm_destroy.html.erb
- app/views/steps/income/client/employments_summary/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- config/routes.rb
- db/schema.rb
- spec/controllers/steps/income/client/deductions_controller_spec.rb
- spec/controllers/steps/income/client/employments_controller_spec.rb
- spec/controllers/steps/income/client/employments_summary_controller_spec.rb
- spec/forms/steps/income/client/employments_summary_form_spec.rb
- spec/models/deduction_spec.rb
- spec/models/employment_spec.rb
- spec/presenters/summary/components/employment_spec.rb
- spec/presenters/summary/sections/employments_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Implement: Employment Loop 
- Add Employment
- Edit Employment
- Remove Employment
[CRIMAPP-871](https://dsdmoj.atlassian.net/browse/CRIMAPP-871)
> [!NOTE]  
> Redirects to 'Employment Status ' page if all employments are deleted from shopping basket
Start the employment journey and add/update/remove employments from shopping basket
[CRIMAPP-871]: https://dsdmoj.atlassian.net/browse/CRIMAPP-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crimapp 871 employed income shopping basket for jobs loop

- app/controllers/crime_applications_controller.rb
- app/presenters/tasks/client_details.rb
- app/services/decisions/client_decision_tree.rb
- config/settings.yml
- spec/presenters/tasks/client_details_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
Switch on no means tested feature flag, and show page
Move has partner page if passported partner ff enabled
If has partner page before tasklist, non means q shows before that
If has partner page in new position (after has nino) non means is first question
**Scenario 1 ppt partner on, non means tested on**
Start a new application
First page is now tasklist
Click Client details, first page is means test
Answer yes to means test q, continue through, as usual
Go back, answer no to means tested q
Continue to complete app
Check:
Datestamp received after client details
No case type asked
No DWP check 
No means questions asked
**Scenario 2 ppt partner off, non means tested on**
Turn off passported partner feature flag - restart server
Start a new application
See Means tested q  - answer yes - …
> Switch on non means tested

- config/locales/en/summary.yml
Fix translation for Employment status
https://dsdmoj.atlassian.net/browse/CRIMAPP-959
> CRIMAPP-959 - Employment status missing from CYA

- app/presenters/summary/html_presenter.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/requests/employments_summary_spec.rb
Add employments(jobs) sections to CYAs page
https://dsdmoj.atlassian.net/browse/CRIMAPP-877
Employments: Shopping basket Page URL
http://localhost:3000/applications/:id/steps/income/client/add_employments
Check your answers page URL
http://localhost:3000/applications/:id/steps/income/check_your_answers_income
> CRIMAPP-877 - Add employments to CYA's page

- app/controllers/crime_applications_controller.rb
- app/services/decisions/client_decision_tree.rb
- app/services/decisions/dwp_decision_tree.rb
- config/settings.yml
- spec/forms/steps/income/client/other_work_benefits_form_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
- Routes to the task list when an application started if the partner journey is enabled and routes to the does client have partner page if the partner journey is not enabled
- Removes partner journey feature flags that are no longer required 
- Sets non means tested ff to false on staging to allow for regression testing on staging and prepare for deployment
Toggle the partner journey feature flag and test the routing is as expected for different application types (means assessed application, non means assessed application, u18 application, appeal no changes etc..)
> Update partner routing

- app/forms/steps/income/client/other_work_benefits_form.rb
- app/forms/steps/income/client/self_assessment_tax_bill_form.rb
Due to the order of actions in the persist method, it would return false if 'No' was selected on the page, meaning that the user does not progress to the next page. This fixes that issue for both the self assessment tax form page and other work benefits page. 
[CRIMAPP-965](https://dsdmoj.atlassian.net/browse/CRIMAPP-965)
[CRIMAPP-965]: https://dsdmoj.atlassian.net/browse/CRIMAPP-965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-965 Fix self assessment tax form bug

- app/models/concerns/type_of_means_assessment.rb
- app/services/decisions/income_decision_tree.rb
- spec/services/decisions/income_decision_tree_spec.rb
Fix routing for both employed journey and unemployed journey, for the 'Does your client have any income, savings or assets under a restraint or freezing order?' page
[CRIMAPP-960](https://dsdmoj.atlassian.net/browse/CRIMAPP-960)
EMPLOYED JOURNEY:
Employed and feature flag is on:
- If they select 'Yes' they should go to 'Who does your client work for'
- If they select 'No' AND case type is not summary only or committal they should go to the property page.
- If they select 'No' AND case type is summary only or committal they should go to the 'Your client's employment income' page
UNEMPLOYED JOURNEY:
Not working OR feature flag not on:
- If they select 'Yes' they should go to 'Income payments'
- If they select 'No' AND case type is not summary only or committal they should go to the property …
> CRIMAPP-960 fix routing for frozen assets page

- Gemfile
- Gemfile.lock
- app/forms/steps/capital/savings_form.rb
- app/models/saving.rb
- app/presenters/summary/components/saving.rb
- app/serializers/submission_serializer/definitions/saving.rb
- app/views/steps/capital/savings/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/summary.yml
- db/migrate/20240605084904_add_are_partner_wages_paid_into_account_to_savings.rb
- db/schema.rb
- spec/presenters/summary/components/saving_spec.rb
- spec/serializers/submission_serializer/definitions/saving_spec.rb
Asks if partner's wages or benefits are paid into a saving account if the partner is included in the means assessment.
[CRIMAPP-945](https://dsdmoj.atlassian.net/browse/CRIMAPP-945)
Schema gem needs updating to official release once merged: https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/156
1. Complete the process of saving an applicant with a partner who has a conflict of interest.
2. Confirm that the question “Are the partner's wages paid into the savings account?” is not asked.
3. Confirm that the savings entry is valid.
4. Update the partner's details to remove the conflict of interest.
5. Confirm that the savings entry is no longer valid on the summary page.
6. Navigate to the savings entry.
7. Confirm that the question “Are the partner's wages paid…” is …
> CRIMAPP-945 are partner wages paid into savings

- app/forms/concerns/steps/applicant_and_partner.rb
- app/forms/concerns/steps/ownership_confirmation.rb
- app/forms/steps/income/client_owns_property_form.rb
- app/forms/steps/income/has_savings_form.rb
- app/forms/steps/income/income_before_tax_form.rb
- app/forms/steps/income/manage_without_income_form.rb
- app/helpers/steps_helper.rb
- app/presenters/summary/components/base_answer.rb
- app/presenters/summary/sections/income_details.rb
- app/presenters/summary/sections/other_income_details.rb
- app/services/adapters/structs/crime_application.rb
- app/value_objects/subject_type.rb
- app/views/steps/income/client_owns_property/edit.html.erb
- app/views/steps/income/has_savings/edit.html.erb
- app/views/steps/income/income_before_tax/edit.html.erb
- app/views/steps/income/manage_without_income/edit.html.erb
- config/locales/en.rb
- config/locales/en.yml
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- spec/helpers/steps_helper_spec.rb
- spec/presenters/summary/components/base_answer_spec.rb
- spec/presenters/summary/sections/dependants_spec.rb
- spec/presenters/summary/sections/income_details_spec.rb
- spec/presenters/summary/sections/other_income_details_spec.rb
Update income pages where they refer to 'your client and their partner' or 'your client or their partner'.
[CRIMAPP-999](https://dsdmoj.atlassian.net/browse/CRIMAPP-999)
This PR introduces changes to handle plural subjects for the first time. When the subject is `ApplicantAndPartner`, translations will automatically have a count of 2; otherwise, the count will be 1. Additionally, a new type, `SubjectType`, is introduced and used in place of `OwnershipType`.
[CRIMAPP-999]: https://dsdmoj.atlassian.net/browse/CRIMAPP-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP 999 add applicant AND partner text to income

- app/controllers/steps/income/income_payments_controller.rb
- app/forms/steps/income/income_payment_fieldset_form.rb
- app/forms/steps/income/income_payments_form.rb
- app/value_objects/income_payment_type.rb
- app/value_objects/outgoings_payment_type.rb
Create a separate subset of IncomePaymentType for other income payment types that do not include employment-related types (work_benefit and employment). This prevents employment payment type categories from appearing on the income payments page and in the income payments section on the CYA and RTA pages, and fixes the translation missing error. 
Also updates the schema version.
This needs to be merged AFTER https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/886 , then tests should also be passing 
[CRIMAPP-968](https://dsdmoj.atlassian.net/browse/CRIMAPP-968)
[CRIMAPP-968]: https://dsdmoj.atlassian.net/browse/CRIMAPP-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-968 update income payment type

- app/validators/passporting_benefit_check/answers_validator.rb
- spec/validators/passporting_benefit_check/answers_validator_spec.rb
Updates the passporting benefit check answers validator to be partner aware 
[CRIMAPP-896](https://dsdmoj.atlassian.net/browse/CRIMAPP-896)
Test the scenarios shown [here in figma](https://www.figma.com/design/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=13705-65710&t=QLp9kyj63Y6lJAIG-0)
[CRIMAPP-896]: https://dsdmoj.atlassian.net/browse/CRIMAPP-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-896] Add partner to benefit check task list validation

- Gemfile
- Gemfile.lock
- app/forms/steps/income/client/self_assessment_tax_bill_form.rb
- db/migrate/20240606154545_move_applicant_self_assessment_tax_bill_column.rb
- db/schema.rb
- spec/forms/steps/income/client/self_assessment_tax_bill_form_spec.rb
- As `Self Assessment tax bill` is an outgoing payment, it must have an entry in `outgoings` table
- Move column `applicant_self_assessment_tax_bill` from `income. applicant_self_assessment_tax_bill` to `outgoings. applicant_self_assessment_tax_bill`
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
> [!NOTE]  
> Initially we were creating outgoings payment of {type: "OutgoingsPayment"} and updating `income. applicant_self_assessment_tax_bill`, which is wrong. 
> Outgoing payments should be associated with outgoings
http://localhost:3000/applications/:id/steps/income/client/self_assessment_client
> CRIMAPP-875 - Move column 'applicant_self_assessment_tax_bill'

- app/controllers/steps/capital/partner_trust_fund_controller.rb
- app/forms/steps/capital/partner_trust_fund_form.rb
- app/models/capital.rb
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/partner_trust_fund.rb
- app/serializers/submission_serializer/sections/capital_details.rb
- app/services/adapters/structs/capital_details.rb
- app/services/adapters/structs/crime_application.rb
- app/services/decisions/capital_decision_tree.rb
- app/validators/capital_assessment/answers_validator.rb
- app/views/steps/capital/partner_trust_fund/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- config/routes.rb
- db/schema.rb
- spec/controllers/steps/capital/partner_trust_fund_controller_spec.rb
- spec/forms/steps/capital/partner_trust_fund_form_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/partner_trust_fund_spec.rb
- spec/serializers/submission_serializer/sections/capital_details_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/validators/capital_assessment/answers_validator_spec.rb
Add partner trust fund page
Add to serializer, struct, CYA, validator
https://dsdmoj.atlassian.net/browse/CRIMAPP-953
This does not cover changing Partner from YES to NO - resetting etc needs to be done as a wider piece.
Start an application, 
Case type Indictable
Partner Yes
Income £12475 Yes
Continue to Capital
Check errors when nothing select
Check errors when Yes selected and no numbers input
Complete page, check shows correctly on Capital CYA
Complete App, check shows correctly on app CYA
> [CRIMAPP-953] Partner trust fund

- app/models/concerns/type_of_means_assessment.rb
- app/presenters/summary/components/property.rb
- app/presenters/summary/sections/base_section.rb
- app/presenters/summary/sections/dependants.rb
- app/presenters/summary/sections/other_income_details.rb
- app/views/steps/income/income_before_tax/edit.html.erb
- app/views/steps/submission/shared/_section.html.erb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- spec/forms/steps/capital/other_investment_type_form_spec.rb
- spec/models/concerns/type_of_means_assessment_spec.rb
- spec/presenters/summary/components/investment_spec.rb
- spec/presenters/summary/components/national_savings_certificate_spec.rb
- spec/presenters/summary/components/property_spec.rb
- spec/presenters/summary/components/saving_spec.rb
- spec/presenters/summary/sections/dependants_spec.rb
- spec/presenters/summary/sections/dwp_details_spec.rb
- spec/presenters/summary/sections/income_details_spec.rb
- spec/presenters/summary/sections/other_income_details_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
- spec/services/dwp/benefit_check_status_service_spec.rb
- spec/services/passporting/means_passporter_spec.rb
- spec/validators/capital_assessment/answers_validator_spec.rb
- spec/validators/employment_details/answers_validator_spec.rb
- spec/validators/outgoings_assessment/answers_validator_spec.rb
Update summary card labels to the latest values.
Also fixes an issue where final submission/review and submitted applications where not correctly understanding if partner should be included in means assessment.
[CRIMAPP-993](https://dsdmoj.atlassian.net/browse/CRIMAPP-993)
[CRIMAPP-993]: https://dsdmoj.atlassian.net/browse/CRIMAPP-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-993 summary cards use latest content

- Gemfile
- Gemfile.lock
- app/controllers/steps/income/client/self_assessment_tax_bill_controller.rb
- app/forms/steps/income/client/self_assessment_tax_bill_form.rb
- app/models/employments_payment.rb
- app/models/income.rb
- app/models/outgoings_payment.rb
- app/presenters/summary/sections/self_assessment_tax_bill.rb
- app/serializers/submission_serializer/sections/income_details.rb
- app/serializers/submission_serializer/sections/outgoings_details.rb
- app/services/adapters/structs/income_details.rb
- app/value_objects/outgoings_payment_type.rb
- app/views/steps/income/client/self_assessment_tax_bill/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/summary.yml
- db/migrate/20240612111633_add_self_assessment_tax_bill_columns_to_incomes.rb
- db/schema.rb
- spec/forms/steps/income/client/self_assessment_tax_bill_form_spec.rb
- spec/models/employments_payment_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/self_assessment_tax_bill_spec.rb
- spec/serializers/submission_serializer/sections/income_details_spec.rb
- spec/serializers/submission_serializer/sections/outgoings_details_spec.rb
- spec/services/adapters/structs/income_details_spec.rb
- spec/value_objects/outgoings_payment_type_spec.rb
- Remove s**elf assessment tax bill** from an outgoings payment.
- Add **self assessment tax bill** attributes to income
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
> [!NOTE]  
> Here is a confluence [doc](https://dsdmoj.atlassian.net/wiki/spaces/CRIMAP/pages/4940759132/Self+Assessment+tax+bill) to support this change
**Page: Check your enswers**
**Page: Review the application** 
Start employment journey
> CRIMAPP-875- Refactor self-assessment-tax-bill

- app/forms/steps/outgoings/council_tax_form.rb
- spec/forms/steps/outgoings/council_tax_form_spec.rb
Fix missing parter next on council tax form.
[CRIMAPP-1038](https://dsdmoj.atlassian.net/browse/CRIMAPP-1038)
[CRIMAPP-1038]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make sure crime_application is set on council_tax form

- app/forms/steps/evidence/upload_form.rb
- config/locales/en/evidence.yml
Update outgoings evidence for partner.
Because in outgoings partner and applicant are combined in the question, here we update the heading for the client outgoings prompt to include "and the partner" if partner is included in means assessment. The is only one evidence trigger.
> CRIMAPP-991 outoings evidence includes 'and partner' in heading 

- app/models/applicant.rb
- app/models/partner.rb
- app/services/evidence/rules/20240426020839_pension_income.rb
- app/services/evidence/rules/20240426022536_maintenance_income.rb
- app/services/evidence/rules/20240426024826_interest_and_investments.rb
- app/services/evidence/rules/20240426030038_rental_income.rb
- app/services/evidence/rules/20240426030754_any_other_income.rb
- config/locales/en/evidence.yml
- spec/services/evidence/rules/20240426020839_pension_income_spec.rb
- spec/services/evidence/rules/20240426022536_maintenance_income_spec.rb
- spec/services/evidence/rules/20240426024826_interest_and_investments_spec.rb
- spec/services/evidence/rules/20240426030038_rental_income_spec.rb
- spec/services/evidence/rules/20240426030754_any_other_income_spec.rb
Add partner evidence checks for income payments
- pension
- maintenance
- investments
- other
- rent
> CRIMAPP-991 partner income evidence rules

- app/services/evidence/rules/20240426032048_trust_fund.rb
- spec/services/evidence/rules/20240426032048_trust_fund_spec.rb
Require evidence of partner's trust fund.
> CRIMAPP-991 partner trust fund evidence

- app/forms/steps/partner/details_form.rb
- app/presenters/summary/components/property.rb
- app/presenters/summary/sections/codefendants.rb
- config/locales/en/summary.yml
- spec/forms/steps/partner/details_form_spec.rb
- spec/presenters/summary/components/property_spec.rb
- spec/presenters/summary/sections/codefendants_spec.rb
Resets partner dwp details when the partner's last name or dob are updated
Also fixes a couple of bugs spotted: 
- Missing co defendants summary section when there are no codefendants 
- Assets partner percentage owned row not displaying
[CRIMAPP-1040](https://dsdmoj.atlassian.net/browse/CRIMAPP-1040)
[CRIMAPP-1039](https://dsdmoj.atlassian.net/browse/CRIMAPP-1039)
[CRIMAPP-1040]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1039]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1040] Reset partner dwp details when partner details updated

- Gemfile
- Gemfile.lock
- app/serializers/submission_serializer/definitions/partner.rb
- app/services/datastore/application_rehydration.rb
- config/locales/en/summary.yml
- spec/serializers/submission_serializer/sections/client_details_spec.rb
Introduces attribute `is_included_in_means_assessment` to the partner to facilitate display of the correct content subject in review depending on whether the partner was part of the means assessment 
[CRIMAPP-992](https://dsdmoj.atlassian.net/browse/CRIMAPP-992)
[CRIMAPP-992]: https://dsdmoj.atlassian.net/browse/CRIMAPP-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-992] Add partner content to review

- app/presenters/summary/sections/partner_income_benefits_details.rb
- app/presenters/summary/sections/partner_income_payments_details.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/partner_income_benefits_details_spec.rb
- spec/presenters/summary/sections/partner_income_payments_details_spec.rb
Fixes a bug where the partner income payment and benefits sections were displaying when the question hadn't been asked
> Amend display logic for partner income payments and benefits sections

- app/forms/steps/partner/nino_form.rb
- spec/forms/steps/partner/nino_form_spec.rb
- spec/models/concerns/type_of_means_assessment_spec.rb
Resets partner dwp attributes if partner nino details are updated
[CRIMAPP-1035](https://dsdmoj.atlassian.net/browse/CRIMAPP-1035)
[CRIMAPP-1035]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1035] Reset partner dwp attributes if nino changed

- app/forms/steps/client/has_partner_form.rb
- spec/forms/steps/client/has_partner_form_spec.rb
The client relationship status attribute was being reset every time the has partner form was saved
A guard clause was added to the persist method to check whether the has partner value had been updated before performing any updates
[CRIMAPP-1032](https://dsdmoj.atlassian.net/browse/CRIMAPP-1032)
[CRIMAPP-1032]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1032] Retain client relationship status value

- app/presenters/summary/sections/partner_details.rb
- app/validators/client_details/answers_validator.rb
- app/validators/sections_completeness_validator.rb
When feature flags are set to production values, certain elements of partner journey (answer playback views, and validators in particular) cause issues with viewing and submitting an application.
Add guard clauses to check partner journey is enabled to ensure we do not cause a regression should we deploy to prod
https://dsdmoj.atlassian.net/browse/CRIMAPP-1051
Set feature flags to prod values (particularly partner journey)
Restart Apply server
Submit an application (try some varieties)
> Add guard clauses for partner journey

- app/presenters/summary/sections/other_outgoings_details.rb
- spec/presenters/summary/sections/other_outgoings_details_spec.rb
When feature flags are set to production values, outgoings answer playback view cause issues with viewing and submitting an application.
Only display partner 40% tax if there is an included partner
Set feature flags to prod values (particularly partner journey)
Restart Apply server
Submit an application (try some varieties)
> Only display partner 40% tax if there is an included partner

- app/controllers/steps/income/business_type_controller.rb
- app/forms/steps/income/business_type_form.rb
- app/lib/errors.rb
- app/models/applicant.rb
- app/models/business.rb
- app/models/crime_application.rb
- app/models/partner.rb
- app/services/decisions/income_decision_tree.rb
- app/services/decisions/self_employed_income_decision_tree.rb
- app/value_objects/business_type.rb
- app/views/steps/income/business_type/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20240617115219_create_businesses.rb
- db/schema.rb
- spec/controllers/steps/income/business_type_controller_spec.rb
- spec/forms/steps/income/business_type_form_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Adds business type for both client and partner.
[CRIMAPP-976](https://dsdmoj.atlassian.net/browse/CRIMAPP-976)
The logic for handling flow when both employed and self employed yet to be determined. Plan to extract subject setting for controllers as pattern evolves.
[CRIMAPP-976]: https://dsdmoj.atlassian.net/browse/CRIMAPP-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-976 Business Type page for Client and Partner

- app/services/evidence/rules/20240425220057_salaried_employee.rb
- app/services/evidence/rules/20240426002316_self_assessed.rb
- app/services/evidence/rules/20240426014955_benefits_in_kind.rb
- spec/services/evidence/rules/20240425220057_salaried_employee_spec.rb
- spec/services/evidence/rules/20240426002316_self_assessed_spec.rb
- spec/services/evidence/rules/20240426014955_benefits_in_kind_spec.rb
Adds the evidence prompts for rules 0a, 2 and 4 (see spreadsheet below)
This is with the exception of the partner triggers for rules 2 and 4 which is awaiting implementation
[CRIMAPP-1022](https://dsdmoj.atlassian.net/browse/CRIMAPP-1022)
[Evidence spreadsheet](https://docs.google.com/spreadsheets/d/1hFVZXo87BhnZ4xUrWubnXjOR0kodN694azBi2y2XstM/edit#gid=764299190)
[CRIMAPP-1022]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1022] Add evidence prompts for employed journey

- app/presenters/summary/sections/base_section.rb
- app/presenters/summary/sections/outgoings_payments_details.rb
- config/locales/en/summary.yml
Fixes subject display for outgoings payments section heading
[CRIMAPP-1086](https://dsdmoj.atlassian.net/browse/CRIMAPP-1086)
[CRIMAPP-1086]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1086] Display correct subject for outgoings payments heading

- app/forms/steps/capital/answers_form.rb
- app/presenters/summary/components/property.rb
- app/presenters/summary/components/saving.rb
- app/views/steps/capital/answers/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/summary.yml
- spec/presenters/summary/components/property_spec.rb
Fixes the following bugs: 
- The capital CYA declaration did not have dynamic text 
- A translation issue with property house types
- The answer for whether the partners wages or benefits are paid into the account for a saving was not displaying on the review page 
[CRIMAPP-1075](https://dsdmoj.atlassian.net/browse/CRIMAPP-1075)
[CRIMAPP-1083](https://dsdmoj.atlassian.net/browse/CRIMAPP-1083)
[CRIMAPP-1090](https://dsdmoj.atlassian.net/browse/CRIMAPP-1090)
Test the scenarios in the linked tickets 
[CRIMAPP-1075]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1083]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> [CRIMAPP-1075, 1083, 1090] CYA and translation bugs

- app/forms/steps/income/income_benefit_fieldset_form.rb
- app/forms/steps/income/income_benefits_form.rb
- app/forms/steps/income/income_payment_fieldset_form.rb
- app/forms/steps/income/income_payments_form.rb
- app/presenters/summary/components/property.rb
- config/locales/en/summary.yml
- spec/forms/steps/income/income_benefits_form_spec.rb
- spec/forms/steps/income/income_payments_form_spec.rb
- spec/forms/steps/income/partner/income_benefits_form_spec.rb
- spec/forms/steps/income/partner/income_payments_form_spec.rb
The income payments and benefits pages for the client were displaying partner payments/benefits as well as the clients. This PR fixes the bug and adds specs
[CRIMAPP-1079](https://dsdmoj.atlassian.net/browse/CRIMAPP-1079)
1. Start an application with a partner and get to the income means assessment section.
2. Go through the screens and enter payment and benefit information for the client and partner 
3. Once you added payment and benefit information for the partner, go back and ensure you cannot see the partner's payment and benefit information on the client payment and benefit forms 
[CRIMAPP-1079]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1079] Display client only income payments/benefits

- app/presenters/summary/sections/partner_details.rb
- app/serializers/submission_serializer/sections/client_details.rb
- app/validators/application_fulfilment_validator.rb
- app/validators/client_details/answers_validator.rb
- app/validators/partner_details/answers_validator.rb
- app/validators/sections_completeness_validator.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/serializers/submission_serializer/sections/client_details_spec.rb
- spec/validators/client_details/answers_validator_spec.rb
- spec/validators/partner_details/answers_validator_spec.rb
- spec/validators/sections_completeness_validator_spec.rb
Fixes bug where you could not submit appeal no changes and under 18 applications due to failing section validation checks on the review your application page 
Also fixes bug where appeal no changes apps where being prevented from being submitted due to means checks in the application fulfilment validator. As appeal no changes apps do not go through means assessment, this check is bypassed
[CRIMAPP-1081](https://dsdmoj.atlassian.net/browse/CRIMAPP-1081)
[CRIMAPP-1074](https://dsdmoj.atlassian.net/browse/CRIMAPP-1074)
Fill in a appeal no changes and u18 application and verify you are able to go past the review page and submit 
[CRIMAPP-1081]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [CRIMAPP-1081] [CRIMAPP-1074] Fix appeal no changes and u18 validation

- app/models/income.rb
- app/services/decisions/income_decision_tree.rb
- spec/models/income_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
The logic for displaying 'How does your client (and their partner) manage with no income?' page did not take employment income into account, meaning that the page would incorrectly display when the client has employment income. This PR fixes that, and should work for both client and partner employment income. 
[CRIMAPP-1062](https://dsdmoj.atlassian.net/browse/CRIMAPP-1062)
1. Process a summary only case
2. Select No to partner
3. Select YES to employed
4. Select yes to > £12475
5. Answer 'Employed and self employed' to go down the jobs loop, and enter an amount > £12475 per year before tax to the wages question
6. Continue with the Income section questions
7. The ‘How does your client manage with no income?’ should not appear - you should get to the Income CYA page without having seen …
> CRIMAPP-1062 fix manage_with_no_income routing for employed journey

- .rubocop.yml
- app/lib/errors.rb
- app/models/concerns/type_of_means_assessment.rb
- app/services/decisions/income_decision_tree.rb
- app/validators/capital_assessment/answers_validator.rb
- app/validators/income_assessment/answers_validator.rb
- app/validators/outgoings_assessment/answers_validator.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/validators/income_assessment/answers_validator_spec.rb
Skip questions when extent of means assessment determined.
Do not require full means assessment when committal for sentencing.
[CRIMAPP-1077](https://dsdmoj.atlassian.net/browse/CRIMAPP-1077)
[CRIMAPP-1033](https://dsdmoj.atlassian.net/browse/CRIMAPP-1033)
The initial phase of the income assessment has four steps: income_before_tax, frozen_income_savings_assets, client_owns_property, and has_savings. These steps primary purpose is to find out if a full means assessment is necessary. This refactor changes the decision tree to make the role of the steps more obvious. After each step, the decision tree checks if the need for a full means assessment is definitively determined. If the determination is still unclear, the process proceeds to the next step in the sequence.
It also fixes a bug …
> CRIMAPP-1077, CRIMAPP-1033

- app/forms/steps/submission/declaration_form.rb
- app/models/crime_application.rb
- app/models/provider.rb
- app/serializers/submission_serializer/sections/provider_details.rb
- app/views/steps/submission/declaration/_initial.html.erb
- app/views/steps/submission/declaration/edit.en.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/forms/steps/submission/declaration_form_spec.rb
- spec/serializers/submission_serializer/application_spec.rb
- spec/serializers/submission_serializer/sections/provider_details_spec.rb
Add partner declaration to declaration page
Shows conditionally if there is a partner
https://dsdmoj.atlassian.net/browse/CRIMAPP-1088
Create an application with a partner (no involvement)
Progress to end of application
See new fields on declaration page
Check errors (no copy in spreadsheet)
Check submits when valid
> Add partner declaration to declaration page

- Gemfile
- Gemfile.lock
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/declarations.rb
- app/serializers/submission_serializer/sections/provider_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/html_presenter_spec.rb
Add declaration details to completed applicaiton view## Link to relevant ticket
https://dsdmoj.atlassian.net/browse/CRIMAPP-1088
Not rehydrating for now
SCENARIO 1:
Create an application on Apply main
Add a partner
Fill in declaration at the end with 'no' and some reason
Submit
Click view completed application
Check the rows show correctly
SCENARIO 2:
Create an application on Apply main
Add a partner
Fill in declaration at the end with 'yes'
Submit
Click view completed application
Check the rows show correctly
SCENARIO 3:
Create an application on Apply main
DO NOT add a partner
Shouldn't see partner declaration on Apply submission
Submit
Click view completed application
Check the rows show correctly
> CRIMAPP-1088 Show declarations on completed applications view

- app/views/steps/income/answers/edit.html.erb
Hide partner heading from income CYA if contrary interest.
[CRIMAPP-1121](https://dsdmoj.atlassian.net/browse/CRIMAPP-1121)
[CRIMAPP-1121]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1121 hide partner heading on income

- app/models/capital.rb
- app/models/concerns/means_ownership_scope.rb
- app/models/crime_application.rb
- app/models/income.rb
- app/models/outgoings.rb
- app/models/person.rb
- spec/models/capital_spec.rb
- spec/models/crime_application_spec.rb
- spec/models/income_spec.rb
- spec/models/outgoings_spec.rb
- spec/support/shared_examples/a_means_ownership_scope.rb
Assets are not owned initially. This pr adds unowned assets to the global scope to fix regression in asset type pages.
[CRIMAPP-1123](https://dsdmoj.atlassian.net/browse/CRIMAPP-1123)
[CRIMAPP-1123]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1123 global scope includes un-owned assets

- app/presenters/summary/sections/partner_employment_details.rb
- app/presenters/summary/sections/partner_premium_bonds.rb
- app/presenters/summary/sections/partner_self_assessment_tax_bill.rb
- app/presenters/summary/sections/partner_trust_fund.rb
- spec/presenters/summary/sections/partner_premium_bonds_spec.rb
- spec/presenters/summary/sections/partner_trust_fund_spec.rb
Capital CYA uses database not json and as such was showing partner details when contrary interest. This PR fixes that.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1115?focusedCommentId=475167
> CRIMAPP-1115 capital CYA hides partner info

- app/serializers/submission_serializer/definitions/partner.rb
- app/services/datastore/application_submission.rb
- app/services/post_submission_application_purger.rb
- app/validators/partner_details/answers_validator.rb
- spec/serializers/submission_serializer/sections/client_details_spec.rb
- spec/services/post_submission_application_purger_spec.rb
Hide partner address questions if changes to partner with contrary interest.
Use application purger on submission to ensure orphaned partner assets are removed.
[CRIMAPP-1124](https://dsdmoj.atlassian.net/browse/CRIMAPP-1124)
[CRIMAPP-1126](https://dsdmoj.atlassian.net/browse/CRIMAPP-1126)
[CRIMAPP-1124]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1126]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1126] remove partner address, and destroy partner assets when changed to conflict

- app/serializers/submission_serializer/sections/capital_details.rb
- spec/serializers/submission_serializer/sections/capital_details_spec.rb
Serialize 'has_no_other_assets' for all applications with any capital details
This question is asked and is required as soon as any capital question is asked (I think!) so needs to be serialized to be stored in ds and shown in review - and therefore make it back to Apply in rehydration if rejected, validator then passes, and no error shown
> CRIMAPP-1124 Serialize 'has_no_other_assets' for all applications with any capital details

- app/services/decisions/income_decision_tree.rb
- spec/services/decisions/income_decision_tree_spec.rb
Route to shopping basket when there are existing employments
https://dsdmoj.atlassian.net/browse/CRIMAPP-1098
> CRIMAPP-1098: Route to shopping basket when there are existing employments

- app/services/decisions/income_decision_tree.rb
- spec/services/decisions/income_decision_tree_spec.rb
Fix partner employment income routing as per 👇 logic.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1001
http://localhost:3000/applications/:id/steps/income/what_is_the_partners_employment_status
> CRIMAPP-1001: Fix partner employment income routing

- Gemfile
- Gemfile.lock
- app/lib/employment_income_payments_calculator.rb
- app/models/concerns/annualized_amount_calculator.rb
- app/models/deduction.rb
- app/models/employment.rb
- app/models/income_payment.rb
- app/serializers/submission_serializer/sections/income_details.rb
- app/services/adapters/structs/income_details.rb
- spec/lib/employment_income_payments_calculator_spec.rb
- spec/serializers/submission_serializer/sections/income_details_spec.rb
Annualise employment income and deductions for income
- below £12,475 (single employment)
- above £12,475 (employments loop)
https://dsdmoj.atlassian.net/browse/CRIMAPP-1095
> [!IMPORTANT]  
> We are not annualising 'other' deductions(deduction_type=='other') as MAAT doesn't need this information
Rails Console
```
crime_application = CrimeApplication.find(:id)
SubmissionSerializer::Application.new( crime_application).generate.as_json["means_details"]["income_details"]
```
You should see 'employment_income_payments' array attribute in payload
> CRIMAPP-1095 Create employed maat schema

- Dockerfile
Delete old CA cert bundle download instruction, replace deprecated MAINTAINER instruction
N/A
> EXPERIMENTAL Remove old CA Bundle instructions, replace MAINTAINER

- app/services/datastore/application_rehydration.rb
Fixes bug when rehydrating an app with no partner
[Link to sentry error alert](https://ministryofjustice.sentry.io/issues/5548400275/?environment=staging&project=4507142444023808&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0) 
[CRIMAPP-1132](https://dsdmoj.atlassian.net/browse/CRIMAPP-1132)
Return a historical application that does not have a partner 
Verify that you are able to rehydrate with no errors and the data is as expected
[CRIMAPP-1132]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1132] Do not rehydrate partner details if there is no partner

- app/models/crime_application.rb
- app/models/income.rb
- app/presenters/summary/sections/income_benefits_details.rb
- app/presenters/summary/sections/income_payments_details.rb
- app/presenters/summary/sections/partner_income_benefits_details.rb
- app/presenters/summary/sections/partner_income_payments_details.rb
- app/services/adapters/structs/crime_application.rb
- app/services/adapters/structs/income_details.rb
- app/services/datastore/application_rehydration.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/income_benefits_details_spec.rb
- spec/presenters/summary/sections/income_payments_details_spec.rb
- spec/presenters/summary/sections/partner_income_benefits_details_spec.rb
- spec/presenters/summary/sections/partner_income_payments_details_spec.rb
Fix issue where datastore amounts were presented as pounds in pence.
Ensure all datastore payments are loaded as ActiveRecord objects rather than structs for IncomePayment or IncomeBenefits rather than struct.
Refactor to makes sure all income payments / benefits are accessed via Income in summary views.
[CRIMAPP-1138](https://dsdmoj.atlassian.net/browse/CRIMAPP-1138)
[CRIMAPP-1138]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1138 initialize payments from dstore as ActiveRecord

- app/services/datastore/application_rehydration.rb
Needs to return partner details even if applicant set` applicant.has_partner` to 'no'
https://dsdmoj.atlassian.net/browse/CRIMAPP-1141
> [!NOTE]  
> Skipping the coverage as [this](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/blob/CRIMAPP-1141-apply-client-only-case-type-indictable-employed-lessthan-12475-when-returned-to-provider/spec/services/datastore/application_rehydration_spec.rb#L457) test needs to be fixed
> CRIMAPP-1141 Apply: client only, case type indictable, employed lessthan 12475, when returned to provider

- app/views/home/index.en.html.erb
- app/views/shared/_eforms_redirect.en.html.erb
Updates start and exit page content ahead of employed release
**Start and exit pages when employed functionality is enabled but self employed is not** 
**Start and exit pages when both employed and self employed functionality is not enabled** 
Set the employed feature flag to true and false and check the correct content appears for the start page and the eforms exit screen (triggered by selecting the employed or self employed option depending on whether employed ff is enabled or not)
> [CRIMAPP-1093] Update start and exit page content

- app/services/decisions/income_decision_tree.rb
- spec/services/decisions/income_decision_tree_spec.rb
When starting the employment loop:
If there are no existing jobs, route to the 'employer details' page.
If there is an incomplete job, route to the 'employer details' page for this job.
If there are existing jobs but all are complete, route to the shopping basket.
[CRIMAPP-1136](https://dsdmoj.atlassian.net/browse/CRIMAPP-1136)
[CRIMAPP-1136]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1136 Fix employed loop incomplete job routing

- app/models/income.rb
- spec/forms/steps/income/client/other_work_benefits_form_spec.rb
- spec/forms/steps/income/partner/other_work_benefits_form_spec.rb
- spec/models/income_spec.rb
- spec/services/evidence/rules/20240426014955_benefits_in_kind_spec.rb
Do not show other employed benefit answer when not required.
[CRIMAPP-1158](https://dsdmoj.atlassian.net/browse/CRIMAPP-1158)
[CRIMAPP-1158]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1158 do not show/send other work benefits if no longer needed

- app/controllers/crime_applications_controller.rb
- app/presenters/summary/sections/other_outgoings_details.rb
- app/presenters/summary/sections/partner_details.rb
- app/presenters/summary/sections/partner_income_benefits_details.rb
- app/presenters/summary/sections/partner_income_payments_details.rb
- app/services/datastore/application_rehydration.rb
- app/services/decisions/capital_decision_tree.rb
- app/services/decisions/client_decision_tree.rb
- app/services/decisions/dwp_decision_tree.rb
- app/services/decisions/income_decision_tree.rb
- app/services/decisions/outgoings_decision_tree.rb
- app/validators/capital_assessment/answers_validator.rb
- app/validators/client_details/answers_validator.rb
- app/validators/income_assessment/answers_validator.rb
- app/validators/outgoings_assessment/answers_validator.rb
- app/validators/sections_completeness_validator.rb
- config/routes.rb
- config/settings.yml
- db/schema.rb
- spec/requests/dashboard_spec.rb
- spec/services/decisions/client_decision_tree_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
Remove has partner feature flag
Because the partner question moved in flow it makes the routing if partner on vs off conditionals really tricky to maintain - especially once combined with non-means.
> Remove has partner feature flag

- config/data/courts.csv
- spec/models/court_spec.rb
Add King's Lynn Magistrates' court to court list
[CRIMAPP-1184](https://dsdmoj.atlassian.net/browse/CRIMAPP-1184)
[CRIMAPP-1184]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1184 add King's Lynn Magistrates' court to court list

- app/models/business.rb
- spec/models/business_spec.rb
Save and come back later uses FormObject#save! which relies on Model, not FormObject, exceptions to prevent saving. Add mode validation to prevent business being created without a business type.
[CRIMAPP-1199](https://dsdmoj.atlassian.net/browse/CRIMAPP-1199)
Bad data will need to be removed from staging after this is deployed.
[CRIMAPP-1199]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Do not create business on save and come back later

- app/validators/sections_completeness_validator.rb
- spec/validators/sections_completeness_validator_spec.rb
Section completeness validator gracefully handles when extent of means is not yet known.
[CRIMAPP-858](https://dsdmoj.atlassian.net/browse/CRIMAPP-858)
[LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-1N](https://ministryofjustice.sentry.io/issues/5559295887/)
[CRIMAPP-858]: https://dsdmoj.atlassian.net/browse/CRIMAPP-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1187 fix submission when means extent unknown

- app/presenters/summary/sections/partner_work_benefits.rb
- app/presenters/summary/sections/work_benefits.rb
- spec/presenters/summary/sections/partner_work_benefits_spec.rb
- spec/presenters/summary/sections/work_benefits_spec.rb
Bug where ‘Other work benefits’ section was not displaying on Apply - CYA and final review screen.
This was when the answer 'no' was selected as the logic was presenting the section if a work benefit payment was present but there is no work benefit payment when the answer selected is no 
[CRIMAPP-1201](https://dsdmoj.atlassian.net/browse/CRIMAPP-1201)
[CRIMAPP-1201]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1201] Fix section display of other work benefits

- app/presenters/summary/sections/supporting_evidence.rb
- spec/presenters/summary/sections/supporting_evidence_spec.rb
Always show evidence card on submission/review
[CRIMAPP-1161](https://dsdmoj.atlassian.net/browse/CRIMAPP-1161)
[CRIMAPP-1161]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-1161 always show evidence card on submission/review

- app/models/concerns/type_of_means_assessment.rb
- spec/forms/steps/capital/other_investment_type_form_spec.rb
- spec/models/concerns/type_of_means_assessment_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/sections/dwp_details_spec.rb
- spec/presenters/summary/sections/other_outgoings_details_spec.rb
- spec/presenters/summary/sections/partner_income_benefits_details_spec.rb
- spec/presenters/summary/sections/partner_income_payments_details_spec.rb
- spec/presenters/summary/sections/passporting_benefit_check_partner_spec.rb
- spec/serializers/submission_serializer/sections/capital_details_spec.rb
- spec/serializers/submission_serializer/sections/income_details_spec.rb
- spec/serializers/submission_serializer/sections/outgoings_details_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/services/decisions/outgoings_decision_tree_spec.rb
- spec/services/decisions/submission_decision_tree_spec.rb
- spec/services/dwp/benefit_check_status_service_spec.rb
- spec/services/passporting/means_passporter_spec.rb
- spec/validators/capital_assessment/answers_validator_spec.rb
- spec/validators/outgoings_assessment/answers_validator_spec.rb
Don't show irrelevant partner declaration section of declarations page if non-means tested even if there is a partner object present (this will not be submitted, and is no longer relevant once type of application is changed to non means)
https://dsdmoj.atlassian.net/browse/CRIMAPP-1207
1. Create an application
2. Is means tested == yes
3. Has partner yes - no involvement in case
4. Return to Is means tested page and change to no
5. Continue through all pages to declaration page
6. Declaration page does not show radios and copy for Partner
> Add non-means check to include partner method

- config/data/courts.csv
- spec/models/court_spec.rb
Add to court list:
Chancery Division
County Court
Court of Protection
Family Court
High Court
https://dsdmoj.atlassian.net/browse/CRIMAPP-1197
Cods are listed as A - as a placeholder for now.
I believe at least 'County Court' 'Family Court' - are catchalls for 'x County Court' or 'y Family Court' where x and y are names of locations. So these I would expect wouldn't really have proper codes given they are not actual names of courts
> Add generic court options

- app/forms/steps/evidence/upload_form.rb
- app/models/crime_application.rb
- app/presenters/tasks/evidence_upload.rb
- app/validators/application_fulfilment_validator.rb
- app/validators/sections_completeness_validator.rb
- app/validators/supporting_evidence/answers_validator.rb
- app/views/steps/evidence/upload/edit.en.html.erb
- config/locales/en/errors.yml
- spec/forms/steps/evidence/upload_form_spec.rb
- spec/presenters/tasks/evidence_upload_spec.rb
- spec/validators/application_fulfilment_validator_spec.rb
- spec/validators/sections_completeness_validator_spec.rb
- spec/validators/supporting_evidence/answers_validator_spec.rb
Adds validation to the evidence upload page, task list, review you application and declaration pages to prevent the submission of applications without the attachment of required evidence when appropriate (see diagram or ticket for  scenarios) 
[CRIMAPP-1170](https://dsdmoj.atlassian.net/browse/CRIMAPP-1170)
Note this does not handle CIFC yet as the work is in progress
Scenarios can be found here:
Test the scenario in the diagram above
[CRIMAPP-1170]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1170] Block submission of app if evidence upload required

- app/services/passporting/means_passporter.rb
- spec/services/passporting/means_passporter_spec.rb
Refactors the means passporter to always calculate an apps passport status regardless of whether the app is resubmitted (with the exception of under 18 applications which need to retain the previous status). This is to prevent inaccuracies in presenting the passporting status when an application is resubmitted and the means passport value has not been updated on resubmission
[CRIMAPP-1195](https://dsdmoj.atlassian.net/browse/CRIMAPP-1195)
The only means passport value that needs to be retained on resubmission is the under 18 status. I did take a look at the benefit check passport but that is recalculated ([see pr](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/838)) 
Requires [datastore](https://github.com/ministryofjustice/laa-criminal-applications-datastore/pu …
> [CRIMAPP-1195] Recalculate means passport value for resubmitted applications

- app/services/evidence/prompt.rb
- config/locales/en/evidence.yml
- spec/services/evidence/prompt_spec.rb
Exempt Non-means applications from evidence.
[CRIMAPP-1208](https://dsdmoj.atlassian.net/browse/CRIMAPP-1208)
[CRIMAPP-1208]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1208 excempt not means tested applications

- app/forms/steps/income/income_payments_form.rb
- app/forms/steps/income/partner/income_payments_form.rb
Fix for an error in production which I couldn't reproduce but has something to do with the Income Payments Validator trying to validate an employment payment type. This validator only runs on the Income Payments form so I think there is no need to validate the employment payment in any case. 
This fix skips the employment type.
> Exclude employment type from income payments validator

- app/models/income.rb
- app/presenters/summary/sections/other_income_details.rb
- spec/controllers/steps/income/manage_without_income_controller_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
Show 'OtherIncomeDetails' section if sum of the following payments  is 0
- income_payments
- income_benefits
- employments_total
[CRIMAPP-1110](https://dsdmoj.atlassian.net/browse/CRIMAPP-1110)
[CRIMAPP-1110]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1110: Update CYA page  after changing income information

- app/services/adapters/structs/capital_details.rb
- spec/services/adapters/structs/capital_details_spec.rb
Capital details adapter converts amounts to Money.
[CRIMAPP-1222](https://dsdmoj.atlassian.net/browse/CRIMAPP-1222)
[CRIMAPP-1223](https://dsdmoj.atlassian.net/browse/CRIMAPP-1223)
Code to cast these values was removed in error. This pr adds that code back and adds specs to prevent that happening again.
[CRIMAPP-1222]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1223]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1223 captial details uses Money for amounts

- app/presenters/tasks/evidence_upload.rb
- spec/presenters/tasks/evidence_upload_spec.rb
- spec/validators/supporting_evidence/answers_validator_spec.rb
Fixes behaviour with the evidence upload task list following work to validate evidence upload 
Previously the evidence upload task will display as complete immediately as there are no evidence prompts yet 
However, we don't really know if an application's evidence is complete, only whether they have uploaded at least one piece of evidence. It may also give unrealistic view to providers that they don't have to upload any more evidence. So it was decided it is best to keep the status as in progress rather than ever setting the task to complete
The evidence form, review application page and declaration page will ensure apps are only submitted if they have fulfilled the validation criteria 
Implemented behaviour:
- Evidence upload status will = not started if there is no evidence uploaded
- …
> Evidence upload task list behaviour amends

- app/forms/steps/evidence/upload_form.rb
- app/presenters/tasks/evidence_upload.rb
- app/services/evidence/prompt.rb
- app/validators/supporting_evidence/answers_validator.rb
- config/locales/en/evidence.yml
- config/locales/en/steps.yml
- spec/forms/steps/evidence/upload_form_spec.rb
- spec/presenters/tasks/evidence_upload_spec.rb
- spec/services/evidence/prompt_spec.rb
- spec/validators/supporting_evidence/answers_validator_spec.rb
Amends the evidence validation logic to display evidence prompts for court custody cases which was previously not being displayed
Also amends the warning text to add a warning for court custody cases
[CRIMAPP-1189](https://dsdmoj.atlassian.net/browse/CRIMAPP-1189)
**This was the text being displayed for court custody cases**
**This was the warning text that has been modified to include court custody cases (see below)**
[CRIMAPP-1189]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1189] Amend evidence validation logic for court custody cases

- config/inactive_offices.yml
Deactivate 4 office codes for firms that no longer have a criminal legal aid contract
[CRIMAPP-1240](https://dsdmoj.atlassian.net/browse/CRIMAPP-1240)
[CRIMAPP-1240]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1240 Deactivate office codes

- app/presenters/summary/components/saving.rb
- spec/presenters/summary/components/saving_spec.rb
The savings partner wages benefit question row was not displaying on the final review your application page
[CRIMAPP-1090](https://dsdmoj.atlassian.net/browse/CRIMAPP-1090)
Not to be merged until after release 
Create an application where you need to go through capital assessment and the client has a partner. Create a saving and fill in the questions. Check the partner wages benefit question row is displayed on the review your application page, the capital cya page and completed applications page 
[CRIMAPP-1090]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1090] Fix display of partner wages benefits row

- app/services/datastore/documents/download.rb
- spec/services/datastore/documents/download_spec.rb
Ensure download disposition filename is wrapped in double quotes.
[CRIMAPP-1242](https://dsdmoj.atlassian.net/browse/CRIMAPP-1242)
[CRIMAPP-1242]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1242 fix download for files with comma in name

- app/forms/steps/client/is_means_tested_form.rb
- spec/forms/steps/client/is_means_tested_form_spec.rb
Default initial applications to being means tested
This is a temporary change whilst content based options explored.
[CRIMAPP-1249](https://dsdmoj.atlassian.net/browse/CRIMAPP-1249)
[CRIMAPP-1249]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1249] applications default to being means tested

- app/presenters/summary/sections/income_details.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/income_details_spec.rb
Fix 'income_above_threshold' text on CYAs page based on the following:
- When partner is included show "Joint annual income more than £12,475 a year before tax?"
- When partner is not included show "Income more than £12,475 a year before tax?" 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1225
http://localhost:3000/applications/:id/steps/income/check_your_answers_income
> CRIMAPP-1225: Fix 'income_above_threshold' text for joint income on CYA page

- app/forms/steps/evidence/upload_form.rb
- app/validators/supporting_evidence/answers_validator.rb
- app/views/steps/evidence/upload/edit.en.html.erb
- config/locales/en/steps.yml
- config/settings.yml
- spec/validators/application_fulfilment_validator_spec.rb
- spec/validators/supporting_evidence/answers_validator_spec.rb
Amends evidence validation logic for cifc and has benefit evidence scenarios
- If a user has answered that they will upload evidence during the benefit check, then they must upload at least one piece of evidence regardless of whether they have any evidence triggers 
- CIFC applications must also upload evidence if there are evidence triggers 
- There is warning text displayed for CIFC applications on the evidence upload page
- An evidence upload logic tree is attached below 
[CRIMAPP-1170](https://dsdmoj.atlassian.net/browse/CRIMAPP-1170)
[CRIMAPP-1190](https://dsdmoj.atlassian.net/browse/CRIMAPP-1190)
Merging will turn on the evidence validation feature flag on staging
[CRIMAPP-1170]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> [CRIMAPP-1190] Update evidence validation logic

- app/forms/steps/capital/national_savings_certificates_form.rb
- config/locales/en/errors.yml
- spec/forms/steps/capital/national_savings_certificates_form_spec.rb
Add validation to prevent user entering strings that end with '-' to avoid modsec errors. It is still possible to enter strings that contain '-' just not those ending in dashes. 
[CRIMAPP-1235](https://dsdmoj.atlassian.net/browse/CRIMAPP-1235)
[CRIMAPP-1235]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1235 Add validation for national savings certificate format

- app/models/property.rb
- spec/models/property_spec.rb
Fix definition of 'incomplete' for property
- check presence of owners details if property has owners
- Sum of ownership percentage should be 0 (Applicant + Partner(if present) + Owners(if present) )
https://dsdmoj.atlassian.net/browse/CRIMAPP-1105
> CRIMAPP-1105: Show assets section incomplete if owners information is missing

- app/views/steps/capital/partner_trust_fund/edit.html.erb
- app/views/steps/capital/trust_fund/edit.html.erb
- config/locales/en/steps.yml
Update text for:
- Capital assessment > partner_benefit_from_trust_fund
- Capital assessment > client_benefit_from_trust_fund
https://dsdmoj.atlassian.net/browse/CRIMAPP-758
Client:
Partner:
Client:
Partner:
> CRIMAPP-758: Apply trust fund screen does not match current design

- Gemfile
- Gemfile.lock
Bump schema version to v1.2.1
https://dsdmoj.atlassian.net/browse/CRIMAPP-963
> CRIMAPP-963: Update schema version to v1.2.1

- app/forms/steps/capital/other_investment_type_form.rb
- app/forms/steps/capital/other_property_type_form.rb
- app/forms/steps/capital/other_saving_type_form.rb
- config/initializers/form_builder.rb
Fixes a bug where when users clicked save and come back later on a form (typically a radio button form), an empty string was saved which then threw an error when submitting the application as the value does not conform to the schema. 
This has been fixed by adding config to the form builder to not include hidden input fields that have been populated with a blank value when rendering radio buttons. 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1243
Note this won't fix any existing applications that have the bug, it will just prevent new draft applications from getting into this state 
Start an application and navigate to a form with radio buttons e.g. case type. Select save and come back later and verify that the attribute is still `nil` and not an empty string. You may also want to check …
> [CRIMAPP-1243] Prevent saving attributes as empty string

- app/validators/application_fulfilment_validator.rb
- config/locales/en/errors.yml
- spec/validators/application_fulfilment_validator_spec.rb
Prevents applications from being submitted without court hearing details by validating the court hearing details are present at submission
https://dsdmoj.atlassian.net/browse/CRIMAPP-1271
More of a temporary fix as this could also happen on other case details pages. The section completeness validator would be better suited to handling this and should be displaying an error but i'll investigate that separately as it doesn't seem to be a quick fix
Start an initial application and submit without court hearing details (by skipping the page via the url and go straight to the ioj page `steps/case/ioj`). Keep going till you reach the submission page then try to submit, you should see an error message like the above
> [CRIMAPP-1271] Validate hearing details on submission

- app/services/passporting/means_passporter.rb
- app/validators/application_fulfilment_validator.rb
- config/locales/en/errors.yml
- spec/services/passporting/means_passporter_spec.rb
- spec/support/shared_contexts/serializable_application.rb
- spec/validators/application_fulfilment_validator_spec.rb
Refactor MeansPassporter to be stateless.
[LAA-CRIMINAL-APPLICATIONS-DATASTORE-6](https://ministryofjustice.sentry.io/issues/5635408008/) and others
Previously, persisting `CrimeApplication#means_passport` within `MeansPassporter#call` caused validation errors to be reset each time `MeansPassporter#call` was invoked. Where multiple validations were run each using the MeansPassporter, only the latest set of errors would exist on the record.
The only known requirement for persisting this value is to allow the consideration of the previous submission's `means_passport` for U18 applications when returns are processed. However, this assumption may not cover all cases, so thorough regression testing is essential. Essentially, after this change, persistence and rehydration of the …
> LAA-CRIMINAL-APPLICATIONS-DATASTORE-6 Make MeansPassporter stateless

- Gemfile
- Gemfile.lock
- app/services/adapters/structs/outgoings_details.rb
Use a version of the schema that default OutgoingsDetails#outgoings to an empty array.
Fixes: [LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-2N](https://ministryofjustice.sentry.io/issues/5656868879/)
Rehydration was failing on means passported applications because outgoings was nil. The version of the schema used here defaults outgoings to an empty array.
1. Return a U18 passported application. 
2. Confirm that it cannot be re-hydrated. 
3. Updated to this branch. 
4. Confirm that it can be rehydrated.
> Use schema version that sets default outgoings to []

- app/validators/supporting_evidence/answers_validator.rb
- config/settings.yml
- spec/validators/supporting_evidence/answers_validator_spec.rb
Updates logic to ensure cifc applications cannot be submitted unless at least one piece of evidence has been uploaded regardless of case type or court custody status
https://dsdmoj.atlassian.net/browse/CRIMAPP-1170
Test scenarios found in the ticket comments
> [CRIMAPP-1170] Update logic for cifc evidence validation

- app/forms/steps/capital/property_form.rb
Apply breaks when the property form is saved and the other owners question has not been answered (i.e. save and come back later). This pr checks has other owners is not nil checking the value of the attribute
[Sentry error](https://ministryofjustice.sentry.io/issues/5672124052/?project=4507142444023808&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=3)
> Handle when has other owners is nil value

- config/locales/en/steps.yml
Update IOJ passported banner content
[CRIMAPP-1291](https://dsdmoj.atlassian.net/browse/CRIMAPP-1291)
[CRIMAPP-1291]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1291 update IOJ passported banner content

- app/forms/steps/income/income_benefits_form.rb
- app/forms/steps/income/income_payments_form.rb
- app/forms/steps/income/partner/income_benefits_form.rb
- app/forms/steps/income/partner/income_payments_form.rb
- spec/forms/steps/income/income_benefits_form_spec.rb
- spec/forms/steps/income/income_payments_form_spec.rb
- spec/forms/steps/income/partner/income_benefits_form_spec.rb
- spec/forms/steps/income/partner/income_payments_form_spec.rb
Add validation message if none of the `income payments` or `income benefits` are selected
https://dsdmoj.atlassian.net/browse/CRIMAPP-1277
income payments
income benefits
> CRIMAPP-1277 Missing validation on Income payments and Benefits pages

- app/forms/steps/outgoings/outgoings_payments_form.rb
- spec/forms/steps/outgoings/outgoings_payments_form_spec.rb
Add validation message if none of the outgoings payments are selected
https://dsdmoj.atlassian.net/browse/CRIMAPP-1277
outgoings payments
> CRIMAPP-1277 Missing validation on outgoings payments

- app/presenters/summary/sections/base_section.rb
- app/presenters/summary/sections/case_details.rb
- app/presenters/summary/sections/client_details.rb
- app/presenters/summary/sections/employment_details.rb
- app/presenters/summary/sections/housing_payments.rb
- app/presenters/summary/sections/overview.rb
- app/presenters/summary/sections/properties.rb
- app/presenters/summary/sections/savings.rb
- app/presenters/summary/sections/supporting_evidence.rb
- app/presenters/summary/sections/trust_fund.rb
- app/views/steps/submission/shared/_list_section.html.erb
- app/views/steps/submission/shared/_section.html.erb
- config/locales/en/steps.yml
- config/locales/en/summary.yml
- spec/presenters/summary/sections/overview_spec.rb
- spec/presenters/summary/sections/supporting_evidence_spec.rb
- spec/requests/dashboard_spec.rb
Makes updates to summary cards and review the application screen to match figma designs
Updates: 
- Add headings to the review the application page (`Application details`, `Case details and offences`, `Income`, `Outgoings`, `Assets`, `Savings and investments`, `Supporting evidence`)
- Changes `Supporting evidence` summary card title to `Files` 
- Changes `Where to send correspondence` row to `Correspondence`
- Content changes to the application confirmed page for cifc and pse applications
https://dsdmoj.atlassian.net/browse/CRIMAPP-695
https://dsdmoj.atlassian.net/browse/CRIMAPP-1292
The content in the checklists in the ticket are outdated and so the changes I have made match the designs in figma which also matches what is currently displayed on review. 
Create different applications e.g. …
> [CRIMAPP-695] updates to summary cards and review application page

- app/controllers/documents_controller.rb
- app/javascript/local/dropzone-cfg.js
- app/validators/file_upload_validator.rb
- spec/models/document_spec.rb
Reduces the minimum upload file size limit to 3kb from 5kb to fix a reported issue where a user could not upload some files. The minimum file size limit was previously arbitrarily chosen and it appears 5kb is too high a threshold and files uploaded could be lower in size. So the decision was taken to reduce and monitor whether this appears to be a better threshold. 
The order of checks are also modified to check the document is valid on storage before checking if the document passes the scan. This is because the error message the user saw was related to the scan service failing. If the size validation checks are ran first it will show the correct error message and not interfere with the scan which seems to pass after
Link to [slack …
> Reduce minimum file size upload limit to 3kb

- config/data/offences.csv
Updated the class of offence "Supply a controlled drug of class A - Cocaine" from C to B.
[CRIMAPP-1302](https://dsdmoj.atlassian.net/browse/CRIMAPP-1302)
[CRIMAPP-1302]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1302] Amend class of 'Supply a controlled drug of class A - Cocaine'

- app/presenters/tasks/ioj.rb
- spec/presenters/tasks/ioj_spec.rb
Mark `Case details` > `Justification for legal aid` : **`Completed`** if justification/details is present
https://dsdmoj.atlassian.net/browse/CRIMAPP-835
> CRIMAPP-835 Apply: Able to submit application with incomplete justification for legal aid details

- app/forms/steps/income/client/self_assessment_tax_bill_form.rb
- app/forms/steps/income/partner/self_assessment_tax_bill_form.rb
- spec/forms/steps/income/client/self_assessment_tax_bill_form_spec.rb
- spec/forms/steps/income/partner/self_assessment_tax_bill_form_spec.rb
Both client and partner self-assessment tax bills can be zero.
[CRIMAPP-1310](https://dsdmoj.atlassian.net/browse/CRIMAPP-1310)
A person may receive a Self Assessment tax calculation which shows their liability as £0 p/a, but the validation prevents entry of 0 as an amount.
This would block the applicant continuing with the application.
[CRIMAPP-1310]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1310] Allow self assessment tax bill to be zero

- spec/rails_helper.rb
- spec/support/capybara_helpers.rb
- spec/system/applying/passported_on_age_spec.rb
Add system spec for submitting an age passported application
This update adds a system spec for the U18 passported application as part of our effort to expand system specs to cover all general means and application types. Initially, the focus will be on confirming the happy path.
This spec takes the application from the initial creation up to datastore submission. To achieve this, a schema-compliant application must be generated (covering steps such as submission and review), and the fulfilment validation must be satisfied. This process, therefore, executes the serialisation and deserialisation of a datastore application for this scenario.
Next up will be the non-means-tested application.
> Add system spec for completed age passported application

- app/forms/steps/income/client/deduction_fieldset_form.rb
- app/forms/steps/income/income_payment_fieldset_form.rb
- app/forms/steps/income/partner/income_payment_fieldset_form.rb
- app/validators/deductions_validator.rb
- app/validators/income_payments_validator.rb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- spec/forms/steps/income/client/deduction_fieldset_form_spec.rb
- spec/forms/steps/income/income_payments_form_spec.rb
- spec/forms/steps/income/partner/deduction_fieldset_form_spec.rb
- spec/forms/steps/income/partner/income_payments_form_spec.rb
- spec/support/shared_examples/deduction_shared_examples.rb
- Update input labels on the Deductions form
- Update error messages on the Deductions form
- Update error messages on the Payments form
[CRIMAPP-1287](https://dsdmoj.atlassian.net/browse/CRIMAPP-1287)
There's some complexity introduced to resolve the correct errors messages in the deductions form. The error messages break the pattern of `"Enter how much %{deduction_type} gets deducted"` when the deduction type is "Other deductions" -- it becomes `"Enter amount of other deductions"`. Also, I've used `count` to deal with the fact that "Other deductions" is plural and the message needs to make grammatical sense.
[CRIMAPP-1287]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1287] Income assessment error message updates

- app/services/decisions/dwp_decision_tree.rb
- app/services/decisions/partner_decision_tree.rb
- app/validators/partner_details/answers_validator.rb
- config/settings.yml
- spec/services/decisions/dwp_decision_tree_spec.rb
- spec/services/decisions/partner_decision_tree_spec.rb
- Partner with a conflict and without a nino cab be complete on task list.
- Disable Arc question on staging for regression testing
[CRIMAPP-1299](https://dsdmoj.atlassian.net/browse/CRIMAPP-1299)
Changes brought in with the feature flagged ARC work cause a number of regressions in the partner Nino code. This PR fixes those.
[CRIMAPP-1299]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1299] Allow partner with conflict to skip nino

- app/presenters/tasks/ioj.rb
- app/validators/interests_of_justice/answers_validator.rb
- app/validators/sections_completeness_validator.rb
- spec/presenters/tasks/ioj_spec.rb
- spec/validators/interests_of_justice/answers_validator_spec.rb
- spec/validators/sections_completeness_validator_spec.rb
Validate Interests of Justice answers on Submission Review
https://dsdmoj.atlassian.net/browse/CRIMAPP-835
Adds an answer validator for the IoJ task and adds it to the section completeness validator.
Confirm that an error message is shown when IoJ are required but have not been given (or have only been partially given). See ticket for details.
> [CRIMAPP-835] Add IoJ answer validator

- app/models/concerns/type_of_means_assessment.rb
- spec/models/concerns/type_of_means_assessment_spec.rb
Fixes an error where `benefit_check_subject` was returning `nil` as the guard clause which checks whether the partner is the benefit check recipient was no longer confirming whether there is a partner before doing the check. [See diff here](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1118/files#diff-2a14e4586f650173e396d6bf21ce071a95efee6e878b446ecf4f67ecf954c73fL88). This is a regression following the work to add the arc radio button.
[Link to sentry error](https://ministryofjustice.sentry.io/issues/5775380732/?project=4507142444023808&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=2)
The application that was encountering this error is somehow in a state where the client has no partner but …
> [CRIMAPP-1325] Only return partner as benefit check subject if partner is present

- app/presenters/tasks/ioj.rb
- spec/presenters/tasks/ioj_spec.rb
IoJ task returns true for 'in_progress' when IoJ passported.
[CRIMAPP-835](https://dsdmoj.atlassian.net/browse/CRIMAPP-835)
Fixes regression cause by refactor.
Confirm that a U18 application shows the Interest of Justice task as complete once case details are complete.
[CRIMAPP-835]: https://dsdmoj.atlassian.net/browse/CRIMAPP-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-835 IoJ task returns true for 'in_progress' when IoJ passported

- app/forms/steps/case/hearing_details_form.rb
- spec/forms/steps/case/hearing_details_form_spec.rb
- spec/support/shared_examples/form_validation_shared_examples.rb
Validate that `hearing_date` is in the 01/01/2010 - 31/12/2035 range. This is to align it with the validation in MAAT. The current upper limit is 31/12/2025, but it is to be updated to 31/12/2035 (MAAT ticket LASB-3572).
[CRIMAPP-1296](https://dsdmoj.atlassian.net/browse/CRIMAPP-1296)
[LASB-3572]: https://dsdmoj.atlassian.net/browse/LASB-3572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1296]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1296] Validate hearing date

- app/forms/steps/capital/property_form.rb
- app/models/property.rb
- app/services/evidence/rules/20240425120827_council_tax_payments.rb
- app/services/evidence/rules/20240425120837_childcare_costs.rb
- app/services/evidence/rules/20240425183405_child_maintenance_costs.rb
- app/services/evidence/rules/20240429122128_restraint_or_freezing_order.rb
- config/locales/en/errors.yml
- spec/forms/steps/capital/residential_form_spec.rb
Adds validation to property form to prevent a property being declared as the client's home address if another property has already been declared as the client's home address
This is required for MAAT as MAAT will only display 1 of the assets that are declared as the home address, each subsequent asset declared as the home address will not display in MAAT. 
https://dsdmoj.atlassian.net/browse/CRIMAPP-801
> CRIMAPP-801 Prevent setting more than one home address

- app/services/evidence/rules/20240425120658_housing_costs.rb
- app/services/evidence/rules/20240425120827_council_tax_payments.rb
- app/services/evidence/rules/20240425120837_childcare_costs.rb
- app/services/evidence/rules/20240425183405_child_maintenance_costs.rb
- app/services/evidence/rules/20240426002316_self_assessed.rb
- app/services/evidence/rules/20240426020839_pension_income.rb
- app/services/evidence/rules/20240426022536_maintenance_income.rb
- app/services/evidence/rules/20240426024826_interest_and_investments.rb
- app/services/evidence/rules/20240426030038_rental_income.rb
- app/services/evidence/rules/20240426030754_any_other_income.rb
The partner outgoing evidence triggers were combined with the client outgoings triggers and appear under the same heading: `Evidence of your client and the partner’s outgoings` instead of separate headings. Implemented [here](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/937/files). See slack discussion [here](https://mojdt.slack.com/archives/C05PAUPJJ10/p1718373287716269?thread_ts=1718016750.660689&cid=C05PAUPJJ10).
So this PR cleans up any unrequired code that was left behind
https://dsdmoj.atlassian.net/browse/CRIMAPP-1329
> [CRIMAPP-1329] Evidence triggers code cleanup

- app/presenters/summary/components/property.rb
- config/locales/en/summary.yml
- spec/presenters/summary/components/property_spec.rb
Forces blank string `house_type` field to be output in the Capital Assesment summary table with 'not provided'.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1289
- This bug just does not manifest in localhost but does so in staging and presumably production. The change makes the 'absence' answer explicit. 
- Also updates the 'Bedrooms' field to show 'Not provided' rather than 'None' because it makes more sense to do so.
If `house_type` is saved with a blank string (``) then localhost will throw an exception:
But if the `house_type` is `nil` then the word 'None' is output:
Follow instructions to reproduce in ticket
> [CRIMAPP-1289] Add explicit 'not provided' for house_type

- config/kubernetes/production/deployment.tpl
- Use ping for livenessProbe on production deployment
- Add startup probe to production deployment
Applies changes tested on staging to production from:
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1162
Using the healthcheck for the liveness probe was causing slow database connection to trigger restarts and pod crash looping. This change is for staging only and tests using ping instead of health for liveness. It also adds a startup probe. (e.g. https://mojdt.slack.com/archives/C056U956ESH/p1725882930025509 )
More discussion here: https://dsdmoj.atlassian.net/browse/CRIMAPP-345?focusedCommentId=499712
> Using ping for liveness probe and add startup probe

- config/settings.yml
Switch on the ARC feature flag in production so users see the ARC number option on the NINO page.
> Switch on ARC feature flag in production

- app/javascript/application.js
- app/views/layouts/govuk_template.html.erb
Try disabling JS if GOVUK components have not initiated or the user agent is an ipad
**This is just to test on staging, this will not necessarily go into production** 
[CRIMAPP-1263](https://dsdmoj.atlassian.net/browse/CRIMAPP-1263)
[CRIMAPP-1263]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Disable JS 

- app/models/person.rb
- app/presenters/summary/sections/client_details.rb
- app/presenters/summary/sections/partner_details.rb
- app/services/adapters/structs/applicant.rb
- spec/models/person_spec.rb
- spec/presenters/summary/sections/client_details_spec.rb
- spec/presenters/summary/sections/partner_details_spec.rb
- spec/requests/dwp_benefit_checker_spec.rb
- spec/services/adapters/structs/applicant_spec.rb
- spec/services/evidence/prompt_spec.rb
- spec/services/evidence/rules/20240425222456_benefits_recipient_spec.rb
The review page shows both the NINO and the ARC number. This should not be possible, as validation on the NINO page restricts both values being recorded and displayed on the review application page 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1334
> CRIMAPP-1334  Apply - ARC and NINO displayed on Review application page

- config/locales/en/errors.yml
Update error message when property cannot be partly owned by someone else if percentage ownership totals 100%
https://dsdmoj.atlassian.net/browse/CRIMAPP-816
> CRIMAPP-816 Update ownership error message

- app/views/steps/income/client/other_work_benefits/edit.html.erb
- app/views/steps/income/client/self_assessment_tax_bill/edit.html.erb
- app/views/steps/income/partner/other_work_benefits/edit.html.erb
- app/views/steps/income/partner/self_assessment_tax_bill/edit.html.erb
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- spec/support/capybara_helpers.rb
- spec/support/shared_contexts/means_tested_with_partner.rb
- spec/system/applying/employed_with_partner_spec.rb
- spec/system/applying/non_means_tested_spec.rb
- spec/system/applying/not_working_with_partner_spec.rb
- spec/system/applying/passported_on_age_spec.rb
- spec/system/applying/self_employed_with_partner_spec.rb
Adds system specs for three means tested routes with a partner (employed, not working, self employed)
For the time being, it verifies whether the submission is successful with some basic expected application information tested. We can look to test expectations in a subsequent pr like whether partner information is deleted when the partner answer has been updated
Also fixes a couple of small content/ux issues I noticed along the way
https://dsdmoj.atlassian.net/browse/CRIMAPP-1344
One thing to note is each test takes a couple of seconds (~3) which will add up in time. We should look into what options we have to ensure this doesn't slow down the pipeline too much as we add more specs
> Add system specs for partner means tested flows

- app/models/concerns/employed_income.rb
- spec/models/concerns/employed_income_spec.rb
Fixes a routing issue uncovered in qa. The partner armed forces question was not appearing when the partner is employed and the client is not working. This is due to an error in the logic in the ticket which said the client also needed to be employed. This has been changed to check whether the partner is employed and whether the client is self employed 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1300
As we are considering moving the partner employment status question we would need to amend the client armed forces logic to check if the partner is self employed. I have left as is for now. 
Check the armed forces question appears for the following scenario: 
- Summary only, Client Unemployed, Partner employed
> [CRIMAPP-1300] Route to armed forces question unless client is self employed

- app/models/concerns/type_of_means_assessment.rb
- app/services/decisions/income_decision_tree.rb
- app/validators/income_assessment/answers_validator.rb
- spec/models/concerns/type_of_means_assessment_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/system/applying/employed_client_with_self_employed_partner_spec.rb
- spec/system/applying/self_employed_with_partner_spec.rb
- spec/validators/income_assessment/answers_validator_spec.rb
A regression has been introduced in the Income Assessment section of the application where the 'How do your client and their partner manage with no income?' question is asked when non-zero employment income has been provided.
[CRIMAPP-1343](https://dsdmoj.atlassian.net/browse/CRIMAPP-1343)
Routing to the 'How do your client and their partner manage with no income?' question has been updated with client and partner self-employed checks where it was previously inconsistent.
The`manage_without_income_complete?` validation method has also been updated to check if the partner is self-employed. 
[CRIMAPP-1343]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1343] Unexpected 'no income' step

- app/forms/steps/case/hearing_details_form.rb
- app/models/case.rb
- app/validators/case_details/answers_validator.rb
- spec/models/case_spec.rb
- spec/validators/case_details/answers_validator_spec.rb
Update case details answers_validator to add  `case.hearing_date` date range validation on review application page
https://dsdmoj.atlassian.net/browse/CRIMAPP-1336
> CRIMAPP-1336 Apply can enter and save a hearing date beyond the permitted date range

- config/locales/en/helpers.yml
> Add hint text to self assessment tax bill question

- spec/system/applying/appeal_to_crown_court_spec.rb
- spec/system/applying/appeal_to_crown_court_with_changes_spec.rb
Adds system specs to verify the routing for appeal to crown court applications. There is one test for the route with changes and the route with no changes. 
The tests verify the expected behaviour outlined here: https://www.figma.com/design/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=11721-62480&node-type=frame&t=YX9OaPb9kRQShoYM-0
https://dsdmoj.atlassian.net/browse/CRIMAPP-1344
> [CRIMAPP-1344] Add system specs for appeal applications

- app/models/crime_application.rb
Retain date stamp on resubmitted non-means applications
A regression meant that a break clause (to protect against case type being missing when determining whether to retain a date stamp) cleared the date stamp on non-means tested application incorrectly 
1. Submit a non-means tested application
2. Return it to provider from Review
3. Resubmit it, check that the date stamp is retained from the initial submission, not overwritten with the submitted_at date of the resubmission
> [FIX] Retain date stamp on resubmitted non-means applications

- app/validators/partner_details/answers_validator.rb
- spec/validators/partner_details/answers_validator_spec.rb
Fixes bug with partner address validation where the partner answer validation fails to pick up on an incomplete home address when a user clicks save and come back later on the partner address screen
https://dsdmoj.atlassian.net/browse/CRIMAPP-1387
Start an application with a partner. Get to the partner home address screen and select save and come back later rather than entering the home address. Verify that the partner details task list still says in progress rather than completed.
> [CRIMAPP-1387] Fix partner address validation

- app/presenters/summary/components/funding_decision.rb
- app/presenters/summary/components/tag_answer.rb
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/sections/funding_decisions.rb
- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
- spec/presenters/summary/components/tag_answer_spec.rb
- spec/presenters/summary/sections/funding_decisions_spec.rb
Show funding decisions on submitted applications.
[CRIMAPP-1356](https://dsdmoj.atlassian.net/browse/CRIMAPP-1356)
1. Submit a non-means application
2. On Review, assign the application to yourself, add a funding decision and submit it
3. Back on Apply, view the application under Submitted applications and you should see the funding decision
[CRIMAPP-1356]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1356] Show funding decisions

- config/kubernetes/staging/ingress.yml
Updated the ModSec rules in staging to prevent common false positives on select endpoints.
Test the endpoints with form input that normally triggers the rules.
> Update ModSec rules in staging

- app/presenters/summary/sections/supporting_evidence.rb
- config/locales/en/summary.yml
- spec/presenters/summary/sections/supporting_evidence_spec.rb
Updates supporting evidence summary card to display card when no files have been uploaded
https://dsdmoj.atlassian.net/browse/CRIMAPP-1335
> [CRIMAPP-1335] Supporting evidence summary card update

- app/presenters/summary/components/funding_decision.rb
- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
- Added the missing "Further information about the decision" row to the funding decision summary component
- Added missing overall result answers
[CRIMAPP-1356](https://dsdmoj.atlassian.net/browse/CRIMAPP-1356)
1. Create and submit an application on Apply
2. Assign it to yourself on Review and submit a funding decision with a comment
3. Back on Apply, view the submitted application, which should have the funding decision with the comment on the "Further information about the decision" row
[CRIMAPP-1356]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1356] Add missing decision row to summary

- docs/clam-av.md
- docs/evidence-prompt.md
Adds some general info for evidence prompt and virus scanning
https://dsdmoj.atlassian.net/browse/CRIMAPP-1445
> [CRIMAPP-1445] Add documentation for evidence prompt and virus scanning

- config/kubernetes/staging/prometheus.yml
Alter the regex of the Prometheus alert rule that creates alerts when 4xx errors occur. It will now ignore 404 errors.
[CRIMAPP-1465](https://dsdmoj.atlassian.net/browse/CRIMAPP-1465)
[CRIMAPP-1465]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1465] Exclude 404 errors from alerts

- Gemfile
- Gemfile.lock
- app/models/concerns/person_capital_assets.rb
Fixes a couple of sentry errors linked in the ticket. 
Users are being thrown errors on the evidence upload and review page when there are incomplete employment, Investment, co-defendant, saving and national saving certificate records. This is because the application's data is used to recreate a draft version of the application based on the schema. For some attributes, nil values were not permitted and so errors were being thrown. This is fixed at the schema level and with some `nil` value handling
https://dsdmoj.atlassian.net/browse/CRIMAPP-1453
Note: this means there will be greater reliance on validation to catch incomplete records before an app is submitted
Start an application and create incomplete employment, Investment, co-defendant, saving and national saving certificate records. …
> [CRIMAPP-1453] Fix error with incomplete records

- app/controllers/developer_tools/crime_applications_controller.rb
- app/models/concerns/type_of_application.rb
Fixes the under 18 and bypass dwp dev tools which were broken since the application has been updated with new questions
https://dsdmoj.atlassian.net/browse/CRIMAPP-1485
These dev tool buttons may need rethinking as a whole as there may be new buttons we could implement that would be useful for testing purposes
Start a new application. Go to the dev tools and select bypass dwp and check that the dwp result is confirmed. 
Then start another application, click the under 18 bypass and check that the applicant is under 18 as expected.
> [CRIMAPP-1485] Fix under 18 and bypass dwp dev tools

- .github/workflows/test-build-deploy.yml
Updated the following GitHub Actions dependencies:
1. `actions/cache@v3` -> `actions/cache@v4`
2. `actions/upload-artifact@v3` - > `actions/upload-artifact@v4`
3. `aws-actions/amazon-ecr-login@v1` - > `aws-actions/amazon-ecr-login@v2`
4. `actions/checkout@v3` -> `actions/checkout@v4`
5. `aws-actions/configure-aws-credentials@v3` - > `aws-actions/configure-aws-credentials@v4`
[CRIMAPP-1353](https://dsdmoj.atlassian.net/browse/CRIMAPP-1353)
[CRIMAPP-1353]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update GitHub Actions

- app/views/application_searches/new.html.erb
- app/views/application_searches/search.html.erb
Hides the warning text that was added for user research purposes. The text will not display when the feature flag is enabled. 
When search is eventually enabled and deployed, we will need to remove the warning text (will add to a ticket)
> Hide warning text when search enabled

- app/views/completed_applications/show.html.erb
Remove back link from completed application page
[CRIMAPP-1499](https://dsdmoj.atlassian.net/browse/CRIMAPP-1499)
Now that search requests use POST, it's better for users to rely on the browser's native back button to return to the search results page. This ensures the search form remains populated.
The GOV.UK Design System advises using back links for question pages and other pages within a multi-page transaction when appropriate. However, it does not apply in this case.
[CRIMAPP-1499]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1499: Remove back link from completed application page

- app/views/steps/client/date_stamp/edit.html.erb
- config/locales/en/steps.yml
Format content on date stamp Notification
[CRIMAPP-1491](https://dsdmoj.atlassian.net/browse/CRIMAPP-1491)
[CRIMAPP-1491]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update date stamp notice content format

- app/models/pagination.rb
- config/initializers/kaminari_config.rb
- spec/models/pagination_spec.rb
Change dashboard page size from 10 to 20 so that is consistent with the new search pagination.
> Standardize default page size

- app/views/completed_applications/_datastore_unavailable.html.erb
- app/views/steps/submission/failure/edit.html.erb
- config/locales/en/dashboard.yml
- config/locales/en/steps.yml
Updates to the content shown when Apply can't connect to the datastore.
[CRIMAPP-1369](https://dsdmoj.atlassian.net/browse/CRIMAPP-1369)
[CRIMAPP-1369]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1369] Datastore unavailable content

- Gemfile
- Gemfile.lock
- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
Use simplified Decisions data model.
> Use simplified decisions data model

- app/presenters/summary/sections/partner_premium_bonds.rb
- app/presenters/summary/sections/premium_bonds.rb
- config/locales/en/summary.yml
Updates to the 'Premium Bonds' summary card to align it with the other summary cards - ': client' is only shown when a partner is included in the application.
[CRIMAPP-1508](https://dsdmoj.atlassian.net/browse/CRIMAPP-1508)
[Figma design](https://www.figma.com/design/thkvnDBbQbHlSqzt1TE3lk/Crime-Apply?node-id=19698-65906&t=Dl32HUvXFHf6vQOF-1)
[CRIMAPP-1508]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1508] Fix premium bonds content

- app/views/crime_applications/edit.html.erb
Make task list page title same as h1
[CRIMAPP-1552](https://dsdmoj.atlassian.net/browse/CRIMAPP-1552)
[CRIMAPP-1552]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1552 make task list page title same as h1

- config/locales/en/errors.yml
Spotted in qa, the error messaging needed to be made flexible for the client and client/partner versions of the form 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1403
> [CRIMAPP-1403] Outgoings payment form error content update

- app/assets/stylesheets/local/accessible-autocomplete.scss
Fixes issue where the red outline was not appearing around the input field for accessible autocomplete components when there is an error message as per gov uk design conventions
https://dsdmoj.atlassian.net/browse/CRIMAPP-1558
> [CRIMAPP-1558] Apply error styling to autocomplete input field

- app/presenters/summary/components/funding_decision.rb
- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
- show simplified overall result
- remove colour tags from overall result
- show court_type (Means test)
https://dsdmoj.atlassian.net/browse/CRIMAPP-1581
> CRIMAPP-1581 prepare for outcome status user research

- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
Rename "Granted - with a contribution" "Granted - with contribution"
Rename "Passed - with a contribution" "Passed - with contribution"
[CRIMAPP-1581](https://dsdmoj.atlassian.net/browse/CRIMAPP-1581)
[CRIMAPP-1581]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rename Granted - with contribution

- app/controllers/concerns/steps/usual_property_details_step.rb
- app/controllers/steps/income/usual_property_details_controller.rb
- app/forms/concerns/steps/usual_property_details.rb
- app/forms/steps/income/usual_property_details_form.rb
- app/models/income.rb
- app/services/decisions/capital_decision_tree.rb
- app/services/decisions/income_decision_tree.rb
- app/validators/income_assessment/answers_validator.rb
- app/value_objects/usual_property_details_capital_answer.rb
- app/value_objects/usual_property_details_income_answer.rb
- app/views/steps/income/usual_property_details/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/income/usual_property_details_controller_spec.rb
- spec/forms/steps/income/usual_property_details_form_spec.rb
- spec/models/income_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/services/decisions/income_decision_tree_spec.rb
- spec/validators/income_assessment/answers_validator_spec.rb
- spec/value_objects/usual_property_details_capital_answer_spec.rb
- spec/value_objects/usual_property_details_income_answer_spec.rb
This changes adds validation in the income section to check whether the answers about property ownership are consistent. A new question is asked to allow the user to change their answers.
The changes are behind the feature flag `property_ownership_validation`.
[CRIMAPP-1516](https://dsdmoj.atlassian.net/browse/CRIMAPP-1516)
1. Create an application and when asked 'Where does your client usually live?' answer 'In a property they own', 'In a property their partner owns', or 'In a property they and their partner both own'.
2. At the income section, when asked 'Does your client (or partner) own their home, or any other land or property?', answer 'No'.
3. You should see the new question.
The new question (and validation) shouldn't be triggered if the client has a partner and they live in a …
> [CRIMAPP-1516] Add property validation to income section

- config/settings.yml
Enables the new property ownership validation questions in production.
[CRIMAPP-1516](https://dsdmoj.atlassian.net/browse/CRIMAPP-1516)
[CRIMAPP-1516]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1516] Enable property ownership validation in prod

- Gemfile
- Gemfile.lock
- app/presenters/summary/components/funding_decision.rb
- spec/presenters/summary/components/funding_decision_spec.rb
Revert to using eForm's overall result text
[CRIMAPP-1597](https://dsdmoj.atlassian.net/browse/CRIMAPP-1597)
[CRIMAPP-1597]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1597 show the overall result text from the datastore

- app/presenters/summary/components/funding_decision.rb
- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
Translate Types::OverallResult in strings
https://dsdmoj.atlassian.net/browse/CRIMAPP-1597
The previous plan was to store MAAT strings directly in the datastore overall_result, as MAAT is the source of truth for decisions and its logic is complex. However, testing has shown that these strings do not fully meet providers' needs and may cause confusion.
Instead, the datastore now stores a constant representing the overall result, which Crime Apply and Review translate into text as needed.
> CRIMAPP-1597 translate overall result

- app/presenters/summary/sections/funding_decisions.rb
- config/settings.yml
- spec/presenters/summary/sections/funding_decisions_spec.rb
Hide decisions added to Crime Review via a Feature Flag
[CRIMAPP-1586](https://dsdmoj.atlassian.net/browse/CRIMAPP-1586)
Before Outcome Playback is released to providers, there will be a trial period where caseworkers can add funding decisions to Crime Review without those decisions being immediately visible to providers on Crime Apply. 
[CRIMAPP-1586]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1586 hide decisions in production

- Gemfile
- Gemfile.lock
- app/presenters/summary/components/funding_decision.rb
- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
- spec/presenters/summary/html_presenter_spec.rb
Also use `assessment_rules` instead of `court_type`
This PR supports displaying "Refused - ineligible" as the overall result for cases assessed under Crown Court Trial rules when the means test has failed.
Expands the types of "Means test" to include display of:
- Non-means
- Committal for sentence
- Appeal to Crown Court
[CRIMAPP-1630](https://dsdmoj.atlassian.net/browse/CRIMAPP-1630)
[CRIMAPP-1630]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1630 Show 'Refused - ineligible' for Crown Court Means Failures

- config/locales/en/summary.yml
- spec/presenters/summary/components/funding_decision_spec.rb
Small content amend to the decision summary card: 
- in Apply Provider view of application: ‘Further information about the decision’ row label should be >> ‘Comments’
https://dsdmoj.atlassian.net/browse/CRIMAPP-1606
> [CRIMAPP-1606] Outcome playback content update

- app/forms/steps/capital/usual_property_details_form.rb
- app/models/capital.rb
- app/services/decisions/capital_decision_tree.rb
- spec/forms/steps/capital/usual_property_details_form_spec.rb
- spec/models/capital_spec.rb
- spec/services/decisions/capital_decision_tree_spec.rb
- spec/system/applying/property_ownership_validation_spec.rb
This fixes an issue where `capital_details.has_no_properties` is not updated if the user chooses to create a residential property as a result of a failed property ownership validation. This causes their assets to not show on Review, where `has_no_properties` is used to determine whether to show their assets.
[CRIMAPP-1641](https://dsdmoj.atlassian.net/browse/CRIMAPP-1641)
[CRIMAPP-1641]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1641] has_no_properties not updated in property validation flow

- config/routes.rb
Follow up of https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1312 to remove the temporarily retained underscored paths that were added to ensure continuity whilst urls were updated
https://dsdmoj.atlassian.net/browse/CRIMAPP-1503
> [CRIMAPP-1503] Remove temporary underscored url routes

- Gemfile
- Gemfile.lock
- app/components/task_list/section_component.rb
- app/views/completed_applications/show.html.erb
- app/views/steps/submission/shared/_list_section.html.erb
- config/locales/en/dashboard.yml
- spec/requests/dashboard_spec.rb
On completed applications page:
- Add application status tag
- Add link to "View funding decision" if decision present
- Add LAA reference heading
- Add applicant name heading
[CRIMAPP-1653](https://dsdmoj.atlassian.net/browse/CRIMAPP-1653)
[CRIMAPP-1653]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1653] show review status tag and decision link

- app/views/layouts/_primary_navigation.html.erb
- spec/system/primary_navigation_spec.rb
Make sure "Your applications" primary navigation tab marked as current when on Submitted, Returned, Decided etc
[CRIMAPP-1652](https://dsdmoj.atlassian.net/browse/CRIMAPP-1652)
[CRIMAPP-1652]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1652]  Make sure `Your applications` marked as current on submitted

- app/models/concerns/type_of_application.rb
- app/models/crime_application.rb
- app/views/completed_applications/_funding_decision_notification.html.erb
- app/views/completed_applications/_return_notification.html.erb
- app/views/completed_applications/show.html.erb
- config/locales/en/dashboard.yml
- spec/models/crime_application_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/adapters/structs/crime_application_spec.rb
Add notification if Funding decision is expected but not present (likely because Funding decision completed before OP released)
[CRIMAPP-1567](https://dsdmoj.atlassian.net/browse/CRIMAPP-1567)
[CRIMAPP-1567]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1567] show notice if funding decision missing

- app/controllers/completed_applications_controller.rb
- spec/system/dashboard/viewing_submitted_applications_spec.rb
Redirect to the submitted applications tab from "/completed/applications"
[LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-5F](https://ministryofjustice.sentry.io/issues/6327861807/)
> [LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-5F] redirect to submitted applications

- app/presenters/summary/sections/properties.rb
- config/locales/en/summary.yml
- spec/support/shared_examples/a_capital_records_section.rb
When there are no capital assets, the section question should refer to "client" or "client or partner" dynamically. 
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1599
> [CRIMAPP-1599] Dynamic subject for asset question

- app/models/document.rb
- app/validators/file_upload_validator.rb
- db/migrate/20250304140637_add_declared_content_type_to_documents.rb
- db/schema.rb
- spec/controllers/steps/evidence/upload_controller_spec.rb
- spec/models/document_spec.rb
- spec/support/matchers/error_message.rb
- spec/support/shared_contexts/with_an_existing_document.rb
- spec/system/applying/with_supporting_evidence_spec.rb
Prevent files with a permitted `content_type` but an incorrect or disallowed extension or `declared_content_type` from being uploaded.
[CRIMAPP-1658](https://dsdmoj.atlassian.net/browse/CRIMAPP-1658)
[CRIMAPP-1658]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1658] ensure declared file type and extension allowed

- config/kubernetes/staging/config_map.yml
This change updates the session and reauthentication timeouts to match those of production. This allows the AppSec team to perform their testing in an environment that's closer to production.
[CRIMAPP-1670](https://dsdmoj.atlassian.net/browse/CRIMAPP-1670)
[CRIMAPP-1670]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1670] Update session timeouts on staging

- app/views/application_searches/search.html.erb
- app/views/completed_applications/index.html.erb
- app/views/crime_applications/index.html.erb
Correct discrepancy in the font-weight of the “name” column of the “In progress” table compared to the other tables.
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?assignee=6320938929083bbe8cc35869&selectedIssue=CRIMAPP-1671
> [CRIMAPP-1671] use regular font-weight on "name" column

- app/views/application_searches/search.html.erb
- config/locales/en/dashboard.yml
When entering the table, the screenreader should announce this and how many search results there are.
https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1532
Activate MacOS Voiceover using CMD + Fn + F5
You can tab into the "copy reference number" link then press CTRL + OPT + SPACE (MacOs)
> announce table label and result count

- app/models/applicant.rb
- spec/fixtures/files/benefit_checker_responses/unsuccessful.xml
- spec/models/applicant_spec.rb
- spec/support/capybara_helpers.rb
- spec/system/applying/benefit_check_retry_spec.rb
Caseworkers in review reported an issue where they could not determine whether a benefit check had been performed for an application. This occurred as the application's passporting benefit check result had changed from undetermined to confirmed during the drafting of the application. However, the answers to the questions that were answered as part of the undetermined flow (e.g. has benefit evidence) were still being used to calculate the benefit check status on submission. This was resulting in a final benefit check status of `nil` which impacted the view of the passporting benefit check result on apply and review
This PR fixes this and ignores the values for these fields if a confirmed result is obtained when calculating the benefit check status to be presented in apply and review. …
> [CRIMAPP-1676] Disregard unrequired benefit check values when result has changed

- app/forms/steps/income/client/employment_income_form.rb
- app/forms/steps/income/partner/employment_income_form.rb
- app/models/income.rb
- app/models/payment.rb
- app/value_objects/value_object.rb
- spec/forms/steps/income/client/employment_income_form_spec.rb
- spec/forms/steps/income/partner/employment_income_form_spec.rb
- spec/lib/employment_income_payments_calculator_spec.rb
- spec/models/income_spec.rb
This change fixes an issue where the user may leave the employment income question in an incomplete state and then face errors when attempting to revisit the question or access the evidence upload page.
Incomplete `IncomePayment` records will now be excluded from calculations and will not be serialized, which causes an exception when accessing the evidence upload page.
[CRIMAPP-1634](https://dsdmoj.atlassian.net/browse/CRIMAPP-1634)
[CRIMAPP-1634]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1634] Ensure income payment completness

- app/views/steps/partner/details/edit.html.erb
Client details has no 'Save and come back later' as the application record is not persisted before the data on that page is saved.
Partner details replicated that page, but should not be missing the save and come back later button as the user is now much 
further into the form and that is not intentional feature
> Fix missing save and come back later button

- config/kubernetes/staging/ingress.yml
This reverts https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1386. The upgrade breaks staging at the moment. I will continue testing it by applying the ingress config from my local machine, but I don't want the config to be redeployed each time in case it keeps breaking.
[CRIMAPP-1721](https://dsdmoj.atlassian.net/browse/CRIMAPP-1721)
[CRIMAPP-1721]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert modsec-non-prod on staging

- config/kubernetes/staging/ingress.yml
Updated the ModSec ingress controller on staging for testing purposes ahead of the wider roll out on 15th April.
[CRIMAPP-1721](https://dsdmoj.atlassian.net/browse/CRIMAPP-1721)
[CRIMAPP-1721]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1721] Upgrade ModSec controller on staging

- config/kubernetes/staging/deployment-clamav.yml
- Add a startup probe
- Use clamscan to determine readyness rather than TCP
I've confirmed that this config works on well and significantly reduces restart time and avoids liveness probe restart loops of the clamav pod.
> CRIMAPP-1712 add startup probe to clamav

- app/controllers/healthcheck_controller.rb
- config/kubernetes/staging/deployment.tpl
- config/routes.rb
- spec/requests/healthcheck_spec.rb
Use dedicated readiness endpoint in staging.
This PR is intended to allow main to be deployed to production should it need to whilst staging uses the updated readyness probe assessment.
Previously, the health endpoint was used for both readiness and liveness checks. #1395 added clamav check to the health endpoint. This commit reverts that change to the health endpoint and adds a dedicated readyz endpoint to determine if clamav is available to the web app. This allows production continues to function as it did before #1395 and also prevents the staging service from being taken down due to transient issues with clamav after deployment.
> CRIMAPP-1712: Use dedicated readiness endpoint in staging

- app/controllers/healthcheck_controller.rb
- config/kubernetes/staging/deployment.tpl
- config/routes.rb
- spec/requests/healthcheck_spec.rb
- Web app only checks clamav working on startupProbe.
- Remove clamav from readynesProbe
Moving to startup probe to ensure requests continue to the app if clamav down and web app has already started.
> CRIMAPP-1712 only check clamav on startup probe

- config/application.rb
This addresses the issue discovered by the latest AppSec test where the HTML tags allowed by `Rails::HTML5::SafeListSanitizer` may be used in our text boxes to alter the HTML of user input when it is rendered, for example in our summary cards.
[CRIMAPP-1675](https://dsdmoj.atlassian.net/browse/CRIMAPP-1675)
All free-text answers rendered using `Summary::Components::FreeTextAnswer` already call `simple_format`, which sanitizes input by default. The config change ensures that no HTML tags are allowed.
[CRIMAPP-1675]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1675] Fully sanitize HTML

- config/kubernetes/production/deployment-clamav.yml
- config/kubernetes/production/deployment.tpl
- config/kubernetes/staging/deployment-clamav.yml
- docs/clam-av.md
This update updates the CLAMAV image for live to use ministryofjustice/clamav-docker instead of the HMPPS image. It also utilises the new MOJ CLAMAV mirror.
[CRIMAPP-1712](https://dsdmoj.atlassian.net/browse/CRIMAPP-1712)
This configuration has been tested and confirmed to work and maintain up to date virus database on staging.
[CRIMAPP-1712]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1712] update ClamAV image and use MoJ mirror in production

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Remove attack-injection-php rules from rails session cookie to prevent false +ve
I've collated the cookie rules into a single rule to be more focused on the cookie rather than the rules themselves.
> Remove attack-injection-php rules from rails session cookie

- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
Remove ModSec rule 932250, 921110, 941130 from saml endpoint
Adding this rule now accounts for all of the 353 incidents of false positives on this endpoint over the last 4 weeks.
> [CRIMAPP-1747] remove 932250 from saml

- app/controllers/steps/dwp/confirm_result_controller.rb
- app/controllers/steps/dwp/partner_confirm_result_controller.rb
- app/forms/steps/dwp/partner_confirm_result_form.rb
- app/services/decisions/dwp_decision_tree.rb
- app/views/steps/dwp/partner_confirm_result/edit.html.erb
- config/locales/en/errors.yml
- config/locales/en/helpers.yml
- config/locales/en/steps.yml
- config/routes.rb
- spec/controllers/steps/dwp/partner_confirm_result_controller_spec.rb
- spec/forms/steps/dwp/partner_confirm_result_form_spec.rb
- spec/services/decisions/dwp_decision_tree_spec.rb
Fixes a bug with the partner benefit check routing when a client has a partner and the client’s benefit check result is undetermined or no. When asked whether the dwp result is correct, if the user selects that the result is correct, the client’s passporting benefit is reset to none and the user is routed to the urn question. However, as the applicant has a partner who is part of the means assessment, the partner passporting benefit question should be asked. 
This was resulting in users reaching the end of the application and being shown an error message saying they have not answered all questions. For more detail, including the step by step to replicate the bug, see [the ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMAPP/boards/1375?selectedIssue=CRIMAPP-1754) …
> [CRIMAPP-1754] Fix partner dwp check routing

- config/locales/en/errors.yml
Provide a descriptive error message for the home address and other owners radio options
https://dsdmoj.atlassian.net/browse/CRIMAPP-1640
Leave blank values for the above options on this or similar pages - steps/capital/land/{id}
> [CRIMAPP-1640] Descriptive error messages for blank values

- config/initializers/content_security_policy.rb
This change updates the content security policy to allow form actions to https://login.microsoftonline.com, enabling us to test EntraID.
[CRIMAPP-1806](https://dsdmoj.atlassian.net/browse/CRIMAPP-1806)
[CRIMAPP-1806]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1806] CSP update to allow EntraID

- config/locales/en/errors.yml
Adds missing error messaging for next hearing date filed on other charges screen 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1829
Error messaging was approved by content designer
> [CRIMAPP-1829] Fix error messaging on other charges screen

- config/kubernetes/staging/deployment-clamav.yml
This change updates the ClamAV deployment on staging by fixing the [security vulnerabilities found by the Snyk IaC scanner](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3ASNYK-CC-K8S-11%2CSNYK-CC-K8S-9%2CSNYK-CC-K8S-8%2CSNYK-CC-K8S-6).
The recommendations suggest restricting the root filesystem to be read-only and disabling privilege escalation. In order to make this work with [MoJ’s clamav-docker image](https://github.com/ministryofjustice/clamav-docker), we would have to modify its scripts to ensure it could write to `/etc/clamav/freshclam.conf` to add a private mirror, as well as use the `/init-unprivileged` script that comes with ClamAV and avoids making calls that assume root privileges. At the moment …
> [CRIMAPP-1837] ClamAV vulnerability fixes staging

- config/kubernetes/staging/deployment-clamav.yml
This change fixes an issue in the ClamAV StatefulSet where the ConfigMap is referenced by the wrong name.
[CRIMAPP-1837](https://dsdmoj.atlassian.net/browse/CRIMAPP-1837)
[CRIMAPP-1837]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1837] Fix ClamAV ConfigMap naming inconsistency

- config/kubernetes/production/ingress.yml
Apply ModSec fix to the rails session cookie tested in staging to production.
Staging PR: 
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1439
> Apply staging fixes to session cookie ModSec to prod

- config/kubernetes/production/deployment-custom-errors.yml
Fixes the vulnerabilities identified by the snyk IaC scan in the custom error page deployment production configuration.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1840
> [CRIMAPP-1840] Prod custom error page vulnerability fixes

- config/kubernetes/production/deployment-custom-errors.yml
- config/kubernetes/staging/deployment-custom-errors.yml
Adds liveness probe configuration to custom error page kubernetes configuration to address [vulnerability](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/security/code-scanning/11) identified by snyk code scanning 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1840
> [CRIMAPP-1840] Ass liveness probe configuration

- config/kubernetes/staging/ingress.yml
Use presence of rails cookie to determine if a user is a likely an authenticated user for deciding which error message to show. Previously IP range.
[CRIMAPP-1865](https://dsdmoj.atlassian.net/browse/CRIMAPP-1865)
See ticket
[CRIMAPP-1865]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1865] use rails cookie instead of ip range for likely users

- config/kubernetes/staging/ingress.yml
Make health endpoints internal on staging
Add /applications to public ingress to allow redirect from auth'd homepage
[CRIMAPP-1865](https://dsdmoj.atlassian.net/browse/CRIMAPP-1865)
[CRIMAPP-1865]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1866] deny internal monitoring endpoints

- app/controllers/documents_controller.rb
- app/validators/scan_validator.rb
- config/locales/en/errors.yml
Removes usage of `html_safe` which has been flagged by snyk
> Unsanitized input from an HTTP parameter flows into unescaped HTML ("html_safe"), where it is used to directly output to a view. This may result in a Cross-Site Scripting attack (XSS).
https://dsdmoj.atlassian.net/browse/CRIMAPP-1860
Updated content has been agreed with design
> [CRIMAPP-1860] Fix snyk vuln

- .env.development
- .env.test
- Gemfile
- Gemfile.lock
- app/controllers/providers/omniauth_callbacks_controller.rb
- app/lib/lassie/oidc_strategy.rb
- app/lib/provider_data_api.rb
- app/lib/provider_data_api/active_office_codes_filter.rb
- app/lib/provider_data_api/http_client.rb
- app/models/provider.rb
- config/application.rb
- config/kubernetes/preprod/config_map.yml
- config/kubernetes/staging/config_map.yml
- config/settings.yml
- spec/lib/lassie/oidc_strategy_spec.rb
- spec/lib/provider_data_api/active_office_codes_filter_spec.rb
- spec/lib/provider_data_api/http_client_spec.rb
- Checks the office codes provided by SILAS against the Provider Data API to ensure that each has an active crime contract.
- Only store active office codes for each provider.
- Retry twice on PDA 409
- Feature toggle between this and the gatekeeper
[CRIMAPP-1892](https://dsdmoj.atlassian.net/browse/CRIMAPP-1892)
There is no optimisation for these office code requests. An exceptional large number of office codes would be 30--which have bearable impact on the authentication time.
[CRIMAPP-1892]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1892] filter SILAS offices codes for active crime contracts

- config/kubernetes/preprod/ingress.yml
- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
This proxy is causing the ModSec logging violation details to be lost. Longer terms custom errors could be explored but for now logging is more important than the error message.
> Don't proxy 423 response

- config/kubernetes/preprod/ingress.yml
- config/kubernetes/production/ingress.yml
- config/kubernetes/staging/ingress.yml
- Remove attack-lfi rule from session cookie
- Removes redundant SAML rule
These rules could not be use to exploit the rails session cookie but they are causing false positives. Fixes observed false positive blocking users.
> Remove attack-lfi rule from session cookie

- app/controllers/concerns/error_handling.rb
- app/controllers/errors_controller.rb
- spec/requests/errors_spec.rb
- spec/system/dashboard/contingent_liability_spec.rb
Return OK http status on Contingent Liability error page
Previously :forbidden was used, however this resulted in the standard 403 error page being shown when deployed to Cloud Platform
[CRIMAPP-1952](https://dsdmoj.atlassian.net/browse/CRIMAPP-1952)
[CRIMAPP-1952]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1952] return OK status on CL error
